### ISSUE TITLE
Crash While Compiling some mods

### ISSUE THREAD

**Issue by DarkErtys** [MultiMC/MultiMC5#1092]
Hey Communauty,
I try to make an modpack but i can't finish the starting sequence.
Her is the log:
```
[01:37:04] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.
[01:37:04] [main/INFO] [FML/]: Forge Mod Loader version 7.99.16.1448 for Minecraft 1.7.10 loading
[01:37:04] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_79, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre7
[01:37:04] [main/DEBUG] [FML/]: Java classpath at launch is C:/Users/Defsy/Desktop/Minecraft/MultiMC/jars/NewLaunch.jar
[01:37:04] [main/DEBUG] [FML/]: Java library path at launch is C:/Users/Defsy/Desktop/Minecraft/MultiMC/instances/Test/natives
[01:37:04] [main/DEBUG] [FML/]: Enabling runtime deobfuscation
[01:37:04] [main/DEBUG] [FML/]: Instantiating coremod class FMLCorePlugin
[01:37:04] [main/DEBUG] [FML/]: Added access transformer class cpw.mods.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[01:37:04] [main/DEBUG] [FML/]: Enqueued coremod FMLCorePlugin
[01:37:04] [main/DEBUG] [FML/]: Instantiating coremod class FMLForgePlugin
[01:37:04] [main/DEBUG] [FML/]: Added access transformer class net.minecraftforge.transformers.ForgeAccessTransformer to enqueued access transformers
[01:37:04] [main/DEBUG] [FML/]: Enqueued coremod FMLForgePlugin
[01:37:04] [main/DEBUG] [FML/]: All fundamental core mods are successfully located
[01:37:04] [main/DEBUG] [FML/]: Attempting to load commandline specified mods, relative to C:\Users\Defsy\Desktop\Minecraft\MultiMC\instances\Test\minecraft
[01:37:04] [main/DEBUG] [FML/]: Discovering coremods
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy 1.7.10_AM2-1.4.0.008.jar
[01:37:04] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in 1.7.10_AM2-1.4.0.008.jar, it will be examined later for regular @Mod instances
[01:37:04] [main/DEBUG] [FML/]: Instantiating coremod class AM2PreloaderContainer
[01:37:04] [main/WARN] [FML/]: The coremod am2.preloader.AM2PreloaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[01:37:04] [main/INFO] [FML/]: AMCore initializing...stand back!  I'm going to try MAGIC!
[01:37:04] [main/DEBUG] [FML/]: Enqueued coremod AM2PreloaderContainer
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy [1.7.10]ArmorStatusHUD-client-1.28.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in [1.7.10]ArmorStatusHUD-client-1.28.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy [1.7.10]bspkrsCore-universal-6.16.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in [1.7.10]bspkrsCore-universal-6.16.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy AdminCommandsToolbox-0.0.2a_1.7.10.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in AdminCommandsToolbox-0.0.2a_1.7.10.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy AdvancedMachinesAS-1.7.10.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in AdvancedMachinesAS-1.7.10.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy AdvancedSolarPanel-1.7.10-3.5.1.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in AdvancedSolarPanel-1.7.10-3.5.1.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy AgriCraft-1.7.10-1.3.1.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in AgriCraft-1.7.10-1.3.1.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy animalsPlus-1.2.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in animalsPlus-1.2.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy AnimationAPI-1.7.10-1.2.4.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in AnimationAPI-1.7.10-1.2.4.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy AOBD-2.6.3.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in AOBD-2.6.3.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy Aroma1997Core-1.7.10-1.0.2.13.jar
[01:37:04] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in Aroma1997Core-1.7.10-1.0.2.13.jar, it will be examined later for regular @Mod instances
[01:37:04] [main/DEBUG] [FML/]: Instantiating coremod class CoreMod
[01:37:04] [main/WARN] [FML/]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[01:37:04] [main/DEBUG] [FML/]: Added access transformer class aroma1997.core.coremod.asm.AromaAccessTransformer to enqueued access transformers
[01:37:04] [main/DEBUG] [FML/]: Enqueued coremod CoreMod
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy Baubles-1.7.10-1.0.1.10.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in Baubles-1.7.10-1.0.1.10.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy bdlib-1.8.2.92-mc1.7.10.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in bdlib-1.8.2.92-mc1.7.10.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy BetterTitleScreen-1.7.10-1.1.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in BetterTitleScreen-1.7.10-1.1.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy BigReactors-0.4.3A.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in BigReactors-0.4.3A.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy binnie-mods-2.0-pre12.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in binnie-mods-2.0-pre12.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy BloodMagic-1.7.10-1.3.3-4.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in BloodMagic-1.7.10-1.3.3-4.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy Botania r1.6-194.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in Botania r1.6-194.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy buildcraft-7.0.12.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in buildcraft-7.0.12.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy Carpenter's Blocks v3.3.6 - MC 1.7.10.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in Carpenter's Blocks v3.3.6 - MC 1.7.10.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy Carpenter's Blocks v3.3.7 DEV - MC 1.7.10.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in Carpenter's Blocks v3.3.7 DEV - MC 1.7.10.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy ChickenChunks-1.7.10-1.3.4.19-universal.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in ChickenChunks-1.7.10-1.3.4.19-universal.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy Chisel2-2.3.10.37.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in Chisel2-2.3.10.37.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy chocolateQuest-1.7.10-1.0.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in chocolateQuest-1.7.10-1.0.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy CodeChickenCore-1.7.10-1.0.4.29-universal.jar
[01:37:04] [main/TRACE] [FML/]: Adding CodeChickenCore-1.7.10-1.0.4.29-universal.jar to the list of known coremods, it will not be examined again
[01:37:04] [main/DEBUG] [FML/]: Instantiating coremod class CodeChickenCorePlugin
[01:37:04] [main/WARN] [FML/]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[01:37:04] [main/INFO] [STDERR/]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of ForgeMultipart, 1.2.0.345 is newer than request 1.1.2.331
[01:37:04] [main/INFO] [STDERR/]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of CodeChickenLib, 1.1.3.138 is newer than request 1.1.3.127
[01:37:04] [main/INFO] [STDERR/]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of bspkrsCore, 6.16 is newer than request 6.15
[01:37:04] [main/DEBUG] [FML/]: Added access transformer class codechicken.core.asm.CodeChickenAccessTransformer to enqueued access transformers
[01:37:04] [main/DEBUG] [FML/]: Enqueued coremod CodeChickenCorePlugin
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy CodeChickenLib-1.7.10-1.1.3.138-universal.jar
[01:37:04] [main/ERROR] [FML/]: Unable to read the jar file CodeChickenLib-1.7.10-1.1.3.138-universal.jar - ignoring
java.io.FileNotFoundException: C:\Users\Defsy\Desktop\Minecraft\MultiMC\instances\Test\minecraft\mods\CodeChickenLib-1.7.10-1.1.3.138-universal.jar (Le fichier sp�cifi� est introuvable)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.7.0_79]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.7.0_79]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.7.0_79]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.7.0_79]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.7.0_79]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:265) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy CoFHCore-[1.7.10]3.0.2-262.jar
[01:37:04] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in CoFHCore-[1.7.10]3.0.2-262.jar, it will be examined later for regular @Mod instances
[01:37:04] [main/DEBUG] [FML/]: Instantiating coremod class LoadingPlugin
[01:37:04] [main/WARN] [FML/]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[01:37:04] [main/DEBUG] [FML/]: Added access transformer class cofh.asm.CoFHAccessTransformer to enqueued access transformers
[01:37:04] [main/DEBUG] [FML/]: Enqueued coremod LoadingPlugin
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy CompactSolars-1.7.10-4.4.39.315-universal.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in CompactSolars-1.7.10-4.4.39.315-universal.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy ComputerCraft1.73.jar
[01:37:04] [main/DEBUG] [FML/]: Not found coremod data in ComputerCraft1.73.jar
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy CookieCore-1.7.10-1.3.1-7.jar
[01:37:04] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in CookieCore-1.7.10-1.3.1-7.jar, it will be examined later for regular @Mod instances
[01:37:04] [main/DEBUG] [FML/]: Instantiating coremod class CookieCoreASM
[01:37:04] [main/DEBUG] [FML/]: The coremod nf.fr.ephys.cookiecore.common.CookieCoreASM requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[01:37:04] [main/DEBUG] [FML/]: Added access transformer class nf.fr.ephys.cookiecore.common.core.CookieCoreAT to enqueued access transformers
[01:37:04] [main/DEBUG] [FML/]: Enqueued coremod CookieCoreASM
[01:37:04] [main/DEBUG] [FML/]: Examining for coremod candidacy Evoc_1.0.0a.jar
[01:37:04] [main/TRACE] [FML/]: Adding Evoc_1.0.0a.jar to the list of known coremods, it will not be examined again
[01:37:04] [main/DEBUG] [FML/]: Instantiating coremod class CoreDescription
[01:37:04] [main/WARN] [FML/]: The coremod mcp.mobius.evoc.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.AbstractMethodError
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:459)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:54)
[01:37:04] [main/ERROR] [FML/]: An error occurred trying to configure the minecraft home at C:\Users\Defsy\Desktop\Minecraft\MultiMC\instances\Test\minecraft for Forge Mod Loader
java.lang.AbstractMethodError
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:459) ~[forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346) ~[forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) ~[forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1448-1.7.10-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[01:37:04] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:313]: Failed to start Minecraft:
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:54)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.AbstractMethodError
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:459)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 8 more
[01:37:04] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:57]: Exiting with -1
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArrayIndexOutOfBoundsException: 5
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[01:37:04] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:58)
```

*EDIT (Loetkolben): Put the chrash log in an code block.*

**Comment by Loetkolben** [comment]
Maybe update your Forge? Also, please provide the complete MMC log using the "*Upload Log*" Button in the Console Window after the game crashes.

**Comment by DarkErtys** [comment]
Im trying to put one by one my mods,
I will upload the log if i get any issues.
Safe way to do for identify the problems
