### ISSUE TITLE
Minecraft keeps renewing jar

### ISSUE THREAD

**Issue by Andrew5545** [MultiMC/MultiMC5#1104]
See I'm running beta 1.8 with mods that work just every time you boot it auto refreshes your jar Adding Something called META-Inf  a file that stops the mods from running.  So how to stop it from re downloading the jar every time I run it.

**Comment by peterix** [comment]
Works as intended.

Add the mods using MultiMC (add jar mod in the version page) and don't touch the jar files.

**Comment by peterix** [comment]
See: https://github.com/MultiMC/MultiMC5/wiki/Instance-Version#advanced

**Comment by Andrew5545** [comment]
IVe tryed adding mods through MultiMC and has I said they cant use metainf and Its there

**Comment by peterix** [comment]
Explain that in detail. Because I've never seen anything like this.

**Comment by Andrew5545** [comment]
The jar has a META-INF File and the mod that Im using cant have that file in the jar. Let me show you the link http://www.djoslin.info/required.php

**Comment by peterix** [comment]
That part of the instructions does not apply to MultiMC.

**Comment by Andrew5545** [comment]
Everytime I launch I get this error with mods in beta 
Exception in thread "main" java.lang.IncompatibleClassChangeError: class rh has interface mp as super class

**Comment by peterix** [comment]
Post the full log.

**Comment by Andrew5545** [comment]
k I sec

**Comment by Andrew5545** [comment]
MultiMC version: 0.4.7

Minecraft folder is:
C:/Users/Andrew/Downloads/MultiMC/instances/b1.5_01/minecraft

Java path is:
C:/Program Files/Java/jre7/bin/javaw.exe

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -XX:PermSize=128m, -Duser.language=en, -jar, C:/Users/Andrew/Downloads/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 2784

Using onesix launcher.

Main Class:
  net.minecraft.client.Minecraft

Native path:
  C:/Users/Andrew/Downloads/MultiMC/instances/b1.5_01/natives

Traits:
  [texturepacks, legacyLaunch]

Libraries:
  C:/Users/Andrew/Downloads/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Andrew/Downloads/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Andrew/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Andrew/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Andrew/Downloads/MultiMC/instances/b1.5_01/minecraft.jar

Jar Mods:
  SinglePlayerCommands-MC1.5.1_V4.7 (ff4ec55c-c2cf-45dc-97d4-9d0bd03ecc75.jar)
  Spawner GUI (76f0c054-b865-4d14-b977-06cf013375b8.jar)
  TooManyItems2013_03_23_1.5.1 (62a64888-1d32-495f-8a63-dd8a09c1f9da.jar)
  CoroAI for MC v1.5.1 (5c11c74f-7610-4680-814e-24c86d076539.jar)
  ModLoader (bb182736-be0c-40a5-a27c-b0f99b65464d.jar)
  Weather v1.4 Mod for MC v1.5.1 (19f1692f-edc2-4784-bf6e-34425bc975b8.jar)

Params:
  [<PROFILE NAME>, <SESSION ID>]

Window size: 854 x 480

Preparing native libraries...
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

Launching with applet wrapper...
Exception in thread "main" java.lang.IncompatibleClassChangeError: class rh has interface mp as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at to.<clinit>(SourceFile:128)
	at ul.<init>(SourceFile:14)
	at net.minecraft.client.Minecraft.<init>(SourceFile:213)
	at p.<init>(SourceFile:34)
	at net.minecraft.client.MinecraftApplet.init(SourceFile:34)
	at net.minecraft.Launcher.init(Launcher.java:109)
	at org.multimc.LegacyFrame.start(LegacyFrame.java:66)
	at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:198)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:389)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by Andrew5545** [comment]
ALl of my mods work together I can tell you them, Ive used them before back in beta

**Comment by peterix** [comment]
Minecraft 1.5.1 is not the same thing as Minecraft b1.5_01.

**Comment by Andrew5545** [comment]
beta goes 1.5 to 1.5_01

**Comment by peterix** [comment]
And these mods are not for those versions.

**Comment by Andrew5545** [comment]
............. Im an idiot but this also happens to my b8.1

**Comment by peterix** [comment]
Then some versions don't match quite right... or you have multiple mods messing with the same files.

**Comment by Andrew5545** [comment]
MultiMC version: 0.4.7

Minecraft folder is:
C:/Users/Andrew/Downloads/MultiMC/instances/b1.8.1/minecraft

Java path is:
C:/Program Files/Java/jre7/bin/javaw.exe

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -XX:PermSize=128m, -Duser.language=en, -jar, C:/Users/Andrew/Downloads/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 2748

Using onesix launcher.

Main Class:
  net.minecraft.client.Minecraft

Native path:
  C:/Users/Andrew/Downloads/MultiMC/instances/b1.8.1/natives

Traits:
  [texturepacks, legacyLaunch]

Libraries:
  C:/Users/Andrew/Downloads/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Andrew/Downloads/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Andrew/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Andrew/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Andrew/Downloads/MultiMC/instances/b1.8.1/minecraft.jar

Mods:
  forge-1.8-11.14.3.1446-universal

Jar Mods:
  SinglePlayerCommands-MC1.8.1V2.12.1 (96db6a07-0dfa-43bd-90e2-a2d4122a3c13.jar)
  TooManyItems2011_09_27_1.8_fix (263d4417-7f9d-4fcd-aee8-4d7d2a12d364.jar)
  forge-1.8-11.14.3.1446-universal (c4621455-7a23-4c65-a545-5b4dd62e2d9e.jar)
  New Compressed (zipped) Folder (78b6dd8f-fa63-4ed5-8d02-6837d3e8c074.jar)
  FiniteLiquidv5_92 (5205c0e0-b039-4b41-9bf0-1f823cddb3a3.jar)
  ModLoader B1.8.1 Javadoc (c34a0d08-a8c6-4764-a183-2a3bfd9bcfdd.jar)

Params:
  [<PROFILE NAME>, <SESSION ID>]

Window size: 854 x 480

Preparing native libraries...
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

Launching with applet wrapper...
17 achievements
Exception in thread "main" java.lang.NoClassDefFoundError: BaseMod
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at adv.l(BlockFire.java:36)
	at lr.<clinit>(Block.java:908)
	at mk.<init>(SourceFile:14)
	at net.minecraft.client.Minecraft.<init>(SourceFile:172)
	at l.<init>(SourceFile:34)
	at net.minecraft.client.MinecraftApplet.init(SourceFile:34)
	at net.minecraft.Launcher.init(Launcher.java:109)
	at org.multimc.LegacyFrame.start(LegacyFrame.java:66)
	at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:198)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:389)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.ClassNotFoundException: BaseMod
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 24 more

**Comment by Kilobyte22** [comment]
Again, you are installing things for Minecraft 1.8.1 - not Minecraft Beta 1.8.1. (Note the lack of the word 'beta') There are about 2 or 3 years at least inbetween those versions iirc.

**Comment by peterix** [comment]
#BlameInconsistentVersioningSchemes

The whole version specifier matters, not just the numbers.

**Comment by Andrew5545** [comment]
Its beta 1.8.1 Ill grab  a snap of it  also all mods are for beta I made sure

**Comment by Andrew5545** [comment]
http://i.imgur.com/uQgfdnb.png

**Comment by Andrew5545** [comment]
I download tmi b1.8 It also works with b1.8.1

**Comment by Kilobyte22** [comment]
The forge jar does suspeciously look like made for non-beta

**Comment by Andrew5545** [comment]
Its Is and I turned it off when running that time

**Comment by peterix** [comment]
And that is modloader developer documentation (javadoc), not modloader.

**Comment by Andrew5545** [comment]
That could be the problem I might have clicked on it 1 sec

**Comment by Andrew5545** [comment]
I disabled forge... also Im so confused about this 1.5.1 one thing cause the mod stoped progress in 2013 at B1.5.1  and On the program 1.5.1 isnt there

**Comment by loordgek** [comment]
wat are you trying to do ?

**Comment by Andrew5545** [comment]
To use mods on B1.5.1 Not B1.5_01

**Comment by loordgek** [comment]
![naamloos](https://cloud.githubusercontent.com/assets/4789835/8460164/7b7f046e-2022-11e5-8267-e04fcbbd61ce.png) this one?

**Comment by Kilobyte22** [comment]
B1.5.1 does not exist. In beta (which the B stands for) the numbering scheme was differently.

**Comment by peterix** [comment]
Ok... confusing versioning.

Hopefully this is now clear.
