### ISSUE TITLE
MultiMC Crashes upon trying to load Minecraft with any version of Forge on 1.7

### ISSUE THREAD

**Issue by AgentUndertaker** [MultiMC/MultiMC5#1122]
Every time I go to create an Instance of Minecraft that is any version below 1.7.10, I can run just fine in Vanilla mode, but if I try to add Forge and play it, the launcher instantly crashes. The moment the console window appears, it fails to launch Minecraft and instantly closes itself, preventing me from being able to copy the crash report. After some troubleshooting, I found the crash log in the Minecraft folder, but I have no idea what that all means. Here it is below:

```
[16:01:42] [main/INFO] [FML/]: Forge Mod Loader version 7.2.211.1121 for Minecraft 1.7.2 loading
[16:01:42] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_45, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_45
[16:01:42] [main/DEBUG] [FML/]: Java classpath at launch is C:/Users/TM/Desktop/MultiMC/jars/NewLaunch.jar
[16:01:42] [main/DEBUG] [FML/]: Java library path at launch is C:/Users/TM/Desktop/MultiMC/instances/Machinima 1.7/natives
[16:01:42] [main/DEBUG] [FML/]: Enabling runtime deobfuscation
[16:01:42] [main/DEBUG] [FML/]: Instantiating coremod class FMLCorePlugin
[16:01:42] [main/DEBUG] [FML/]: Added access transformer class cpw.mods.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[16:01:42] [main/DEBUG] [FML/]: Enqueued coremod FMLCorePlugin
[16:01:42] [main/DEBUG] [FML/]: Instantiating coremod class FMLForgePlugin
[16:01:42] [main/DEBUG] [FML/]: Added access transformer class net.minecraftforge.transformers.ForgeAccessTransformer to enqueued access transformers
[16:01:42] [main/DEBUG] [FML/]: Enqueued coremod FMLForgePlugin
[16:01:42] [main/DEBUG] [FML/]: All fundamental core mods are successfully located
[16:01:42] [main/DEBUG] [FML/]: Discovering coremods
[16:01:42] [main/DEBUG] [FML/]: Examining for coremod candidacy AnimatedPlayer-1.7.2-1.5.0.jar
[16:01:42] [main/DEBUG] [FML/]: Not found coremod data in AnimatedPlayer-1.7.2-1.5.0.jar
[16:01:42] [main/DEBUG] [FML/]: Examining for coremod candidacy AnimationAPI-1.7.2-1.2.2.jar
[16:01:42] [main/DEBUG] [FML/]: Not found coremod data in AnimationAPI-1.7.2-1.2.2.jar
[16:01:42] [main/DEBUG] [FML/]: Examining for coremod candidacy BiomesOPlenty-1.7.2-2.0.2.934-universal.jar
[16:01:42] [main/DEBUG] [FML/]: Not found coremod data in BiomesOPlenty-1.7.2-2.0.2.934-universal.jar
[16:01:42] [main/DEBUG] [FML/]: Examining for coremod candidacy CoroUtil-1.0.jar
[16:01:42] [main/DEBUG] [FML/]: Not found coremod data in CoroUtil-1.0.jar
[16:01:42] [main/DEBUG] [FML/]: Examining for coremod candidacy FreezeCamMod1.7.2.jar
[16:01:42] [main/DEBUG] [FML/]: Not found coremod data in FreezeCamMod1.7.2.jar
[16:01:42] [main/DEBUG] [FML/]: Examining for coremod candidacy OptiFine_1.7.2_HD_U_D5.jar
[16:01:42] [main/INFO] [FML/]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.2_HD_U_D5.jar
[16:01:42] [main/DEBUG] [FML/]: Examining for coremod candidacy ParticleMan-1.0.jar
[16:01:42] [main/DEBUG] [FML/]: Not found coremod data in ParticleMan-1.0.jar
[16:01:42] [main/DEBUG] [FML/]: Examining for coremod candidacy Slabcraftmod 1.7 - 1.7.10 Forge.jar
[16:01:42] [main/DEBUG] [FML/]: Not found coremod data in Slabcraftmod 1.7 - 1.7.10 Forge.jar
[16:01:42] [main/DEBUG] [FML/]: Examining for coremod candidacy Staircraftmod 1.7 - 1.7.10 Forge.jar
[16:01:42] [main/DEBUG] [FML/]: Not found coremod data in Staircraftmod 1.7 - 1.7.10 Forge.jar
[16:01:42] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:01:42] [main/INFO] [LaunchWrapper/]: Loading tweak class name optifine.OptiFineForgeTweaker
[16:01:42] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[16:01:42] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:01:42] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_45]
	at java.util.ArrayList$Itr.remove(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:117) [launchwrapper-1.9.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
```

I hope I can get an answer as to why this is happening.

**Comment by 02JanDal** [comment]
This is an issue with older forge versions and java 8. Put this in your mods/ folder: http://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar

**Comment by peterix** [comment]
Assuming fixed.

**Comment by Adriano72** [comment]
You saved me, thanks!!!!
