### ISSUE TITLE
Instances Not Starting

### ISSUE THREAD

**Issue by Luke1215** [MultiMC/MultiMC5#1162]
Whenever I try to load an instance, new or old, it kills Minecraft very quickly. My logs are here: http://paste.ee/p/b0YA0. I have my suspicions that this is a vanilla based problem. As the Minecraft launcher itself will not load either (it just gives me a gray window).
If anyone is able to help that would be amazing!

**Comment by Loetkolben** [comment]
Most likely a currupted librarie for Minecraft.
```
Failed to extract native library:
java.util.zip.ZipException: ZIP_Read: error reading zip file
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(Unknown Source)
	at java.util.zip.ZipFile$ZipFileInputStream.read(Unknown Source)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.multimc.Utils.copyStream(Utils.java:203)
	at org.multimc.Utils.unzipNatives(Utils.java:268)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:355)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
```
Rename the "*libraries*" folder in your MMC install folder to make MMC redownload them. If this makes it work, you can delete the old "*libraires*" folder.

**Comment by Luke1215** [comment]
Worked perfectly! Thank you! I also reinstalled base Minecraft and got that to load. Thank you, again
