### ISSUE TITLE
Multimc crashing when trying to load up minecraft

### ISSUE THREAD

**Issue by marioandluigi878** [MultiMC/MultiMC5#1214]
http://paste.ee/p/yPc2u I don't know if this belongs here but It does happen when i try to load up mc in multimc

**Comment by peterix** [comment]
You appear to not have a working graphics card. Or its drivers are being rather stubborn :)

Try:
* renaming MultiMC.exe to Minecraft.exe
* updating your graphics drivers - using the drivers from your graphics card manufacturer, not any third party like Microsoft.

**Comment by peterix** [comment]
```
[20:30:53] [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class 
java.lang.ClassNotFoundException: 
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.11.jar:?]
	at cpw.mods.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:32) [forge-1.7.10-10.13.3.1408-1.7.10-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	... 14 more
```

This is weird too...

**Comment by peterix** [comment]
See if it starts without liteloader first.

**Comment by marioandluigi878** [comment]
well how am i gonna fix it cus my system for some reason dosent wanna install the update to my driver no matter what i do 
 


     On Thursday, August 27, 2015 10:54 PM, Petr Mrázek <notifications@github.com> wrote:
   

 See if it starts without liteloader first.—

**Comment by cosmicdan** [comment]
Hi @peterix,

I am getting this "A critical problem occurred registering the ASM transformer class" error too, but MultiMC doesnt crash.

Sorry to hijack this issue, but was just wondering if this is a problem from MultiMC only, and therefore can be safely ignored? Thanks.

**Comment by marioandluigi878** [comment]
XD dont worry actually I forgot to put this as solved

**Comment by marioandluigi878** [comment]
hey @peterix when your done helping this guy can u mark this as closed

**Comment by Slikrick** [comment]
you created it, you have the ability to close the issue.

**Comment by peterix** [comment]
The original log is gone. The additional issue - I have no idea.

None of this is in any way related to MultiMC - it's a problem with the mods and mod loaders.

So I'm just going to close it.

If you have graphics problems with Intel drivers on Windows 10, use older Java - for example 8u25. It seems 8u60 is broken.
