### ISSUE TITLE
Crash when loading a map

### ISSUE THREAD

**Issue by djesty** [MultiMC/MultiMC5#1215]
Hello guys! :D 
I have a problem with my MultiMC 5... When I launch the game, everything works correctly but when I load a world, the game says "shutting down internal server" and then, it crashes... MultiMC gives me this error code : 

https://paste.ee/p/KCYFm

I don't understand anything but I'm sure you can help me :D

**Comment by Loetkolben** [comment]
Ok, i think you real problem is this:
```
[12:43:50] [Server thread/ERROR] [FML]: HandshakeCompletionHandler exception
net.minecraft.util.ReportedException: Exception getting block type in world
```

But right before the crash comes this:
```
[12:43:50] [Server thread/ERROR] [FastCraft]: NPE FROM StructureStart.generateStructure, obj=diversity.MapGenVillageDiversity$Start@4902daf2.
[12:43:50] [Server thread/ERROR] [FastCraft]: components=[diversity.village.VillageSettled$Start@11317f95, diversity.village.VillageSettled$Path@48af1804, diversity.village.VillageSettled$Path@5f51d3e3, diversity.village.VillageSettled$Path@752e0cf8, diversity.village.VillageSettled$Path@2255a9e2, diversity.village.VillageSettled$House3@2604460a, diversity.village.VillageSettled$Hall@62924e05, diversity.village.VillageSettled$Church@73405cd1, diversity.village.VillageSettled$House1@68dd874, diversity.village.VillageSettled$Field1@4a7dab08, diversity.village.VillageSettled$House2@67c06d, diversity.village.VillageSettled$House4Garden@1b8a3450, diversity.village.VillageSettled$Torch@e707e50, diversity.village.VillageSettled$Field2@7b74bd97, diversity.village.VillageSettled$Field2@2d4b43d3, diversity.village.VillageSettled$Path@2851e8e0, diversity.village.VillageSettled$Path@198fdece].
[12:43:50] [Server thread/ERROR] [FastCraft]: iterator=java.util.LinkedList$ListItr@346cb37e.
```
So maybe update (if possible) / remove FastCraft and see if it still crashes (FastCraft is also in the the stacktrace of the crashlog), as it messes with MC classes.

**Comment by djesty** [comment]
it seems to be better now, I've deleted FastCraft and I can see my map during 2 seconds... x)
I have another crash...    : 

https://paste.ee/p/UvSqa

PS : sorry if my English is not perfect or if there is french in the logs, but I speak french... :S 
       The english community seems to be more helpful than the french community... ^^

**Comment by Loetkolben** [comment]
Might not be related, but fix you TwilightForest Biome IDS...
```
[13:40:08] [Server thread/WARN] [FML]: [TwilightForest] Biome ID conflict.  Biome ID 68 contains a biome named Extreme Rainforest Mountains, but Twilight Forest is set to use that ID.
[13:40:08] [Server thread/WARN] [FML]: [TwilightForest] Biome ID conflict detected.  Edit the Twilight Forest config to give all biomes unique IDs.
```
This seems to be the real problem:
```
java.lang.NullPointerException: Exception in server tick loop
	at net.slimevoid.littleblocks.world.LittleWorldServer.func_72977_a(LittleWorldServer.java:410)
	at org.millenaire.common.building.Building.updateBuildingServer(Building.java:5808)
	at org.millenaire.common.MillWorld.updateWorldServer(MillWorld.java:1068)
	at org.millenaire.common.forge.ServerTickHandler.tickStart(ServerTickHandler.java:18)
```
This looks like either a problem with LittleBlocks or an incomplatability with Millenaire. Update (if possible) and / or remove one of them to see if that causes the crash.

**Comment by djesty** [comment]
I've changed the ID for TwilightForest and updated LittleBlock and Millenaire but it seems to be the same result as my last message :(

https://paste.ee/p/KEJuO

**Comment by Loetkolben** [comment]
Then remove either LittleBlocks or Millenaire and see if it still crashes.

**Comment by djesty** [comment]
I've tried without Millenaire and then, without LittleBlock but nothing change, the game crashes when I load a map...

**Comment by Loetkolben** [comment]
Logs?

**Comment by djesty** [comment]
without Little Block : 

https://paste.ee/p/69fJP

Without Millenaire : 

https://paste.ee/p/BpKLw

**Comment by marioandluigi878** [comment]
took a look at the crash log it looks like it has to do with the villages being generated http://pastebin.com/avfTTAjJ try removing diversity or something to do with worldgen hope I fixed it

**Comment by djesty** [comment]
it seems to work perfectly now! :D I've created a new world (to avoid the problems with the villages) and now, I can create a world and load the map without any problem! :D 
Thank you so much! :D

**Comment by marioandluigi878** [comment]
your welcome
