### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by bopaloni** [MultiMC/MultiMC5#1235]
```
MultiMC version: 0.4.5

Minecraft folder is:
C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/instances/Wiggle/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_31/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/jars/NewLaunch.jar]

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/instances/Wiggle/natives

Traits:
  []

Libraries:
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1492-1.7.10/forge-1.7.10-10.13.4.1492-1.7.10-universal.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/versions/1.7.10/1.7.10.jar

Params:
  [--username, <PROFILE NAME>, --version, 1.7.10, --gameDir, C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/instances/Wiggle/minecraft, --assetsDir, C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {"twitch_access_token":["<TWITCH_ACCESS_TOKEN>"]}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-64.jar
Exiting with -1
Failed to extract native library:
java.io.FileNotFoundException: C:\Users\penka_000\AppData\Roaming\.minecraft\MMC\instances\Wiggle\natives\twitchsdk.dll (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at org.multimc.Utils.unzipNatives(Utils.java:255)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:337)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Minecraft exited with exitcode -1.
```

**Comment by Heufneutje** [comment]
Start by updating MultiMC. You're using 0.4.5. The latest version is 0.4.7.

**Comment by peterix** [comment]
Looks like you are trying to run one instance twice? Or you have a leftover java process that didn't exit properly from the last time you played it.

**Comment by bopaloni** [comment]
Alright just saw your replies and have updated but it still doesn't work

**Comment by Famous5000** [comment]
Same here, but I'm on the latest version, and the last time it opened it crashed due to "Out Of Memory Exception".

**Comment by Famous5000** [comment]
And yes, I know it's an old thread, but I still need an answer to this. Because I am having the literal exact same problem.

**Comment by Famous5000** [comment]
Nevermind; restarting the program fixed it.

You: Have you tried turning it off and on again?
Me: No. Trying now......
Me facepalms
Me: False alarm. It works now.
