### ISSUE TITLE
Help with a crashing modpack?

### ISSUE THREAD

**Issue by Samuelson99** [MultiMC/MultiMC5#1255]
I have been creating a modpack for my friends and I to use. 
I have been sequentially adding the mods to isolate all the errors that occur but for some reason I can't  
find the current error. the log is saying this when I try loading any world...
```
[OptiFine] Texture size: textures/blocks, 2048x1024
[11:11:12] [Client thread/INFO]: Created: 2048x1024 textures/blocks-atlas
[OptiFine] Loading texture map: textures/items
[11:11:13] [Client thread/ERROR]: Using missing texture, unable to load minefactoryreloaded:textures/items/item.mfr.rednet.meter.debug.png, java.io.FileNotFoundException
[OptiFine] Texture size: textures/items, 2048x1024
[11:11:15] [Client thread/INFO]: Created: 2048x1024 textures/items-atlas
[11:11:16] [Client thread/INFO] [LiteLoader]: Baking listener list for ViewportListener with 0 listeners
[11:11:16] [Client thread/INFO] [LiteLoader]: Sound handler reload inhibit removed
[11:11:16] [Client thread/INFO] [LiteLoader]: Reloading sound handler
[11:11:16] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:11:16] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[11:11:16] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[11:11:16] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:11:16] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:11:16] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[11:11:16] [Thread-24/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[11:11:16] [Thread-24/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[11:11:16] [Thread-24/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[11:11:17] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:11:17] [Sound Library Loader/INFO]: Sound engine started
[11:11:23] [Client thread/INFO] [LiteLoader]: Baking listener list for GameLoopListener with 0 listeners
[11:11:23] [Client thread/INFO] [LiteLoader]: Baking listener list for RenderListener with 0 listeners
[OptiFine] *** Reloading custom textures ***
[OptiFine] Loading custom colors: textures/colormap/grass.png
[OptiFine] Loading custom colors: textures/colormap/foliage.png
[11:11:24] [Client thread/INFO] [LiteLoader]: Baking listener list for TickObserver with 3 listeners
[11:11:24] [Client thread/INFO] [LiteLoader]: Baking listener list for PostRenderObserver with 3 listeners
[11:11:24] [Client thread/INFO] [LiteLoader]: Baking listener list for Tickable with 0 listeners
[11:11:24] [Client thread/INFO] [LiteLoader]: Baking listener list for WorldObserver with 2 listeners
[11:11:24] [Client thread/INFO] [LiteLoader]: Baking listener list for FrameBufferListener with 0 listeners
[11:16:34] [Client thread/INFO] [LiteLoader]: Baking listener list for ServerCommandProvider with 0 listeners
[11:16:34] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[11:16:34] [Server thread/INFO]: Generating keypair
[11:16:34] [Server thread/ERROR] [fml.ModTracker]: This world was saved with mod FastCraft which appears to be missing, things may not work well
[11:16:34] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[11:16:34] [Server thread/INFO] [FML]: Applying holder lookups
[11:16:34] [Server thread/INFO] [FML]: Holder lookups applied
[OptiFine] WorldServer.nextTickSet updated
[11:16:35] [Server thread/INFO] [FML]: Loading dimension 0 (New World-) (net.minecraft.server.integrated.IntegratedServer@248cc112)
[OptiFine] WorldServer.nextTickSet updated
[11:16:35] [Server thread/INFO] [FML]: Loading dimension -37 (New World-) (net.minecraft.server.integrated.IntegratedServer@248cc112)
[OptiFine] WorldServer.nextTickSet updated
[11:16:37] [Server thread/INFO] [FML]: Loading dimension -38 (New World-) (net.minecraft.server.integrated.IntegratedServer@248cc112)
[OptiFine] WorldServer.nextTickSet updated
[11:16:37] [Server thread/INFO] [FML]: Loading dimension -39 (New World-) (net.minecraft.server.integrated.IntegratedServer@248cc112)
[OptiFine] WorldServer.nextTickSet updated
[11:16:37] [Server thread/INFO] [FML]: Loading dimension -42 (New World-) (net.minecraft.server.integrated.IntegratedServer@248cc112)
[OptiFine] WorldServer.nextTickSet updated
[11:16:37] [Server thread/INFO] [FML]: Loading dimension 1 (New World-) (net.minecraft.server.integrated.IntegratedServer@248cc112)
[11:16:40] [Server thread/INFO] [FML]: Applying holder lookups
[11:16:40] [Server thread/INFO] [FML]: Holder lookups applied
[11:16:40] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.OutOfMemoryError: PermGen space
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:114)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.apache.logging.log4j.core.impl.Log4jLogEvent.<init>(Log4jLogEvent.java:90)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.apache.logging.log4j.core.impl.DefaultLogEventFactory.createEvent(DefaultLogEventFactory.java:49)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:365)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:609)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:450)
[11:16:40] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[11:16:43] [Client thread/INFO]: Stopping!
[11:16:43] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:16:43] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[11:16:44] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[11:16:44] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:16:45] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:313]: Failed to start Minecraft:
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:54)
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.OutOfMemoryError: PermGen space
[11:16:45] [Client thread/INFO] [STDOUT]: [org.multimc.EntryPoint:main:57]: Exiting with -1
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArrayIndexOutOfBoundsException: 5
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[11:16:45] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:58)
```

Can Anyone help?

**Comment by peterix** [comment]
1. Use java 8 - this error is impossible in java 8
2. Make sure you actually set up the java memory settings.

**Comment by Samuelson99** [comment]
Thanks so much!
I finally got java 8 installed and my game is working fine!
 You're the best.

**Comment by peterix** [comment]
Alright :)
