### ISSUE TITLE
Crash When tying to open my world

### ISSUE THREAD

**Issue by QMGSaint** [MultiMC/MultiMC5#1288]
```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 10/17/15 8:55 AM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 1
	at cpw.mods.fml.common.registry.GameRegistry$UniqueIdentifier.<init>(GameRegistry.java:391)
	at cpw.mods.fml.common.registry.GameData.getUniqueName(GameData.java:238)
	at cpw.mods.fml.common.registry.GameRegistry.findUniqueIdentifierFor(GameRegistry.java:462)
	at portablejim.veinminer.event.client.ItemNameTooltip.addTooltip(ItemNameTooltip.java:40)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_249_ItemNameTooltip_addTooltip_ItemTooltipEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:162)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:626)
	at elec332.craftingtableiv.handler.WrappedRecipe.registerItemName(WrappedRecipe.java:75)
	at elec332.craftingtableiv.handler.WrappedRecipe.<init>(WrappedRecipe.java:68)
	at elec332.craftingtableiv.handler.WrappedRecipe.<init>(WrappedRecipe.java:45)
	at elec332.craftingtableiv.handler.WrappedRecipe.<init>(WrappedRecipe.java:33)
	at elec332.craftingtableiv.handler.CraftingHandler.getWrappedRecipe(CraftingHandler.java:271)
	at elec332.craftingtableiv.handler.CraftingHandler.InitRecipes(CraftingHandler.java:215)
	at elec332.craftingtableiv.CraftingTableIV.loadRecipes(CraftingTableIV.java:141)
	at elec332.craftingtableiv.CraftingTableIV.serverStarted(CraftingTableIV.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:802)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:283)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:389)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1299039472 bytes (1238 MB) / 2210398208 bytes (2108 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 Optifine OptiFine_1.7.10_HD_U_C1 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
	UCHIJAAAA	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-13.jar) 
	UCHIJAAAA	ChestTransporter{2.0.3} [Chest Transporter] (ChestTransporter-2.0.3-MC1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJAAAA	gud_cooler{1.1.5.0} [Coolers] (cooler-1.7.10-1.1.5.0.jar) 
	UCHIJAAAA	ElecCore{1.4.161} [ElecCore] (ElecCore-1.7.10-1.4.161.jar) 
	UCHIJAAAE	CraftingTableIV{1.1Beta.62} [CraftingTableIV] (CraftingTableIV-1.7.10-1.1Beta.62.jar) 
	UCHIJAAAA	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHIJAAAA	sciapi{0.5.2} [SciAPI] (SciAPI v0.5.3.jar) 
	UCHIJAAAA	heatcraft{0.4.0} [InvWorks] (InvWorks v0.4.0.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.12.9} [MalisisCore] (malisiscore-1.7.10-0.12.9.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.10} [Malisis' Doors] (malisisdoors-1.7.10-1.10.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	MapWriter{2.1.8} [MapWriter] (MapWriter-1.7.10-2.1.10.jar) 
	UCHIJAAAA	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar) 
	UCHIJAAAA	minechem{5.0.5.406} [Minechem] (Minechem-1.7.10-5.0.5.406.jar) 
	UCHIJAAAA	numina{0.4.0.119} [Numina] (Numina-0.4.0.119.jar) 
	UCHIJAAAA	powersuits{0.11.0.283} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.283.jar) 
	UCHIJAAAA	NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) 
	UCHIJAAAA	neiintegration{1.0.13} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.13.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-5} [PortalGun] (PortalGun-4.0.0-beta-5.jar) 
	UCHIJAAAA	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCHIJAAAA	simplyjetpacks{1.5.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.1.jar) 
	UCHIJAAAA	ashjacksimukraftreloaded{1.0.2a} [Sim-U-Kraft Reloaded] (simukraft-1.7.10-1.0.2a.jar) 
	UCHIJAAAA	SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar) 
	UCHIJAAAA	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (SoulShards-TOW-1.7.10-0.1-RC9-7.jar) 
	UCHIJAAAA	SpecialMobs{3.2.0} [Special Mobs] (SpecialMobs-1.7.10-3.2.0.jar) 
	UCHIJAAAA	StacksOnStacks{{$version}} [Stacks on Stacks!] (StacksOnStacks-1.7.10-2.1.0.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCHIJAAAA	thutcore{2.0} [ThutCore] (ThutMods-2.0.jar) 
	UCHIJAAAA	ThutConcrete{2.0.0} [Thut's Concrete] (ThutMods-2.0.jar) 
	UCHIJAAAA	ThutTech{2.0.0} [Thut's Tech] (ThutMods-2.0.jar) 
	UCHIJAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJAAAA	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UCHIJAAAA	VeinMiner{0.28.0_build.unknown} [Vein Miner] (VeinMiner-1.7.10_0.28.3.unknown.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.28.0_build.unknown} [Mod Support] (VeinMiner-1.7.10_0.28.3.unknown.jar) 
	UCHIJAAAA	veinminermodintegration{1.7.10-0.2.0} [Veinminer Mod Integration] (veinminermodintegration-1.7.10-0.4.2.unknown.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHIJAAAA	XPT{1.1.0} [XP Teleporters] (XPTeleporters-1.7.10-1.1.0.jar) 
	UCHIJAAAA	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	UCHIJAAAA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	UCHIJAAAA	FMPIntegration{1.0} [FMPIntegration] (fmpintegration-1.2.2-1.7.10.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```
Please Help :)

**Comment by peterix** [comment]
Please use the Updated button on the console window and post the resulting link here. With just the crash report, it's not clear when or how this happens.

```
    at cpw.mods.fml.common.registry.GameRegistry$UniqueIdentifier.<init>(GameRegistry.java:391)
    at cpw.mods.fml.common.registry.GameData.getUniqueName(GameData.java:238)
    at cpw.mods.fml.common.registry.GameRegistry.findUniqueIdentifierFor(GameRegistry.java:462)
    at portablejim.veinminer.event.client.ItemNameTooltip.addTooltip(ItemNameTooltip.java:40)
```

ItemTooltipEvent is fired when an item tooltip is to be drawn on screen. Veinminer adds an event handler for it. It crashes here:
https://github.com/portablejim/VeinMiner/blob/1.7/src/main/java/portablejim/veinminer/event/client/ItemNameTooltip.java#L40

What were you doing when this happened?

**Comment by QMGSaint** [comment]
i just try to open my world up then it crashes

**Comment by peterix** [comment]
Anyway, upload the whole log, not just the crash report.
