### ISSUE TITLE
MultiMC 0.4.8-dev-648 cannot launch Minecraft at all when using Java 9 EA

### ISSUE THREAD

**Issue by Sonickyle27** [MultiMC/MultiMC5#1365]
After updating I cannot launch any Minecraft version, modded or not due to a java.lang.ArrayIndexOutOfBoundsException.
I'm running Ubuntu 14.04 amd64.
```
MultiMC version: 0.4.8-dev-648

Minecraft folder is:
instances/Minecraft/minecraft

Java path is:
/usr/bin/java

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en, -jar, /home/sonickyle27/Documents/Minecraft/MultiMC/bin/jars/NewLaunch.jar]

Minecraft process ID: 1074

Using onesix launcher.

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/sonickyle27/Documents/Minecraft/MultiMC/instances/Minecraft/natives

Traits:
  []

Libraries:
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/com/mojang/realms/1.7.23/realms-1.7.23.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  /home/sonickyle27/Documents/Minecraft/MultiMC/versions/1.8.7/1.8.7.jar

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, /home/sonickyle27/Documents/Minecraft/MultiMC/instances/Minecraft/minecraft, --assetsDir, /home/sonickyle27/Documents/Minecraft/MultiMC/assets, --assetIndex, 1.8, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang]

Window size: 680 x 480

Preparing native libraries...
Extracting jinput-platform-2.0.5-natives-linux.jar
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at org.multimc.Utils.unzipNatives(Utils.java:239)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:355)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Process exited with code 1.
```

**Comment by Sonickyle27** [comment]
Turns out that it was because I was using Oracle Java 9 EA. Downgrading to 8 solved this issue.

**Comment by peterix** [comment]
So, definitely something to look into.

**Comment by wlhlm** [comment]
A small suggestion: Maybe include the Java version in the log before trying to launch any java code, so that an error like this becomes more obvious.

**Comment by peterix** [comment]
Should now be actually done.
