### ISSUE TITLE
Installed new forge and some mods, now I can't play

### ISSUE THREAD

**Issue by thegreatwhite97** [MultiMC/MultiMC5#1368]
```
MultiMC version: 0.4.7

Minecraft folder is:
C:/Users/gamer_000/Desktop/MultiMC/instances/ChallengeCraft/minecraft

Java path is:
C:/Program Files (x86)/Java/jre7/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/gamer_000/Desktop/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 5936

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/gamer_000/Desktop/MultiMC/instances/ChallengeCraft/natives

Traits:
  []

Libraries:
  C:/Users/gamer_000/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1557-1.7.10/forge-1.7.10-10.13.4.1557-1.7.10-universal.jar (missing)
  C:/Users/gamer_000/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar (missing)
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/gamer_000/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/gamer_000/Desktop/MultiMC/versions/1.7.10/1.7.10.jar

Mods:
  advancedgenetics-1.7.10-1.5.7
  weaponmod-1.14.3
  BiblioCraft[v1.9.1][MC1.7.10]
  CustomNPCs_1.7.10d
  IGW-Mod-1.7.10-1.1.11-32-universal
  Mantle-1.7.10-0.3.2
  1.7.10-MB_Battlegear2-Bullseye-1.0.6.3
  PneumaticCraft-1.7.10-1.12.3-146-universal
  SecureCraftProtect-1.7.10-r141.28df7e9
  SecurityCraft v1.6.1 for 1.7.10
  TConstruct-1.7.10-1.8.2a

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/gamer_000/Desktop/MultiMC/instances/ChallengeCraft/minecraft, --assetsDir, C:/Users/gamer_000/Desktop/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-32.jar
Extracting twitch-external-platform-4.5-natives-windows-32.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

Failed to find Minecraft main class:
java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:239)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Exiting with -1
Game exited with exitcode -1.
```

**Comment by thegreatwhite97** [comment]
Two of the new mods that I got this same error for that aren't on this list are Clay Soldiers and SanAndreasPs Manager Pack 2.5.1

**Comment by 02JanDal** [comment]
C:/Users/gamer_000/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1557-1.7.10/forge-1.7.10-10.13.4.1557-1.7.10-universal.jar (missing)

Note the **missing**. Try reinstalling forge, or installing a different version. If the problem persist please upload MultiMC-0.log to pastebin or similar and post the link here.
