### ISSUE TITLE
AL lib: (EE) alc_cleanup: 1 device not closed

### ISSUE THREAD

**Issue by Vehiron** [MultiMC/MultiMC5#1375]
I've created a custom modpack for my private server using MultiMC, but whenever I try to join my server or even load a singleplayer world, my client crashes.

Crash Report
```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 27/12/15 9:49 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Duplicate entries not allowed
	at cofh.repack.cofh.lib.util.LinkedHashList.set(LinkedHashList.java:116)
	at fastcraft.a.o.a(F:126)
	at fastcraft.Hooks.t(F:147)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cofh.repack.cofh.lib.util.LinkedHashList.set(LinkedHashList.java:116)
	at fastcraft.a.o.a(F:126)
	at fastcraft.Hooks.t(F:147)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Vehiron'/389, l='MpServer', x=-201.50, y=64.62, z=48.50]]
	Chunk stats: MultiplayerChunkCache: 85, 85
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-208,64,48), Chunk: (at 0,4,0 in -13,3; contains blocks -208,0,48 to -193,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 615 game time, 615 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 95 total; [EntitySquid['Squid'/130, l='MpServer', x=-246.16, y=59.31, z=-11.41], EntityBat['Bat'/259, l='MpServer', x=-163.94, y=54.97, z=24.66], EntitySquid['Squid'/131, l='MpServer', x=-244.41, y=58.00, z=-11.50], EntityBat['Bat'/260, l='MpServer', x=-164.41, y=12.56, z=45.75], EntityCreeper['Creeper'/132, l='MpServer', x=-252.06, y=35.00, z=27.53], EntitySquid['Squid'/261, l='MpServer', x=-160.53, y=54.06, z=77.81], EntitySkeleton['Skeleton'/133, l='MpServer', x=-241.66, y=33.00, z=34.69], EntitySquid['Squid'/262, l='MpServer', x=-164.72, y=57.34, z=85.13], EntityZombie['Zombie'/134, l='MpServer', x=-241.47, y=33.00, z=32.78], EntityItem['item.item.seeds'/390, l='MpServer', x=-168.44, y=63.13, z=15.31], EntityClientPlayerMP['Vehiron'/389, l='MpServer', x=-201.50, y=64.62, z=48.50], EntitySkeleton['Skeleton'/263, l='MpServer', x=-163.13, y=27.00, z=102.47], EntityZombie['Zombie'/135, l='MpServer', x=-243.50, y=35.00, z=37.50], EntityBat['Bat'/264, l='MpServer', x=-175.25, y=22.00, z=100.09], EntityZombie['Zombie'/136, l='MpServer', x=-240.63, y=35.00, z=38.22], EntitySquid['Squid'/265, l='MpServer', x=-173.50, y=55.06, z=107.06], EntityCreeper['Creeper'/137, l='MpServer', x=-243.50, y=35.00, z=33.50], EntitySquid['Squid'/266, l='MpServer', x=-163.75, y=57.22, z=106.41], EntitySkeleton['Skeleton'/138, l='MpServer', x=-240.38, y=35.00, z=39.16], EntitySquid['Squid'/267, l='MpServer', x=-171.13, y=58.47, z=105.13], EntitySquid['Squid'/139, l='MpServer', x=-251.50, y=48.16, z=55.16], EntitySquid['Squid'/268, l='MpServer', x=-170.06, y=57.31, z=102.06], EntitySquid['Squid'/140, l='MpServer', x=-254.28, y=51.31, z=49.50], EntitySquid['Squid'/269, l='MpServer', x=-169.44, y=57.31, z=106.38], EntitySquid['Squid'/141, l='MpServer', x=-249.72, y=50.69, z=59.91], EntitySquid['Squid'/270, l='MpServer', x=-169.22, y=58.34, z=111.69], EntitySquid['Squid'/142, l='MpServer', x=-242.41, y=53.34, z=58.63], EntitySquid['Squid'/271, l='MpServer', x=-166.09, y=56.34, z=104.75], EntitySquid['Squid'/143, l='MpServer', x=-246.19, y=59.47, z=73.50], EntitySquid['Squid'/272, l='MpServer', x=-162.47, y=56.44, z=108.56], EntitySquid['Squid'/144, l='MpServer', x=-244.22, y=59.16, z=72.31], EntitySquid['Squid'/273, l='MpServer', x=-164.53, y=58.06, z=111.66], EntitySquid['Squid'/145, l='MpServer', x=-245.41, y=53.34, z=68.50], EntitySquid['Squid'/146, l='MpServer', x=-242.06, y=57.91, z=75.91], EntitySquid['Squid'/147, l='MpServer', x=-253.25, y=54.31, z=64.78], EntitySquid['Squid'/148, l='MpServer', x=-241.53, y=58.38, z=70.22], EntitySquid['Squid'/149, l='MpServer', x=-248.09, y=60.19, z=88.34], EntitySquid['Squid'/150, l='MpServer', x=-251.56, y=61.41, z=85.38], EntitySquid['Squid'/151, l='MpServer', x=-249.44, y=61.41, z=81.03], EntitySquid['Squid'/280, l='MpServer', x=-144.91, y=57.19, z=51.44], EntityZombie['Zombie'/152, l='MpServer', x=-248.91, y=14.00, z=100.63], EntitySquid['Squid'/281, l='MpServer', x=-147.97, y=55.28, z=85.44], EntitySquid['Squid'/282, l='MpServer', x=-155.56, y=52.94, z=93.47], EntitySquid['Squid'/283, l='MpServer', x=-145.03, y=56.06, z=88.94], EntitySquid['Squid'/284, l='MpServer', x=-153.06, y=55.88, z=86.47], EntityZombie['Zombie'/156, l='MpServer', x=-229.78, y=17.00, z=7.31], EntitySquid['Squid'/285, l='MpServer', x=-147.03, y=52.25, z=90.38], EntitySkeleton['Skeleton'/157, l='MpServer', x=-235.13, y=17.00, z=9.44], EntitySquid['Squid'/286, l='MpServer', x=-150.25, y=53.28, z=89.22], EntitySkeleton['Skeleton'/158, l='MpServer', x=-228.53, y=17.00, z=9.06], EntitySquid['Squid'/287, l='MpServer', x=-154.75, y=55.25, z=80.09], EntitySkeleton['Skeleton'/159, l='MpServer', x=-233.25, y=17.00, z=10.34], EntityZombie['Zombie'/160, l='MpServer', x=-230.50, y=19.00, z=38.50], EntitySquid['Squid'/288, l='MpServer', x=-154.75, y=54.34, z=99.06], EntityCreeper['Creeper'/161, l='MpServer', x=-236.97, y=43.00, z=38.53], EntitySquid['Squid'/289, l='MpServer', x=-149.16, y=56.19, z=104.81], EntityCreeper['Creeper'/162, l='MpServer', x=-228.50, y=45.00, z=42.50], EntityCreeper['Creeper'/163, l='MpServer', x=-230.06, y=45.00, z=39.50], EntitySkeleton['Skeleton'/291, l='MpServer', x=-140.50, y=18.00, z=32.50], EntityCreeper['Creeper'/164, l='MpServer', x=-226.50, y=45.00, z=37.50], EntityCreeper['Creeper'/165, l='MpServer', x=-229.50, y=45.00, z=38.50], EntityZombie['Zombie'/166, l='MpServer', x=-227.50, y=32.00, z=32.03], EntitySkeleton['Skeleton'/167, l='MpServer', x=-232.88, y=32.00, z=35.44], EntityBat['Bat'/168, l='MpServer', x=-241.38, y=15.94, z=58.97], EntityZombie['Zombie'/169, l='MpServer', x=-239.50, y=34.00, z=51.50], EntityBat['Bat'/297, l='MpServer', x=-139.47, y=33.00, z=91.16], EntitySquid['Squid'/170, l='MpServer', x=-239.63, y=52.75, z=60.47], EntityBat['Bat'/298, l='MpServer', x=-141.06, y=33.50, z=91.69], EntitySquid['Squid'/171, l='MpServer', x=-234.41, y=54.84, z=73.50], EntitySquid['Squid'/299, l='MpServer', x=-142.22, y=51.06, z=80.97], EntitySquid['Squid'/172, l='MpServer', x=-236.16, y=58.34, z=79.88], EntitySquid['Squid'/301, l='MpServer', x=-141.13, y=54.34, z=96.84], EntitySkeleton['Skeleton'/303, l='MpServer', x=-133.91, y=17.00, z=120.00], EntityCreeper['Creeper'/304, l='MpServer', x=-140.41, y=17.00, z=115.00], EntityCreeper['Creeper'/305, l='MpServer', x=-131.50, y=17.00, z=120.03], EntityBat['Bat'/306, l='MpServer', x=-131.13, y=17.75, z=115.94], EntitySpider['Spider'/183, l='MpServer', x=-212.28, y=22.00, z=-10.84], EntitySheep['Sheep'/184, l='MpServer', x=-210.81, y=70.00, z=-14.50], EntityZombie['Zombie'/185, l='MpServer', x=-215.91, y=18.00, z=2.50], EntityBat['Bat'/186, l='MpServer', x=-216.00, y=13.06, z=73.84], EntityBat['Bat'/187, l='MpServer', x=-216.53, y=16.41, z=69.50], EntityZombie['Zombie'/188, l='MpServer', x=-217.50, y=30.00, z=100.50], EntityZombie['Zombie'/189, l='MpServer', x=-216.50, y=30.00, z=103.50], EntitySpider['Spider'/91, l='MpServer', x=-271.47, y=19.00, z=-9.72], EntitySkeleton['Skeleton'/92, l='MpServer', x=-264.56, y=21.00, z=-15.94], EntityBat['Bat'/93, l='MpServer', x=-266.38, y=25.03, z=-2.94], EntityCreeper['Creeper'/95, l='MpServer', x=-257.50, y=18.00, z=34.50], EntityCreeper['Creeper'/96, l='MpServer', x=-259.00, y=18.00, z=35.56], EntityZombie['Zombie'/97, l='MpServer', x=-270.50, y=17.00, z=48.50], EntityCreeper['Creeper'/98, l='MpServer', x=-269.50, y=17.00, z=48.50], EntitySquid['Squid'/102, l='MpServer', x=-262.81, y=57.47, z=80.91], EntitySquid['Squid'/231, l='MpServer', x=-176.50, y=57.00, z=107.59], EntitySquid['Squid'/104, l='MpServer', x=-261.34, y=58.25, z=84.69], EntitySquid['Squid'/105, l='MpServer', x=-263.31, y=52.31, z=83.41], EntityZombie['Zombie'/108, l='MpServer', x=-256.09, y=15.00, z=99.53]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 323020584 bytes (308 MB) / 1019215872 bytes (972 MB) up to 1019215872 bytes (972 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 CoFHTweaks v1.0.1 Minecraft Forge 10.13.4.1566 96 mods loaded, 96 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	<CoFH Tweak>{1.7.10R1.0.1} [CoFH Tweak ASM] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14-core.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14-builders.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14-energy.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14-factory.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14-robotics.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14-silicon.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14-transport.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAAAA	ProjectE{1.7.10-PE1.9.3} [ProjectE] (ProjectE-1.7.10-PE1.9.3h.jar) 
	UCHIJAAAA	equivalentenergistics{0.6} [Equivalent Energistics] (EquivalentEnergistics - 0.6 - 1.7.10.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	Forestry{4.2.3.51} [Forestry for Minecraft] (forestry_1.7.10-4.2.3.51.jar) 
	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.7.10-5.1.3-unlimited.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	Mekanism{8.1.7} [Mekanism] (Mekanism-1.7.10-8.1.7.252.jar) 
	UCHIJAAAA	MekanismGenerators{8.1.7} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.7.252.jar) 
	UCHIJAAAA	MekanismTools{8.1.7} [MekanismTools] (MekanismTools-1.7.10-8.1.7.252.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.1.0} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.0.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCHIJAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJAAAA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJAAAA	OpenPeripheralCore{1.2} [OpenPeripheralCore] (OpenPeripheral-1.7.10-AIO-5.jar) 
	UCHIJAAAA	OpenPeripheral{0.4} [OpenPeripheralAddons] (OpenPeripheral-1.7.10-AIO-5.jar) 
	UCHIJAAAA	OpenPeripheralIntegration{0.3} [OpenPeripheralIntegration] (OpenPeripheral-1.7.10-AIO-5.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	Translocator{1.1.2.15} [Translocator] (Translocator-1.7.10-1.1.2.15-universal.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4256' Renderer: 'Intel(R) HD Graphics 4400'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	Mantle Environment: Environment healthy.
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0-12
	ThermalDynamics: -[1.7.10]1.1.0-161
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.15.4256, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by Vehiron** [comment]
I've tried running it with my GTX 970, but the same error occurs. All my drivers are up to date, so I have no idea what is going on.

**Comment by peterix** [comment]
Try removing fastcraft. It seems to be involved.

**Comment by Vehiron** [comment]
Okay, i removed Fastcraft and it fixed the problem. Thanks for that.

**Comment by peterix** [comment]
It would be best to report this problem to fastcraft's author.
Here:
http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820
