### ISSUE TITLE
FTBInfinity exported (works of FTB launcher)

### ISSUE THREAD

**Issue by Velken** [MultiMC/MultiMC5#1392]
I've exported my instance of Infinity to MultiMC so I could play offline, but I keep getting this error (other instances, like dw20, works just fine):
```
MultiMC version: 0.4.7

Minecraft folder is:
c:/ftb/Data/FTBInfinity/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_45/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en, -jar, C:/Users/brend_000/Desktop/Thiago/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 8712

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  c:/ftb/Data/FTBInfinity/natives

Traits:
  []

Libraries:
  C:/ftb/Data/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/ftb/Data/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/ftb/Data/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/ftb/Data/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/ftb/Data/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/ftb/Data/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/ftb/Data/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/ftb/Data/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/ftb/Data/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/ftb/Data/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/ftb/Data/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/ftb/Data/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/ftb/Data/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/ftb/Data/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/ftb/Data/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-universal.jar (missing)
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/com/google/guava/guava/16.0/guava-16.0.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/org/apache/commons/commons-lang3/3.2.1/commons-lang3-3.2.1.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/com/mojang/authlib/1.5.16/authlib-1.5.16.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/brend_000/Desktop/Thiago/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  c:/ftb/Data/versions/1.7.10/1.7.10.jar

Mods:
  AdvancedSolarPanel-1.7.10-3.5.1
  AgriCraft-1.7.10-1.4.5
  AOBD-2.8.4
  appliedenergistics2-rv2-stable-10
  Avaritia-0.2b
  bdlib-1.9.2.104-mc1.7.10
  BiblioCraft[v1.11.4][MC1.7.10]
  BiblioWoods[BiomesOPlenty][v1.9]
  BiblioWoods[Forestry][v1.7]
  BiblioWoods[Natura][v1.5]
  BigReactors-0.4.3A
  binnie-mods-2.0-pre14
  BiomesOPlenty-1.7.10-2.1.0.1396-universal
  BloodMagic-1.7.10-1.3.3-17
  Botania r1.7-237
  buildcraft-7.1.13
  buildcraft-compat-7.1.2
  Carpenter's Blocks v3.3.7 - MC 1.7.10
  ChickenChunks-1.7.10-1.3.4.19-universal
  Chisel-2.9.3.9
  CodeChickenCore-1.7.10-1.0.7.47-universal
  CoFHCore-[1.7.10]3.0.3-303
  CoFHLib-[1.7.10]1.0.3-175
  ComputerCraft1.74
  CustomMainMenu-MC1.7.10-1.9.2
  Decocraft-2.2.1_1.7.10
  denseores-1.6.2
  Draconic-Evolution-1.7.10-1.0.2-Snapshot_8-bugfix
  EnderIO-1.7.10-2.3.0.421_beta
  EnderZoo-1.7.10-1.0.15.32
  EnderCore-1.7.10-0.2.0.31_beta
  EnderStorage-1.7.10-1.4.7.37-universal
  EnderTech-1.7.10-0.3.2.405
  BrandonsCore-1.0.0.10-bugfix
  INpureCore-[1.7.10]1.0.0B9-62
  ExtraCells-1.7.10-2.3.2b158
  extrautilities-1.2.12
  ExtraTiC-1.7.10-1.4.5
  FastLeafDecay-1.7.10-1.3
  fastcraft-1.21
  Forbidden Magic-1.7.10-0.571
  forestry_1.7.10-3.6.6.24
  FTBTweaks-1.0.0
  FTBLib-1.7.10-1.0.11.3
  FTBUtilities-1.7.10-1.0.11.3
  funky-locomotion-1.7.10-beta-7
  gendustry-1.6.0.125-mc1.7.10
  GraviSuite-1.7.10-2.0.3
  Guide-API-1.7.10-1.0.1-20
  Hats-4.0.1
  HatStand-4.0.0
  Headcrumbs-1.6.2
  iChunUtil-4.2.2
  ImmersiveEngineering-0.6.2
  immersiveintegration-0.6.1
  industrialcraft-2-2.2.804-experimental
  InventoryTweaks-1.59-dev-152
  ironchest-1.7.10-6.0.62.742-universal
  Jabba-1.2.1a_1.7.10
  journeymap-1.7.10-5.1.3b1-unlimited
  logisticspipes-0.9.3.70
  magicbees-1.7.10-2.3.6
  Mantle-1.7.10-0.3.2b
  mcjtylib-1.8.0
  MineFactoryReloaded-[1.7.10]2.8.0-104
  MineTweaker3-1.7.10-3.0.10B
  ModTweaker2-0.9.4
  Morpheus-1.7.10-1.6.18
  mystcraft-1.7.10-0.12.3.01
  natura-1.7.10-2.2.0.1
  neiaddons-1.12.11.36-mc1.7.10
  NEIIntegration-MC1.7.10-1.0.12
  NetherOres-[1.7.10]2.3.0-12
  NotEnoughResources-1.7.10-0.1.0.106
  NotEnoughItems-1.7.10-1.0.5.118-universal
  IC2NuclearControl-2.3.3a-Exist
  OpenBlocks-1.7.10-1.4.4
  OpenModsLib-1.7.10-0.8
  OpenPeripheralAddons-1.7.10-0.4
  OpenPeripheralCore-1.7.10-1.2
  OpenPeripheralIntegration-1.7.10-0.3
  Pam's HarvestCraft 1.7.10k
  PortalGun-4.0.0-beta-6
  PortalGunSounds
  ProjectRed-1.7.10-4.7.0pre9.92-Compat
  ProjectRed-1.7.10-4.7.0pre9.92-Base
  ProjectRed-1.7.10-4.7.0pre9.92-Mechanical
  ProjectRed-1.7.10-4.7.0pre9.92-World
  ProjectRed-1.7.10-4.7.0pre9.92-Lighting
  ProjectRed-1.7.10-4.7.0pre9.92-Integration
  Railcraft_1.7.10-9.8.0.0
  RedstoneArsenal-[1.7.10]1.1.1-89
  ResourceLoader-1.2
  rftools-4.13
  runicdungeons-1.1.6a
  SimplyJetpacks-MC1.7.10-1.5.3
  SolarExpansion-Basic-1.6a
  Springboards-1.7.10-0.1
  StevesAddons-1.7.10-0.10.16
  StevesCarts2.0.0.b18
  StevesFactoryManagerA93
  StevesWorkshop-0.5.1
  StorageDrawers-1.7.10-1.7.2
  StorageDrawers-BiomesOPlenty-1.7.10-1.0.3
  StorageDrawers-Forestry-1.7.10-1.0.5
  StorageDrawers-Misc-1.7.10-1.0.2
  StorageDrawers-Natura-1.7.10-1.0.4
  Thaumcraft-1.7.10-4.2.3.5
  thaumcraftneiplugin-1.7.10-1.7a
  thaumicenergistics-0.8.10.10
  ThaumicExploration-1.7.10-1.1-53
  ThaumicTinkerer-2.5-1.7.10-512
  twilightforest-1.7.10-2.3.7
  ThermalDynamics-[1.7.10]1.1.0-161
  ThermalExpansion-[1.7.10]4.0.3B1-218
  ThermalFoundation-[1.7.10]1.2.0-102
  TiCTooltips-mc1.7.10-1.2.5
  TConstruct-1.7.10-1.8.8
  TMechworks-1.7.10-0.2.14.100
  Translocator-1.7.10-1.1.2.15-universal
  Waila-1.5.10_1.7.10
  WailaHarvestability-mc1.7.10-1.1.5
  Wawla-1.3.3-1.7.10
  witchery-1.7.10-0.24.1
  WR-CBE-1.7.10-1.4.1.9-universal

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, c:/ftb/Data/FTBInfinity/minecraft, --assetsDir, C:/Users/brend_000/Desktop/Thiago/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {"twitch_access_token":["<TWITCH_ACCESS_TOKEN>"]}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting lwjgl-platform-2.9.1-natives-windows.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting twitch-platform-5.16-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar

[00:32:45] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[00:32:45] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_45]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Game exited with exitcode 1.
```

**Comment by peterix** [comment]
```
  C:/ftb/Data/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-universal.jar (missing)
```

Forge isn't there.

Not sure how you exported it. Please elaborate.

**Comment by Velken** [comment]
Well, I checked the Track FTB instances box.
And the file is there, I've also tried launching with elevated permissions.

**Comment by peterix** [comment]
The file definitely isn't there, otherwise it wouldn't be missing. Maybe it's unreadable.

Easiest thing you can do:
Select the tracked instance.
Click the copy button.
Edit the instance.
In the version page:
* Revert Minecraft version using the revert button. (if needed)
* If there's a pack component, remove it
* Add real Forge

That should make a normal MultiMC instance out of it, completely disconnected from FTB.

**Comment by Velken** [comment]
I've deleted the forge at libraries\net\minecraftforge and downloaded a new forge lib. Now it is working (my guess: corrupted file)

**Comment by peterix** [comment]
OK.
