### ISSUE TITLE
unknown network based log spam

### ISSUE THREAD

**Issue by Spaig** [MultiMC/MultiMC5#1416]
Not sure if this is a MultiMC issue, but it did start right after the latest client upgrade, so it's a fair shot. While Minecraft is running and we're in game, the client side logs continuously give off a looping error, attached below. As far as we can tell, it's not actually causing any problems aside from making the log files gigantic, but we're kind of wondering what's up with this and it's beyond our areas of expertise. Looping section is below, full logs at 

http://paste.ee/r/I1DZb

```
Jan 18, 2016 7:47:20 PM io.netty.channel.embedded.EmbeddedChannel recordException
WARNING: More than one exception was raised. Will report only the first one and log others.
java.lang.NullPointerException
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:193)
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688)
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239)
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210)
	at cn.annoreg.mc.network.NetworkCallManager$1.invoke(NetworkCallManager.java:142)
	at cn.annoreg.mc.network.NetworkCallManager.onNetworkCall(NetworkCallManager.java:115)
	at cn.academy.ability.block.TileDeveloper.syncTheUser(TileDeveloper.java)
	at cn.academy.ability.block.TileDeveloper.func_145845_h(TileDeveloper.java:128)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
```

**Comment by peterix** [comment]
```
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210) [SimpleNetworkWrapper.class:?]
	at cn.annoreg.mc.network.NetworkCallManager$1.invoke(NetworkCallManager.java:142) [NetworkCallManager$1.class:?]
	at cn.annoreg.mc.network.NetworkCallManager.onNetworkCall(NetworkCallManager.java:115) [NetworkCallManager.class:?]
	at cn.academy.ability.block.TileDeveloper.syncTheUser(TileDeveloper.java) [TileDeveloper.class:?]
	at cn.academy.ability.block.TileDeveloper.func_145845_h(TileDeveloper.java:128) [TileDeveloper.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
```

That's AcademyCraft, which you can find the issue tracker of here:
https://github.com/LambdaInnovation/AcademyCraft/issues

**Comment by peterix** [comment]
Seeing that this is only one mod doing it, I doubt it is related to MultiMC in any way.

**Comment by Spaig** [comment]
Ah, welp. Thanks though!
