### ISSUE TITLE
Everytime I load world I get this crash report. 

### ISSUE THREAD

**Issue by PurpleFox327** [MultiMC/MultiMC5#1449]
```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2/3/16 8:12 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.WorldRenderer.func_78912_a(WorldRenderer.java:365)
	at net.minecraft.client.renderer.RenderGlobal.addToSortedWorldRenderers(RenderGlobal.java:2808)
	at net.minecraft.client.renderer.WorldRenderer.updateFinished(WorldRenderer.java:438)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:305)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1812)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1318)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1148)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.WorldRenderer.func_78912_a(WorldRenderer.java:365)
	at net.minecraft.client.renderer.RenderGlobal.addToSortedWorldRenderers(RenderGlobal.java:2808)
	at net.minecraft.client.renderer.WorldRenderer.updateFinished(WorldRenderer.java:438)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:305)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1812)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1318)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Purple_Fox327'/381, l='MpServer', x=409.16, y=67.62, z=-19.98]]
	Chunk stats: MultiplayerChunkCache: 140, 140
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (395,64,-1), Chunk: (at 11,4,15 in 24,-1; contains blocks 384,0,-16 to 399,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1178 game time, 1178 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 157 total; [EntityCreeper['Creeper'/256, l='MpServer', x=415.00, y=25.00, z=8.44], EntityZombie['Zombie'/257, l='MpServer', x=404.50, y=13.00, z=25.25], EntityZombie['Zombie'/258, l='MpServer', x=405.66, y=14.00, z=27.25], EntityBat['Bat'/259, l='MpServer', x=404.38, y=13.36, z=17.99], EntityBat['Bat'/260, l='MpServer', x=405.75, y=15.33, z=27.64], EntityBat['Bat'/261, l='MpServer', x=404.56, y=16.08, z=26.03], EntitySkeleton['Skeleton'/262, l='MpServer', x=411.50, y=17.00, z=30.50], EntityZombie['Zombie'/263, l='MpServer', x=406.51, y=14.00, z=32.38], EntityBat['Bat'/264, l='MpServer', x=411.93, y=17.22, z=31.62], EntityItem['item.tile.gravel'/276, l='MpServer', x=424.63, y=22.13, z=-80.81], EntitySquid['Squid'/277, l='MpServer', x=416.47, y=47.58, z=-83.81], EntitySquid['Squid'/278, l='MpServer', x=417.73, y=54.96, z=-81.69], EntitySquid['Squid'/279, l='MpServer', x=418.65, y=48.28, z=-81.70], EntityItem['item.tile.gravel'/280, l='MpServer', x=422.66, y=25.13, z=-77.72], EntityItem['item.tile.gravel'/281, l='MpServer', x=421.66, y=24.13, z=-79.81], EntityItem['item.tile.gravel'/282, l='MpServer', x=423.56, y=25.13, z=-78.59], EntityItem['item.tile.gravel'/283, l='MpServer', x=422.44, y=24.13, z=-78.53], EntityItem['item.tile.gravel'/284, l='MpServer', x=425.19, y=23.13, z=-78.63], EntitySquid['Squid'/285, l='MpServer', x=421.93, y=54.18, z=-71.74], EntitySquid['Squid'/286, l='MpServer', x=422.22, y=53.91, z=-76.24], EntitySquid['Squid'/287, l='MpServer', x=424.21, y=53.28, z=-79.78], EntitySquid['Squid'/288, l='MpServer', x=421.87, y=52.30, z=-66.80], EntitySquid['Squid'/289, l='MpServer', x=423.53, y=50.99, z=-62.49], EntitySquid['Squid'/290, l='MpServer', x=418.35, y=49.91, z=-55.26], EntitySquid['Squid'/291, l='MpServer', x=420.97, y=53.36, z=-63.11], EntityCreeper['Creeper'/292, l='MpServer', x=427.97, y=25.00, z=-25.44], EntityTFNagaSegment['unknown'/549, l='MpServer', x=0.00, y=0.00, z=0.00], EntityBat['Bat'/293, l='MpServer', x=429.41, y=26.10, z=-23.25], EntityTFNagaSegment['unknown'/550, l='MpServer', x=0.00, y=0.00, z=0.00], EntitySkeleton['Skeleton'/294, l='MpServer', x=422.94, y=54.00, z=-16.50], EntityTFNagaSegment['unknown'/551, l='MpServer', x=0.00, y=0.00, z=0.00], EntityZombie['Zombie'/295, l='MpServer', x=428.59, y=21.00, z=-3.34], EntityTFNagaSegment['unknown'/552, l='MpServer', x=0.00, y=0.00, z=0.00], EntityZombie['Zombie'/296, l='MpServer', x=430.31, y=21.00, z=-7.69], EntityTFNagaSegment['unknown'/553, l='MpServer', x=0.00, y=0.00, z=0.00], EntitySpider['Spider'/297, l='MpServer', x=431.25, y=21.00, z=-6.25], EntityTFNagaSegment['unknown'/554, l='MpServer', x=0.00, y=0.00, z=0.00], EntityCreeper['Creeper'/298, l='MpServer', x=418.50, y=24.00, z=5.50], EntityTFNagaSegment['unknown'/555, l='MpServer', x=0.00, y=0.00, z=0.00], EntityZombie['Zombie'/299, l='MpServer', x=424.69, y=21.00, z=1.09], EntityTFNagaSegment['unknown'/556, l='MpServer', x=0.00, y=0.00, z=0.00], EntitySquid['Squid'/300, l='MpServer', x=428.80, y=48.00, z=10.11], EntityTFNagaSegment['unknown'/557, l='MpServer', x=0.00, y=0.00, z=0.00], EntitySquid['Squid'/301, l='MpServer', x=424.41, y=48.11, z=6.26], EntityTFNagaSegment['unknown'/558, l='MpServer', x=0.00, y=0.00, z=0.00], EntitySquid['Squid'/302, l='MpServer', x=425.85, y=50.30, z=13.60], EntityTFNagaSegment['unknown'/559, l='MpServer', x=0.00, y=0.00, z=0.00], EntityCreeper['Creeper'/303, l='MpServer', x=429.29, y=39.00, z=45.50], EntityTFNagaSegment['unknown'/560, l='MpServer', x=0.00, y=0.00, z=0.00], EntityZombie['Zombie'/304, l='MpServer', x=426.50, y=38.00, z=42.59], EntityCreeper['Creeper'/305, l='MpServer', x=431.69, y=39.00, z=36.03], EntitySkeleton['Skeleton'/306, l='MpServer', x=428.03, y=13.00, z=50.69], EntitySkeleton['Skeleton'/307, l='MpServer', x=425.63, y=19.00, z=58.69], EntitySkeleton['Skeleton'/308, l='MpServer', x=428.82, y=19.00, z=60.50], EntitySkeleton['Skeleton'/310, l='MpServer', x=440.50, y=30.00, z=-80.13], EntityZombie['Zombie'/311, l='MpServer', x=432.00, y=25.00, z=-16.56], EntityZombie['Zombie'/312, l='MpServer', x=432.69, y=22.00, z=-5.31], EntityZombie['Zombie'/313, l='MpServer', x=432.69, y=21.00, z=-6.31], EntitySkeleton['Skeleton'/314, l='MpServer', x=446.16, y=36.00, z=0.50], EntitySquid['Squid'/315, l='MpServer', x=433.54, y=50.41, z=12.49], EntitySquid['Squid'/316, l='MpServer', x=435.74, y=48.05, z=11.97], EntitySquid['Squid'/317, l='MpServer', x=435.26, y=49.39, z=15.62], EntitySkeleton['Skeleton'/319, l='MpServer', x=432.31, y=19.00, z=27.50], EntitySkeleton['Skeleton'/320, l='MpServer', x=432.94, y=16.08, z=26.25], EntitySpider['Spider'/321, l='MpServer', x=432.94, y=16.00, z=26.22], EntityZombie['Zombie'/322, l='MpServer', x=436.50, y=34.00, z=22.50], EntityZombie['Zombie'/323, l='MpServer', x=443.41, y=38.00, z=24.91], EntitySkeleton['Skeleton'/324, l='MpServer', x=436.49, y=38.00, z=29.31], EntitySkeleton['Skeleton'/325, l='MpServer', x=435.50, y=38.00, z=30.50], EntitySquid['Squid'/326, l='MpServer', x=436.40, y=48.00, z=18.34], EntitySquid['Squid'/327, l='MpServer', x=434.86, y=48.00, z=16.70], EntitySkeleton['Skeleton'/334, l='MpServer', x=460.50, y=63.00, z=-66.50], EntityCreeper['Creeper'/335, l='MpServer', x=456.63, y=34.00, z=-8.09], EntityCreeper['Creeper'/336, l='MpServer', x=454.75, y=33.00, z=-0.97], EntityItem['item.tile.mushroom'/337, l='MpServer', x=463.16, y=16.13, z=14.09], EntityZombie['Zombie'/338, l='MpServer', x=461.50, y=16.00, z=9.50], EntityZombie['Zombie'/339, l='MpServer', x=462.50, y=16.00, z=8.50], EntityZombie['Zombie'/340, l='MpServer', x=460.53, y=16.00, z=3.94], EntityCreeper['Creeper'/341, l='MpServer', x=449.50, y=34.00, z=3.50], EntitySkeleton['Skeleton'/342, l='MpServer', x=453.06, y=33.00, z=1.31], EntitySkeleton['Skeleton'/343, l='MpServer', x=456.13, y=34.00, z=3.53], EntityZombie['Zombie'/344, l='MpServer', x=457.50, y=33.00, z=1.50], EntityCreeper['Creeper'/88, l='MpServer', x=330.38, y=21.00, z=-90.14], EntitySpider['Spider'/345, l='MpServer', x=455.84, y=33.00, z=0.72], EntityBat['Bat'/346, l='MpServer', x=454.59, y=25.10, z=20.25], EntityCreeper['Creeper'/347, l='MpServer', x=460.50, y=17.00, z=19.50], EntityZombie['Zombie'/348, l='MpServer', x=450.55, y=45.00, z=52.42], EntityZombie['Zombie'/349, l='MpServer', x=452.50, y=45.00, z=54.50], EntitySheep['Sheep'/354, l='MpServer', x=470.13, y=65.00, z=-22.06], EntitySheep['Sheep'/355, l='MpServer', x=468.56, y=68.00, z=-16.34], EntitySheep['Sheep'/356, l='MpServer', x=478.53, y=67.00, z=-21.66], EntityCreeper['Creeper'/100, l='MpServer', x=334.46, y=24.28, z=-48.67], EntityItem['item.tile.mushroom'/357, l='MpServer', x=464.19, y=16.13, z=14.91], EntityZombie['Zombie'/358, l='MpServer', x=473.06, y=18.00, z=13.50], EntityZombie['Zombie'/359, l='MpServer', x=470.85, y=17.00, z=13.09], EntityCreeper['Creeper'/360, l='MpServer', x=465.50, y=17.00, z=20.50], EntityZombie['Zombie'/361, l='MpServer', x=471.38, y=44.00, z=27.88], EntityZombie['Zombie'/362, l='MpServer', x=476.09, y=46.00, z=28.63], EntityCreeper['Creeper'/363, l='MpServer', x=469.31, y=48.00, z=35.31], EntityZombie['Zombie'/364, l='MpServer', x=464.50, y=29.00, z=57.50], EntityBat['Bat'/111, l='MpServer', x=336.45, y=29.41, z=47.55], EntitySheep['Sheep'/368, l='MpServer', x=486.78, y=67.00, z=-85.81], EntitySheep['Sheep'/372, l='MpServer', x=480.69, y=66.00, z=-20.53], EntitySquid['Squid'/120, l='MpServer', x=347.20, y=47.00, z=-68.07], EntitySquid['Squid'/123, l='MpServer', x=351.50, y=48.11, z=-65.47], EntitySkeleton['Skeleton'/125, l='MpServer', x=341.50, y=19.00, z=-59.50], EntityClientPlayerMP['Purple_Fox327'/381, l='MpServer', x=409.16, y=67.62, z=-19.98], EntitySkeleton['Skeleton'/126, l='MpServer', x=347.63, y=18.00, z=-59.88], EntityBat['Bat'/127, l='MpServer', x=347.92, y=20.00, z=-58.77], EntityBat['Bat'/128, l='MpServer', x=336.18, y=21.81, z=-56.94], EntityCreeper['Creeper'/136, l='MpServer', x=336.44, y=25.00, z=-46.97], EntitySquid['Squid'/138, l='MpServer', x=346.52, y=53.72, z=-4.35], EntitySquid['Squid'/140, l='MpServer', x=346.70, y=55.10, z=-12.09], EntitySquid['Squid'/144, l='MpServer', x=348.11, y=53.16, z=-1.46], EntityCreeper['Creeper'/157, l='MpServer', x=362.50, y=31.00, z=-96.50], EntityBat['Bat'/159, l='MpServer', x=359.99, y=23.17, z=-73.60], EntitySquid['Squid'/160, l='MpServer', x=356.35, y=47.38, z=-59.22], EntitySheep['Sheep'/187, l='MpServer', x=382.28, y=70.00, z=-8.41], EntityCreeper['Creeper'/188, l='MpServer', x=373.50, y=37.00, z=15.50], EntityCreeper['Creeper'/189, l='MpServer', x=380.50, y=39.00, z=15.50], EntitySheep['Sheep'/190, l='MpServer', x=376.81, y=70.00, z=7.88], EntitySheep['Sheep'/191, l='MpServer', x=372.25, y=69.00, z=10.41], EntityCreeper['Creeper'/192, l='MpServer', x=378.50, y=37.00, z=16.50], EntitySquid['Squid'/193, l='MpServer', x=376.64, y=58.91, z=27.90], EntitySquid['Squid'/194, l='MpServer', x=371.11, y=51.36, z=27.12], EntitySquid['Squid'/195, l='MpServer', x=383.24, y=57.61, z=29.55], EntitySquid['Squid'/196, l='MpServer', x=382.32, y=59.34, z=32.11], EntitySquid['Squid'/197, l='MpServer', x=379.36, y=57.25, z=26.50], EntitySquid['Squid'/199, l='MpServer', x=375.47, y=58.91, z=37.99], EntitySquid['Squid'/200, l='MpServer', x=379.69, y=57.84, z=35.52], EntitySquid['Squid'/225, l='MpServer', x=398.81, y=52.30, z=-63.20], EntitySheep['Sheep'/226, l='MpServer', x=388.44, y=68.00, z=-18.34], EntitySheep['Sheep'/227, l='MpServer', x=395.22, y=71.00, z=-5.16], EntitySheep['Sheep'/228, l='MpServer', x=390.38, y=70.00, z=-12.88], EntitySheep['Sheep'/229, l='MpServer', x=386.25, y=66.00, z=9.75], EntitySquid['Squid'/230, l='MpServer', x=394.67, y=55.74, z=26.02], EntitySquid['Squid'/231, l='MpServer', x=388.73, y=58.38, z=31.09], EntitySquid['Squid'/232, l='MpServer', x=393.09, y=52.98, z=19.56], EntitySquid['Squid'/233, l='MpServer', x=384.82, y=59.11, z=28.59], EntitySquid['Squid'/234, l='MpServer', x=384.30, y=56.36, z=41.67], EntitySquid['Squid'/235, l='MpServer', x=390.77, y=57.37, z=32.94], EntitySquid['Squid'/236, l='MpServer', x=386.19, y=56.32, z=34.19], EntitySquid['Squid'/241, l='MpServer', x=412.16, y=47.12, z=-68.53], EntitySquid['Squid'/242, l='MpServer', x=415.82, y=46.99, z=-71.82], EntitySquid['Squid'/243, l='MpServer', x=402.48, y=54.19, z=-74.39], EntitySquid['Squid'/244, l='MpServer', x=404.14, y=50.23, z=-75.73], EntitySquid['Squid'/245, l='MpServer', x=411.13, y=54.72, z=-69.59], EntitySquid['Squid'/246, l='MpServer', x=408.45, y=51.44, z=-66.04], EntitySquid['Squid'/247, l='MpServer', x=410.03, y=51.15, z=-74.94], EntitySquid['Squid'/248, l='MpServer', x=411.38, y=53.11, z=-69.23], EntitySquid['Squid'/249, l='MpServer', x=405.21, y=52.35, z=-65.53], EntitySquid['Squid'/250, l='MpServer', x=403.79, y=49.36, z=-60.68], EntitySquid['Squid'/251, l='MpServer', x=411.55, y=55.27, z=-61.55], EntitySquid['Squid'/252, l='MpServer', x=409.24, y=48.29, z=-55.26], EntitySheep['Sheep'/253, l='MpServer', x=409.26, y=65.16, z=-17.51], EntitySkeleton['Skeleton'/254, l='MpServer', x=413.91, y=54.00, z=-13.69], EntitySkeleton['Skeleton'/255, l='MpServer', x=415.56, y=54.00, z=-11.94]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 428858496 bytes (408 MB) / 1034944512 bytes (987 MB) up to 1034944512 bytes (987 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	BugfixMod{2.5.0} [BugfixMod] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.5.22.43} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
	UCHIJAAAA	OpenModsCore{0.9} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (_Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	AwesomeSauceCore{0.1.0} [AwesomeSauce Core] (AwesomeSauceCore-1.7.x-b52.jar) 
	UCHIJAAAA	AwesomeSauceComponents{0.1.0} [AwesomeSauce Components] (AwesomeSauceCore-1.7.x-b52.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14-core.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14-builders.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14-energy.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14-factory.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14-robotics.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14-silicon.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14-transport.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAAAA	Forestry{4.2.6.54} [Forestry for Minecraft] (forestry_1.7.10-4.2.6.54.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.3} [BuildCraft Compat] (buildcraft-compat-7.1.3.jar) 
	UCHIJAAAA	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UCHIJAAAA	bcadditions{2.2.5} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.2.5.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.4.10} [Chisel] (Chisel-2.9.4.10.jar) 
	UCHIJAAAA	elementalcreepers{4.3.0} [Elemental Creepers] (Elemental Creepers-universal_1.7.10-4.3.0.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.7.10-5.1.3-unlimited.jar) 
	UCHIJAAAA	LogisticsPipes{0.9.3.70} [Logistics Pipes] (logisticspipes-0.9.3.70.jar) 
	UCHIJAAAA	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre10.93} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre10.93-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre10.93} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre10.93-Integration.jar) 
	UCHIJAAAA	OpenComputers{1.5.22.43} [OpenComputers] (OpenComputers-MC1.7.10-1.5.22.43-universal.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	OpenAutomation{1.7.x-b160} [OpenAutomation] (OpenAutomation-1.7.x-b160.jar) 
	UCHIJAAAA	OpenMods{0.9} [OpenMods] (OpenModsLib-1.7.10-0.9.jar) 
	UCHIJAAAA	OpenBlocks{1.5} [OpenBlocks] (OpenBlocks-1.7.10-1.5.jar) 
	UCHIJAAAA	openfm{0.1.0.29} [OpenFM] (OpenFM-1.7.10-0.1.0-29.jar) 
	UCHIJAAAA	opengrave{1.7.10-1.5} [Open Grave] (OpenGrave-1.7.10-1.5.jar) 
	UCHIJAAAA	openlights{0.1.0.22} [OpenLights] (OpenLights-MC1.7.10-OC1.4-0.1.0.22.jar) 
	UCHIJAAAA	openmodularturrets{2.1.8-199} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.1.8-199.jar) 
	UCHIJAAAA	openprinter{0.1.0.130} [OpenPrinter] (OpenPrinter-MC1.7.10-0.1.0.130.jar) 
	UCHIJAAAA	opensecurity{1.0.87} [OpenSecurity] (OpenSecurity-1.7.10-1.0-87.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre10.93} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre10.93-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre10.93} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre10.93-World.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre10.93} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre10.93-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre10.93} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre10.93-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre10.93} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre10.93-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre10.93} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre10.93-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre10.93} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre10.93-Mechanical.jar) 
	UCHIJAAAA	smoothbedrock{2.2.0.9} [SmoothBedrock] (SmoothBedrock-1.7.10-2.2.0.9.jar) 
	UCHIJAAAA	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
	UCHIJAAAA	StevesAddons{0.10.16} [Steve's Addons] (StevesAddons-1.7.10-0.10.16.jar) 
	UCHIJAAAA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCHIJAAAA	StevesWorkshop{0.5.1} [Steve's Workshop] (StevesWorkshop-0.5.1.jar) 
	UCHIJAAAA	Translocator{1.1.2.16} [Translocator] (Translocator-1.7.10-1.1.2.16-universal.jar) 
	UCHIJAAAA	WailaNBT{1.4} [Waila NBT] (WailaNBT-1.7.10-1.4.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.43' Renderer: 'GeForce GTX 650/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: found misbehaving transformers: williewillus.BugfixMod.BugfixModClassTransformer(williewillus.BugfixMod.BugfixModClassTransformer@4fbbf99b) crashed with java.lang.NullPointerException(null),me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@459dadd2) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@55fae3db) returned non-null result: 0
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 650/PCIe/SSE2 GL version 4.5.0 NVIDIA 361.43, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by peterix** [comment]
Please, use the 'Upload' button on the console window.

**Comment by PurpleFox327** [comment]
@peterix Noted.

**Comment by PurpleFox327** [comment]
@peterix http://paste.ee/p/KNiB4
