### ISSUE TITLE
MultiMC exit code -1 

### ISSUE THREAD

**Issue by PotatoWarriorMC** [MultiMC/MultiMC5#1458]
It was working yesterday, now it doesn't work
[iDea4.txt](https://github.com/MultiMC/MultiMC5/files/120773/iDea4.txt)

**Comment by peterix** [comment]
Looks like your world files got corrupted. 

```
[16:43:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.util.zip.ZipException: Not in GZIP format
[16:43:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
[16:43:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
[16:43:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
[16:43:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:29)
[16:43:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.storage.MapStorage.func_75742_a(SourceFile:45)
[16:43:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.World.<init>(World.java:281)
[16:43:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
[16:43:54] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WorldServerOF.<init>(WorldServerOF.java:69)
```

```
[16:44:11] [Server thread/ERROR]: Chunk file at -81,-66 is in the wrong location; relocating. (Expected -81, -66, got -78, -70)
[16:44:11] [Server thread/ERROR] [FML]: HandshakeCompletionHandler exception
java.lang.ArrayIndexOutOfBoundsException: -24
	at net.minecraft.world.chunk.NibbleArray.func_76582_a(SourceFile:28) ~[apv.class:?]
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76665_b(SourceFile:75) ~[apz.class:?]
	at net.minecraft.world.chunk.Chunk.func_76628_c(Chunk.java:548) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:878) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:862) ~[apx.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:500) ~[aqk.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) ~[ms.class:?]
```

Corrupted files are bad. It's also hard to say where such an error could come from - is it a one time problem caused by a mod, or something much worse? Better play it safe and make a complete backup. Start with important things and prepare for more things to fail this way.

As for the world:
If you have a recent backup of the world, use that.

You could try removing chunks(s) it complains about. They seem to be at coords ( -81, -66) and (-78, -70). You could try opening it with MCEdit and removing those chunks, if it will even load.

Other than that, make a new world...

**Comment by PotatoWarriorMC** [comment]
Thanks For The Help
