### ISSUE TITLE
Minecraft forge start crash problem!

### ISSUE THREAD

**Issue by blackfirez** [MultiMC/MultiMC5#1464]
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2/10/16 2:11 PM
Description: Registering texture

java.lang.NoSuchFieldError: field_110553_a
	at shadersmodcore.client.ShadersTex.deleteTextures(ShadersTex.java:152)
	at net.minecraft.client.renderer.texture.AbstractTexture.func_147631_c(AbstractTexture.java)
	at net.minecraft.client.renderer.texture.SimpleTexture.loadTexture(SimpleTexture.java:27)
	at net.minecraft.client.renderer.texture.TextureManager.loadTexture(TextureManager.java:94)
	at net.minecraft.client.renderer.texture.TextureManager.bindTexture(TextureManager.java:50)
	at net.minecraft.client.Minecraft.loadScreen(Minecraft.java:749)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:558)
	at net.minecraft.client.Minecraft.run(Minecraft.java:922)
	at net.minecraft.client.main.Main.main(Main.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at shadersmodcore.client.ShadersTex.deleteTextures(ShadersTex.java:152)
	at net.minecraft.client.renderer.texture.AbstractTexture.func_147631_c(AbstractTexture.java)
	at net.minecraft.client.renderer.texture.SimpleTexture.loadTexture(SimpleTexture.java:27)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/gui/title/mojang.png
	Texture object class: net.minecraft.client.renderer.texture.SimpleTexture
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.loadTexture(TextureManager.java:94)
	at net.minecraft.client.renderer.texture.TextureManager.bindTexture(TextureManager.java:50)
	at net.minecraft.client.Minecraft.loadScreen(Minecraft.java:749)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:558)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:922)
	at net.minecraft.client.main.Main.main(Main.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 364602208 bytes (347 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7900 Series GL version 4.5.13416 Compatibility Profile Context 15.300.1025.1001, ATI Technologies Inc.
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: N/A
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
	Anisotropic Filtering: Off (1)
```

**Comment by peterix** [comment]
Use the `Upload` button on the console window after the crash. Post the link to the uploaded log.
