### ISSUE TITLE
Pack wont launch

### ISSUE THREAD

**Issue by Evan-mckay123** [MultiMC/MultiMC5#1465]
can i get some help, i made sure all the mods were 1.7.10 and it still isnt working
```
MultiMC version: 0.4.10-733

Minecraft folder is:
instances/Crazier Craft/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx2048m, -Duser.language=en, -jar, C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 4240

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/instances/Crazier Craft/natives

Traits:
  []

Libraries:
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-universal.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/versions/1.7.10/1.7.10.jar

Mods:
  adventurebackpack-1.7.10-0.8c (1)
  AetherCraft-1.7.10-1.4.3.24
  appliedenergistics2-rv3-beta-5
  Baubles-1.7.10-1.0.1.10 (1)
  BiblioCraft-Mod-1.7.10
  BiomesOPlenty-1.7.10-2.1.0.1548-universal (1)
  _BuildCraft-Mod-1.7.10
  Carpenters-Blocks-Mod-1.7.10
  Chisel2-2.5.1.44 (3)
  CodeChickenCore-1.7.10 (2)
  CoFHCore-[1.7.10]3.0.0B1-19
  darkcore-0.3-86 (1)
  Deadly-World-Mod-1.7.10
  Decocraft-v1.11_1.7.10
  denseores-1.5 (1)
  _Ender-IO-Mod-1.7.10
  Equivalent-Exchange-3-Mod-1.7.10
  extrautilities-1.1.0k
  fairylights-0.6-1.7.10 (1)
  Falling-Meteors-Mod-1.7.10
  fastcraft-1.21 (1)
  gilded-games-util-1.7.10-1.9 (1)
  Gravity-Gun-Mod-1.7.10
  HardcoreEnderExpansion  MC-1.7.10  v1.6.2
  Hats-Mod-1.7.10
  Hat-Stand-Mod-1.7.10
  iChun-Util-Mod-1.7.10 (1)
  inventorypets-1.7.10-1.3.91-universal
  Inventory-Tweaks-Mod-1.7.10
  Iron-Chests-Mod-1.7.10
  IvToolkit-1.7.10
  Java7Checker  MC-1.7.10  v1.1
  _Lycanites-Mobs-Mod-1.7.10
  magicalcrops-1.7.10_0.1 (1)
  Mantle-1.7.10-0.3.2b
  MineFactoryReloaded-[1.7.10]2.8.0-104
  MineTweaker3-1.7.10-3.0.10B
  MineTweakerRecipeMaker-1.7.10-1.1.0.11 (1)
  MobiusCore-1.2.5_1.7.10 (1)
  Morph-Beta-0.9.1
  MrCrayfishs-Furniture-Mod-1.7.10
  NetherOres-[1.7.10]2.3.0RC3-84
  Not-Enough-Items-1.7.10 (2)
  OpenBlocks-1.7.10-1.4.4-snapshot-653
  OpenModsLib-1.7.10-0.6
  OptiFine_1.7.10_HD_C1
  Pandoras-Box-Mod-1.7.10
  Portal-Gun-Mod-1.7.10
  ProjectSuperhuman - v1.2 - 1.7.10 (1)
  Roguelike-Dungeons-Mod-1.7.10
  Runic-Dungeons-Mod-1.7.10
  Soul-Shards-Reborn-Mod-1.7.10
  SoundFilters-0.8_for_1.7.X (2)
  Steves-Carts-2-Mod-1.7.10
  StorageDrawers-1.7.10-1.7.7 (1)
  tardismod-1.7.10-0.994-124-DS (1)
  orespawn-1.7.10-20.3 (1)
  Secret-Rooms-Mod-1.7.10
  TConstruct-1.7.10-1.8.8 (1)
  Trail-Mix-Mod-1.7.10
  Transformers-1.7.10-0.4.4
  VeinMiner-1.7.10_0.31.1.unknown (1)
  Vein-Miner-Mod-1.7.10
  WailaHarvestability-mc1.7.10-1.1.4
  Waila-Mod-1.7.10 (1)
  witchery-1.7.10-0.22.0

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/instances/Crazier Craft/minecraft, --assetsDir, C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 1280 x 720

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[15:02:31] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[15:02:31] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[15:02:31] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[15:02:31] [main/INFO] [FML]: Forge Mod Loader version 7.99.36.1558 for Minecraft 1.7.10 loading
[15:02:31] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_71, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_71
[15:02:32] [main/INFO] [FML]: [AppEng] Core Init
[15:02:32] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:02:32] [main/INFO] [STDERR]: [codechicken.core.launch.DepLoader$DepLoadInst:scanDepInfo:510]: Failed to load dependencies.info from CoFHCore-[1.7.10]3.0.0B1-19.jar as JSON
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.RuntimeException: Invalid filename format for dependency: CodeChickenLib-universal-@MCVERSION@-@VERSION@.jar
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.DepLoader$DepLoadInst.loadJson(DepLoader.java:558)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.DepLoader$DepLoadInst.loadJSon(DepLoader.java:521)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfo(DepLoader.java:507)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfos(DepLoader.java:497)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:445)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.DepLoader.load(DepLoader.java:584)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[15:02:32] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:54)
[15:02:33] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:02:33] [main/WARN] [FML]: The coremod fastcraft.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:02:33] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:02:33] [main/WARN] [FML]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:02:33] [main/WARN] [FML]: The coremod chylex.java7check.JavaCheckerCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:02:33] [main/WARN] [FML]: The coremod mcp.mobius.mobiuscore.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:02:33] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:02:33] [main/WARN] [FML]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:02:33] [main/WARN] [FML]: The coremod openmods.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:02:33] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_C1.jar
[15:02:33] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:02:34] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[15:02:34] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[15:02:34] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:02:34] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:02:34] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[15:02:34] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: acceptOptions
[15:02:34] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: injectIntoClassLoader
[15:02:34] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ClassTransformer
[15:02:34] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine URL: file:/C:/Users/Jeremy/Desktop/Modpacks/MULTIMC/MultiMC/instances/Crazier%20Craft/minecraft/mods/OptiFine_1.7.10_HD_C1.jar
[15:02:34] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ZIP file: java.util.zip.ZipFile@2145b572
[15:02:34] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:37] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[15:02:37] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[15:02:37] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:37] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:37] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:37] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:37] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:38] [main/INFO] [OpenMods]: openmods.config.simple.ConfigProcessor.process(ConfigProcessor.java:73): Parsing config file 'C:\Users\Jeremy\Desktop\Modpacks\MULTIMC\MultiMC\instances\Crazier Craft\minecraft\config\OpenModsLibCore.json'
[15:02:38] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:02:38] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.IllegalStateException: OpenModsLib not present, not yet loaded or too old (needs at least 0.7.1)
	at openblocks.OpenBlocksCorePlugin.getASMTransformerClass(OpenBlocksCorePlugin.java:16) ~[OpenBlocks-1.7.10-1.4.4-snapshot-653.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:105) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[15:02:38] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:313]: Failed to start Minecraft:
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:54)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 8 more
[15:02:38] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:57]: Exiting with -1
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArrayIndexOutOfBoundsException: 5
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[15:02:38] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:58)
Exception in thread "main" 
Process exited with code 1.
Clipboard copy at: 10 Feb 2016 15:02:58 -0800
```

**Comment by peterix** [comment]
Handled on discord.
