### ISSUE TITLE
Minecraft won't start, Just crashes

### ISSUE THREAD

**Issue by Emmanuel0124** [MultiMC/MultiMC5#1511]
Log: https://paste.ee/p/ZU07N

**Comment by whitephoenix0** [comment]
I need more details. What version of minecraft? Were you using mods? Are you sure this isn't an issue with your modpack?

**Comment by Heufneutje** [comment]
> Minecraft Version: 1.9
Is Modded: Probably not. Jar signature remains and client brand is untouched.

There are no mods involved here...

`org.lwjgl.LWJGLException: Pixel format not accelerated` generally points to a graphics driver issue. Possible fixes are renaming `multimc.exe` to `minecraft.exe` or updating the graphics drivers. You appear to be running Windows 10, which is known to cause issues with old integrated Intel graphics.

**Comment by peterix** [comment]
If you have intel graphics, you might have to use an older version of java. 8u51 is the last that works with the intel integrated GPUs *unsupported on windows 10*.

See:
#1276
http://www.intel.com/content/www/us/en/support/graphics-drivers/000005526.html
https://github.com/LWJGL/lwjgl/issues/119

**Comment by Emmanuel0124** [comment]
Yeah, there are no mods, and I will try using older Java. Thank you guys for your help. I will let you guys know what happens.

**Comment by peterix** [comment]
But that's the 64bit version...

**Comment by peterix** [comment]
Extract it into the MultiMC foder and make MultiMC use the `javaw.exe` inside.

**Comment by peterix** [comment]
The zip has a folder inside. Where it ends up doesn't really matter that much. Putting it into MultiMc's folder is fine. If you want to organize it a bit more... you could add a 'JREs' folder in there and extract it there.

Up to you. It just has to be accessible :)

**Comment by Emmanuel0124** [comment]
Nope, Didn't work. Just got this again

---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/10/16 11:26 AM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bcf.ap(SourceFile:594)
	at bcf.an(SourceFile:430)
	at bcf.a(SourceFile:377)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bcf.ap(SourceFile:594)
	at bcf.an(SourceFile:430)

-- Initialization --
Details:
Stacktrace:
	at bcf.a(SourceFile:377)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 470772704 bytes (448 MB) / 514850816 bytes (491 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>

The CPU is an intel Pentium T4500, I noticed it says unknown.
Also, is my hardware just too old? XD Cuz if it is, then I understand.

**Comment by Emmanuel0124** [comment]
Also, I'm windows 10, not 8.1, weird.

**Comment by peterix** [comment]
Again, refer to http://www.intel.com/content/www/us/en/support/graphics-drivers/000005526.html
