### ISSUE TITLE
Won't open - exited with code 1

### ISSUE THREAD

**Issue by Mutleymuffin** [MultiMC/MultiMC5#1530]
**MultiMC version:** 
MultiMC 5 Version 0.4.11-713

**Operating System:**
 OSx 64

**Summary of the issue or suggestion:**
It crashes

**What should happen:**
It should open...

**Steps to reproduce the issue (Add more if needed):**
Open MultiMC, try and open Minecraft

**Suspected cause:**
Its Broken

**Logs/Screenshots:**
https://paste.ee/p/7KuEs

**Additional Info:**
Please help me :)

**Comment by peterix** [comment]
This looks like a bug in Java.

Found something similar, a few lines of code before this one:
https://java.net/jira/browse/MACOSX_PORT-774

**Comment by peterix** [comment]
This shouldn't be returning a null pointer:
http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/sun/font/FontDesignMetrics.java#l156

```
    private static FontRenderContext getDefaultFrc() {

        if (DEFAULT_FRC == null) {
            AffineTransform tx;
            if (GraphicsEnvironment.isHeadless()) {
                tx = new AffineTransform();
            } else {
                tx =  GraphicsEnvironment
                    .getLocalGraphicsEnvironment()
                    .getDefaultScreenDevice()
                    .getDefaultConfiguration() // <-- HERE
                    .getDefaultTransform();
            }
            DEFAULT_FRC = new FontRenderContext(tx, false, false);
        }
        return DEFAULT_FRC;
    }
```

**Comment by peterix** [comment]
```
java.lang.NullPointerException
	at sun.font.FontDesignMetrics.getDefaultFrc(FontDesignMetrics.java:157) ~[?:1.8.0_71]
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:278) ~[?:1.8.0_71]
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113) ~[?:1.8.0_71]
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626) ~[?:1.8.0_71]
	at javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:276) ~[?:1.8.0_71]
	at com.apple.laf.AquaButtonUI.getPreferredSize(AquaButtonUI.java:443) ~[?:1.8.0_71]
	at com.apple.laf.AquaButtonUI.getMinimumSize(AquaButtonUI.java:431) ~[?:1.8.0_71]
	at javax.swing.JComponent.getMinimumSize(JComponent.java:1744) ~[?:1.8.0_71]
	at javax.swing.plaf.basic.BasicOptionPaneUI.addButtonComponents(BasicOptionPaneUI.java:693) ~[?:1.8.0_71]
	at javax.swing.plaf.basic.BasicOptionPaneUI.createButtonArea(BasicOptionPaneUI.java:630) ~[?:1.8.0_71]
	at com.apple.laf.AquaOptionPaneUI.createButtonArea(AquaOptionPaneUI.java:53) ~[?:1.8.0_71]
	at javax.swing.plaf.basic.BasicOptionPaneUI.installComponents(BasicOptionPaneUI.java:178) ~[?:1.8.0_71]
	at javax.swing.plaf.basic.BasicOptionPaneUI.installUI(BasicOptionPaneUI.java:141) ~[?:1.8.0_71]
	at javax.swing.JComponent.setUI(JComponent.java:666) ~[?:1.8.0_71]
	at javax.swing.JOptionPane.setUI(JOptionPane.java:1860) ~[?:1.8.0_71]
	at javax.swing.JOptionPane.updateUI(JOptionPane.java:1882) ~[?:1.8.0_71]
	at javax.swing.JOptionPane.<init>(JOptionPane.java:1845) ~[?:1.8.0_71]
	at javax.swing.JOptionPane.<init>(JOptionPane.java:1808) ~[?:1.8.0_71]
	at javax.swing.JOptionPane.<init>(JOptionPane.java:1776) ~[?:1.8.0_71]
	at javax.swing.JOptionPane.<init>(JOptionPane.java:1754) ~[?:1.8.0_71]
	at javax.swing.JOptionPane.<init>(JOptionPane.java:1734) ~[?:1.8.0_71]
	at javax.swing.JOptionPane.<init>(JOptionPane.java:1718) ~[?:1.8.0_71]
	at javax.swing.JOptionPane.<init>(JOptionPane.java:1706) ~[?:1.8.0_71]
	at codechicken.core.launch.DepLoader$Downloader.<init>(DepLoader.java:65) ~[DepLoader$Downloader.class:?]
	at codechicken.core.launch.DepLoader$DepLoadInst.loadDeps(DepLoader.java:460) ~[DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:449) ~[DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader.load(DepLoader.java:584) ~[DepLoader.class:?]
	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47) ~[CodeChickenCore-1.7.10-1.0.7.46-universal.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_71]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_71]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_71]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
```

**Comment by peterix** [comment]
Did the computer go to sleep or did it turn of the screen at any point? Adduming not, but I've seen that references in that other bug report.

**Comment by Mutleymuffin** [comment]
Nope, not at all.

**Comment by peterix** [comment]
You should report this to chickenbones (author of the mod) and it should end up on Java's bugtracker. You can give them a link to this issue, but this is not a problem with MultiMC.
