### ISSUE TITLE
Pack won't start

### ISSUE THREAD

**Issue by venraga** [MultiMC/MultiMC5#1553]
I followed the tutorial on how to set up a modpack and it won't start. Please help.
MultiMC version: 0.4.11-751Minecraft folder is:instances/Pughlands/minecraftJava path is:C:/Program Files/Java/jre1.8.0_65/bin/javaw.exeJava Arguments:[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx3072m, -Duser.language=en, -jar, C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/jars/NewLaunch.jar]Minecraft process ID: 3920Using onesix launcher.Main Class:  net.minecraft.launchwrapper.LaunchNative path:  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/instances/Pughlands/nativesTraits:  []Libraries:  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/libraries/net/minecraftforge/forge/1.8.9-11.15.1.1722/forge-1.8.9-11.15.1.1722-universal.jar  C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/versions/1.8.9/1.8.9.jarMods:  [1.8.8] SecurityCraft v1.8.1  ActuallyAdditions-1.8.9-r26  generators-0.9.19.4-mc1.8.9  Aroma1997Core-1.8.9-1.0.4.1  Aroma1997s-Dimensional-World-1.8.9-1.1.2.0  AutomatedRedstone-1.8.9-3.0.0  BaseMetals-1.7.4  BaublesHud-2.2.1  bdlib-1.10.0.23-mc1.8.9  BetterBuildersWands-0.5.1-1.8.9r83+04d387c  BetterTitleScreen-1.8.9-1.2  BiomesOPlenty-1.8.9-3.0.0.1927-universal  BloodMagic-1.8.9-2.0.0-19  Bookshelf-1.8.9-1.1.2.206  Bookshelf-API-1.8.9-2.3.6  Botania.r1.8-unofficial-0.6.4  BowInfinityFix-1.8.x-rv2  BuildingBricks-1.8.9-1.3.3  CD4017BE_lib-1.8.9-3.0.0  Chameleon-1.8.9-0.2.1  ChestTransporter-2.2.0-MC1.8.9  Chisel-MC1.8.9-0.0.2.6  ClayWorldGen-1.0.1  ComputerCraft1.78  craftingtweaks-mc1.8.9-3.0.52  craftingcraft-mc1.8.9-2.0.13  craftingtweaksaddons-mc1.8.9-3.0.8  CustomBackgrounds-1.0  DarkUtilities-1.8.9-1.0.0.18  deepresonance-1.8.9-1.1.4beta11  DummyCore-2.2.189.0  Durability Show-1.8.9-2.1.2  ElecCore-1.8.9-1.4.240  ElectricAdvantage-1.1.1  End Ores-1.0-a.009  EnderZoo-1.8.9-1.1.3.35  EnderCore-1.8.9-0.3.0.1-beta  denseores-1.8-alpha-2.0.0  MysticalCrops-1.3.1  ezstorage-1.8.9-1.2.6  FastLeafDecay-1.8-1.6  fastcraft-1.23  Fluxed Redstone-1.3.0.31  fluxedsolars-1.9  FTBLib-1.8.9-2.0.2  FTBUtilities-1.8.9-2.0.2  Furnus-1.8.9-1.73  graves-1.8.9-b45-universal  Hammerz-1.8.9-0.1.5.18  Harvest-1.8.9-1.0.0-2  HelpFixer-1.8.9-1.2.12  intangible-1.8.9-0.0.25  InventoryTweaks-1.60-beta-39  IronBackpacks-1.8-1.0.7  ironchest-1.8.9-6.0.125.770  journeymap-1.8.9-5.1.5-fairplay  jei_1.8.9-2.28.7.174  JEIAddons_1.8.9-0.12.0.57  LaunchGui-1.8.8-2.0.1-19-client  Loot++-1.4_for_1.8.9  malisiscore-1.8.9-2.0.5  malisisdoors-1.8.9-3.0.2  Mantle-1.8.9-0.8.2  mdecore-1.8.9-1.1.1  mcjtylib-1.8.9-1.8.1beta7  MCMultiPart-1.0.8-universal  MorePlayerModels_1.8.9(27feb16)  Morpheus-1.8.9-2.0.58  MrCrayfishFurntiureModv3.6.1(1.8.9)  NeoTech-1.8.9-2.4.1  netherportalfix-mc1.8.9-2.1.6  OreDictionaryConverter-1.7.2  Packing Tape-0.3.5  Pam's Get all the Seeds! 1.8.9a  parachutemod-ng-1.8.9-1.2.2-341  PowerAdvantage-1.5.3  pressure-1.3.0.18-mc1.8.9  ProgressiveAutomation-1.8.9-1.6.35  Psi-beta-19  quantumflux-1.8.9-2.0.0-b3  RandomThings-MC1.8.9-3.6.4  RebornCore-1.8.9-1.4.3.20-universal  reptilemod-1.8.9-3.2.1-40  rftools-1.8.9-4.22beta28  rftoolsdim-1.8.9-4.22beta25  ringkydinks-1.8.9-beta2  RoguelikeDungeons-1.8.9-1.4.5  RopeBridge-v1.3-mc1.8.8  RouterReborn-1.8.9-3.0.5.5_universal  Sigma-0.7  SilentsGems-1.8.9-1.3.10-104  sodacanutils-2.0.4  SteamAdvantage-1.5.3  StorageDrawers-1.8.9-2.4.4  StorageNetwork-1.8.9-1.7.3  Thaumcraft-1.8.9-5.2.1  tchelper-1.8.9-1.4  TConstruct-1.8.9-2.1.0  Trashcans-1.8.9-1.0.1  trashslot-mc1.8.9-2.0.7  Waila-1.6.0-B3_1.8.8  WailaHarvestability-mc1.8.x-1.1.6  waterhooks-2.2.0  CyanosWonderfulWands_1.8.9-1.8.0  worldedit-forge-mc1.8.9-6.1.1Params:  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/instances/Pughlands/minecraft, --assetsDir, C:/Users/Moki/Desktop/MAYBE U WORK NOW/MultiMC/assets, --assetIndex, 1.8, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, legacy, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker]Window size: 854 x 480Preparing native libraries...Extracting twitch-platform-6.5-natives-windows-64.jarExtracting twitch-external-platform-4.5-natives-windows-64.jarExtracting jinput-platform-2.0.5-natives-windows.jarExtracting lwjgl-platform-2.9.1-natives-windows.jar2016-04-23 14:51:40,741 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream[14:51:40] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker[14:51:40] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker[14:51:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker[14:51:40] [main/INFO]: Forge Mod Loader version 11.15.1.1722 for Minecraft 1.8.9 loading[14:51:40] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_65, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_65[14:51:41] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft2016-04-23 14:51:41,094 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream2016-04-23 14:51:41,201 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream[14:51:41] [main/WARN]: The coremod com.github.parker8283.bif.BIFLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft[14:51:41] [main/INFO]: Loading tweaker fastcraft.Tweaker from fastcraft-1.23.jar[14:51:41] [main/WARN]: The coremod com.olafski.fastleafdecay.FldLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft[14:51:41] [main/WARN]: The coremod io.drakon.forgelinFR.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft[14:51:41] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft[14:51:41] [main/WARN]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft[14:51:41] [main/WARN]: The coremod com.mattdahepic.mdecore.asm.MDECoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft[14:51:41] [main/WARN]: The coremod lumien.randomthings.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft[14:51:41] [main/WARN]: The coremod thaumcraft.loader.ThaumcraftLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft[14:51:41] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker[14:51:41] [main/INFO]: Loading tweak class name fastcraft.Tweaker[14:51:41] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker[14:51:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker[14:51:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker[14:51:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:43] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557[14:51:43] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc[14:51:43] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:43] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:43] [main/INFO]: Finished data injection.[14:51:43] [main/INFO]: Finished data injection.[14:51:43] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:43] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:43] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:43] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:43] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:43] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker[14:51:44] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:44] [main/INFO]: Starting to apply transformations[14:51:44] [main/INFO]: Starting to apply transformations[14:51:44] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:44] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:44] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:44] [main/INFO]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World[14:51:44] [main/INFO]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World[14:51:44] [main/INFO]: [ChunkCollisionTransformer] Hook registered for net.minecraft.item.ItemBlock[14:51:44] [main/INFO]: [ChunkCollisionTransformer] Hook registered for net.minecraft.network.NetHandlerPlayServer[14:51:44] [main/INFO]: [ChunkBlockTransformer] Hook registered for net.minecraft.world.chunk.Chunk[14:51:44] [main/INFO]: [MalisisRendererTransformer] Hook registered for net.minecraft.client.renderer.BlockRendererDispatcher[14:51:44] [main/INFO]: [MalisisRendererTransformer] Hook registered for net.minecraft.client.renderer.entity.RenderItem[14:51:44] [main/INFO]: [MalisisRendererTransformer] Hook registered for net.minecraft.client.renderer.BlockModelShapes[14:51:44] [main/INFO]: [TextureMapTransformer] Hook registered for net.minecraft.client.renderer.texture.TextureMap[14:51:44] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:44] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:44] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:44] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper[14:51:44] [main/INFO]: Calling tweak class fastcraft.Tweaker[14:51:44] [main/WARN]: Initialization pending while executing for cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:313]: Failed to start Minecraft:[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:395]: java.lang.reflect.InvocationTargetException[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:395]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:395]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:395]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:395]: 	at java.lang.reflect.Method.invoke(Unknown Source)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:395]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:395]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:395]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:170)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:395]: 	at org.multimc.EntryPoint.main(EntryPoint.java:54)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/common/asm/transformers/deobf/FMLDeobfuscatingRemapper[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: 	at fastcraft.C.b(F:4300)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: 	at fastcraft.C.b(F:138)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: 	at fastcraft.a.b(F:116)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: 	at fastcraft.L.<init>(F:44)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: 	at java.lang.Class.newInstance(Unknown Source)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: 	at fastcraft.Tweaker.injectIntoClassLoader(F:16)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)[14:51:44] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:314]: 	... 8 more[14:51:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper[14:51:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)[14:51:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)[14:51:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)[14:51:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 20 more[14:51:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException[14:51:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)[14:51:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 22 more[14:51:44] [main/INFO]: [org.multimc.EntryPoint:main:57]: Exiting with -1[14:51:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.ArrayIndexOutOfBoundsException: 5[14:51:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)[14:51:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)[14:51:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)[14:51:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)[14:51:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:58)Exception in thread "main" Process exited with code 1.MultiMC: Log upload triggered at: 23 Apr 2016 15:01:53 -0400

**Comment by Loetkolben** [comment]
Sorry, but this log is pretty unreadable (the newlines are missing, I put the log in code tags so it's not a wall of text, but the newlines where already missing - I promise!).
Please give us the link to the uploaded log, than we may be able to help you.

**Comment by venraga** [comment]
I edited the post. Hopefully it helps.

**Comment by QuImUfu** [comment]
This crash was caused by you using fastcraft for 1.7.10 on a 1.8.9 modpack. 
(There is currently no version of fastcraft for 1.8.9)

**Comment by venraga** [comment]
Lol.. that is the only reason? Wow Thank you. =D
