### ISSUE TITLE
Realms Module missing?

### ISSUE THREAD

**Issue by SeeEmAge** [MultiMC/MultiMC5#1573]
Hello! Its me again with the Liteloader Problem!

MMC Version: 0.4.12-develop-750 Win/OS X

Now i get a new error... Since 1.9.4 i get the error REALMS MODULE IS MISSING!
There is nothing more... I think it crashing my lideloader instance too because i am getting this
error:

```
20:31:32] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker has already been visited -- skipping
[20:31:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]: java.lang.ClassNotFoundException: The specified class 'com.mojang.realmsclient.RealmsMainScreen' was not found
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.spongepowered.asm.mixin.transformer.TreeInfo.loadClass(TreeInfo.java:96)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.spongepowered.asm.mixin.transformer.TreeInfo.getClassNode(TreeInfo.java:59)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1497)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:359)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:332)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:286)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.spongepowered.asm.mixin.transformer.MixinConfig.initialiseMixins(MixinConfig.java:379)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.spongepowered.asm.mixin.transformer.MixinConfig.initialise(MixinConfig.java:312)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.spongepowered.asm.mixin.transformer.MixinTransformer.initConfigs(MixinTransformer.java:630)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.spongepowered.asm.mixin.transformer.MixinTransformer.init(MixinTransformer.java:563)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:472)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:179)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at java.lang.Class.forName0(Native Method)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at java.lang.Class.forName(Class.java:348)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at java.lang.reflect.Method.invoke(Method.java:498)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[20:31:33] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.ClassInfo:forName:1500]:  at org.multimc.EntryPoint.main(EntryPoint.java:54)
[20:31:33] [main/ERROR] [mixin]: InvalidMixinException has no mixin!
org.spongepowered.asm.mixin.transformer.InvalidMixinException: Error initialising mixin null - class org.spongepowered.asm.mixin.MixinException: @Mixin target com.mojang.realmsclient.RealmsMainScreen was not found mixins.liteloader.client.json:MixinRealmsMainScreen
    at org.spongepowered.asm.mixin.transformer.MixinConfig.initialiseMixins(MixinConfig.java:399) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinConfig.initialise(MixinConfig.java:312) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.initConfigs(MixinTransformer.java:630) [liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.init(MixinTransformer.java:563) [liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:472) [liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:179) [liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_91]
    at java.lang.Class.forName0(Native Method) [?:1.8.0_91]
    at java.lang.Class.forName(Class.java:348) [?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: org.spongepowered.asm.mixin.MixinException: @Mixin target com.mojang.realmsclient.RealmsMainScreen was not found mixins.liteloader.client.json:MixinRealmsMainScreen
    at org.spongepowered.asm.mixin.transformer.MixinInfo.checkTarget(MixinInfo.java:371) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:360) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:332) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:286) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinConfig.initialiseMixins(MixinConfig.java:379) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    ... 21 more
[20:31:33] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: org.spongepowered.asm.mixin.MixinException: org.spongepowered.asm.mixin.transformer.InvalidMixinException: Error initialising mixin null - class org.spongepowered.asm.mixin.MixinException: @Mixin target com.mojang.realmsclient.RealmsMainScreen was not found mixins.liteloader.client.json:MixinRealmsMainScreen
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:475) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:179) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
    ... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.InvalidMixinException: Error initialising mixin null - class org.spongepowered.asm.mixin.MixinException: @Mixin target com.mojang.realmsclient.RealmsMainScreen was not found mixins.liteloader.client.json:MixinRealmsMainScreen
    at org.spongepowered.asm.mixin.transformer.MixinConfig.initialiseMixins(MixinConfig.java:399) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinConfig.initialise(MixinConfig.java:312) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.initConfigs(MixinTransformer.java:630) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.init(MixinTransformer.java:563) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:472) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:179) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
    ... 14 more
Caused by: org.spongepowered.asm.mixin.MixinException: @Mixin target com.mojang.realmsclient.RealmsMainScreen was not found mixins.liteloader.client.json:MixinRealmsMainScreen
    at org.spongepowered.asm.mixin.transformer.MixinInfo.checkTarget(MixinInfo.java:371) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:360) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:332) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:286) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinConfig.initialiseMixins(MixinConfig.java:379) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinConfig.initialise(MixinConfig.java:312) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.initConfigs(MixinTransformer.java:630) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.init(MixinTransformer.java:563) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:472) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:179) ~[liteloader-1.9.4.jar:1.9.4-SNAPSHOT+jnks-b7.git-b98d20880bf15e845ae5c0cc7a5b9bcd0e660d7c]
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
    ... 14 more
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:285]: Failed to start Minecraft:
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:364]: java.lang.reflect.InvocationTargetException
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:364]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:364]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:364]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:364]:    at java.lang.reflect.Method.invoke(Method.java:498)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:364]:    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:364]:    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:364]:    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:364]:    at org.multimc.EntryPoint.main(EntryPoint.java:54)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:286]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:286]:   at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:286]:   at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:286]:   at java.lang.Runtime.exit(Runtime.java:107)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:286]:   at java.lang.System.exit(System.java:971)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:286]:   at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:286]:   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:31:33] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:286]:   ... 8 more
[20:31:33] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:57]: Exiting with -1
[20:31:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ArrayIndexOutOfBoundsException: 5
[20:31:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[20:31:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[20:31:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.Runtime.exit(Runtime.java:107)
[20:31:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.System.exit(System.java:971)
[20:31:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at org.multimc.EntryPoint.main(EntryPoint.java:58)
Exception in thread "main" 
Das Program wurde mit Status 1 beendet.
```

**Comment by peterix** [comment]
Works for me. Try removing the realms libraries from the 'libraries' folder.

**Comment by peterix** [comment]
Updated the gist with the 1.9.4 liteloader:
https://gist.github.com/peterix/d5571257e7d4511a9018

**Comment by peterix** [comment]
![image](https://cloud.githubusercontent.com/assets/203326/15387943/e193d42e-1daf-11e6-9721-84f6a6da841f.png)

**Comment by peterix** [comment]
Remove this one:
![image](https://cloud.githubusercontent.com/assets/203326/15388045/5f9bd6d2-1db0-11e6-9c2f-2f0f6b9da99b.png)

It should get re-downloaded.
