### ISSUE TITLE
[1.7.10] java.lang.VerifyError

### ISSUE THREAD

**Issue by deframet** [MultiMC/MultiMC5#1576]
System Information
-----------------------------
MultiMC version: MultiMC 5 0.4.11-751

Operating System: Windows 10 (Version 1151, Build 10586.318)

Minecraft version: 1.7.10

Forge version: 10.13.4.1614

Summary of the issue or suggestion:
----------------------------------------------
Immediate crash

Then I tried doubling the memory but nothing....

What should happen:
------------------------------
Minecraft inizialize ---> The window pops up ---> Immediately crashes

Suspected cause:
---------------------------
MultiMC bug

Logs/Screenshots:
----------------------------
[crash](https://github.com/MultiMC/MultiMC5/files/277988/crash-2016-05-23_19.23.18-client.txt)

```
---- Minecraft Crash Report ----
// Oops.

Time: 5/23/16 7:23 PM
Description: Initializing game

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/client/renderer/RenderBlocks.func_147805_b(Lnet/minecraft/block/Block;III)Z @9: invokestatic
  Reason:
    Type integer (current frame, stack[3]) is not assignable to 'net/minecraft/block/Block'
  Current Frame:
    bci: @9
    flags: { }
    locals: { 'net/minecraft/client/renderer/RenderBlocks', 'net/minecraft/block/Block', integer, integer, integer }
    stack: { 'net/minecraft/block/Block', integer, integer, integer, integer, integer, integer }
  Bytecode:
    0x0000000: 2b1c 1d15 041c 1d15 04b8 00eb 3605 2ab4
    0x0000010: 0071 1c1d 1504 2b15 05b8 00f1 3605 1505
    0x0000020: 02a0 0005 03ac 2b2a b400 711c 1d15 04b6
    0x0000030: 00f5 2a2b b600 f715 05aa 0000 0000 028f
    0x0000040: 0000 0000 0000 0029 0000 00b7 0000 00d5
    0x0000050: 0000 00ec 0000 0156 0000 00c1 0000 0117
    0x0000060: 0000 014c 0000 016d 0000 0163 0000 012b
    0x0000070: 0000 0177 0000 0100 0000 019e 0000 0121
    0x0000080: 0000 01bc 0000 01c6 0000 01ed 0000 01f8
    0x0000090: 0000 0203 0000 0138 0000 00f6 0000 021a
    0x00000a0: 0000 028f 0000 0142 0000 0227 0000 024e
    0x00000b0: 0000 025b 0000 0184 0000 0268 0000 01a8
    0x00000c0: 0000 01b2 0000 00cb 0000 0191 0000 0234
    0x00000d0: 0000 0275 0000 0241 0000 01d3 0000 01e0
    0x00000e0: 0000 0282 0000 010d 0000 00df 0000 0210
    0x00000f0: 2a2b 1c1d 1504 b600 faac 2a2b 1c1d 1504
    0x0000100: b600 fdac 2a2b 1c1d 1504 b601 00ac 2a2b
    0x0000110: 1c1d 1504 b601 03ac 2a2b c001 051c 1d15
    0x0000120: 04b6 0109 ac2a 2b1c 1d15 04b6 010c ac2a
    0x0000130: 2b1c 1d15 04b6 010f ac2a 2bc0 0111 1c1d
    0x0000140: 1504 b601 15ac 2a2b 1c1d 1504 b601 18ac
    0x0000150: 2a2b 1c1d 1504 b601 1bac 2a2b 1c1d 1504
    0x0000160: b601 1eac 2a2b c001 201c 1d15 04b6 0124
    0x0000170: ac2a 2b1c 1d15 04b6 0127 ac2a 2b1c 1d15
    0x0000180: 04b6 012a ac2a 2b1c 1d15 04b6 012d ac2a
    0x0000190: 2bc0 012f 1c1d 1504 b601 33ac 2a2b 1c1d
    0x00001a0: 1504 b601 36ac 2a2b 1c1d 1504 b601 39ac
    0x00001b0: 2a2b c001 3b1c 1d15 04b6 013f ac2a 2bc0
    0x00001c0: 0141 1c1d 1504 b601 45ac 2a2b c001 471c
    0x00001d0: 1d15 04b6 014b ac2a 2b1c 1d15 04b6 014e
    0x00001e0: ac2a 2b1c 1d15 04b6 0151 ac2a 2b1c 1d15
    0x00001f0: 04b6 0154 ac2a 2b1c 1d15 04b6 0157 ac2a
    0x0000200: 2bc0 0159 1c1d 1504 b601 5dac 2a2b c001
    0x0000210: 5f1c 1d15 04b6 0163 ac2a 2bc0 0165 1c1d
    0x0000220: 1504 b601 69ac 2a2b 1c1d 1504 03b6 016d
    0x0000230: ac2a 2b1c 1d15 0404 b601 70ac 2a2b c001
    0x0000240: 721c 1d15 04b6 0176 ac2a 2b1c 1d15 04b6
    0x0000250: 0179 ac2a 2bc0 017b 1c1d 1504 b601 7fac
    0x0000260: 2a2b c001 811c 1d15 04b6 0185 ac2a 2bc0
    0x0000270: 0187 1c1d 1504 b601 8bac 2a2b c001 8d1c
    0x0000280: 1d15 04b6 0191 ac2a 2bc0 0193 1c1d 1504
    0x0000290: b601 97ac 2a2b c001 991c 1d15 04b6 019d
    0x00002a0: ac2a 2bc0 019f 1c1d 1504 b601 a3ac 2a2b
    0x00002b0: c001 a51c 1d15 04b6 01a9 ac2a 2bc0 01ab
    0x00002c0: 1c1d 1504 b601 afac 2a2a b400 711c 1d15
    0x00002d0: 042b 1505 b801 b5ac                    
  Stackmap Table:
    append_frame(@38,Integer)
    same_frame_extended(@240)
    same_frame(@250)
    same_frame(@260)
    same_frame(@270)
    same_frame(@280)
    same_frame(@293)
    same_frame(@303)
    same_frame(@313)
    same_frame(@326)
    same_frame(@336)
    same_frame(@346)
    same_frame(@356)
    same_frame(@369)
    same_frame(@379)
    same_frame(@389)
    same_frame(@399)
    same_frame(@412)
    same_frame(@422)
    same_frame(@432)
    same_frame(@445)
    same_frame(@458)
    same_frame(@471)
    same_frame(@481)
    same_frame(@491)
    same_frame(@501)
    same_frame(@511)
    same_frame(@524)
    same_frame(@537)
    same_frame(@550)
    same_frame(@561)
    same_frame(@572)
    same_frame(@585)
    same_frame(@595)
    same_frame(@608)
    same_frame(@621)
    same_frame(@634)
    same_frame(@647)
    same_frame(@660)
    same_frame(@673)
    same_frame(@686)
    same_frame(@699)
    same_frame(@712)

	at net.minecraft.client.renderer.entity.Render.<init>(SourceFile:26)
	at net.minecraft.client.renderer.entity.RenderItem.<init>(RenderItem.java:46)
	at net.minecraft.client.gui.achievement.GuiAchievement.<init>(SourceFile:29)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:469)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.Render.<init>(SourceFile:26)
	at net.minecraft.client.renderer.entity.RenderItem.<init>(RenderItem.java:46)
	at net.minecraft.client.gui.achievement.GuiAchievement.<init>(SourceFile:29)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:469)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:282)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:364)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1668317752 bytes (1591 MB) / 1762656256 bytes (1681 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 365.10, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [F32-1.7.10.zip]
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On **(4)**
```

[complete log](https://paste.ee/p/icFBR)

Additional Info:
---------------------------
[modlist](https://github.com/MultiMC/MultiMC5/files/277984/modlist.txt)

```
[1.7.10]DamageIndicatorsMod-3.2.3.jar
[1.7.10]StatusEffectHUD-client-1.27.jar
[1.7.10]Treecapitator-universal-2.0.4.jar
1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar
1.7.10-Pistronics2-v0.6.3.jar
4Space-4.1.9.jar
ABO-MC1.7.10-BC7-release3.0.1.jar
additionalpipes-4.6.0.jar
advanced-machines-59.0.2.jar
AdvancedSolarPanel-1.7.10-3.5.1.jar
ae2stuff-0.5.0.56-mc1.7.10.jar
AgriCraft-1.7.10-1.5.0.jar
AnimationAPI-1.7.10-1.2.4.jar
AOBD-2.9.1.jar
AppleCore-mc1.7.10-1.1.0.jar
AppleMilkTea2-1.7.10_2.8o.jar
appliedenergistics2-rv3-beta-5.jar
Aroma1997Core-1.7.10-1.0.2.16.jar
Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar
AromaBackup-1.7.10-0.1.0.0.jar
AsieLib-1.7.10-0.4.5.jar
ATG-1.7.10-0.12.0.jar
AttachableGrinder-4.0.0.jar
Avaritia-1.11.jar
backpack-2.0.1-1.7.x.jar
bdlib-1.9.4.109-mc1.7.10.jar
Better HUD by NukeDuck [1.7.10][1.3.5].jar
BetterFoliage-MC1.7.10-2.0.4.jar
BetterRecords-1.7.10-1.2.0.jar
BiblioCraft[v1.11.4][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiblioWoods[ExtraBiomesXL][v1.4].jar
BiblioWoods[Forestry][v1.7].jar
BiblioWoods[Natura][v1.5].jar
BigReactors-0.4.3A.jar
Binnie Patcher 1.6.jar
binnie-mods-2.0-pre14.jar
BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar
Bookshelf-1.7.10-1.2.0.jar
Botania r1.8-249.jar
BrandonsCore-1.0.0.12.jar
buildcraft-7.1.16.jar
buildcraft-compat-7.1.3.jar
BuildcraftAdditions-1.7.10-2.2.5.jar
Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
CartFixes-1.7.10-0.1.0.jar
catwalks-2.0.3.jar
ChickenChunks-1.7.10-1.3.4.19-universal.jar
Chisel-2.9.5.11.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.1.2-325.jar
CoFHLib-[1.7.10]1.1.1-181.jar
compacter-1.1.0.12-mc1.7.10.jar
compactmachines-1.7.10-1.21.jar
CompactSolars-1.7.10-4.4.39.315-universal.jar
compactstorage-1.7.10-release-2.1.0-lts.21-universal.jar
ComputerCraft1.75.jar
ComputerCraftEdu1.74.jar
Computronics-1.7.10-1.6.0.jar
CookieCore-1.7.10-1.3.1-5.jar
coroutil-1.1.2 for MC v1.7.10.jar
CraftHeraldry 1.1.3.jar
darkcore-0.25-35.jar
Decocraft-2.3.2_1.7.10.jar
DefenseTech-1.7.10-1.0.1.26.jar
denseores-1.6.2.jar
dimensional-anchor-59.0.2.jar
Draconic-Evolution-1.7.10-1.0.2b.jar
DragonAPI 1.7.10 V12e.jar
DrZharks MoCreatures Mod v6.3.1.zip
DynamicLights-1.7.10.jar
ElectricalAge_BETA-1.10_r50.jar
ElectriCraft 1.7.10 V12c.jar
EnchantingPlus-1.7.10-3.0.2-d.jar
EnderCompass-1.7.10-1.2.jar
EnderCore-1.7.10-0.2.0.34_beta.jar
EnderIO-1.7.10-2.3.0.424_beta.jar
EnderIOAddons-1.7.10-2.3.0.424_beta-0.10.7.50_beta.jar
EnderStorage-1.7.10-1.4.7.37-universal.jar
EnderTech-1.7.10-0.3.2.405.jar
Eureka-1.7.10-3.0.2.jar
Extinguisher-V0.1 - 1.7.10.jar
ExtraCells-1.7.10-2.3.9b188.jar
ExtraTiC-1.7.10-1.4.5.jar
extrautilities-1.2.12.jar
Factorization-1.7.10-0.8.95.jar
Farseek-1.0.10.jar
fastcraft-1.23.jar
FastLeafDecay-1.7.10-1.4.jar
Flans Mod-1.7.10-4.10.0.jar
Flaxbeard'sSteamPower-1.7.10-0.28.7.jar
FlenixCitiesCore_[1.7.10]-0.16.1-b122.jar
FlenixCitiesResearch_[1.7.10]-0.4.jar
FlenixRoads_[1.7.10]-0.10.0-b40.jar
Forbidden Magic-1.7.10-0.562.jar
forestry_1.7.10-4.2.11.59.jar
FortuneOres-MC1.7.10-2.0.5.jar
Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar
FTBLib-1.7.10-1.0.17.6.jar
FTBUtilities-1.7.10-1.0.17.6.jar
Galacticraft-Planets-1.7-3.0.12.441.jar
GalacticraftCore-1.7-3.0.12.441.jar
Ganys End-1.11.3.jar
Ganys Nether-1.8.3.jar
Ganys Surface-1.12.8.jar
GardenStuff-1.7.10-1.7.0.jar
gendustry-1.6.3.132-mc1.7.10.jar
generators-0.9.19.120-mc1.7.10.jar
GraviSuite-1.7.10-2.0.3.jar
GravisuitePatcher_1.7.10.jar
Gravity Science-V0.1 - 1.7.10.jar
Grim3212 Core-V0.2 - 1.7.10.jar
growthcraft-1.7.10-2.4.0-complete.jar
Guide-API-1.7.10-1.0.1-29.jar
HardcoreEnderExpansion  MC-1.7.10  v1.8.5.jar
Hats-4.0.1.jar
HatStand-4.0.0.jar
Heart Crystal by NukeDuck [1.7.10][1.1.1].jar
hopperductmod-1.7.10-1.3.2.jar
HQM-The Journey-4.4.4.jar
HydCraft-1.7.10-2.1.253-universal.jar
IC2NuclearControl-2.3.4a.jar
iChunUtil-4.2.2.jar
IguanaTinkerTweaks-1.7.10-2.1.6.jar
IGW-Mod.jar
ImmersiveEngineering-0.7.5.jar
immersiveintegration-0.6.8.jar
immibis-core-59.1.0.jar
immibis-microblocks-59.1.0.jar
industrialcraft-2-2.2.821-experimental.jar
InGameInfoXML-1.7.10-2.8.1.82-universal.jar
INpureCore-[1.7.10]1.0.0B9-62.jar
InventoryTweaks-1.59-dev-152.jar
ironchest-1.7.10-6.0.62.742-universal.jar
IvToolkit-1.2.jar
Jabba-1.2.1a_1.7.10.jar
journeymap-1.7.10-5.1.4-unlimited.jar
JustAnotherSpawner-0.17.7.jar
k4lib-1.7.10-0.1.57-universal.jar
LampsAndTrafficlights-1.2-Minecraft_1.7.10.jar
lib_voxellib_2.3.1_mc1.7.10.litemod
Light Bridges and Doors V 2.0.zip
liquid-xp-59.0.0.jar
logisticspipes-0.9.3.114.jar
LunatriusCore-1.7.10-1.1.2.21-universal.jar
magicbees-1.7.10-2.4.3.jar
magneticraft-0.6.1-final.jar
malisiscore-1.7.10-0.12.5.jar
malisisdoors-1.7.10-1.9.3.jar
Mantle-1.7.10-0.3.2.jar
MAtmos_r28b__1.7.10.litemod
MatterOverdrive-1.7.10-0.4.1-build-35.jar
MCEF-1.7.10-0.6.jar
mcjtylib-1.8.1.jar
Mekanism-1.7.10-8.1.9.265.jar
MekanismGenerators-1.7.10-8.1.9.265.jar
MekanismTools-1.7.10-8.1.9.265.jar
MicdoodleCore-1.7-3.0.12.441.jar
Minechem-1.7.10-5.0.5.406.jar
MineFactoryReloaded-[1.7.10]2.8.1-174.jar
MineMenu-1.7.10-1.2.0.B44-universal.jar
MineTweaker3-1.7.10-3.0.10B.jar
MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar
mithril_mod-1.7.2-1.6.jar
MmmMmmMmmMmm-1.6.jar
MobAmputation-4.0.1.jar
modlist.txt
ModTweaker2-0.9.5.jar
ModularPowersuits-0.11.0.7-QMX.jar
ModularPowersuitsAddons-0.11.0.7-QMX.jar
ModularSystems-1.7.10-2.2.1.jar
mod_VoxelCam_1.3.2_mc1.7.10-client.litemod
mod_voxelMap_1.5.20_for_1.7.10.litemod
mod_voxelmenu_4.1.4_mc1.7.10.litemod
mod_worldeditcui_1.7.10_00_mc1.7.10.litemod
Monoblocks-1.10.25.jar
MoreEnchantments-1.7.10-1.3.2.1.jar
Morph-Beta-0.9.2.jar
Morpheus-1.7.10-1.6.21.jar
MrCrayfishFurnitureModv3.4.8(1.7.10).jar
MultiMine-1.7.10.zip
MutantCreatures-1.7.10-1.4.9.jar
mystcraft-1.7.10-0.12.3.01.jar
natura-1.7.10-2.2.0.1.jar
Necromancy-1.7.10a.jar
neiaddons-1.12.14.40-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.1.2.jar
NetherOres-[1.7.10]2.3.1-22.jar
NoMoreRecipeConflict-0.2(1.7.10).jar
NotEnoughCodecs-1.7.10-0.3.jar
NotEnoughIDs-1.4.3.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
NotEnoughResources-1.7.10-0.1.0-121.jar
Numina-0.4.0.7-QMX.jar
ObsidiPlates-1.7.10-universal-3.0.0.18.jar
OpenBlocks-1.7.10-1.5.1.jar
OpenComputers-MC1.7.10-1.6.0.3-rc.1-universal.jar
OpenEye-0.6-1.7.10.jar
OpenModsLib-1.7.10-0.9.1.jar
OpenModularTurrets-1.7.10-2.2.2-217.jar
OpenPeripheral-1.7.10-AIO-7.jar
OpenPeripheralAddons-1.7.10-0.5.1.jar
OpenPeripheralCore-1.7.10-1.3.jar
OpenPeripheralIntegration-1.7.10-0.5.jar
OreDictionaryConverter-1.6.1.jar
Origin-1.7.10-7.1.0.jar
Pam's HarvestCraft 1.7.10Lb.jar
PiP-4.0.0-client.jar
PlanetguyLib-1.9.1.jar
PlayerAPI-1.7.10-1.4.jar
PneumaticCraft-1.7.10-1.12.7-150-universal.jar
PortalGun-4.0.0-beta-6.jar
PortalGunSounds.pak
pressure-1.3.0.130-mc1.7.10.jar
ProgressiveAutomation-1.7.10-1.6.34.jar
ProjectE-1.7.10-PE1.9.5.jar
ProjectRed-1.7.10-4.7.0pre12.95-Base.jar
ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar
ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar
ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar
ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar
ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar
ProjectRed-1.7.10-4.7.0pre12.95-World.jar
qCraft1.2_1.7.10.jar
QuantumFlux-1.7.10-1.3.4.jar
QuarryPlus-1.7.10-2.1.0.jar
quickhotbar_1710_1.04.jar
Railcraft_1.7.10-9.10.0.0.jar
ReactorCraft 1.7.10 V12d.jar
RecurrentComplex-0.9.6.3.jar
RedstoneArsenal-[1.7.10]1.1.2-92.jar
RefinedRelocation-mc1.7.10-1.1.28.jar
Reliquary-1.2.jar
RemainInMotion-2.8.9.jar
RenderPlayerAPI-1.7.10-1.4-client.jar
ResourceLoader-MC1.7.10-1.3.jar
res_voxelmenumusic_v_mc1.7.10.litemod
rftools-4.23.jar
rivalrebels-1.7.10S.jar
RoadWorks-2.02-Minecraft_1.7.10.jar
roguelike-1.7.10-1.4.4.jar
RotaryCraft 1.7.10 V12e.jar
SimplyJetpacks-MC1.7.10-1.5.3.jar
SirenMod-3.0.0.jar
SmartCursor-1.5.0-MC1.7.10.jar
SolarExpansion-Basic-1.6a.jar
SolarFlux-1.7.10-0.8b.jar
squidless-1.7.10-0.6.1.jar
SSR-rc3.jar
statues-1.7.10-2.1.4.jar
StevesAddons-1.7.10-0.10.16.jar
StevesCarts2.0.0.b18.jar
StevesFactoryManagerA93.jar
StevesWorkshop-0.5.1.jar
StorageDrawers-1.7.10-1.9.7.jar
StorageDrawers-BiomesOPlenty-1.7.10-1.1.1.jar
StorageDrawers-Forestry-1.7.10-1.1.2.jar
StorageDrawers-Misc-1.7.10-1.1.2.jar
StorageDrawers-Natura-1.7.10-1.1.1.jar
Streams-0.1.5.jar
SuperEnchants-0.5.jar
switchescontinued-0.0.1.jar
Sync-4.0.0.jar
TabbyChat-1.7.10-1.11.2.2-liteloader.litemod
TaintedMagic-1.1.6.4.jar
tcnodetracker-1.7.10-1.1.2.jar
TConstruct-1.7.10-1.8.8.jar
Thaumcarpentry-0.0.1.5-1.7.10.jar
Thaumcraft-1.7.10-4.2.3.5.jar
thaumcraftneiplugin-1.7.10-1.7a.jar
thaumicenergistics-1.0.0.1-RV2.jar
ThaumicExploration-1.7.10-1.1-53.jar
ThaumicTinkerer-2.5-1.7.10-517.jar
Thaumic_Upholstery-1.2_1.7.10.jar
thermalcasting-0.0.3.jar
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalExpansion-[1.7.10]4.1.2-240.jar
ThermalFoundation-[1.7.10]1.2.3-112.jar
ThermalRecycling-1.7.10-1.1.0.5.jar
thirstmod-1.8.14.jar
TiCTooltips-mc1.7.10-1.2.5-client.jar
TMechworks-1.7.10-0.2.15.106.jar
Translocator-1.7.10-1.1.2.16-universal.jar
TSteelworks-1.7.10-1.1.0-6.jar
tubestuff-59.0.3.jar
TWarden-1.1.1.jar
twilightforest-1.7.10-2.3.7.jar
UniversalCoins-1.7.10-1.6.39b.jar
UtilityWorlds-1.7.10_1.0.7.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.10-1.1.6.jar
WAILAPlugins-MC1.7.10-0.2.0-23.jar
warpbook-1.7.10_2.0.36.jar
waterhooks-1.2.0.jar
Wawla-1.3.3-1.7.10.jar
Weather-2.3.7.jar
WebDisplays-0.11.jar
WeepingAngels-1.7.10-4.0.0.jar
witchery-1.7.10-0.24.1.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar
Yampst-The 1.7.10 Pack-0.8.4.jar
YeGamolChattels-1.1.2.jar
Ztones-1.7.10-2.2.1.jar
```

**Comment by jikuja** [comment]
Does some pack work with other launchers? Which version of java is used in working launchers?

**Comment by deframet** [comment]
- This is not a modpack.
- If it works with Minnecraft Launcher that would be probably a MultiMC bug, so I'll definitely try it. 
Do u know other launchers?
- I'm using java 1.8.0_91 64-bit

**Comment by jikuja** [comment]
Did you configure your vanilla launcher to use 1.8.0_91 64-bit? Did you test it with vanilla or not?

**Comment by peterix** [comment]
That is not a MultiMC log. Use the upload button, do not fish for random files please.

**Comment by peterix** [comment]
http://files.inpureprojects.info/libs/commons-codec-1.9.jar is not accessible and couldn't be downloaded... some mod depends on it -> it is a very dead mod now.

You could try grabbing the file yourself from a different source and putting it in `mods/1.7.10`.
Like this source:
http://central.maven.org/maven2/commons-codec/commons-codec/1.9/commons-codec-1.9.jar

**Comment by deframet** [comment]
Hi @peterix, the MultiMC log I updated with the Update button can be found below the crash report. I did not copy and paste it because it's very long.
BTW I moved the pack to the vanilla launcher. It's initializing. Let's see if it loads....

**Comment by peterix** [comment]
If this doesn't fix the crash that comes after, you probably have some mods screwing up that class file... different mods modifying the same code.

**Comment by deframet** [comment]
I built this pack in vanilla launcher then I moved it to MultiMC. In vanilla launcher either gave me that errors but it launched perfectly.

**Comment by deframet** [comment]
In vanilla launcher it loads (5 minutes but yes :O). Tomorrow I'm going to move it again to MultiMC and see what happen.

**Comment by jikuja** [comment]
`Did you configure your vanilla launcher to use 1.8.0_91 64-bit?`

**Comment by deframet** [comment]
yes, I gave minecraft 8GB

**Comment by deframet** [comment]
I imported the pack in MultiMC again and it magically works now...
Thank you for the support :heart:
