### ISSUE TITLE
Crashed: MultiMC exited with exit code 1 HELP?

### ISSUE THREAD

**Issue by DarkLordDLDL** [MultiMC/MultiMC5#1582]
MultiMC version: 0.4.11-751

Minecraft folder is:
instances/1.7.10 with forge and mods (test 1)/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_40/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 6184

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/instances/1.7.10 with forge and mods (test 1)/natives

Traits:
  []

Libraries:
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-universal.jar
  C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/versions/1.7.10/1.7.10.jar

Mods:
  AgriCraft-1.7.10-1.5.0
  appliedenergistics2-rv2-stable-10
  buildcraft-7.1.16
  BuildcraftAdditions-1.7.10-2.2.5
  GalacticraftCore-1.7-3.0.12.375
  DrZharks MoCreatures Mod v6.3.1
  EnderIO-1.7.10-2.2.8.381
  Eureka-1.7.10-3.0.2
  forestry_1.7.10-4.2.12.60
  Galacticraft-Planets-1.7-3.0.12.375
  industrialcraft-2-2.2.822-experimental
  ModularPowersuits-0.11.0.301
  magicalcrops-1.7.10_0.1
  Mantle-1.7.10-0.3.2
  MicdoodleCore-1.7-3.0.12.375
  MineFactoryReloaded-[1.7.10]2.8.1-174
  MooFluids-1.7.10-1.5.01.19a
  Not-Enough-Items-1.7.10-Recommended
  Numina-0.4.0.131
  Pam's HarvestCraft 1.7.10Lb
  ProgressiveAutomation-1.7.10-1.6.35
  TConstruct-1.7.10-1.8.8

Core Mods:
  CodeChickenCore-1.7.10-Recommended

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/instances/1.7.10 with forge and mods (test 1)/minecraft, --assetsDir, C:/Users/<PROFILE NAME>/AppData/Roaming/MultiMC/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {"twitch_access_token":["<TWITCH_ACCESS_TOKEN>"]}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[23:49:34] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[23:49:34] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[23:49:34] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[23:49:34] [main/INFO]: Forge Mod Loader version 7.99.36.1558 for Minecraft 1.7.10 loading
[23:49:34] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_40, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_40
[23:49:34] [main/INFO]: [AppEng] Core Init
[23:49:34] [main/INFO]: Loading tweaker forestry.shade.javacheck.Java7Checker from forestry_1.7.10-4.2.12.60.jar
[23:49:34] [main/WARN]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:49:34] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:49:34] [main/INFO]: [micdoodle8.mods.miccore.DepLoader$DepLoadInst:<init>:333]: MicdoodleCore searching for dependencies in mods file: C:\Users<PROFILE NAME>\AppData\Roaming\MultiMC\MultiMC\instances\1.7.10 with forge and mods (test 1)\minecraft\mods
[23:49:34] [main/WARN]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.reflect.Constructor.newInstance(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.Class.newInstance(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.reflect.Method.invoke(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.multimc.EntryPoint.main(EntryPoint.java:54)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    ... 23 more
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    ... 25 more
[23:49:34] [main/ERROR]: An error occurred trying to configure the minecraft home at C:\Users<PROFILE NAME>\AppData\Roaming\MultiMC\MultiMC\instances\1.7.10 with forge and mods (test 1)\minecraft for Forge Mod Loader
java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
    at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18) ~[Not-Enough-Items-1.7.10-Recommended.jar:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_40]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_40]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_40]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_40]
    at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_40]
    at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
    at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
    ... 23 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
    ... 23 more
[23:49:34] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:313]: Failed to start Minecraft:
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.reflect.Method.invoke(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.multimc.EntryPoint.main(EntryPoint.java:54)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.reflect.Constructor.newInstance(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.Class.newInstance(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    ... 8 more
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    ... 23 more
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    ... 25 more
[23:49:34] [main/INFO]: [org.multimc.EntryPoint:main:57]: Exiting with -1
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArrayIndexOutOfBoundsException: 5
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.SecurityManager.checkExit(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.Runtime.exit(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.System.exit(Unknown Source)
[23:49:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at org.multimc.EntryPoint.main(EntryPoint.java:58)
Exception in thread "main" 
Process exited with code 1.

**Comment by Slikrick** [comment]
Seems codechickenlib isn't properly downloaded/running. It is a required library for codechickencore and chickenbones's mods. Try downloading the 1.7.10 version here http://files.minecraftforge.net/CodeChickenLib/ and putting it in the 1.7.10 folder in the mods folder (deleting the old version if there is one)

**Comment by DarkLordDLDL** [comment]
Found the problem. Added the mods one by one and started the mc after each added mod to find the problem. Turns out it was the Not Enough Items mod for some reason.

**Comment by Loetkolben** [comment]
Does this mean this is fixed now? If yes, close this please.

**Comment by Fred1124** [comment]
I have similar problem https://paste.ee/p/9nvk7

**Comment by peterix** [comment]
@Fred1124 nope, that's a different problem. You should just use Minecraft 1.12.2.

And I'm closing this because it has not been touched for almost 2 years.
