### ISSUE TITLE
Crash code -1 trying to just run plain vanilla 

### ISSUE THREAD

**Issue by sarahtar1** [MultiMC/MultiMC5#1606]
System Information
-----------------------------
MultiMC version: 5

Operating System: win 10

Summary of the issue or suggestion:  
----------------------------------------------
MultiMC doesn't seem to be able to run any version of MC on this computer. I've tried several plain vanilla versions, and tried adding forge and a mod to a version, also. No dice.

What should happen: 
------------------------------
It should run Minecraft, or so I've been told. :)

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click New Instance

2. Choose a MC Version

3. Double click to run it.

Suspected cause:
---------------------------
I have no clue.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
```
MultiMC version: 0.4.11-751

Minecraft folder is:
instances/1.10.2/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/Wally/Documents/MC Stuff/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 2400

Using onesix launcher.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/Wally/Documents/MC Stuff/MultiMC/instances/1.10.2/natives

Traits:
  []

Libraries:
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/com/mojang/realms/1.9.3/realms-1.9.3.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Wally/Documents/MC Stuff/MultiMC/versions/1.10.2/1.10.2.jar

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/Wally/Documents/MC Stuff/MultiMC/instances/1.10.2/minecraft, --assetsDir, C:/Users/Wally/Documents/MC Stuff/MultiMC/assets, --assetIndex, 1.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userType, mojang, --versionType, release]

Window size: 854 x 480

Preparing native libraries...
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[22:28:14] [Client thread/INFO]: Setting user: <PROFILE NAME>
[22:28:18] [Client thread/INFO]: LWJGL Version: 2.9.1
[22:28:19] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.1.jar:?]
	at bcx.ap(SourceFile:585) [1.10.2.jar:?]
	at bcx.an(SourceFile:434) [1.10.2.jar:?]
	at bcx.a(SourceFile:381) [1.10.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [1.10.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 7/1/16 10:28 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bcx.ap(SourceFile:598)
	at bcx.an(SourceFile:434)
	at bcx.a(SourceFile:381)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bcx.ap(SourceFile:598)
	at bcx.an(SourceFile:434)

-- Initialization --
Details:
Stacktrace:
	at bcx.a(SourceFile:381)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 466736168 bytes (445 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Wally\Documents\MC Stuff\MultiMC\instances\1.10.2\minecraft\crash-reports\crash-2016-07-01_22.28.20-client.txt
Process exited with code -1.





---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/1/16 10:28 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bcx.ap(SourceFile:598)
	at bcx.an(SourceFile:434)
	at bcx.a(SourceFile:381)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bcx.ap(SourceFile:598)
	at bcx.an(SourceFile:434)

-- Initialization --
Details:
Stacktrace:
	at bcx.a(SourceFile:381)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 466736168 bytes (445 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
```

Additional Info:
---------------------------

**Comment by peterix** [comment]
You do not have a working graphics card or a working graphics driver.

If it's one of those Intel integrated GPUs unsupported on Windows 10, you will have to use Java older than 8u60.

See:
http://www.intel.com/content/www/us/en/support/graphics-drivers/000005526.html

**Comment by sarahtar1** [comment]
How is that possible when we've never had a problem with anything else? (Not challenging you, just wondering.)

**Comment by sarahtar1** [comment]
Yay, it seems to be working now. Thank you!!

**Comment by peterix** [comment]
The vanilla launcher comes with a very old version of java included. And everything that uses the vanilla launcher in some way just ends up using that version. Last I checked, it was 8u25. It's all outdated.

The issue is actually in the intel driver itself. Basically, it detects the OS version and refuses to work on anything above Windows 8.1. The system call this uses also depends on what version of Windows the application declares to support. So, old Java doesn't declare Windows 10 support, and the graphics driver loads...

I tried talking to Intel and all I got from them is 'we do not support these GPUs on windows 10 anymore and do not plan to fix this'. You end up running outdated java - potentially exposing yourself to harm if you connect to anything online with it, or if it gets installed in your browser. It **SUCKS**.

I plan to fix this - by making a custom java exe file that does not declare Windows 10 support. You can expect that to appear in a stable release in a month or two. I already started working on this, but I'm in Israel on a business trip and left all the progress on a machine that's turned off ~_~

**Comment by peterix** [comment]
Ideally, you should only use outdated java for minecraft and not let it find its way into anything else. So, for example grab 8u25 64bit .tar.gz from here: 
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jre-8u25-oth-JPR

Extract it into somewhere and set up MultiMC to use it (javaw.exe).

Alternatively, you could use the Java that comes with the Vanilla launcher. I'm not entirely sure where it is stored, but if you look for javaw.exe, you should find it.

**Comment by Sakata-MC** [comment]
The reason that Intel won't support them on Windows 10 is due to Microsoft. Microsoft and Intel have a deal about support with windows 10 and the skylake processors.

**Comment by peterix** [comment]
Do you have a source for that?

**Comment by peterix** [comment]
There is a **BIG** difference between 'we will only support new hardware on the new OS' and 'we won't support recent, still good hardware on the new OS, buy more crap because we have a deal with Intel that makes you'.

**Comment by KingDGrizzle** [comment]
@peterix Minecraft Launcher installs Java 8up25 in a folder called bin, in %AppData%\.minecraft

**Comment by peterix** [comment]
So?

**Comment by KingDGrizzle** [comment]
I didnt say you are. I only said that so you knew where it is

**Comment by peterix** [comment]
I do not intend to use that.

**Comment by KingDGrizzle** [comment]
I only let you know where it is.. And speaking of Java.. I'm running Java 8up102.. Thats not even released
