### ISSUE TITLE
Game exited with exit code 1

### ISSUE THREAD

**Issue by SupaSpider** [MultiMC/MultiMC5#1608]
-----------------------------
MultiMC version:0.4.7

Operating System: Windows 8

Summary of the issue or suggestion: I downloaded lite loader and forge( Just those!) And it ends in less than a minute.
----------------------------------------------

What should happen:Load the game fine
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Load game with forge and liteloader

2.

3.

Suspected cause: idk
---------------------------

Logs/Screenshots:MultiMC version: 0.4.7

Minecraft folder is:
C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/instances/1.7.10/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_66/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 1856

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/instances/1.7.10/natives

Traits:
  []

Libraries:
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1566-1.7.10/forge-1.7.10-10.13.4.1566-1.7.10-universal.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/com/mumfrey/liteloader/1.7.10_04/liteloader-1.7.10_04.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/versions/1.7.10/1.7.10.jar

Mods:
  forge-1.7.10-10.13.4.1448-1.7.10-installer.jar
  Not-Enough-Items-1.7.10
  ReiMinimap-1.7.10-3.6

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/instances/1.7.10/minecraft, --assetsDir, C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang, --tweakClass, com.mumfrey.liteloader.launch.LiteLoaderTweaker, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[21:10:52] [main/INFO] [LaunchWrapper]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[21:10:52] [main/INFO] [LaunchWrapper]: Using primary tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[21:10:52] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:10:53] [main/INFO] [LaunchWrapper]: Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker
[21:10:53] [main/INFO] [LiteLoader]: Bootstrapping LiteLoader 1.7.10
[21:10:53] [main/INFO] [LiteLoader]: Registering API provider class com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient
[21:10:53] [main/INFO] [LiteLoader]: Spawning API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' ...
[21:10:53] [main/INFO] [LiteLoader]: API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' provides API 'liteloader'
[21:10:53] [main/INFO] [LiteLoader]: Initialising API 'liteloader' ...
[21:10:53] [main/INFO] [LiteLoader]: LiteLoader begin PREINIT...
[21:10:53] [main/INFO] [LiteLoader]: Initialising Loader properties...
[21:10:53] [main/INFO] [LiteLoader]: Setting up logger...
[21:10:54] [main/INFO] [LiteLoader]: LiteLoader 1.7.10_04 starting up...
[21:10:54] [main/INFO] [LiteLoader]: Java reports OS="windows 8.1"
[21:10:54] [main/INFO] [LiteLoader]: Enumerating class path...
[21:10:54] [main/INFO] [LiteLoader]: Class path separator=";"
[21:10:54] [main/INFO] [LiteLoader]: Class path entries=(
   classpathEntry=C:/Users/Admin/Downloads/mmc-stable-win32/MultiMC/jars/NewLaunch.jar
)
[21:10:54] [main/INFO] [LiteLoader]: Registering discovery module EnumeratorModuleClassPath: [<Java Class Path>]
[21:10:54] [main/INFO] [LiteLoader]: Registering discovery module EnumeratorModuleFolder: [C:\Users\Admin\Downloads\mmc-stable-win32\MultiMC\instances\1.7.10\minecraft\mods]
[21:10:54] [main/INFO] [LiteLoader]: Registering discovery module EnumeratorModuleFolder: [C:\Users\Admin\Downloads\mmc-stable-win32\MultiMC\instances\1.7.10\minecraft\mods\1.7.10]
[21:10:54] [main/INFO] [LiteLoader]: Adding supported mod class prefix 'LiteMod'
[21:10:54] [main/INFO] [LiteLoader]: Discovering tweaks on class path...
[21:10:54] [main/INFO] [LiteLoader]: Discovering valid mod files in folder C:\Users\Admin\Downloads\mmc-stable-win32\MultiMC\instances\1.7.10\minecraft\mods
[21:10:54] [main/INFO] [LiteLoader]: Discovering valid mod files in folder C:\Users\Admin\Downloads\mmc-stable-win32\MultiMC\instances\1.7.10\minecraft\mods\1.7.10
[21:10:54] [main/INFO] [LiteLoader]: LiteLoader PREINIT complete
[21:10:54] [main/INFO] [LiteLoader]: Sorting registered packet transformers by priority
[21:10:54] [main/INFO] [LiteLoader]: Added 0 packet transformer classes to the transformer list
[21:10:54] [main/INFO] [LiteLoader]: Injecting required class transformer 'com.mumfrey.liteloader.transformers.event.EventProxyTransformer'
[21:10:54] [main/INFO] [LiteLoader]: Injecting required class transformer 'com.mumfrey.liteloader.launch.LiteLoaderTransformer'
[21:10:54] [main/INFO] [LiteLoader]: Injecting required class transformer 'com.mumfrey.liteloader.client.transformers.CrashReportTransformer'
[21:10:54] [main/INFO] [LiteLoader]: Queuing required class transformer 'com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer'
[21:10:54] [main/INFO] [LiteLoader]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer'
[21:10:54] [main/INFO] [LiteLoader]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer'
[21:10:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[21:10:54] [main/INFO] [FML]: Forge Mod Loader version 7.99.39.1566 for Minecraft 1.7.10 loading
[21:10:54] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_66, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_66
[21:10:55] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:54)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 23 more
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 25 more
[21:10:55] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at C:\Users\Admin\Downloads\mmc-stable-win32\MultiMC\instances\1.7.10\minecraft for Forge Mod Loader
java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18) ~[Not-Enough-Items-1.7.10.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_66]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_66]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501) ~[forge-1.7.10-10.13.4.1566-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1566-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1566-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1566-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1566-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1566-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1566-1.7.10-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	... 23 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	... 23 more
[21:10:55] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:313]: Failed to start Minecraft:
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:54)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 8 more
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 23 more
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 25 more
[21:10:55] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:57]: Exiting with -1
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArrayIndexOutOfBoundsException: 5
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[21:10:55] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:58)
Exception in thread "main" 
Game exited with exitcode 1.

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info: none
---------------------------

**Comment by jikuja** [comment]
Install missing dependencies for *mods* you added: `Caused by: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit`

or remove mods to launch game forge+liteloader only like described.

**Comment by SupaSpider** [comment]
I didn't add mods though

**Comment by jikuja** [comment]
Someone added those:
```
Mods:
forge-1.7.10-10.13.4.1448-1.7.10-installer.jar
Not-Enough-Items-1.7.10
ReiMinimap-1.7.10-3.6
```

**Comment by SupaSpider** [comment]
so should add those to fix it?

**Comment by SupaSpider** [comment]
I doesn't show them in my instance settings

**Comment by SupaSpider** [comment]
nvm found them
