### ISSUE TITLE
(FTB Presents) Skyfactory 2.5 Crashes while using MultiMC

### ISSUE THREAD

**Issue by EnderHunterFTW** [MultiMC/MultiMC5#1640]
Hi all, 

I'm new around here.
So, i've made an instance on MultiMC, im using a few folders from the FTB Presents Skyfactory 2.5 modpack (on the curse launcher.)

But i'm on mac, so I hate the curse launcher, and because I can't have curse offline, it makes it worse.

Pretty much instantly after opening the instance, this error pops up
_[23:09:25] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_102]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 14 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Pattern not found while trying to inject into h
	at mcp.mobius.mobiuscore.asm.CoreTransformer.transform(CoreTransformer.java:89) ~[MobiusCore-1.2.4_1.7.10.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_102]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 14 more
Caused by: java.lang.RuntimeException: Pattern not found while trying to inject into h
	at mcp.mobius.mobiuscore.asm.transformers.TransformerBase.applyPayloadBefore(TransformerBase.java:209) ~[MobiusCore-1.2.4_1.7.10.jar:?]
	at mcp.mobius.mobiuscore.asm.transformers.forge.TransformerWorld.transform(TransformerWorld.java:156) ~[MobiusCore-1.2.4_1.7.10.jar:?]
	at mcp.mobius.mobiuscore.asm.CoreTransformer.transform(CoreTransformer.java:37) ~[MobiusCore-1.2.4_1.7.10.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_102]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 14 more
[23:09:25] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:313]: Failed to start Minecraft:
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.multimc.EntryPoint.main(EntryPoint.java:54)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:971)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 8 more
[23:09:25] [main/INFO]: [org.multimc.EntryPoint:main:57]: Exiting with -1
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException: 5
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:971)
[23:09:25] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.multimc.EntryPoint.main(EntryPoint.java:58)
Exception in thread "main" 
Process exited with code 1._

Help would be nice, and I felt like shouting out my YT (http://www.youtube.com/enderhunterftw)

**Comment by peterix** [comment]
Provide a full log. Use the `Upload` button.

**Comment by EnderHunterFTW** [comment]
http://paste.ee/p/khvo5

@peterix

**Comment by peterix** [comment]
You have a lot of duplicated mods. Disable or remove all the duplicates you do not intend to use.

**Comment by EnderHunterFTW** [comment]
@peterix 

Thank you so much!

It's working now, and my game runs really smooth.
