### ISSUE TITLE
Opens the mod pack, crashes when I join the server

### ISSUE THREAD

**Issue by bgreenlaw** [MultiMC/MultiMC5#1656]
## System Information

MultiMC version: 5 - 0.4.11-751 on win32

Operating System: Windows 10
## Summary of the issue or suggestion:

I had a custom Mod pack made for 1.7.10 with 33 mods on it, whats been happening is that I can open and load up the pack fine but the when I try and join the server (which has these mods loaded onto it) the game crashes before I can connect. I'm running 64 bit Java and I have a Max of 6048 MB of Memory devoted to it.  
## What should happen:

I should be able to join the server and have it function as a normal game would
## Logs/Screenshots:

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 8/25/16 10:26 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 8
    at jds.bibliocraft.blocks.BlockItemWeaponCaseMaster.func_77667_c(BlockItemWeaponCaseMaster.java:36)
    at net.minecraft.item.Item.func_77657_g(Item.java:547)
    at net.minecraft.item.Item.func_77653_i(Item.java:636)
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
    at noppes.mpm.client.RenderEvent.overlay(RenderEvent.java:137)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_105_RenderEvent_overlay_RenderGameOverlayEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
    at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:102)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1328)
    at noppes.mpm.client.EntityRendererAlt.func_78480_b(EntityRendererAlt.java:34)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at jds.bibliocraft.blocks.BlockItemWeaponCaseMaster.func_77667_c(BlockItemWeaponCaseMaster.java:36)
    at net.minecraft.item.Item.func_77657_g(Item.java:547)
    at net.minecraft.item.Item.func_77653_i(Item.java:636)
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
    at noppes.mpm.client.RenderEvent.overlay(RenderEvent.java:137)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_105_RenderEvent_overlay_RenderGameOverlayEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
    at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:102)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1328)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Booboogirl2015'/1601637, l='MpServer', x=152.20, y=84.62, z=68.80]]
    Chunk stats: MultiplayerChunkCache: 100, 100
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (115,81,237), Chunk: (at 3,5,13 in 7,14; contains blocks 112,0,224 to 127,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 41689293 game time, 5836634 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 16 total; [EntityPainting['Painting'/32, l='MpServer', x=128.94, y=82.50, z=126.00], EntityMinecartEmpty['entity.MinecartRideable.name'/39, l='MpServer', x=180.72, y=80.34, z=114.26], EntityClientPlayerMP['Booboogirl2015'/1601637, l='MpServer', x=152.20, y=84.62, z=68.80], EntityPig['Pig'/1602192, l='MpServer', x=197.50, y=81.00, z=23.19], EntityMinecartEmpty['entity.MinecartRideable.name'/40, l='MpServer', x=178.94, y=80.34, z=114.10], EntityMinecartEmpty['entity.MinecartRideable.name'/41, l='MpServer', x=177.78, y=80.34, z=114.38], EntityMinecartEmpty['entity.MinecartRideable.name'/42, l='MpServer', x=180.48, y=80.34, z=116.07], EntityMinecartEmpty['entity.MinecartRideable.name'/43, l='MpServer', x=177.94, y=80.34, z=116.32], EntityMinecartEmpty['entity.MinecartRideable.name'/44, l='MpServer', x=179.41, y=80.34, z=116.88], EntitySheep['Sheep'/1602184, l='MpServer', x=178.88, y=81.00, z=32.75], EntityPig['Pig'/1602185, l='MpServer', x=192.03, y=81.00, z=68.50], EntityHorse['Buttercup'/1602186, l='MpServer', x=97.94, y=82.00, z=32.38], EntityPainting['Painting'/32, l='MpServer', x=128.94, y=82.50, z=126.00], EntityCow['Cow'/1602191, l='MpServer', x=103.09, y=81.00, z=18.94], EntityPig['Pig'/1602182, l='MpServer', x=143.22, y=81.00, z=32.50], EntityPig['Pig'/1602183, l='MpServer', x=138.16, y=81.00, z=46.78]]
    Retry entities: 0 total; []
    Server brand: thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1146352872 bytes (1093 MB) / 2082471936 bytes (1986 MB) up to 3728736256 bytes (3556 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4000m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_C1 33 mods loaded, 33 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    UCHIJA  Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    UCHIJA  CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
    UCHIJA  adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
    UCHIJA  BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) 
    UCHIJA  CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCHIJA  chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
    UCHIJA  customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c.jar) 
    UCHIJA  props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) 
    UCHIJA  DynamicLights{1.3.7} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
    UCHIJA  DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
    UCHIJA  DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
    UCHIJA  DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
    UCHIJA  DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJA  DynamicLights_mobEquipment{1.0.7} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJA  DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJA  DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
    UCHIJA  DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJA  DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
    UCHIJA  Emotes{1.0} [Emotes] (Emotes 1.0.1.jar) 
    UCHIJA  flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
    UCHIJA  FoodPlus{3.2rS} [�bFood Plus] (FoodPlus-1.7.2-3.2rS.jar) 
    UCHIJA  hidenames{1.1.7} [Hide Names] (Hide Names.jar) 
    UCHIJA  malisiscore{1.7.10-0.12.9} [MalisisCore] (malisiscore-1.7.10-0.12.9.jar) 
    UCHIJA  malisisdoors{1.7.10-1.10} [Malisis' Doors] (malisisdoors-1.7.10-1.10.jar) 
    UCHIJA  moreplayermodels{1.7.10b} [MorePlayerModels] (MorePlayerModels_1.7.10b (5).jar) 
    UCHIJA  cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
    UCHIJA  harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
    UCHIJA  corerm{1.0b} [RikMuld's Core] (TheCampingMod_2.1f.jar) 
    UCHIJA  camping{2.1f} [The Camping Mod 2] (TheCampingMod_2.1f.jar) 
    UCHIJA  worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
    UCHIJA  Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics'
    Launched Version: MultiMC5
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4358, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```

**Comment by peterix** [comment]
To me that looks like a mod bug, not MultiMC related.

**Comment by peterix** [comment]
Either it's bibliocraft or whatever is drawing one of its items or blocks in the GUI.
