### ISSUE TITLE
[Bug] AFK Fishing is glitchy / Errors are outputted to the console

### ISSUE THREAD

**Issue by KingDGrizzle** [MultiMC/MultiMC5#1657]
System Information
-----------------------------
MultiMC version: 0.4.12-develop-817

Operating System: Windows 7 Ultimate x64

Summary of the issue or suggestion:
----------------------------------------------

Whenever you use an AFK fish farm, there are moments where its glitchy

What should happen:
------------------------------

It should always work, without it glitching

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Set up the 1.11 fishing farm to use in 1.10 (Still works)

2. Start fishing by using the full-screen method F3 + P till PauseOnLoftFocus is disabled, Hold right click on the fence with the farm running, and press F11 while releasing the right click button. It might take a few attempts)

3. Alt + Tab out of the game, and look at the console

Suspected cause:
---------------------------

No clue...

Logs/Screenshots:
----------------------------
http://paste.ee/p/jcQYd

Additional Info:
---------------------------

When trying to use the iron door, the fishing rod just casts intead of acting like a fence post

**Comment by jikuja** [comment]
Does it work with vanilla launcher(without mods)?

**Comment by KingDGrizzle** [comment]
`[13:51:31] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_102]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_102]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:191) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:252) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147287_a(NetHandlerPlayClient.java:698) ~[bll.class:?]
	at net.minecraft.network.play.server.SPacketMultiBlockChange.func_148833_a(SourceFile:53) ~[gd.class:?]
	at net.minecraft.network.play.server.SPacketMultiBlockChange.func_148833_a(SourceFile:13) ~[gd.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_102]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 17 more`

Also, got to mention. Using Forge

**Comment by KingDGrizzle** [comment]
I will try to use vanilla, and the vanilla launcher, although that should work

**Comment by KingDGrizzle** [comment]
Ok, seems to be a Forge issue so far.. Will update forge, to see if that changes anything

**Comment by KingDGrizzle** [comment]
Found out the issue, as its related to an old version of Forge. Updating it seems to be fixed. I guess it isn't a bug?
