### ISSUE TITLE
Minecraft wont start!

### ISSUE THREAD

**Issue by HoppinAround** [MultiMC/MultiMC5#1688]
I have a problem i just created an Modpack and it worked at the first few Starts after some time (i didnt changed anything in the mods or config) my Minecraft dont Start i have a lot of Errors at the End of my Log and canty say why Please help!
ForgeVersion 10.13.4.1558-1.7.10 (Custom) (1.7.10)
ModVersions 1.7.10
MC 1.7.10

I hope you guys can help me! THX for reading!
###### #LOG

```
MultiMC version: 0.4.11-751

Minecraft folder is:
instances/1.7.10/minecraft

Java path is:
C:/Users/simon/Desktop/runtime/jre-x64/1.8.0_25/bin/javaw.exe

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 5792

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/instances/1.7.10/natives

Traits:
  []

Libraries:
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/versions/1.7.10/1.7.10.jar

Mods:
  Flan's Mod-1.7.10-4.10.0
  InventoryTweaks-1.59-dev-156
  NotEnoughItems-1.7.10-1.0.5.120-universal

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/instances/1.7.10/minecraft, --assetsDir, C:/Users/simon/Desktop/mmc-stable-win32/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[14:57:40] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[14:57:40] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[14:57:40] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[14:57:40] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[14:57:40] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 8.1:amd64:6.3, installed at C:\Users\simon\Desktop\runtime\jre-x64\1.8.0_25
[14:57:40] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:57:40] [main/WARN]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.Class.newInstance(Class.java:438)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.reflect.Method.invoke(Method.java:483)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at org.multimc.EntryPoint.main(EntryPoint.java:54)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   ... 23 more
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   ... 25 more
[14:57:40] [main/ERROR]: An error occurred trying to configure the minecraft home at C:\Users\simon\Desktop\mmc-stable-win32\MultiMC\instances\1.7.10\minecraft for Forge Mod Loader
java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
    at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18) ~[NotEnoughItems-1.7.10-1.0.5.120-universal.jar:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_25]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_25]
    at java.lang.Class.newInstance(Class.java:438) ~[?:1.8.0_25]
    at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
    at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    ... 23 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
    ... 23 more
[14:57:40] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:313]: Failed to start Minecraft:
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.reflect.Method.invoke(Method.java:483)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at org.multimc.EntryPoint.main(EntryPoint.java:54)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.Class.newInstance(Class.java:438)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   ... 8 more
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   ... 23 more
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   ... 25 more
[14:57:40] [main/INFO]: [org.multimc.EntryPoint:main:57]: Exiting with -1
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException: 5
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.Runtime.exit(Runtime.java:107)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at java.lang.System.exit(System.java:968)
[14:57:40] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]:   at org.multimc.EntryPoint.main(EntryPoint.java:58)
Exception in thread "main" 
Process exited with code 1.
Clipboard copy at: 16 Oct 2016 15:00:29 +0200
```

**Comment by Eufranio** [comment]
Redownload/download CodeChickenLib.

**Comment by HoppinAround** [comment]
It dont works!

**Comment by Eufranio** [comment]
Please post your crash in hastebin.com

**Comment by HoppinAround** [comment]
didnt know

**Comment by HoppinAround** [comment]
sry

**Comment by Pyker** [comment]
Solution: Add CodeChickenCore
