### ISSUE TITLE
Loader crashes after installing Forge to minecraft 1.7.2

### ISSUE THREAD

**Issue by bluereef1** [MultiMC/MultiMC5#1695]
System Information
-----------------------------
MultiMC version: Multi MC 5 - Version 0.4..11-751 on win32

Operating System: Win 8.1 Pro

Summary of the issue or suggestion: Loader quits with Vanilla+Forge
----------------------------------------------

What should happen:
------------------------------
Minecraft should open, but quits before it fully loads

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a Vanilla MC, version 1.7.2. Open it once. Then close.

2. Create a copy of the instance in Step 1, open it once, then close. Then add a Forge using the apps Forge installer. Choose Forge 10.12.2.1121.

3. Open the new MC 1.7.2 with Forge 10.12.2.1121. It tries to open but the loading quits fore the game ever gets to start screen. The loading window and log window automatically close, bringing you to the MultiMC main screen.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
latest log:

[16:24:07] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[16:24:07] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[16:24:07] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[16:24:07] [main/INFO]: Forge Mod Loader version 7.2.211.1121 for Minecraft 1.7.2 loading
[16:24:07] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_101, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_101
[16:24:07] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:24:07] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[16:24:07] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:24:07] [main/ERROR]: Unable to launch
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_101]
	at java.util.ArrayList$Itr.remove(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:117) [launchwrapper-1.9.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

Additional Info (logs/2016-10-23-2.log.gz):
---------------------------
[16:23:44] [main/INFO]: Setting user: AwesomeJordu
[16:23:44] [main/INFO]: (Session ID is token:94be5db8e37a4dbd8445da339161f245:95ca794a7467479894477aa4bcbc491c)
[16:23:44] [Client thread/INFO]: LWJGL Version: 2.9.1
[16:23:44] [Client thread/INFO]: Reloading ResourceManager: Default
[16:23:45] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[16:23:45] [Sound Library Loader/INFO]: Sound engine started
[16:23:45] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[16:23:48] [Client thread/INFO]: Stopping!

**Comment by peterix** [comment]
That's a forge bug.

You need this mod to fix it:
http://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar

**Comment by KamranMackey** [comment]
@bluereef1 What I'd love to know is why you're still playing 1.7.2 when 1.7.10 and newer versions exist. 1.7.2 is ridiculously buggy.

**Comment by peterix** [comment]
Maybe it has some unique mods? Idk...

**Comment by bluereef1** [comment]
I'm trying to add the SuperHeroes Mod, which I thought required an  
older version of Minecraft. I'm a parent--who doesn't play  
Minecraft--trying to install the mod for my child. It's like being  
thrown into the deep end of the pool and being commanded to swim! Any  
insight you can give on how to install the Mod would be appreciated.  
Almost all the instructions assume that the user is experienced with  
Minecraft.


Kind regards,
Wendy

Quoting Kamran Mackey <notifications@github.com>:

**Comment by deframet** [comment]
@bluereef1 You should create a new issue for that
