### ISSUE TITLE
Code -1 exit

### ISSUE THREAD

**Issue by DarkMatter980** [MultiMC/MultiMC5#1738]
MultiMC version: 0.4.11-751Minecraft folder is:instances/Predator /minecraftJava path is:C:/Program Files/Java/jre1.8.0_111/bin/java.exeJava Arguments:[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/Caldwell family/Documents/MultiMC/jars/NewLaunch.jar]Minecraft process ID: 7976Using onesix launcher.Main Class:  net.minecraft.client.main.MainNative path:  C:/Users/Caldwell family/Documents/MultiMC/instances/Predator /nativesTraits:  []Libraries:  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/google/guava/guava/15.0/guava-15.0.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar  C:/Users/Caldwell family/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar  C:/Users/Caldwell family/Documents/MultiMC/versions/1.7.10/1.7.10.jarParams:  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, C:/Users/Caldwell family/Documents/MultiMC/instances/Predator /minecraft, --assetsDir, C:/Users/Caldwell family/Documents/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang]Window size: 854 x 480Preparing native libraries...Extracting twitch-platform-5.16-natives-windows-64.jarExtracting twitch-external-platform-4.5-natives-windows-64.jarExtracting jinput-platform-2.0.5-natives-windows.jarExtracting lwjgl-platform-2.9.1-natives-windows.jarFailed to start Minecraft:java.lang.reflect.InvocationTargetException	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)	at java.lang.reflect.Method.invoke(Unknown Source)	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)	at org.multimc.EntryPoint.listen(EntryPoint.java:170)	at org.multimc.EntryPoint.main(EntryPoint.java:54)Caused by: java.lang.ExceptionInInitializerError	at java.nio.file.FileSystems.getDefault(Unknown Source)	at java.io.File.toPath(Unknown Source)	at sun.security.provider.SeedGenerator$1.run(Unknown Source)	at sun.security.provider.SeedGenerator$1.run(Unknown Source)	at java.security.AccessController.doPrivileged(Native Method)	at sun.security.provider.SeedGenerator.getSystemEntropy(Unknown Source)	at sun.security.provider.SecureRandom$SeederHolder.<clinit>(Unknown Source)	at sun.security.provider.SecureRandom.engineNextBytes(Unknown Source)	at java.security.SecureRandom.nextBytes(Unknown Source)	at java.util.UUID.randomUUID(Unknown Source)	at ri.<init>(SourceFile:19)	at bao.<init>(SourceFile:110)	at net.minecraft.client.main.Main.main(SourceFile:129)	... 8 moreExiting with -1Caused by: java.nio.file.InvalidPathException: Trailing char < > at index 61: C:\Users\Caldwell family\Documents\MultiMC\instances\Predator \minecraft	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)	at sun.nio.fs.WindowsFileSystem.<init>(Unknown Source)	at sun.nio.fs.WindowsFileSystemProvider.<init>(Unknown Source)	at sun.nio.fs.DefaultFileSystemProvider.create(Unknown Source)	at java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(Unknown Source)	at java.nio.file.FileSystems$DefaultFileSystemHolder.access$000(Unknown Source)	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(Unknown Source)	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(Unknown Source)	at java.security.AccessController.doPrivileged(Native Method)	at java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(Unknown Source)	at java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(Unknown Source)	... 21 moreProcess exited with code -1.MultiMC: Log upload triggered at: 29 Nov 2016 17:03:51 -0700

this is very odd no mods!
http://paste.ee/p/VLkus#

**Comment by peterix** [comment]
`Trailing char < > at index 61: C:\Users\Caldwell family\Documents\MultiMC\instances\Predator \minecraft`

Rename that folder so it doesn't have a space at the end.

This has to be done from command line because the windows explorer can't do it.

So, open up cmd.exe and:
```
cd "C:\Users\Caldwell family\Documents\MultiMC\instances\"
rename "Predator " "Predator"
```

**Comment by peterix** [comment]
Closing for lack of activity.
