### ISSUE TITLE
Nothing but white screen after attempting to launch the game

### ISSUE THREAD

**Issue by jezmerez** [MultiMC/MultiMC5#1806]
I attempted to run the exact same launcher with the exact mods that I had on my other computer and it crashed on this computer and not the other. So the launcher wasn't the problem it seems to be that my computer won't allow the application to run. I downloaded MultiMc from the website and tried to run simple 1.2.5 vanilla Minecraft and all that happened was I got a white screen and no Mojang screen.

Logs/Screenshots:
----------------------------
MultiMC version: 0.5.0-929

Minecraft folder is:
instances/More creeps and weirdoes/minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/java.exe

Java is version 1.8.0_121, using 64-bit architecture.

Main Class:
  

Native path:
  C:/Users/Lim/Desktop/multimc/instances/More creeps and weirdoes/natives

Traits:
traits texturepacks
traits legacyLaunch

Libraries:
  C:/Users/Lim/Desktop/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Lim/Desktop/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Lim/Desktop/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Lim/Desktop/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Lim/Desktop/multimc/instances/More creeps and weirdoes/minecraft/bin/minecraft.jar
  C:/Users/Lim/Desktop/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Lim/Desktop/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar

Mods:
  [1.2.5]ReiMinimap_v3.2_05
  1.2.5_Jammy_Furniture_Mod_Client_V3.6
  CraftGuide-1.5.0
  CraftGuideInv
  CustomMobSpawner 1.4.3
  MoreCreeps
  MoreCreepsAndWeirdos
  OptiFine_1.2.5_HD_U_C7

Jar Mods:
  Forge (minecraftforge-client-3.4.9.171.zip)
  TooManyItems2012_04_13_1.2.5 (f5a55a3e-4a4f-4c87-b3f4-ec87d966afd3.jar)
  skinpatchv18503826 (a5ee8124-dd34-418d-9702-c7d95dbd4e6c.jar)

Params:
   

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 8996

Using onesix launcher.

Launching with applet wrapper...
27 achievements
182 recipes
Setting user: <PROFILE NAME>, token:<ACCESS TOKEN>:<PROFILE ID>
LWJGL Version: 2.9.1
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at net.minecraft.client.Minecraft.a(Minecraft.java:360)
	at net.minecraft.client.Minecraft.run(Minecraft.java:738)
	at java.lang.Thread.run(Unknown Source)
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.a(Minecraft.java:375)
	at net.minecraft.client.Minecraft.run(Minecraft.java:738)
	at java.lang.Thread.run(Unknown Source)
Jan 29, 2017 9:09:38 PM uu <init>
SEVERE: A critical error has occurred.
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.a(Minecraft.java:375)
	at net.minecraft.client.Minecraft.run(Minecraft.java:738)
	at java.lang.Thread.run(Unknown Source)

Exception in thread "Minecraft main thread" java.lang.RuntimeException: sidedDelegate null when attempting to getMinecraftLogger, this is generally caused by you not installing FML properly, or installing some other mod that edits Minecraft.class on top of FML such as ModLoader, do not do this. Reinstall FML properly and try again.
	at cpw.mods.fml.common.FMLCommonHandler.getMinecraftLogger(FMLCommonHandler.java:358)
	at cpw.mods.fml.common.Loader.<init>(Loader.java:138)
	at cpw.mods.fml.common.Loader.instance(Loader.java:129)
	at uu.<init>(PanelCrashReport.java:25)
	at n.a(SourceFile:38)
	at net.minecraft.client.Minecraft.b(Minecraft.java:300)
	at net.minecraft.client.Minecraft.run(Minecraft.java:743)
	at java.lang.Thread.run(Unknown Source)
Clipboard copy at: 29 Jan 2017 21:09:52 -0500

**Comment by peterix** [comment]
You do not have a working graphics driver on that computer.

**Comment by peterix** [comment]
If this is Windows 10 and an old Intel GPU, you will have to use old Java (versions older than 8u60).

**Comment by jezmerez** [comment]
@peterix It worked! Thank you so much!!

**Comment by peterix** [comment]
Alright.

**Comment by HelloiAmAplayer** [comment]
I keep having this same issue can someone help me?

**Comment by Janrupf** [comment]
Just create a new one so you have 16, name it java-8u51

**Comment by HelloiAmAplayer** [comment]
ok

**Comment by HelloiAmAplayer** [comment]
Still a white screen :/

**Comment by HelloiAmAplayer** [comment]
I'm trying to launch 1.5.1 with mods

**Comment by Janrupf** [comment]
Sure, now go to the instance settings -> Settings.
Check "Java Installation" and choose the folder you created and in there bin/java

**Comment by HelloiAmAplayer** [comment]
??? I don't have Java Installation

**Comment by HelloiAmAplayer** [comment]
I only have Java

**Comment by Janrupf** [comment]
![image](https://user-images.githubusercontent.com/25827180/43101394-9996765e-8ec8-11e8-993d-5d4072a53e8f.png)
Here, check Java Installation (DON'T COPY THE TEXT FIELD)

**Comment by HelloiAmAplayer** [comment]
Ah ok

**Comment by HelloiAmAplayer** [comment]
So I am good now?

**Comment by Janrupf** [comment]
No, no click on Browse, search your folder java-8u51/bin/javaw.exe

**Comment by HelloiAmAplayer** [comment]
Ok I did that

**Comment by Janrupf** [comment]
You should be good to go now

**Comment by HelloiAmAplayer** [comment]
![capture 3](https://user-images.githubusercontent.com/28176065/43101657-7c168da6-8e8e-11e8-874e-b73d71a18421.JPG)

**Comment by Janrupf** [comment]
Don't run MultiMC from zip files... Extract it

**Comment by HelloiAmAplayer** [comment]
Ok (Sorry if I sound like a complete noob) I have never used MultiMC before so where do I go??? Do I extract the download?

**Comment by Janrupf** [comment]
Yeah, extract it somewhere

**Comment by HelloiAmAplayer** [comment]
![capture 4](https://user-images.githubusercontent.com/28176065/43101869-1b2f4f68-8e8f-11e8-988a-84735d7aa5d2.JPG)

**Comment by HelloiAmAplayer** [comment]
So where.......

**Comment by HelloiAmAplayer** [comment]
??

**Comment by Janrupf** [comment]
Close that, extract the MultiMC.zip to you desktop

**Comment by HelloiAmAplayer** [comment]
K, I extracted MultiMC to my desktop

**Comment by Janrupf** [comment]
Ok, try to run it again

**Comment by HelloiAmAplayer** [comment]
![wat](https://user-images.githubusercontent.com/28176065/43102125-e289dbfa-8e8f-11e8-913d-c0a8a4e483ad.JPG)

**Comment by HelloiAmAplayer** [comment]
Ima just not play Minecraft right now

**Comment by HelloiAmAplayer** [comment]
Thanks for your help anyways
