### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by SPACEFACE2394** [MultiMC/MultiMC5#1821]
https://paste.ee/p/GPikM
```
MultiMC version: 0.5.0-945


Minecraft folder is:
instances/Deco/minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_111/bin/javaw.exe


Java is version 1.8.0_111, using 64-bit architecture.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/instances/Deco/natives

Libraries:
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-universal.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/versions/1.7.10/1.7.10.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  BiblioCraft[v1.11.5][MC1.7.10]
  BrewingAPI-1.7.10-3.0.2
  ClashsoftLib-1.7.10-2.4.1
  Decocraft-2.0.2_1.7.10
  MorePotionsMod-1.7.10-1.0.4
  OptiFine_1.7.10_HD_U_D6
  TheKitchenMod-1.3.23-1.7.2-10

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/instances/Deco/minecraft --assetsDir C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 8288


Using onesix launcher.

[17:21:20] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[17:21:20] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[17:21:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[17:21:20] [main/INFO] [FML]: Forge Mod Loader version 7.99.36.1558 for Minecraft 1.7.10 loading
[17:21:20] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_111, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_111
[17:21:20] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_U_D6.jar
[17:21:20] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:21:20] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[17:21:20] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:21:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:21:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:21:20] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[17:21:20] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[17:21:20] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[17:21:20] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ClassTransformer
[17:21:20] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine URL: file:/C:/Users/Caldwell/Downloads/mmc-stable-win32/MultiMC/instances/Deco/minecraft/mods/OptiFine_1.7.10_HD_U_D6.jar
[17:21:20] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ZIP file: C:\Users\Caldwell\Downloads\mmc-stable-win32\MultiMC\instances\Deco\minecraft\mods\OptiFine_1.7.10_HD_U_D6.jar
[17:21:20] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:21:25] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:21:25] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[17:21:25] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:21:25] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:21:28] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[17:21:28] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[17:21:29] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[17:21:29] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:21:31] [main/INFO]: Setting user: <PROFILE NAME>
[OptiFine] (Reflector) Class not present: ModLoader
[OptiFine] (Reflector) Class not present: net.minecraft.src.FMLRenderAccessLibrary
[OptiFine] (Reflector) Class not present: LightCache
[OptiFine] (Reflector) Class not present: BlockCoord
[17:21:40] [Client thread/INFO]: LWJGL Version: 2.9.1
[OptiFine] 
[OptiFine] OptiFine_1.7.10_HD_U_D6
[OptiFine] Build: 20160629-164100
[OptiFine] OS: Windows 10 (amd64) version 10.0
[OptiFine] Java: 1.8.0_111, Oracle Corporation
[OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[OptiFine] LWJGL: 2.9.1
[OptiFine] OpenGL: AMD Radeon(TM) R5 Graphics, version 4.5.13397 Compatibility Profile Context 15.200.1055.0, ATI Technologies Inc.
[OptiFine] OpenGL Version: 4.0
[OptiFine] OpenGL Fancy fog: Not available (GL_NV_fog_distance)
[OptiFine] Maximum texture size: 16384x16384
[OptiFine] Checking for new version
[OptiFine] Version found: D6
[17:21:42] [Client thread/INFO] [FML]: Forge Mod Loader has detected optifine OptiFine_1.7.10_HD_U_D6, enabling compatibility features
[17:21:42] [Client thread/INFO] [STDOUT]: [cpw.mods.fml.client.SplashProgress:start:188]: ---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2/19/17 5:21 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 562002768 bytes (535 MB) / 668991488 bytes (638 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13397 Compatibility Profile Context 15.200.1055.0' Renderer: 'AMD Radeon(TM) R5 Graphics'
[17:21:42] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[17:21:42] [Client thread/INFO] [FML]: MinecraftForge v10.13.4.1558 Initialized
[17:21:42] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[17:21:43] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[17:21:44] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[17:21:44] [Client thread/INFO] [FML]: Searching C:\Users\Caldwell\Downloads\mmc-stable-win32\MultiMC\instances\Deco\minecraft\mods for mods
[17:22:06] [Client thread/INFO] [FML]: Forge Mod Loader has identified 9 mods to load
[17:22:07] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, BiblioCraft, brewingapi, cslib, props, morepotions, kitchen] at CLIENT
[17:22:07] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, BiblioCraft, brewingapi, cslib, props, morepotions, kitchen] at SERVER
[17:22:13] [Client thread/ERROR] [morepotions]: Skipping event FMLConstructionEvent and marking errored mod morepotions since required dependency brewingapi has errored
[17:22:13] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from CONSTRUCTING to PREINITIALIZATION. Loading cannot continue
[17:22:13] [Client thread/ERROR] [FML]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UC	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UC	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UC	cslib{1.7.10-2.4.1} [Clashsoft Lib] (ClashsoftLib-1.7.10-2.4.1.jar) 
	UE	brewingapi{1.7.10-3.0.2} [Brewing API] (BrewingAPI-1.7.10-3.0.2.jar) 
	UC	props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) 
	UE	morepotions{1.7.10-1.0.4} [More Potions Mod] (MorePotionsMod-1.7.10-1.0.4.jar) 
	UC	kitchen{1.3.23} [The Kitchen Mod] (TheKitchenMod-1.3.23-1.7.2-10.jar) 
[17:22:13] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[17:22:13] [Client thread/ERROR] [FML]: Caught exception from brewingapi
java.lang.NoSuchFieldError: description
	at clashsoft.brewingapi.BrewingAPI.<init>(BrewingAPI.java:99) ~[BrewingAPI.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_111]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_111]
	at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:506) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
[17:22:14] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/19/17 5:22 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: description
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Caused by: java.lang.NoSuchFieldError: description
	at clashsoft.brewingapi.BrewingAPI.<init>(BrewingAPI.java:99)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:506)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 313604464 bytes (299 MB) / 607125504 bytes (579 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D6 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UC	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UC	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UC	cslib{1.7.10-2.4.1} [Clashsoft Lib] (ClashsoftLib-1.7.10-2.4.1.jar) 
	UE	brewingapi{1.7.10-3.0.2} [Brewing API] (BrewingAPI-1.7.10-3.0.2.jar) 
	UC	props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) 
	UE	morepotions{1.7.10-1.0.4} [More Potions Mod] (MorePotionsMod-1.7.10-1.0.4.jar) 
	UC	kitchen{1.3.23} [The Kitchen Mod] (TheKitchenMod-1.3.23-1.7.2-10.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13397 Compatibility Profile Context 15.200.1055.0' Renderer: 'AMD Radeon(TM) R5 Graphics'
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.13397 Compatibility Profile Context 15.200.1055.0
	OpenGlRenderer: AMD Radeon(TM) R5 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
[17:22:14] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Caldwell\Downloads\mmc-stable-win32\MultiMC\instances\Deco\minecraft\crash-reports\crash-2017-02-19_17.22.13-client.txt
Process exited with code -1.
Clipboard copy at: 19 Feb 2017 17:22:27 -0700
Clipboard copy at: 19 Feb 2017 17:22:30 -0700
MultiMC: Log upload triggered at: 19 Feb 2017 17:22:37 -0700
MultiMC: Log uploaded to: https://paste.ee/p/GPikM
Clipboard copy at: 19 Feb 2017 17:23:44 -0700
```

**Comment by QuImUfu** [comment]
ClashsoftLib (and  Decocraft) are outdated and the old version of ClashsoftLib is causing that crash. 
newest ClashsoftLib download:
https://github.com/Clashsoft/Clashsoft-Lib/releases/download/1.7.10-2.7.3/ClashsoftLib-1.7.10-2.7.3.jar

**Comment by SPACEFACE2394** [comment]
it seems to have worked thanks!
