### ISSUE TITLE
I get "Shutting down internal server" when ever I start up a world. Help

### ISSUE THREAD

**Issue by LegitSting** [MultiMC/MultiMC5#1833]
**# I am trying to make a modded minecraft world with mineshafter and forge, but ever time I start it up I get "Shutting down internal server" I tried deleting my options and restarting minecraft, but it doesn't work. I've also tried reinstalling minecraft, yet that doesn't work either. Could someone help me?

Here is the crash report.**

```
**_---- Minecraft Crash Report ----
// My bad.

Time: 3/4/17 3:51 PM
Description: Updating screen events

com.eclipsesource.json.ParseException: Expected value at 1:0
	at com.eclipsesource.json.JsonParser.error(JsonParser.java:371)
	at com.eclipsesource.json.JsonParser.expected(JsonParser.java:364)
	at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:97)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:62)
	at com.eclipsesource.json.JsonValue.readFrom(JsonValue.java:105)
	at com.eclipsesource.json.JsonObject.readFrom(JsonObject.java:138)
	at info.mineshafter.datasources.MineshafterProfileAuthority.getProfile(MineshafterProfileAuthority.java:51)
	at info.mineshafter.storage.Profiles.byId(Profiles.java:74)
	at info.mineshafter.intercept.ProfileHandler.getProfile(ProfileHandler.java:75)
	at info.mineshafter.intercept.ProfileHandler.handle(ProfileHandler.java:51)
	at info.mineshafter.hacks.URLConnectionAdapter.doRequest(URLConnectionAdapter.java:43)
	at info.mineshafter.hacks.URLConnectionAdapter.getInputStream(URLConnectionAdapter.java:59)
	at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:126)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:54)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2350)
	at net.minecraftforge.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:733)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186777_e(GuiListWorldSelectionEntry.java:245)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186774_a(GuiListWorldSelectionEntry.java:199)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_148278_a(GuiListWorldSelectionEntry.java:168)
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41)
	at net.minecraft.client.gui.GuiWorldSelection.func_73864_a(SourceFile:118)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiWorldSelection.func_146274_d(SourceFile:50)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at info.mineshafter.GameStarter.main(GameStarter.java:24)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.eclipsesource.json.JsonParser.error(JsonParser.java:371)
	at com.eclipsesource.json.JsonParser.expected(JsonParser.java:364)
	at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:97)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:62)
	at com.eclipsesource.json.JsonValue.readFrom(JsonValue.java:105)
	at com.eclipsesource.json.JsonObject.readFrom(JsonObject.java:138)
	at info.mineshafter.datasources.MineshafterProfileAuthority.getProfile(MineshafterProfileAuthority.java:51)
	at info.mineshafter.storage.Profiles.byId(Profiles.java:74)
	at info.mineshafter.intercept.ProfileHandler.getProfile(ProfileHandler.java:75)
	at info.mineshafter.intercept.ProfileHandler.handle(ProfileHandler.java:51)
	at info.mineshafter.hacks.URLConnectionAdapter.doRequest(URLConnectionAdapter.java:43)
	at info.mineshafter.hacks.URLConnectionAdapter.getInputStream(URLConnectionAdapter.java:59)
	at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:126)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:54)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2350)
	at net.minecraftforge.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:733)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186777_e(GuiListWorldSelectionEntry.java:245)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186774_a(GuiListWorldSelectionEntry.java:199)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_148278_a(GuiListWorldSelectionEntry.java:168)
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41)
	at net.minecraft.client.gui.GuiWorldSelection.func_73864_a(SourceFile:118)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiWorldSelection.func_146274_d(SourceFile:50)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiScreenWorking
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at info.mineshafter.GameStarter.main(GameStarter.java:24)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 199913568 bytes (190 MB) / 500711424 bytes (477 MB) up to 13945274368 bytes (13299 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx13G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2239 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2239.jar) 
	UCHIJAAAA	Forge{12.18.3.2239} [Minecraft Forge] (forge-1.10.2-12.18.3.2239.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4531' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2239
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.3.0 - Build 20.19.15.4531, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Pentium(R) 3558U @ 1.70GHz_**
```

**Comment by LegitSting** [comment]
I do understand that Forge doesn't care about cracked/pirated content, but my bro is able to use all the mods he wants, but I can't find a way to fix my mineshafter.

**Comment by peterix** [comment]
MultiMC is not Mineshafter. I cannot help you.

**Comment by LegitSting** [comment]
Oh
