### ISSUE TITLE
Narrator does not work with MultiMC

### ISSUE THREAD

**Issue by mattiemonster** [MultiMC/MultiMC5#1852]
System Information
-----------------------------
MultiMC version: 0.5.0-945

Operating System: Windows 10 (64-bit)

Summary of the issue or suggestion:
----------------------------------------------
The narrator feature of the 1.12 version of Minecraft does not work when the game is launched using the MultiMC launcher. It works fine when using the usual Minecraft Launcher.

What should happen:
------------------------------
The narrator will turn on and anything said in the chat (or system messages if said to do so) will be spoken by a text to speech voice.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Load up Minecraft _17w14a or above_ using MultiMC.

2. Create or load a world.

3. Ctrl+B. 

Suspected cause:
---------------------------
Missing a library or the library is not allowed by MultiMC.

Logs/Screenshots:
----------------------------
https://paste.ee/p/aLJrX

[18:00:50] [Narrator/INFO]: [STDERR]: java.lang.UnsatisfiedLinkError: com.mojang.text2speech.NarratorWindows$SAPIWrapperSolutionDLL.say(Lcom/sun/jna/WString;)J
[18:00:50] [Narrator/INFO]: [STDERR]: 	at com.mojang.text2speech.NarratorWindows$SAPIWrapperSolutionDLL.say(Native Method)
[18:00:50] [Narrator/INFO]: [STDERR]: 	at com.mojang.text2speech.NarratorWindows$NarratorThread.say(NarratorWindows.java:65)
[18:00:50] [Narrator/INFO]: [STDERR]: 	at com.mojang.text2speech.NarratorWindows$NarratorThread.run(NarratorWindows.java:45)
[18:00:50] [Narrator/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:745)

Additional Info:
---------------------------
None.

**Comment by peterix** [comment]
Already fixed in develop.

**Comment by mattiemonster** [comment]
@peterix Oh, didn't know that.. sorry!

**Comment by peterix** [comment]
No problem... the next few months will be interesting.

Mojang is changing a lot of things currently. Forge will change a lot of things. It will likely upset a lot of MultiMC functionality...
