### ISSUE TITLE
Error code -1

### ISSUE THREAD

**Issue by Valantain** [MultiMC/MultiMC5#1880]
System Information
-----------------------------
MultiMC version: MultiMC5

Logs/Screenshots:
----------------------------
```
MultiMC version: 0.5.0-945


Minecraft folder is:
instances/ADve/minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_131/bin/javaw.exe


Java is version 1.8.0_131, using 32-bit architecture.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/instances/ADve/natives

Libraries:
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/com/mojang/realms/1.9.8/realms-1.9.8.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/net/minecraftforge/forge/1.10.2-12.18.3.2185/forge-1.10.2-12.18.3.2185-universal.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/versions/1.10.2/1.10.2.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar

Mods:
  Biome_Bundle-v5
  OpenTerrainGenerator-1.10.2-v17

Params:
  --username  --version MultiMC5 --gameDir C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/instances/ADve/minecraft --assetsDir C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156/MultiMC/assets --assetIndex 1.10 --uuid  --accessToken  --userType  --versionType custom --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 9120


Using onesix launcher.

2017-05-06 16:27:37,570 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-05-06 16:27:37,572 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:27:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:27:37] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:27:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:27:37] [main/INFO] [FML]: Forge Mod Loader version 12.18.3.2185 for Minecraft 1.10.2 loading
[16:27:37] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_131, running on Windows 10:x86:10.0, installed at C:\Program Files\Java\jre1.8.0_131
[16:27:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:27:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:27:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:27:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:27:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:27:41] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[16:27:41] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[16:27:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:27:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:27:41] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:27:41] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:27:41] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
2017-05-06 16:27:42,399 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-05-06 16:27:42,425 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-05-06 16:27:42,430 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:27:42] [Client thread/INFO]: Setting user: <PROFILE NAME>
[16:27:48] [Client thread/INFO]: LWJGL Version: 2.9.1
[16:27:52] [Client thread/INFO] [FML]: Could not load splash.properties, will create a default one
[16:27:52] [Client thread/INFO] [STDOUT]: [net.minecraftforge.fml.client.SplashProgress:start:219]: ---- Minecraft Crash Report ----
// My bad.

Time: 5/6/17 4:27 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 275062960 bytes (262 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 8600M GT/PCIe/SSE2'
[16:27:52] [Client thread/INFO] [FML]: MinecraftForge v12.18.3.2185 Initialized
[16:27:52] [Client thread/INFO] [FML]: Replaced 231 ore recipes
[16:27:53] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[16:27:53] [Client thread/INFO] [FML]: Searching C:\Users\Séverine\AppData\Local\Temp\Rar$EX03.156\MultiMC\instances\ADve\minecraft\mods for mods
[16:27:55] [Client thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[16:27:55] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, biomebundle, openterraingenerator] at CLIENT
[16:27:55] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, biomebundle, openterraingenerator] at SERVER
[16:27:56] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Biome Bundle, FMLFileResourcePack:Open Terrain Generator
[16:27:56] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[16:27:56] [Client thread/INFO] [FML]: Found 423 ObjectHolder annotations
[16:27:56] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[16:27:56] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[16:27:56] [Client thread/INFO] [FML]: Applying holder lookups
[16:27:56] [Client thread/INFO] [FML]: Holder lookups applied
[16:27:56] [Client thread/INFO] [FML]: Applying holder lookups
[16:27:56] [Client thread/INFO] [FML]: Holder lookups applied
[16:27:56] [Client thread/INFO] [FML]: Applying holder lookups
[16:27:56] [Client thread/INFO] [FML]: Holder lookups applied
[16:27:56] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[16:27:56] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[16:27:56] [Client thread/INFO] [FML]: Applying holder lookups
[16:27:56] [Client thread/INFO] [FML]: Holder lookups applied
[16:27:56] [Client thread/INFO] [FML]: Injecting itemstacks
[16:27:56] [Client thread/INFO] [FML]: Itemstack injection complete
[16:27:57] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Found status: UP_TO_DATE Target: null
[16:28:00] [Sound Library Loader/INFO]: Starting up SoundSystem...
[16:28:00] [Thread-7/INFO]: Initializing LWJGL OpenAL
[16:28:00] [Thread-7/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:28:01] [Thread-7/INFO]: OpenAL initialized.
[16:28:01] [Sound Library Loader/INFO]: Sound engine started
[16:28:04] [Client thread/INFO] [FML]: Max texture size: 8192
[16:28:04] [Client thread/INFO]: Created: 16x16 textures-atlas
[16:28:07] [Client thread/INFO] [OTG]: 22 Global custom objects loaded
[16:28:08] [Client thread/ERROR] [biomebundle]: Skipping event FMLInitializationEvent and marking errored mod biomebundle since required dependency openterraingenerator has errored
[16:28:08] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from INITIALIZATION to POSTINITIALIZATION. Loading cannot continue
[16:28:08] [Client thread/ERROR] [FML]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHI	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHE	openterraingenerator{v14} [Open Terrain Generator] (OpenTerrainGenerator-1.10.2-v17.jar) 
	UCHE	biomebundle{1.0} [Biome Bundle] (Biome_Bundle-v5.jar) 
[16:28:08] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[16:28:08] [Client thread/ERROR] [FML]: Caught exception from Open Terrain Generator (openterraingenerator)
java.lang.IllegalArgumentException: Invalid dimension id 58
	at net.minecraft.world.DimensionType.func_186069_a(DimensionType.java:77) ~[atm.class:?]
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:99) ~[DimensionManager.class:?]
	at com.khorn.terraincontrol.forge.TCPlugin.registerDimensions(TCPlugin.java:153) ~[TCPlugin.class:?]
	at com.khorn.terraincontrol.forge.TCPlugin.load(TCPlugin.java:141) ~[TCPlugin.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
[16:28:08] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----
// Why did you do that?

Time: 5/6/17 4:28 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Open Terrain Generator (openterraingenerator)
Caused by: java.lang.IllegalArgumentException: Invalid dimension id 58
	at net.minecraft.world.DimensionType.func_186069_a(DimensionType.java:77)
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:99)
	at com.khorn.terraincontrol.forge.TCPlugin.registerDimensions(TCPlugin.java:153)
	at com.khorn.terraincontrol.forge.TCPlugin.load(TCPlugin.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 262160256 bytes (250 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHI	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHE	openterraingenerator{v14} [Open Terrain Generator] (OpenTerrainGenerator-1.10.2-v17.jar) 
	UCHE	biomebundle{1.0} [Biome Bundle] (Biome_Bundle-v5.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 8600M GT/PCIe/SSE2'
[16:28:08] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\SVERIN~1\AppData\Local\Temp\Rar$EX03.156\MultiMC\instances\ADve\minecraft\crash-reports\crash-2017-05-06_16.28.08-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Minecraft s'est arrété avec le code de d'arrêt -1.
MultiMC: Log upload triggered at: 06 May 2017 16:28:24 +0200
MultiMC: Log uploaded to: https://paste.ee/p/KyZ6H


```

**Comment by Valantain** [comment]
PS: Sorry, i'm french, it's hard to me to know what i have to write :/ hope u can help me

**Comment by peterix** [comment]
1.
Running MultiMC from a temporary folder: `C:/Users/SVERIN~1/AppData/Local/Temp/Rar$EX03.156`
These will be deleted by the system, or whatever application created them (in this case WinRar).

2.
The actual problem seems to be in openterraingenerator. Not sure where it comes from.

**Comment by peterix** [comment]
The same setup seems to work on the develop version of MultiMC. I haven't tried 'stable', but you might want to try 'develop':
![image](https://cloud.githubusercontent.com/assets/203326/25773482/3d31bbb4-327e-11e7-80d6-d6b152838cee.png)

Select the development update channel and then update. Reinstall Forge in the instance.
