### ISSUE TITLE
Fechamento 

### ISSUE THREAD

**Issue by leolinscraft** [MultiMC/MultiMC5#1931]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.6.jar)
  CoFH Loading Plugin (CoFHCore-1.11.2-4.2.2.6-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 7/11/17 5:28 PM
Description: Rendering item

java.lang.AbstractMethodError: Method codechicken/enderstorage/client/render/item/EnderTankItemRender.renderItem(Lnet/minecraft/item/ItemStack;Lnet/minecraft/client/renderer/block/model/ItemCameraTransforms$TransformType;)V is abstract
	at codechicken.enderstorage.client.render.item.EnderTankItemRender.renderItem(EnderTankItemRender.java)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:85)
	at codechicken.lib.render.item.CCRenderItem.func_184390_a(CCRenderItem.java:155)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:219)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:25)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:19)
	at mezz.jei.render.GuiIngredientFast.renderSlow(GuiIngredientFast.java:204)
	at mezz.jei.render.GuiIngredientFast.renderSlow(GuiIngredientFast.java:192)
	at mezz.jei.render.GuiIngredientFastList.render(GuiIngredientFastList.java:210)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:141)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:174)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_322_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:586)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:547)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1433)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at codechicken.enderstorage.client.render.item.EnderTankItemRender.renderItem(EnderTankItemRender.java)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:85)
	at codechicken.lib.render.item.CCRenderItem.func_184390_a(CCRenderItem.java:155)

-- Item being rendered --
Details:
	Item Type: codechicken.enderstorage.item.ItemEnderStorage@1d9f9600
	Item Aux: 1
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:219)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:25)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:19)

-- Ingredient being rendered --
Details:
	Ingredient Mod: EnderStorage
	Ingredient Info: 1xtile.enderStorage@1 enderstorage:enderstorage
Stacktrace:
	at mezz.jei.render.GuiIngredientFast.createRenderIngredientException(GuiIngredientFast.java:407)
	at mezz.jei.render.GuiIngredientFast.renderSlow(GuiIngredientFast.java:194)
	at mezz.jei.render.GuiIngredientFastList.render(GuiIngredientFastList.java:210)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:141)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:174)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_322_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:586)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:547)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1433)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- Screen render details --
Details:
	Screen name: mekanism.client.gui.GuiEnergyCube
	Mouse location: Scaled: (341, 176). Absolute: (683, 352)
	Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['LeoLinsCraft'/388, l='MpServer', x=-307.79, y=71.00, z=355.39]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-236,64,248), Chunk: (at 4,4,8 in -15,15; contains blocks -240,0,240 to -225,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 393115 game time, 465684 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 91 total; [EntityBat['Bat'/1282, l='MpServer', x=-277.24, y=23.16, z=371.78], EntityZombie['Zombie'/1540, l='MpServer', x=-288.50, y=28.00, z=392.50], EntitySkeleton['Skeleton'/1541, l='MpServer', x=-233.50, y=23.00, z=296.50], EntitySkeleton['Skeleton'/140, l='MpServer', x=-308.31, y=28.00, z=375.50], EntityWitch['Witch'/908, l='MpServer', x=-245.67, y=17.00, z=289.51], EntitySheep['Sheep'/144, l='MpServer', x=-306.20, y=71.00, z=400.63], EntityZombie['Zombie'/145, l='MpServer', x=-308.50, y=27.00, z=419.50], EntityItem['item.item.egg'/913, l='MpServer', x=-256.00, y=69.00, z=418.69], EntityBat['Bat'/1298, l='MpServer', x=-269.36, y=45.48, z=358.95], EntitySkeleton['Skeleton'/1043, l='MpServer', x=-327.50, y=67.00, z=292.71], EntityBat['Bat'/1299, l='MpServer', x=-274.81, y=45.09, z=358.28], EntitySkeleton['Skeleton'/1428, l='MpServer', x=-349.50, y=28.00, z=363.50], EntityCreeper['Creeper'/791, l='MpServer', x=-359.50, y=21.00, z=321.50], EntityCreeper['Creeper'/792, l='MpServer', x=-360.50, y=21.00, z=319.50], EntitySkeleton['Skeleton'/1049, l='MpServer', x=-276.50, y=21.00, z=312.50], EntityCreeper['Creeper'/1050, l='MpServer', x=-273.50, y=21.00, z=312.50], EntityBat['Bat'/923, l='MpServer', x=-345.61, y=28.52, z=367.41], EntityCreeper['Creeper'/160, l='MpServer', x=-288.50, y=15.00, z=369.50], EntitySheep['Sheep'/166, l='MpServer', x=-302.57, y=71.00, z=401.73], EntityZombieVillager['Zombie Villager'/168, l='MpServer', x=-301.76, y=34.00, z=436.46], EntityZombie['Zombie'/683, l='MpServer', x=-251.25, y=22.00, z=419.55], EntityBabySkeleton['entity.BabySkeleton.name'/1579, l='MpServer', x=-307.50, y=17.00, z=375.50], EntityZombie['Zombie'/1452, l='MpServer', x=-240.48, y=15.00, z=378.81], EntityCreeper['Creeper'/1580, l='MpServer', x=-289.92, y=23.00, z=314.27], EntitySkeleton['Skeleton'/685, l='MpServer', x=-255.50, y=21.00, z=421.50], EntitySpider['Spider'/1581, l='MpServer', x=-287.50, y=23.00, z=317.50], EntitySkeleton['Skeleton'/1582, l='MpServer', x=-284.31, y=22.26, z=316.50], EntitySkeleton['Skeleton'/1583, l='MpServer', x=-286.50, y=23.00, z=318.50], EntityCreeper['Creeper'/1072, l='MpServer', x=-309.70, y=37.00, z=427.30], EntitySpider['Spider'/1073, l='MpServer', x=-310.30, y=39.10, z=428.70], EntityBat['Bat'/179, l='MpServer', x=-282.37, y=46.10, z=326.89], EntityConcussionCreeper['Concussion Creeper'/1715, l='MpServer', x=-292.05, y=39.00, z=381.77], EntityCreeper['Creeper'/181, l='MpServer', x=-287.50, y=15.00, z=369.50], EntitySpider['Spider'/1717, l='MpServer', x=-292.60, y=39.00, z=376.50], EntityConcussionCreeper['Concussion Creeper'/182, l='MpServer', x=-283.50, y=20.00, z=368.50], EntitySquid['Squid'/1462, l='MpServer', x=-261.09, y=57.97, z=336.06], EntitySkeleton['Skeleton'/1718, l='MpServer', x=-293.50, y=39.00, z=379.50], EntityBabySkeleton['entity.BabySkeleton.name'/183, l='MpServer', x=-280.70, y=28.00, z=398.50], EntitySquid['Squid'/1463, l='MpServer', x=-266.82, y=61.47, z=331.06], EntitySkeleton['Skeleton'/1719, l='MpServer', x=-292.58, y=39.00, z=380.52], EntityBat['Bat'/1080, l='MpServer', x=-254.31, y=19.09, z=369.57], EntitySquid['Squid'/1469, l='MpServer', x=-240.76, y=58.16, z=342.03], EntitySquid['Squid'/1470, l='MpServer', x=-250.23, y=60.00, z=334.40], EntityChicken['Chicken'/193, l='MpServer', x=-261.42, y=69.00, z=282.50], EntityBat['Bat'/706, l='MpServer', x=-352.55, y=22.63, z=363.82], EntitySkeleton['Skeleton'/962, l='MpServer', x=-382.50, y=42.00, z=317.50], EntitySkeleton['Skeleton'/963, l='MpServer', x=-383.50, y=42.00, z=318.50], EntitySheep['Sheep'/196, l='MpServer', x=-289.55, y=70.00, z=357.14], EntityBat['Bat'/836, l='MpServer', x=-382.71, y=49.58, z=343.70], EntityBat['Bat'/710, l='MpServer', x=-337.65, y=31.10, z=280.13], EntityChicken['Chicken'/73, l='MpServer', x=-374.14, y=64.00, z=313.83], EntityZombie['Zombie'/842, l='MpServer', x=-242.50, y=14.00, z=385.50], EntityChicken['Chicken'/75, l='MpServer', x=-373.18, y=64.00, z=321.52], EntityChicken['Chicken'/76, l='MpServer', x=-380.26, y=63.00, z=348.17], EntityChicken['Chicken'/78, l='MpServer', x=-378.56, y=73.00, z=383.31], EntityChicken['Chicken'/79, l='MpServer', x=-379.77, y=69.00, z=380.50], EntityBat['Bat'/208, l='MpServer', x=-244.25, y=14.10, z=300.73], EntitySkeleton['Skeleton'/210, l='MpServer', x=-241.49, y=21.00, z=364.30], EntityBat['Bat'/1490, l='MpServer', x=-232.63, y=38.06, z=360.42], EntityChicken['Chicken'/82, l='MpServer', x=-380.80, y=75.00, z=386.15], EntityBat['Bat'/1747, l='MpServer', x=-354.27, y=26.00, z=371.75], EntityChicken['Chicken'/214, l='MpServer', x=-239.86, y=70.00, z=415.59], EntityChicken['Chicken'/215, l='MpServer', x=-255.13, y=69.00, z=418.65], EntityItem['item.item.egg'/600, l='MpServer', x=-359.68, y=64.00, z=293.78], EntityChicken['Chicken'/90, l='MpServer', x=-358.94, y=64.00, z=294.06], EntityChicken['Chicken'/91, l='MpServer', x=-365.92, y=63.00, z=293.86], EntityChicken['Chicken'/92, l='MpServer', x=-367.44, y=64.00, z=315.54], EntityBat['Bat'/1501, l='MpServer', x=-321.52, y=30.08, z=381.57], EntityItem['item.item.egg'/93, l='MpServer', x=-367.79, y=64.00, z=315.61], EntitySkeleton['Skeleton'/94, l='MpServer', x=-362.50, y=25.00, z=375.91], EntityItem['item.item.egg'/1886, l='MpServer', x=-365.96, y=63.24, z=293.34], EntitySkeleton['Skeleton'/863, l='MpServer', x=-328.50, y=26.00, z=380.50], EntityWitch['Witch'/96, l='MpServer', x=-362.50, y=25.00, z=373.50], EntityConcussionCreeper['Concussion Creeper'/1248, l='MpServer', x=-260.50, y=28.00, z=367.50], EntityZombie['Zombie'/1510, l='MpServer', x=-337.50, y=35.00, z=278.50], EntityZombie['Zombie'/1511, l='MpServer', x=-337.50, y=35.00, z=276.50], EntitySheep['Sheep'/106, l='MpServer', x=-347.18, y=66.00, z=326.51], EntityZombie['Zombie'/1514, l='MpServer', x=-276.50, y=20.00, z=310.50], EntityZombie['Zombie'/1386, l='MpServer', x=-351.50, y=35.00, z=280.50], EntitySheep['Sheep'/108, l='MpServer', x=-345.27, y=66.00, z=358.49], EntityChicken['Chicken'/236, l='MpServer', x=-230.69, y=64.00, z=285.84], EntityChicken['Chicken'/237, l='MpServer', x=-228.47, y=64.00, z=294.85], EntitySkeleton['Skeleton'/1005, l='MpServer', x=-288.50, y=24.00, z=290.50], EntityPlayerSP['LeoLinsCraft'/388, l='MpServer', x=-307.79, y=71.00, z=355.39], EntityBat['Bat'/244, l='MpServer', x=-242.53, y=39.01, z=360.60], EntityCow['Cow'/119, l='MpServer', x=-335.20, y=74.00, z=389.46], EntityZombie['Zombie'/247, l='MpServer', x=-237.50, y=38.00, z=398.50], EntitySheep['Sheep'/120, l='MpServer', x=-321.24, y=71.00, z=408.58], EntitySheep['Sheep'/248, l='MpServer', x=-241.63, y=66.00, z=392.51], EntitySheep['Sheep'/121, l='MpServer', x=-324.72, y=70.00, z=414.52], EntitySheep['Sheep'/122, l='MpServer', x=-330.55, y=71.00, z=400.18]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 514173776 bytes (490 MB) / 2036858880 bytes (1942 MB) up to 2036858880 bytes (1942 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.1.2386 Optifine OptiFine_1.11.2_HD_U_C2 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2386-universal.jar) 
	UCHIJAAAA	forge{13.20.1.2386} [Minecraft Forge] (forge-1.11.2-13.20.1.2386-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-3.0.0.284-universal.jar) 
	UCHIJAAAA	codechickenlib{3.0.0.284} [CodeChicken Lib] (CodeChickenLib-1.11.2-3.0.0.284-universal.jar) 
	UCHIJAAAA	cofhcore{4.2.2} [CoFH Core] (CoFHCore-1.11.2-4.2.2.6-universal.jar) 
	UCHIJAAAA	enderstorage{1.0} [EnderStorage] (Ender-Storage-Mod-1.11.2.jar) 
	UCHIJAAAA	shetiphiancore{3.4.5} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.6.jar) 
	UCHIJAAAA	endertanks{1.5.5} [EnderTanks] (endertanks-1.11.0-1.5.5.jar) 
	UCHIJAAAA	enderzoo{1.11.2-1.3.0.47} [Ender Zoo] (EnderZoo-1.11.2-1.3.0.47.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.4.jar) 
	UCHIJAAAA	forestry{5.3.4.119} [Forestry] (forestry_1.11.2-5.3.4.119.jar) 
	UCHIJAAAA	jei{4.5.0.289} [Just Enough Items] (jei_1.11.2-4.5.0.289.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.7} [JourneyMap] (journeymap-1.11.2-5.4.7.jar) 
	UCHIJAAAA	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJAAAA	mekanism{9.3.2} [Mekanism] (Mekanism-1.11.2-9.3.2.307.jar) 
	UCHIJAAAA	mekanismgenerators{9.3.2} [MekanismGenerators] (MekanismGenerators-1.11.2-9.3.2.307.jar) 
	UCHIJAAAA	mekanismtools{9.3.2} [MekanismTools] (MekanismTools-1.11.2-9.3.2.307.jar) 
	UCHIJAAAA	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCHIJAAAA	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4.jar) 
	UCHIJAAAA	rftools{6.01} [RFTools] (rftools-1.1x-6.01.jar) 
	UCHIJAAAA	tconstruct{1.11.2-2.7.0.26} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.26.jar) 
	UCHIJAAAA	thermalfoundation{2.2.2} [Thermal Foundation] (ThermalFoundation-1.11.2-2.2.2.4-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.2.3} [Thermal Expansion] (ThermalExpansion-1.11.2-5.2.3.4-universal.jar) 
	UCHIJAAAA	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.11.2-1.1.2.jar) 
	UCHIJAAAA	waila{1.7.1} [waila] (Waila-1.7.1_1.11.2.jar) 
	UCHIJAAAA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHIJAAAA	denseores{1.0} [denseores] (denseores-1.11-1.0.2.jar) 
	Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.6.jar)
  shetiphian.core.asm.ClassTransformer
CoFH Loading Plugin (CoFHCore-1.11.2-4.2.2.6-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 9500 GT/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	enderstorage Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce 9500 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.11.2-rv4.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU Q8400 @ 2.66GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_C2
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.0
	OpenGlRenderer: GeForce 9500 GT/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by peterix** [comment]
Sorry for not getting back to you. This was some sort of mod or mod API compatibility issue.
