### ISSUE TITLE
Help! Process exited with code 1

### ISSUE THREAD

**Issue by eroisgaming** [MultiMC/MultiMC5#1935]
MultiMC version: 5 Modify by hackphoenix.com

Minecraft folder is:
instances/Swag/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_131/bin/java.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2024m, -Xmx5048m, -Duser.language=en, -jar, D:/Swag/jars/NewLaunch.jar]

Minecraft process ID: 7348

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  D:/Swag/instances/Swag/natives

Traits:
  []

Libraries:
  D:/Swag/libraries/com/mojang/netty/1.6/netty-1.6.jar
  D:/Swag/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  D:/Swag/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Swag/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Swag/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Swag/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Swag/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  D:/Swag/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  D:/Swag/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/Swag/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  D:/Swag/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/Swag/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/Swag/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/Swag/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/Swag/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/Swag/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  D:/Swag/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  D:/Swag/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  D:/Swag/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  D:/Swag/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  D:/Swag/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  D:/Swag/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  D:/Swag/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  D:/Swag/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  D:/Swag/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  D:/Swag/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/Swag/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/Swag/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  D:/Swag/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  D:/Swag/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  D:/Swag/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  D:/Swag/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  D:/Swag/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  D:/Swag/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  D:/Swag/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  D:/Swag/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  D:/Swag/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  D:/Swag/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  D:/Swag/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  D:/Swag/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  D:/Swag/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  D:/Swag/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  D:/Swag/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  D:/Swag/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-universal.jar
  D:/Swag/versions/1.7.10/1.7.10.jar

Mods:
  ArchimedesShips-1.7.1
  [1.7.10]ArmorStatusHUD-client-1.28
  Atum-1.7.10-0.6.77
  AutoSwitch-v5.1.1-mc1.7.10
  BetterPvP_1.12.9_Forge_1.7.10
  BiblioCraft[v1.11.7][MC1.7.10]
  buildcraft-7.1.22
  Chisel-2.9.5.11
  chocolateQuest-1.7.10-1.0
  CodeChickenCore-1.7.10-1.0.7.47-universal
  denseores-1.6.2
  DynamicLights-1.7.10
  EnchantingPlus-1.10.2-4.1.0.115
  extrabiomesxl_1.7.10-3.16.4
  GalacticraftCore-1.7-3.0.12.497
  Galacticraft-Planets-1.7-3.0.12.497
  ShadersModCore-v2.3.31-mc1.7.10-f
  Hats-Mod-1.7.10
  HatStand-4.0.0
  Highlands-1.7.2-v-2.2.3
  MicdoodleCore-1.7-3.0.12.497
  Millenaire6.0.0
  MCA-1.7.10-5.2.0-universal
  Morph-Beta-0.9.3
  NotEnoughItems-1.7.10-1.0.5.120-universal
  OptiFine_1.7.10_HD_U_D8
  RTG-1.7.10-1.1.1.6
  RunicDungeons-1.1.7b
  Streams-1.7.10-0.3.3
  TheKitchenMod-1.3.23-1.7.2-10
  twilightforest-1.7.10-2.3.7
  [1.7.10]Treecapitator-universal-2.0.4
  tropicraftv6_0_5 for MC v1_7_10

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, D:/Swag/instances/Swag/minecraft, --assetsDir, D:/Swag/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[22:11:29] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[22:11:29] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[22:11:29] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[22:11:30] [main/INFO]: Forge Mod Loader version 7.99.36.1558 for Minecraft 1.7.10 loading
[22:11:30] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_131, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_131
[22:11:30] [main/WARN]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
Downloading file http://files.minecraftforge.net/maven/codechicken/CodeChickenLib/1.7.10-1.1.3.138//CodeChickenLib-1.7.10-1.1.3.138-universal.jar
[22:11:31] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:download:343]: Download complete
Downloading file http://bspk.rs/MC/bspkrsCore/[1.7.10]bspkrsCore-universal-6.15.jar
[22:11:31] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:download:343]: Download complete
[22:11:32] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:11:32] [main/INFO]: [micdoodle8.mods.miccore.DepLoader$DepLoadInst:<init>:333]: MicdoodleCore searching for dependencies in mods file: D:\Swag\instances\Swag\minecraft\mods
[22:11:32] [main/WARN]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:11:32] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_U_D8.jar
[22:11:32] [main/INFO]: Loading tweaker shadersmodcore.loading.SMCTweaker from ShadersModCore-v2.3.31-mc1.7.10-f.jar
[22:11:32] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:11:32] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[22:11:32] [main/INFO]: Loading tweak class name shadersmodcore.loading.SMCTweaker
[22:11:32] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[22:11:32] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:11:32] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:11:32] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[22:11:32] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[22:11:32] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[22:11:32] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ClassTransformer
[22:11:32] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine URL: file:/D:/Swag/instances/Swag/minecraft/mods/OptiFine_1.7.10_HD_U_D8.jar
[22:11:32] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ZIP file: D:\Swag\instances\Swag\minecraft\mods\OptiFine_1.7.10_HD_U_D8.jar
[22:11:32] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:11:33] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[22:11:33] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[22:11:33] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:11:33] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:11:33] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:11:33] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:11:33] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:102]: Successfully Registered Transformer
[22:11:33] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[22:11:33] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[22:11:33] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:11:33] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[22:11:34] [main/INFO]: Calling tweak class shadersmodcore.loading.SMCTweaker
[22:11:34] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[22:11:34] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[22:11:34] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[22:11:34] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[SMC FNE]transforming bao net.minecraft.client.Minecraft
[SMC FNE] 79456 (+59)
[22:11:34] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: ahb (1 / 1)
[22:11:34] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[22:11:34] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: sa (1 / 1)
[22:11:34] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: bdi (1 / 1)
[22:11:35] [main/INFO]: Setting user: <PROFILE NAME>
[SMC FNE]transforming aji net.minecraft.block.Block
[SMC INF]   blockAoLight
[SMC FNE] 69873 (+60)
[22:11:35] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: xk (1 / 1)
[SMC FNE]transforming abh net.minecraft.item.ItemBlock
[SMC FNE] 6426 (+0)
[22:11:36] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: zc (1 / 1)
[22:11:37] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: ModLoader
[SMC FNE]transforming blm net.minecraft.client.renderer.RenderBlocks
[SMC FNE] 163944 (+245)
[22:11:37] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: LightCache
[22:11:37] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: BlockCoord
[22:11:37] [Client thread/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: net/minecraftforge/client/ForgeHooksClient (1 / 1)
[SMC FNE]transforming bqf net.minecraft.client.renderer.texture.TextureManager
[SMC FNE] 8356 (+123)
[SMC FNE]transforming bma net.minecraft.client.renderer.RenderGlobal
[SMC FNR]  patch method net/minecraft/client/renderer/RenderGlobal.func_147589_a(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/client/renderer/culling/ICamera;F)V
[SMC FNR]  patch method net/minecraft/client/renderer/RenderGlobal.func_72719_a(Lnet/minecraft/entity/EntityLivingBase;ID)I
[SMC FNR]  patch method net/minecraft/client/renderer/RenderGlobal.func_72714_a(F)V
[SMC FNR]  patch method net/minecraft/client/renderer/RenderGlobal.func_72717_a(Lnet/minecraft/client/renderer/Tessellator;Lnet/minecraft/entity/player/EntityPlayer;F)V
[SMC FNR]  patch method net/minecraft/client/renderer/RenderGlobal.drawBlockDamageTexture(Lnet/minecraft/client/renderer/Tessellator;Lnet/minecraft/entity/EntityLivingBase;F)V
[SMC FNR]  patch method net/minecraft/client/renderer/RenderGlobal.func_72731_b(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/MovingObjectPosition;IF)V
[SMC FNE] 74687 (+200)
[SMC FNE]transforming bpz net.minecraft.client.renderer.texture.TextureMap
[SMC FNT]    allocateTextureMap
[SMC FNT]    setSprite setIconName
[SMC FNT]    uploadTexSubForLoadAtlas
[SMC FNE] 25421 (+300)
[SMC FNE]transforming bqh net.minecraft.client.renderer.texture.ITextureObject
[SMC FNE] 410 (+47)
[SMC FNE]transforming bpp net.minecraft.client.renderer.texture.AbstractTexture
[SMC FNE] 1616 (+324)
[SMC FNE]transforming bno net.minecraft.client.renderer.entity.Render
[SMC FNR]    conditionally skip default shadow
[SMC FNE] 11780 (+47)
[22:11:38] [Client thread/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: bjb (2 / 2)
[22:11:38] [Client thread/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1905]: Potential problem: Galacticraft did not complete injection of bytecode into: blt (4 / 5)
[SMC FNE]transforming blt net.minecraft.client.renderer.EntityRenderer
[SMC FNR]  patch method net/minecraft/client/renderer/EntityRenderer.func_78476_b(FI)V
[SMC FNR]  patch method net/minecraft/client/renderer/EntityRenderer.func_78483_a(D)V
[SMC FNR]  patch method net/minecraft/client/renderer/EntityRenderer.func_78463_b(D)V
[SMC FNR]  patch method net/minecraft/client/renderer/EntityRenderer.func_78471_a(FJ)V
[SMC FNR]  patch method net/minecraft/client/renderer/EntityRenderer.func_82829_a(Lnet/minecraft/client/renderer/RenderGlobal;F)V
[SMC FNR]  patch method net/minecraft/client/renderer/EntityRenderer.func_78466_h(F)V
[SMC FNR]  patch method net/minecraft/client/renderer/EntityRenderer.func_78468_a(IF)V
[SMC FNR]  patch method net/minecraft/client/renderer/EntityRenderer.func_78469_a(FFFF)Ljava/nio/FloatBuffer;
[SMC FNE] 61012 (+496)
[SMC FNE]transforming bnx net.minecraft.client.renderer.tileentity.RenderItemFrame
[SMC FNE] 11682 (+108)
[22:11:38] [Client thread/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: boh (1 / 1)
[SMC FNE]transforming boh net.minecraft.client.renderer.entity.RendererLivingEntity
[SMC FNE] 15959 (+256)
[22:11:38] [Client thread/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: bkn (1 / 1)
[22:11:38] [Client thread/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: bly (1 / 1)
[SMC FNE]transforming bly net.minecraft.client.renderer.ItemRenderer
[SMC FNR]  patch method net/minecraft/client/renderer/ItemRenderer.func_78443_a(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/item/ItemStack;I)V
[SMC FNR]  patch method net/minecraft/client/renderer/ItemRenderer.renderItem(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/item/ItemStack;ILnet/minecraftforge/client/IItemRenderer$ItemRenderType;)V
[SMC FNR]  patch method net/minecraft/client/renderer/ItemRenderer.func_78441_a()V
[SMC FNE] 20474 (+109)
[22:11:38] [Client thread/INFO]: LWJGL Version: 2.9.1
[SMC FNE]transforming buu net.minecraft.client.renderer.OpenGlHelper
[SMC FNT]    set activeTexUnit
[SMC FNE] 16015 (+65)
[22:11:40] [Client thread/INFO]: [OptiFine] 
[22:11:40] [Client thread/INFO]: [OptiFine] OptiFine_1.7.10_HD_U_D8
[22:11:40] [Client thread/INFO]: [OptiFine] Build: 20170504-230608
[22:11:40] [Client thread/INFO]: [OptiFine] OS: Windows 8.1 (amd64) version 6.3
[22:11:40] [Client thread/INFO]: [OptiFine] Java: 1.8.0_131, Oracle Corporation
[22:11:40] [Client thread/INFO]: [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[22:11:40] [Client thread/INFO]: [OptiFine] LWJGL: 2.9.1
[22:11:40] [Client thread/INFO]: [OptiFine] OpenGL: GeForce GT 730/PCIe/SSE2, version 4.5.0 NVIDIA 381.89, NVIDIA Corporation
[22:11:40] [Client thread/INFO]: [OptiFine] OpenGL Version: 4.5.0
[22:11:40] [Client thread/INFO]: [OptiFine] Maximum texture size: 16384x16384
[22:11:40] [Thread-8/INFO]: [OptiFine] Checking for new version
[22:11:41] [Thread-8/INFO]: [OptiFine] Version found: D8
[22:11:41] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 7/19/17 10:11 PM
Description: Initializing game

java.lang.RuntimeException: Shaders Mod detected. Please remove it, OptiFine has built-in support for shaders.
	at shadersmod.client.Shaders.checkShadersModInstalled(Shaders.java:5453)
	at shadersmod.client.Shaders.startup(Shaders.java:1762)
	at Config.initDisplay(Config.java:212)
	at net.minecraft.client.renderer.OpenGlHelper.func_77474_a(OpenGlHelper.java:79)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:455)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at shadersmod.client.Shaders.checkShadersModInstalled(Shaders.java:5453)
	at shadersmod.client.Shaders.startup(Shaders.java:1762)
	at Config.initDisplay(Config.java:212)
	at net.minecraft.client.renderer.OpenGlHelper.func_77474_a(OpenGlHelper.java:79)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:455)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1811638352 bytes (1727 MB) / 2034237440 bytes (1940 MB) up to 4705484800 bytes (4487 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2024m -Xmx5048m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GT 730/PCIe/SSE2 GL version 4.5.0 NVIDIA 381.89, NVIDIA Corporation
	GL Caps: 
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 381.89
	OpenGlRenderer: GeForce GT 730/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
[22:11:41] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# D:\Swag\instances\Swag\minecraft\crash-reports\crash-2017-07-19_22.11.40-client.txt
Process exited with code -1.

**Comment by QuImUfu** [comment]
````Shaders Mod detected. Please remove it, OptiFine has built-in support for shaders.````
Read the log.

**Comment by eroisgaming** [comment]
thanks
