### ISSUE TITLE
Custom jar launching another custom jar?

### ISSUE THREAD

**Issue by filip3712** [MultiMC/MultiMC5#1996]
System Information
-----------------------------
MultiMC version: Latest Develop-1068
Operating System: W10
Summary of the issue or suggestion: What if add custom jar to instance and this customjar trying run custom minecraft client? Something like "loader" a Minecraft Client(?)
I'm trying something like this but i get this error:

`java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:193)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:254)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at xxx.test.launcher.xxxLauncher.main(xxxLauncher.java:27)
	... 8 more`

I don't know where to put my custom minecraft client... i don't know where this searching (lol)

Sorry for my english.

**Comment by Chewsterchew** [comment]
Like a different client (e.g. hacked client)? In the versions tab, you have to Add Jar Mod (in Advanced, bottom right of the version tab). Then add the extracted client.jar there. That's how I got it, if that doesn't work, it might be a problem with the client.jar

**Comment by filip3712** [comment]
Most player and servers in Poland using Custom Minecraft Client from group "BlazingPack" this client is protected from hack/xray txt/cheat engine/xray(anty cheat) etc...we can't edit this minecraft client .jar because he automatically download newest. Ckecking MD5 when starting or something. This client have 2 jars, starter/loader(?) and client. I can upload here if you want check this.

**Comment by QuImUfu** [comment]
i am not able to get this running as it is pretty different to a normal minecraft installation. If it is possible to start this BlazingPack client over MultiMC, it is not easy.
Additionally this "BlazingPack" clearly violates the minecraft EULA, by redistributing a complete minecraft client and by offering a launcher you can play minecaft with, without an account.

**Comment by peterix** [comment]
Probably not, but I'll look into it.

**Comment by peterix** [comment]
It definitely is not following the EULA.

**Comment by peterix** [comment]
It seems heavily obfuscated. Do not use this, do not trust this. It does really shady things no application should.
