### ISSUE TITLE
Issues in linux with exit code 255

### ISSUE THREAD

**Issue by 23235599** [MultiMC/MultiMC5#2010]
MultiMC version: 0.5.0-887

Minecraft folder is:
instances/1.7.10/minecraft

Java path is:
/usr/bin/java

Java版本9, 在64-bit架构上

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/instances/1.7.10/natives

Libraries:
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/google/guava/guava/15.0/guava-15.0.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/versions/1.7.10/1.7.10.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-linux.jar

Params:
  --username  --version MultiMC5 --gameDir /home/<PROFILE NAME>/Desktop/mc/MultiMC/instances/1.7.10/minecraft --assetsDir /home/<PROFILE NAME>/Desktop/mc/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType 

Window size: 854 x 480

Java Arguments:
[-Xms2048m, -Xmx4096m, -Duser.language=en]

Minecraft进程ID：23381

Using onesix launcher.

Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/google/guava/guava/15.0/guava-15.0.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
Exiting with -1
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: /home/<PROFILE NAME>/Desktop/mc/MultiMC/versions/1.7.10/1.7.10.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Halting launch due to previous errors.
进程退出，代码：255。

**Comment by peterix** [comment]
Do not use java 9.
