### ISSUE TITLE
Process exited with code -1. (No mods installed)

### ISSUE THREAD

**Issue by Fi3ryMadness** [MultiMC/MultiMC5#2013]
System Information
-----------------------------
MultiMC version: 0.5.0-945 on win32

Operating System: Windows 7 Home Premium 32bit

Summary of the issue or suggestion:
----------------------------------------------
So I've been playing minecraft for a while and I wanted to install some light mods. 
I installed MultiMC and tried launching just vanilla 1.12.2 but it won't launch.
If anyone can tell what's the issue that would be great. Thanks.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
MultiMC version: 0.5.0-945

Minecraft folder is:
instances/1.12.2/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_141/bin/javaw.exe

Java is version 1.8.0_141, using 32-bit architecture.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Program Files/MultiMC/instances/1.12.2/natives

Libraries:
  C:/Program Files/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Program Files/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Program Files/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Program Files/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Program Files/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Program Files/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Program Files/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Program Files/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Program Files/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Program Files/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Program Files/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Program Files/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Program Files/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Program Files/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Program Files/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Program Files/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Program Files/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Program Files/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Program Files/MultiMC/libraries/com/mojang/realms/1.10.17/realms-1.10.17.jar
  C:/Program Files/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Program Files/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Program Files/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Program Files/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Program Files/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Program Files/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Program Files/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Program Files/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Program Files/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Program Files/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Program Files/MultiMC/versions/1.12.2/1.12.2.jar
  C:/Program Files/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Program Files/MultiMC/instances/1.12.2/minecraft --assetsDir C:/Program Files/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 3636

Using onesix launcher.

ERROR StatusLogger Error creating converter for d
 java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.logging.log4j.core.pattern.PatternParser.createConverter(PatternParser.java:582)
	at org.apache.logging.log4j.core.pattern.PatternParser.finalizeConverter(PatternParser.java:638)
	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:414)
	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:177)
	at org.apache.logging.log4j.core.layout.PatternLayout$SerializerBuilder.build(PatternLayout.java:376)
	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:128)
	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:58)
	at org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:652)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.setToDefault(AbstractConfiguration.java:577)
	at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:47)
	at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:86)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:171)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:145)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:70)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:147)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:537)
	at bib.<clinit>(SourceFile:224)
	at net.minecraft.client.main.Main.main(SourceFile:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Caused by: java.lang.Error: java.io.FileNotFoundException: C:\Program Files\Java\jre1.8.0_141\lib\tzdb.dat (The system cannot find the file specified)
	at sun.util.calendar.ZoneInfoFile$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.util.calendar.ZoneInfoFile.<clinit>(Unknown Source)
	at sun.util.calendar.ZoneInfo.getTimeZone(Unknown Source)
	at java.util.TimeZone.getTimeZone(Unknown Source)
	at java.util.TimeZone.setDefaultZone(Unknown Source)
	at java.util.TimeZone.getDefaultRef(Unknown Source)
	at java.util.TimeZone.getDefault(Unknown Source)
	at org.apache.logging.log4j.core.util.datetime.FixedDateFormat.createIfSupported(FixedDateFormat.java:237)
	at org.apache.logging.log4j.core.pattern.DatePatternConverter.createFormatter(DatePatternConverter.java:177)
	at org.apache.logging.log4j.core.pattern.DatePatternConverter.<init>(DatePatternConverter.java:172)
	at org.apache.logging.log4j.core.pattern.DatePatternConverter.newInstance(DatePatternConverter.java:191)
	... 34 more
Caused by: java.io.FileNotFoundException: C:\Program Files\Java\jre1.8.0_141\lib\tzdb.dat (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	... 46 more
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class sun.util.calendar.ZoneInfoFile
	at sun.util.calendar.ZoneInfo.getTimeZone(Unknown Source)
	at java.util.TimeZone.getTimeZone(Unknown Source)
	at java.util.TimeZone.setDefaultZone(Unknown Source)
	at java.util.TimeZone.getDefaultRef(Unknown Source)
	at java.util.TimeZone.getDefault(Unknown Source)
	at java.text.SimpleDateFormat.initializeCalendar(Unknown Source)
	at java.text.SimpleDateFormat.<init>(Unknown Source)
	at java.text.SimpleDateFormat.<init>(Unknown Source)
	at org.apache.logging.log4j.status.StatusData.getFormattedStatus(StatusData.java:122)
	at org.apache.logging.log4j.status.StatusConsoleListener.log(StatusConsoleListener.java:81)
	at org.apache.logging.log4j.status.StatusLogger.logMessage(StatusLogger.java:254)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1960)
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:733)
	at org.apache.logging.log4j.core.pattern.PatternParser.createConverter(PatternParser.java:591)
	at org.apache.logging.log4j.core.pattern.PatternParser.finalizeConverter(PatternParser.java:638)
	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:414)
	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:177)
	at org.apache.logging.log4j.core.layout.PatternLayout$SerializerBuilder.build(PatternLayout.java:376)
	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:128)
	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:58)
	at org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:652)
	at org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:516)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:537)
	at bib.<clinit>(SourceFile:224)
	at net.minecraft.client.main.Main.main(SourceFile:38)
	... 8 more
Exiting with -1
can't open C:\Program Files\Java\jre1.8.0_141\lib\tzmappings.
can't open C:\Program Files\Java\jre1.8.0_141\lib\tzmappings.
can't open C:\Program Files\Java\jre1.8.0_141\lib\tzmappings.
Process exited with code -1.
MultiMC: Log upload triggered at: 09 Oct 2017 17:45:54 +0800

**Comment by QuImUfu** [comment]
Seems to be a problem with you java installation that is caused by a file missing from your java version. 

Uninstall all versions of Java from your PC, delete the "C:/Program Files/Java" folder and install the newest Java 8 version from https://www.java.com/de/download/manual.jsp (Windows online).
Than let MultiMC search for the java version, select it and try again.

**Comment by Fi3ryMadness** [comment]
Okayyyyy, so it worked!!! Thanks a bunch <3
