### ISSUE TITLE
Im Having a error with my server i tested evry thing on MultiMC 

### ISSUE THREAD

**Issue by TrollMasterHD** [MultiMC/MultiMC5#2015]
[20:12:48] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[20:12:48] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[20:12:48] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[20:12:48] [main/INFO] [FML]: Forge Mod Loader version 7.99.36.1558 for Minecraft 1.7.10 loading
[20:12:48] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_144, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_144
[20:12:49] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:12:49] [main/INFO] [STDERR]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of Baubles, 1.7.10 is newer than request 1.0.1.10
[20:12:49] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:12:49] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:12:49] [main/WARN] [FML]: The coremod mrtjp.relocation.asm.RelocationPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:12:49] [main/WARN] [FML]: The coremod mods.immibis.core.ICCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:12:49] [main/WARN] [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:12:49] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:12:49] [main/INFO] [FML]: Loading tweaker com.mumfrey.liteloader.launch.LiteLoaderTweaker from liteloader-1.7.10.jar
[20:12:49] [main/WARN] [FML]: The coremod logisticspipes.asm.LogisticsPipesCoreLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:12:49] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:12:49] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.DepLoader$DepLoadInst:<init>:333]: MicdoodleCore searching for dependencies in mods file: C:\Users\AndrÚ\Desktop\CustomServer\.\mods
[20:12:49] [main/WARN] [FML]: The coremod mrtjp.core.handler.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:12:49] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:12:49] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_U_D8.jar
[20:12:49] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:12:49] [main/WARN] [FML]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:12:49] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:12:49] [main/INFO] [LaunchWrapper]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[20:12:49] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[20:12:49] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[20:12:49] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:12:49] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:12:49] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[20:12:49] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[20:12:49] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: Forge server detected, skipping class transformer
[20:12:49] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [IC2-core]: Loaded library EJML-core-0.26.jar.
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:102]: Successfully Registered Transformer
[20:12:50] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[20:12:50] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:12:50] [main/INFO] [STDERR]: [thaumcraft.codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:459]: Warning: version of Baubles, 1.7.10 is newer than request 1.0.1.10
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker
[20:12:50] [main/INFO] [LiteLoader]: Bootstrapping LiteLoader 1.7.10
[20:12:50] [main/INFO] [LiteLoader]: Registering API provider class com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient
[20:12:50] [main/INFO] [LiteLoader]: Spawning API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' ...
[20:12:50] [main/INFO] [LiteLoader]: API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' provides API 'liteloader'
[20:12:50] [main/INFO] [LiteLoader]: Initialising API 'liteloader' ...
[20:12:50] [main/INFO] [LiteLoader]: LiteLoader begin PREINIT...
[20:12:50] [main/INFO] [LiteLoader]: Initialising Loader properties...
[20:12:50] [main/INFO] [LiteLoader]: Setting up logger...
[20:12:50] [main/INFO] [LiteLoader]: LiteLoader 1.7.10 starting up...
[20:12:50] [main/INFO] [LiteLoader]: Java reports OS="windows 10"
[20:12:50] [main/INFO] [LiteLoader]: Enumerating class path...
[20:12:50] [main/INFO] [LiteLoader]: Class path separator=";"
[20:12:50] [main/INFO] [LiteLoader]: Class path entries=(
   classpathEntry=forge-1.7.10-10.13.4.1558-1.7.10-universal.jar
)
[20:12:50] [main/INFO] [LiteLoader]: Registering discovery module EnumeratorModuleClassPath: [<Java Class Path>]
[20:12:50] [main/INFO] [LiteLoader]: Registering discovery module EnumeratorModuleFolder: [C:\Users\AndrÚ\Desktop\CustomServer\mods]
[20:12:50] [main/INFO] [LiteLoader]: Registering discovery module EnumeratorModuleFolder: [C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10]
[20:12:50] [main/INFO] [LiteLoader]: Adding supported mod class prefix 'LiteMod'
[20:12:50] [main/INFO] [LiteLoader]: Discovering tweaks on class path...
[20:12:50] [main/INFO] [LiteLoader]: Discovering valid mod files in folder mods
[20:12:50] [main/INFO] [LiteLoader]: Discovering valid mod files in folder mods\1.7.10
[20:12:50] [main/INFO] [LiteLoader]: Searching for tweaks in 'Baubles-1.7.10.jar'
[20:12:50] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\Baubles-1.7.10.jar'
[20:12:50] [main/INFO] [LiteLoader]: Searching for tweaks in 'CodeChickenLib-1.7.10-1.1.3.136-universal.jar'
[20:12:50] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\CodeChickenLib-1.7.10-1.1.3.136-universal.jar'
[20:12:50] [main/INFO] [LiteLoader]: Searching for tweaks in 'ForgeMultipart-1.7.10-1.2.0.345-universal.jar'
[20:12:50] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\ForgeMultipart-1.7.10-1.2.0.345-universal.jar'
[20:12:50] [main/INFO] [LiteLoader]: Searching for tweaks in 'ForgeRelocation-1.7.10-0.0.1.4-universal.jar'
[20:12:50] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\ForgeRelocation-1.7.10-0.0.1.4-universal.jar'
[20:12:50] [main/INFO] [LiteLoader]: Searching for tweaks in 'ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar'
[20:12:50] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar'
[20:12:50] [main/INFO] [LiteLoader]: Searching for tweaks in 'MrTJPCore-1.7.10-1.1.0.33-universal.jar'
[20:12:50] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\MrTJPCore-1.7.10-1.1.0.33-universal.jar'
[20:12:50] [main/INFO] [LiteLoader]: Searching for tweaks in '[1.7.10]bspkrsCore-universal-6.15.jar'
[20:12:50] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\[1.7.10]bspkrsCore-universal-6.15.jar'
[20:12:50] [main/INFO] [LiteLoader]: LiteLoader PREINIT complete
[20:12:50] [main/INFO] [LiteLoader]: Sorting registered packet transformers by priority
[20:12:50] [main/INFO] [LiteLoader]: Added 0 packet transformer classes to the transformer list
[20:12:50] [main/INFO] [LiteLoader]: Injecting required class transformer 'com.mumfrey.liteloader.launch.LiteLoaderTransformer'
[20:12:50] [main/INFO] [LiteLoader]: Injecting required class transformer 'com.mumfrey.liteloader.client.transformers.CrashReportTransformer'
[20:12:50] [main/INFO] [LiteLoader]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer'
[20:12:50] [main/INFO] [LiteLoader]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer'
[20:12:50] [main/INFO] [LiteLoader]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer'
[20:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
A problem occurred running the Server launcher.[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.reflect.Method.invoke(Unknown Source)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.IllegalAccessError: tried to access class com.google.common.base.Splitter$2 from class com.google.common.base.Splitter
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at com.google.common.base.Splitter.on(Splitter.java:174)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.common.asm.transformers.AccessTransformer$1.processLine(AccessTransformer.java:141)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at com.google.common.io.CharStreams.readLines(CharStreams.java:317)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at com.google.common.io.CharSource.readLines(CharSource.java:240)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.common.asm.transformers.AccessTransformer.processATFile(AccessTransformer.java:125)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.common.asm.transformers.AccessTransformer.readMapFile(AccessTransformer.java:120)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:101)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:97)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.reflect.Constructor.newInstance(Unknown Source)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.Class.newInstance(Unknown Source)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:32)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:12:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   ... 6 more
Press any key to continue . . .

**Comment by TrollMasterHD** [comment]
[20:21:31] [main/INFO] [LiteLoader]: Discovering valid mod files in folder mods
[20:21:31] [main/INFO] [LiteLoader]: Discovering valid mod files in folder mods\1.7.10
[20:21:31] [main/INFO] [LiteLoader]: Searching for tweaks in 'Baubles-1.7.10.jar'
[20:21:31] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\Baubles-1.7.10.jar'
[20:21:31] [main/INFO] [LiteLoader]: Searching for tweaks in 'CodeChickenLib-1.7.10-1.1.3.136-universal.jar'
[20:21:31] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\CodeChickenLib-1.7.10-1.1.3.136-universal.jar'
[20:21:31] [main/INFO] [LiteLoader]: Searching for tweaks in 'ForgeMultipart-1.7.10-1.2.0.345-universal.jar'
[20:21:31] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\ForgeMultipart-1.7.10-1.2.0.345-universal.jar'
[20:21:31] [main/INFO] [LiteLoader]: Searching for tweaks in 'ForgeRelocation-1.7.10-0.0.1.4-universal.jar'
[20:21:31] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\ForgeRelocation-1.7.10-0.0.1.4-universal.jar'
[20:21:31] [main/INFO] [LiteLoader]: Searching for tweaks in 'ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar'
[20:21:31] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar'
[20:21:31] [main/INFO] [LiteLoader]: Searching for tweaks in 'MrTJPCore-1.7.10-1.1.0.33-universal.jar'
[20:21:31] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\MrTJPCore-1.7.10-1.1.0.33-universal.jar'
[20:21:31] [main/INFO] [LiteLoader]: Searching for tweaks in '[1.7.10]bspkrsCore-universal-6.15.jar'
[20:21:31] [main/WARN] [LiteLoader]: Error parsing manifest entries in 'C:\Users\AndrÚ\Desktop\CustomServer\mods\1.7.10\[1.7.10]bspkrsCore-universal-6.15.jar'
trying to solve this i need some help

**Comment by QuImUfu** [comment]
Please upload the whole log to https://paste.ee/ or some similar place, pust the link and describe your problem accurately.

**Comment by peterix** [comment]
No response, closing.
