### ISSUE TITLE
Error -1?

### ISSUE THREAD

**Issue by Opesis** [MultiMC/MultiMC5#2036]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Opesis** [comment]
Im new to MultiMC and trying to figure out what error -1 is.....

**Comment by peterix** [comment]
Anything, everything, without more information, nothing.

**Comment by xXblack-lionXx** [comment]
Maybe he had the same problem like me:

MultiMC version: 0.5.2-1096


Minecraft folder is:
instances/1.12.2/minecraft


Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe


Java is version 9, using 64-bit architecture.


Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/Leo/Desktop/MultiMC/instances/1.12.2/natives

Libraries:
  C:/Users/Leo/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/com/mojang/realms/1.10.17/realms-1.10.17.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Leo/Desktop/MultiMC/versions/1.12.2/1.12.2.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Leo/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Leo/Desktop/MultiMC/instances/1.12.2/minecraft --assetsDir C:/Users/Leo/Desktop/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms409m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 2744


Using onesix launcher.

Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/com/mojang/realms/1.10.17/realms-1.10.17.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Unable to load: C:/Users/Leo/Desktop/MultiMC/versions/1.12.2/1.12.2.jar
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.multimc.Utils.addToClassPath(Utils.java:80)
	at org.multimc.Utils.addToClassPath(Utils.java:100)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:261)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Halting launch due to previous errors.
Exiting with -1
Process exited with code -1.
Clipboard copy at: 19 Nov 2017 23:01:09 +0100

**Comment by peterix** [comment]
Do not use java 9. Get java 8 instead.
