### ISSUE TITLE
I can not run minecraft on this computer but on mine I get there. I haven't got mods.

### ISSUE THREAD

**Issue by Quentindwx** [MultiMC/MultiMC5#2066]
System Information
-----------------------------
MultiMC version : MultiMC 0.5.2

Operating System : win7

Summary of the issue or suggestion : I can not run Minecraft on this computer but on mine I get there. I do not understand where it may come from even though I suspect java.
----------------------------------------------

What should happen : get started
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.open it

2.

3.

Suspected cause: java
---------------------------

Logs/Screenshots:
```
MultiMC version: 0.5.2-1096


Minecraft folder is:
instances/adventures/minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_151/bin/javaw.exe


Java is version 1.8.0_151, using 64-bit architecture.


Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/instances/adventures/natives

Libraries:
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/com/mojang/realms/1.10.17/realms-1.10.17.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/versions/1.12.2/1.12.2.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/user/Documents/Quentin/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/user/Documents/Quentin/Minecraft/MultiMC/instances/adventures/minecraft --assetsDir C:/Users/user/Documents/Quentin/Minecraft/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms128m, -Xmx512m, -Duser.language=en]


Minecraft process ID: 1864


Using onesix launcher.

[14:39:59] [Client thread/INFO]: Setting user: <PROFILE NAME>
[14:40:02] [Client thread/INFO]: LWJGL Version: 2.9.1
[14:40:02] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.1.jar:?]
	at bib.at(SourceFile:622) [1.12.2.jar:?]
	at bib.aq(SourceFile:458) [1.12.2.jar:?]
	at bib.a(SourceFile:404) [1.12.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [1.12.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 12/13/17 2:40 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bib.at(SourceFile:635)
	at bib.aq(SourceFile:458)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bib.at(SourceFile:635)
	at bib.aq(SourceFile:458)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 175961976 bytes (167 MB) / 264241152 bytes (252 MB) up to 477626368 bytes (455 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms128m -Xmx512m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\user\Documents\Quentin\Minecraft\MultiMC\instances\adventures\minecraft\crash-reports\crash-2017-12-13_14.40.03-client.txt
Process exited with code -1.
```

----------------------------

Additional Info : Sorry for mistakes, I'm french.
---------------------------

**Comment by peterix** [comment]
Looks like you do not have a GPU driver that would provide OpenGL functionality. This can be caused by many things.

Follow this:
https://support.nexon.net/hc/en-us/articles/204335909-How-to-create-a-DxDiag-Report-in-Windows

Upload the dxdiag report here.

**Comment by spannerman79** [comment]
`Pixel format not accelerated`
You are running GPU and drivers that do not support newer versions of minecraft on the Windows platform.

Either;

- Switch to using Linux

or

- Upgrade/buy new hardware


https://help.mojang.com/customer/en/portal/articles/928791-problematic-frame-or-pixel-format-not-accelerated

**Comment by Quentindwx** [comment]
ok

thank you !!

2018-01-05 23:19 GMT+01:00 Spanner_Man <notifications@github.com>:
