### ISSUE TITLE
What is "code 1"

### ISSUE THREAD

**Issue by spidrmnky** [MultiMC/MultiMC5#2078]
Trying to set up a mod pack for me and a friend to play but can not get it to open, not good with code and can not find anything online. Any help would be much appreciated, thank you.

```
MultiMC version: 0.5.2-1096


Minecraft folder is:
instances/My Mods/minecraft


Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_151, using 64-bit architecture.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/instances/My Mods/natives

Libraries:
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.10.17/realms-1.10.17.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.1.2555/forge-1.12.2-14.23.1.2555-universal.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/versions/1.12.2/1.12.2.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar

Mods:
  ActuallyAdditions-1.12.2-r126
  angelRingToBauble-1.11.2-0.2.4.24+6570ea2
  AppleCore-mc1.12.2-3.1.0
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv5-stable-3
  Baubles-1.12-1.5.1
  BetterBuildersWands-1.11-0.11.1.239+9162f74
  BetterFps-1.4.5-1.10
  BiomesOPlenty-1.12.2-7.0.1.2302-universal
  Bookshelf-1.12.2-2.3.515
  Botania r1.10-352
  BrandonsCore-1.12-2.3.7.140-universal
  Ceramics-1.12-1.3.3b
  Chameleon-1.12-4.1.3
  Chisel-2.9.5.11
  chiselsandbits-14.11
  ClientTweaks_1.12-3.1.2
  Clumps-3.0.0
  CommonCapabilities-1.10.2-1.3.4
  CookingForBlockheads_1.12.1-6.3.17
  CraftTweaker2-1.12-4.0.12
  CTMLib-MC1.7.10-1.4.1.5
  CTM-MC1.12-0.2.3.9
  CyclopsCore-1.12.2-0.11.0
  DarkUtils-1.12.2-1.7.181
  Draconic-Evolution-1.12-2.3.7.278-universal
  DrawersBits-1.11.2-0.41
  ElevatorMod-1.12.2-1.3.5
  EnderCore-1.10.2-0.4.1.66-beta
  EnderIO-1.10.2-3.1.183
  EnderStorage-1.12.2-2.4.2.126-universal
  energyconverters_1.12.1-1.0.1.2
  environmentaltech-1.12.2-2.0.6b
  etlunar-1.12.2-2.0.6a
  ExtraBitManipulation-1.12-3.2.1
  extrautils2-1.10.2-1.7.2
  ExtremeReactors-1.12-0.4.5.44
  fairylights-2.1.2-1.12.x
  fluxnetworks-1.12.2-3.0.2
  Forgelin-1.6.0
  FTBLib-4.2.5
  GardenOfGlass
  generators-0.9.20.123-mc1.7.10
  gravestone-1.10.0
  Gyth-1.10.2-2.0.0.27
  Headcrumbs-2.0.3
  ImmersiveEngineering-0.12-75
  ImmersiveEngineering-0.12-75-core
  inventorysorter-1.12.2-1.12.4+52
  IronBackpacks-1.10.2-2.2.36
  ironchest-1.8.9-6.0.125.770
  jei_1.12.2-4.8.5.138
  journeymap-1.12.2-5.5.2
  KleeSlabs_1.12-5.3.2
  LunatriusCore-1.12.2-1.2.0.42-universal
  Mantle-1.12-1.3.1.21
  mcjtylib-1.12-2.6.1
  MCMultiPart-1.4.0-universal
  Mercurius-1.12.2
  minicoal-1.11.2-1.0
  MoarSigns-1.11.2-5.0.1.10
  MobGrindingUtils-0.3.4
  modtweaker-4.0.6
  MoreShearables1.2.3-1.12
  MouseTweaks-2.8-mc1.12.1
  mpbasic-1.12-1.3.0
  MPUtils-1.12-1.4.1
  MTLib-3.0.1
  mysticalagriculture-1.12-1.6.7
  natura-1.12-4.3.0.23
  Neat 1.4-15
  nice-1.12-0.2.0
  NotEnoughItems-1.12.2-2.4.1.233-universal
  notenoughwands-1.12-1.6.0
  Pam's HarvestCraft 1.12.2b - Re-Balance Update
  RebornCore-1.12.2-3.5.4.176-universal
  RebornStorage-1.12.2-3.0.2.33
  refinedstorage-1.5.30
  Reliquia-[1.10.2]-0.0.7
  ResourceLoader-MC1.12.1-1.5.3
  rftools-1.12-7.22
  rftoolsctrl-1.12-1.8.0
  rftoolsdim-1.12-5.10
  roots-2-0.104
  ShadowMC-1.12.2-3.8.3
  shetiphiancore-1.11.0-3.4.9
  simplebarrels-1.26e
  SimpleCorn1.12-2.3.7
  simplegenerators-1.10.2-0.10.6a
  SimplyJetpacks2-1.10.2-2.1.3.55
  StorageDrawers-1.12.1-5.3.3
  TConstruct-1.12-2.8.1.49
  The Beneath-1.12.2-1.3.0
  TinkerToolLeveling-1.12-1.0.3
  tinyprogressions-1.10.2-1.2.6
  UniDict-1.12.2-2.0
  valkyrielib-1.12.2-2.0.6b
  WanionLib-1.12.2-1.4
  Wawla-1.12.2-2.5.246
  witherCrumbs-1.10.2-0.9
  zerocore-1.10.2-0.1.1.1

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/instances/My Mods/minecraft --assetsDir C:/Users/Danielle/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType custom --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 3692


Using onesix launcher.

2017-12-29 23:40:08,017 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-12-29 23:40:08,021 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[23:40:08] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:40:08] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:40:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:40:08] [main/INFO] [FML]: Forge Mod Loader version 14.23.1.2555 for Minecraft 1.12.2 loading
[23:40:08] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_151, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_151
[23:40:08] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.1.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
2017-12-29 23:40:08,488 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-12-29 23:40:08,523 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-12-29 23:40:08,525 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[23:40:08] [main/WARN] [FML]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[23:40:08] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.5-1.10.jar
[23:40:08] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12-0.2.3.9.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:40:08] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:40:08] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[23:40:08] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in EnderCore-1.10.2-0.4.1.66-beta.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:40:08] [main/ERROR] [FML]: The coremod com.enderio.core.common.transform.EnderCorePlugin is requesting minecraft version 1.10.2 and minecraft is 1.12.2. It will be ignored.
[23:40:08] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.6.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:40:08] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:40:08] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[23:40:08] [main/WARN] [FML]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:40:08] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:40:08] [main/WARN] [FML]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:40:08] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in shetiphiancore-1.11.0-3.4.9.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:40:08] [main/WARN] [FML]: The coremod shetiphian.core.asm.TweakPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:40:08] [main/WARN] [FML]: The coremod ShetiPhian-ASM (shetiphian.core.asm.TweakPlugin) is not signed!
[23:40:08] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:40:08] [main/INFO] [LaunchWrapper]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[23:40:08] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:40:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:40:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:40:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:40:10] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[23:40:11] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[23:40:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:40:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:40:11] [main/INFO] [LaunchWrapper]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
[23:40:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:40:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:40:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:40:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:40:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:40:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:40:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:40:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:40:11] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[23:40:12] [main/INFO] [ShetiPhian-ASM]: Attempting: Injection of Run Particle Override into Entity.createRunningParticles
[23:40:12] [main/INFO] [ShetiPhian-ASM]: Searching for: Entity.createRunningParticles (func_174808_Z)
[23:40:12] [main/INFO] [ShetiPhian-ASM]: Found Method: Entity.createRunningParticles
[23:40:12] [main/INFO] [ShetiPhian-ASM]: Injecting: Run Particle Override
[23:40:12] [main/INFO]: Setting user: <PROFILE NAME>
[23:40:12] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:185]: Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
[23:40:12] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:197]: Transforming net.minecraft.block.Block Finished.
[23:40:13] [main/INFO] [BetterFps]: Patching net.minecraft.block.material.MaterialTransparent... (bcx)
[23:40:13] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/block/material/MaterialTransparent.an()V @5: getfield
  Reason:
    Type 'net/minecraft/block/material/MaterialTransparent' (current frame, stack[0]) is not assignable to 'guichaguri/betterfps/patches/misc/MinecraftPatch'
  Current Frame:
    bci: @5
    flags: { }
    locals: { 'net/minecraft/block/material/MaterialTransparent' }
    stack: { 'net/minecraft/block/material/MaterialTransparent' }
  Bytecode:
    0x0000000: 04b3 0025 2ab4 002b bb00 2d59 b700 2fb9
    0x0000010: 0035 0200 57b8 003a b1                 

	at net.minecraft.block.material.Material.<clinit>(SourceFile:4) ~[bcz.class:?]
	at net.minecraft.block.BlockAir.<init>(SourceFile:16) ~[aom.class:?]
	at net.minecraft.block.Block.func_149671_p(Block.java:2238) ~[aow.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:364) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 14 more
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:239]: Failed to start Minecraft:
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:297]: java.lang.reflect.InvocationTargetException
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:297]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:297]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:297]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:297]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:297]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:297]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:297]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:297]: 	at org.multimc.EntryPoint.main(EntryPoint.java:53)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:240]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:240]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:240]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:240]: 	at java.lang.Runtime.exit(Unknown Source)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:240]: 	at java.lang.System.exit(Unknown Source)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:240]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:240]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:40:13] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:240]: 	... 8 more
[23:40:13] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:56]: Exiting with -1
[23:40:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:40:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[23:40:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[23:40:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[23:40:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[23:40:13] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:57)
Exception in thread "Client thread" 
Process exited with code 1.
```

**Comment by tehbasshunter** [comment]
I can tell you off the bat you're using 1.10.2 and 1.12.2 mods. That'll be the 1st thing you need to fix before anything.

**Comment by spidrmnky** [comment]
thank you i thought older ones and work on newer updates as well, now i see that its a different file to download

**Comment by tehbasshunter** [comment]
That sometimes will work but generally if it's just a minor update not full version.

**Comment by jikuja** [comment]
Also one important piece of information is missing. Did that pack ever work and if it did what did you change?

**Comment by calloatti** [comment]
To answer your question, "1" may be the exit code returned by Java. Executables when run return an exit code, "0" is no errors and non-zero is something bad happened.

This is an operating system thing.

**Comment by peterix** [comment]
It's really the program calling `exit(1)` or having `return 1;` in its main function. It says absolutely nothing about why that happened.
