### ISSUE TITLE
Cannot install/upgrade Forge on Version 0.6.0-1154 win32

### ISSUE THREAD

**Issue by Syndaryl** [MultiMC/MultiMC5#2086]
System Information
-----------------------------
MultiMC version: 0.6.0-1154 Win32

Operating System: Windows 10

Summary of the issue:
----------------------------------------------
MultiMC is silently failing to update or install Forge when requested. This makes creating a new Forge-based instance impossible, and it makes upgrading an existing instance also quite impossible.

What should happen:
------------------------------
Forge should be installed, so I can create instances that use Forge mods.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create a new Vanilla instance.

2. Start instance, proving it works.

3. Edit Instance, go to Version tab, click Install Forge. I have tried the recommended stable version and a random assortment of newer versions (I need at least 2560 for one of my mods). Don't install any mods, it's not required to demonstrate the issue.

4. Try to launch instance.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
The log is dreadfully short.

2018-01-02 10:16:13,067 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[10:16:13] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[10:16:13] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_152]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_152]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Process exited with code 1.

Additional Info:
---------------------------
Instances that I set up before being updated to .60 have a "custom" note after the forge version (and have forge). Instances that I set up after being updated to .60 do not have this note (and do not have forge).

I cloned a legacy instance and tried to update it, and the version does not change, nor does it lose the "custom" flag.

**Comment by peterix** [comment]
Please post a complete log, not this fragment. There is an upload button, just for thiis purpose.

**Comment by Syndaryl** [comment]
Sure.

Since running it last I'm trying the development branch, but it's not showing any change in behavior.

https://paste.ee/p/oRa6k

**Comment by Syndaryl** [comment]
Resolved on Discord: The version choosing tab does not actually install the plugins. They are installed when launched in online mode. An instance must be run once in online mode to install everything before it can be launched offline.
