### ISSUE TITLE
3gb ram win10 intel pentium inside 

### ISSUE THREAD

**Issue by minecraftmannnnnnnnnnnasda** [MultiMC/MultiMC5#2109]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 1/17/18 11:05 AM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bsu.am(SourceFile:523)
	at bsu.aj(SourceFile:352)
	at bsu.a(SourceFile:299)
	at net.minecraft.client.main.Main.main(SourceFile:120)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bsu.am(SourceFile:523)
	at bsu.aj(SourceFile:352)

-- Initialization --
Details:
Stacktrace:
	at bsu.a(SourceFile:299)
	at net.minecraft.client.main.Main.main(SourceFile:120)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 1890520 bytes (1 MB) / 149954560 bytes (143 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)

**Comment by peterix** [comment]
This looks like a graphics driver issue.

Please attach the full dxdiag report so we can figure out what is wrong. You can do it like this:

* Press the `[Windows]+[R]` keys on your keyboard to bring up the Run command.
* In the `Run` command box, type in `dxdiag` and press `<Enter>`. The DirectX Diagnostic Tool pop-up window should appear.
* Click on `Save all Information.`
* Save the information to your Desktop, keep the file name as is.
* Attach the file here.

Here is an example of what the DirectX Diagnostic Tool will look like:

![dxdiag example](https://user-images.githubusercontent.com/203326/34328124-4489aa8e-e8d6-11e7-9984-0f5e8561564b.png)

**Comment by peterix** [comment]
Closing, no reaction.
