### ISSUE TITLE
MultiMC Crash Issue

### ISSUE THREAD

**Issue by Fred1124** [MultiMC/MultiMC5#2137]
System Information
-----------------------------
MultiMC version:
0.6.1
Operating System:
Windows 10 Home
Summary of the issue or suggestion:
----------------------------------------------
The game is crashing when loading mods.

What should happen:
------------------------------
Minecraft should launch to the login screen.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Add all the mods.

2.Rename to my modpack.

3.Launch the game and wait

Suspected cause:
---------------------------
To many mods

Logs/Screenshots:
----------------------------
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2/9/18 9:03 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Inventory Pets (inventorypets)
Caused by: java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Unknown Source)
	at java.util.Scanner.next(Unknown Source)
	at com.inventorypets.events.UpdateHandler.getNewestVersion(UpdateHandler.java:43)
	at com.inventorypets.events.UpdateHandler.init(UpdateHandler.java:23)
	at com.inventorypets.InventoryPets.preload(InventoryPets.java:819)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 227827000 bytes (217 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version         | Source                                          | Signature                                |
	|:----- |:------------------- |:--------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2          | minecraft.jar                                   | None                                     |
	| UCH   | mcp                 | 9.42            | minecraft.jar                                   | None                                     |
	| UCH   | FML                 | 8.0.99.99       | forge-1.12.2-14.23.2.2611-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.2.2611    | forge-1.12.2-14.23.2.2611-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | appliedenergistics2 | rv5-stable-8    | appliedenergistics2-rv5-stable-8.jar            | None                                     |
	| UCH   | codechickenlib      | 3.1.5.331       | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCE   | redstoneflux        | 2.0.1           | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCE   | brandonscore        | 2.3.7           | BrandonsCore-1.12-2.3.7.140-universal.jar       | None                                     |
	| UCH   | chiselsandbits      | 14.13           | chiselsandbits-14.13.jar                        | None                                     |
	| UCE   | cofhcore            | 4.3.10          | CoFHCore-1.12.2-4.3.10.5-universal.jar          | None                                     |
	| UCH   | cofhworld           | 1.1.1           | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCE   | thermalfoundation   | 2.3.10          | ThermalFoundation-1.12.2-2.3.10.6-universal.jar | None                                     |
	| UCE   | draconicevolution   | 2.3.8           | Draconic-Evolution-1.12-2.3.8.279-universal.jar | None                                     |
	| UCH   | exnihilocreatio     | 1.12-0.1.7      | exnihilocreatio-1.12-0.1.7.jar                  | None                                     |
	| UCH   | jei                 | 4.8.5.147       | jei_1.12.2-4.8.5.147.jar                        | None                                     |
	| UCH   | mantle              | 1.12-1.3.1.21   | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCH   | tconstruct          | 1.12.2-2.9.0.55 | TConstruct-1.12.2-2.9.0.55.jar                  | None                                     |
	| UCH   | extrautils2         | 1.0             | extrautils2-1.12-1.7.3.jar                      | None                                     |
	| UCH   | zerocore            | 1.12-0.1.1.0    | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UCH   | bigreactors         | 1.12.2-0.4.5.46 | ExtremeReactors-1.12.2-0.4.5.46.jar             | None                                     |
	| UCH   | hatchery            | 2.1.2           | hatchery-1.12.2-2.1.2.jar                       | None                                     |
	| UCE   | inventorypets       | 1.4.9.9b        | inventorypets-1.12-1.4.9.9b.jar                 | None                                     |
	| UCH   | nei                 | 2.4.1           | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | orespawn            | 3.2.1           | OreSpawn-1.12-3.2.1.109.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | projecte            | 1.12-PE1.0.0    | ProjectE-1.12-PE1.2.0.jar                       | None                                     |
	| UCH   | rftools             | 7.27            | rftools-1.12-7.27.jar                           | None                                     |
	| UCE   | thermalexpansion    | 5.3.10          | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 6000'
	AE2 Version: stable rv5-stable-8 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

Additional Info:
---------------------------
https://paste.ee/p/4yvoE

**Comment by tehbasshunter** [comment]
2 Issues:  
  
You're using 32bit java. You need 64bit (https://java.com/en/download/manual.jsp )  
You need to add more ram once you switch to 64 bit java. 1GB is not even remotely enough for those mods.

**Comment by peterix** [comment]
```
java.util.NoSuchElementException: null
	at java.util.Scanner.throwFor(Unknown Source) ~[?:1.8.0_161]
	at java.util.Scanner.next(Unknown Source) ~[?:1.8.0_161]
	at com.inventorypets.events.UpdateHandler.getNewestVersion(UpdateHandler.java:43) ~[UpdateHandler.class:?]
```
Disable mod updaters. For this mod in particular. Its update check is buggy.

```
[09:03:18] [main/ERROR] [FML]: Caught exception from redstoneflux (Redstone Flux)
java.lang.RuntimeException: 
RedstoneFlux has detected that the following OLD API classes from CoFHLib are being repacked!
    cofh.api.energy.ItemEnergyContainer, loaded from: buildcraft-7.1.22-core.jar
    cofh.api.energy.EnergyStorage, loaded from: buildcraft-7.1.22-core.jar
    cofh.api.energy.TileEnergyHandler, loaded from: buildcraft-7.1.22-core.jar
    cofh.api.energy.IEnergyConnection, loaded from: buildcraft-7.1.22-core.jar
    cofh.api.energy.IEnergyProvider, loaded from: buildcraft-7.1.22-core.jar
    cofh.api.energy.IEnergyHandler, loaded from: buildcraft-7.1.22-core.jar
    cofh.api.energy.IEnergyStorage, loaded from: buildcraft-7.1.22-core.jar
    cofh.api.energy.IEnergyContainerItem, loaded from: buildcraft-7.1.22-core.jar
    cofh.api.energy.IEnergyReceiver, loaded from: buildcraft-7.1.22-core.jar

To prevent this crash, add "-Dcofh.rf.crashOnOldAPI=false" to your command line arguments.
```

You will have to resolve this version conflict. Your version of buildcraft is for 1.7.10.

**Comment by Fred1124** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2/9/18 9:32 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Inventory Pets (inventorypets)
Caused by: java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Unknown Source)
	at java.util.Scanner.next(Unknown Source)
	at com.inventorypets.events.UpdateHandler.getNewestVersion(UpdateHandler.java:43)
	at com.inventorypets.events.UpdateHandler.init(UpdateHandler.java:23)
	at com.inventorypets.InventoryPets.preload(InventoryPets.java:819)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1125487952 bytes (1073 MB) / 1745354752 bytes (1664 MB) up to 3340763136 bytes (3186 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3584m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version         | Source                                          | Signature                                |
	|:----- |:------------------- |:--------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2          | minecraft.jar                                   | None                                     |
	| UCH   | mcp                 | 9.42            | minecraft.jar                                   | None                                     |
	| UCH   | FML                 | 8.0.99.99       | forge-1.12.2-14.23.2.2611-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.2.2611    | forge-1.12.2-14.23.2.2611-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | appliedenergistics2 | rv5-stable-8    | appliedenergistics2-rv5-stable-8.jar            | None                                     |
	| UCH   | codechickenlib      | 3.1.5.331       | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux        | 2.0.1           | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | brandonscore        | 2.3.7           | BrandonsCore-1.12-2.3.7.140-universal.jar       | None                                     |
	| UCH   | chiselsandbits      | 14.13           | chiselsandbits-14.13.jar                        | None                                     |
	| UCH   | cofhcore            | 4.3.10          | CoFHCore-1.12.2-4.3.10.5-universal.jar          | None                                     |
	| UCH   | cofhworld           | 1.1.1           | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCH   | thermalfoundation   | 2.3.10          | ThermalFoundation-1.12.2-2.3.10.6-universal.jar | None                                     |
	| UCH   | draconicevolution   | 2.3.8           | Draconic-Evolution-1.12-2.3.8.279-universal.jar | None                                     |
	| UCH   | exnihilocreatio     | 1.12-0.1.7      | exnihilocreatio-1.12-0.1.7.jar                  | None                                     |
	| UCH   | jei                 | 4.8.5.147       | jei_1.12.2-4.8.5.147.jar                        | None                                     |
	| UCH   | mantle              | 1.12-1.3.1.21   | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCH   | tconstruct          | 1.12.2-2.9.0.55 | TConstruct-1.12.2-2.9.0.55.jar                  | None                                     |
	| UCH   | extrautils2         | 1.0             | extrautils2-1.12-1.7.3.jar                      | None                                     |
	| UCH   | zerocore            | 1.12-0.1.1.0    | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UCH   | bigreactors         | 1.12.2-0.4.5.46 | ExtremeReactors-1.12.2-0.4.5.46.jar             | None                                     |
	| UCH   | hatchery            | 2.1.2           | hatchery-1.12.2-2.1.2.jar                       | None                                     |
	| UCE   | inventorypets       | 1.4.9.9b        | inventorypets-1.12-1.4.9.9b.jar                 | None                                     |
	| UCH   | nei                 | 2.4.1           | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | orespawn            | 3.2.1           | OreSpawn-1.12-3.2.1.109.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | projecte            | 1.12-PE1.0.0    | ProjectE-1.12-PE1.2.0.jar                       | None                                     |
	| UCH   | rftools             | 7.27            | rftools-1.12-7.27.jar                           | None                                     |
	| UCH   | thermalexpansion    | 5.3.10          | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 6000'
	AE2 Version: stable rv5-stable-8 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

https://paste.ee/p/E763D

**Comment by Fred1124** [comment]
Could not find the RedstoneFlux Config.

**Comment by peterix** [comment]
This should be resolved elsewhere (inventorypets)
