### ISSUE TITLE
Minecraft Crashed while Loading Mods

### ISSUE THREAD

**Issue by Fred1124** [MultiMC/MultiMC5#2141]
System Information
-----------------------------
MultiMC version:
0.6.1
Operating System:
Windows 10 Home
Summary of the issue or suggestion:
----------------------------------------------
Minecraft is crashing

What should happen:
------------------------------
Minecraft Should load into the welcome screen

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Add the mods

2.Launch Minecraft

3.Wait for crash

Suspected cause:
---------------------------
To many mods

Logs/Screenshots:
----------------------------
---- Minecraft Crash Report ----

WARNING: coremods are present:
  HammerCoreCore (HammerCore-1.12.2-1.9.6.5.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.133.jar)
  SFRCore (SolarFluxReborn_1.12.2-3.42r.jar)
  SRM-Core (secretroomsmod-1.12.2-5.2.7.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 2/11/18 12:28 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Nether Metals (nethermetals)
Caused by: java.lang.NoClassDefFoundError: com/mcmoddev/nethermetals/util/Config
	at com.mcmoddev.nethermetals.proxy.CommonProxy.preInit(CommonProxy.java:39)
	at com.mcmoddev.nethermetals.NetherMetals.preInit(NetherMetals.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: com.mcmoddev.nethermetals.util.Config
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 50 more
Caused by: java.lang.NoClassDefFoundError: com/mcmoddev/lib/util/ConfigBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 52 more
Caused by: java.lang.ClassNotFoundException: com.mcmoddev.lib.util.ConfigBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 56 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2188373120 bytes (2086 MB) / 2844786688 bytes (2713 MB) up to 5622464512 bytes (5362 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6032m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 80 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version                      | Source                                          | Signature                                |
	|:----- |:----------------------- |:---------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft               | 1.12.2                       | minecraft.jar                                   | None                                     |
	| UCH   | mcp                     | 9.42                         | minecraft.jar                                   | None                                     |
	| UCH   | FML                     | 8.0.99.99                    | forge-1.12.2-14.23.2.2611-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                   | 14.23.2.2611                 | forge-1.12.2-14.23.2.2611-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore           |                              | minecraft.jar                                   | None                                     |
	| UCH   | securitycraft           | v1.8.4.1                     | [1.12.x]+SecurityCraft+v1.8.4.1.jar             | None                                     |
	| UCH   | appliedenergistics2     | rv5-stable-8                 | appliedenergistics2-rv5-stable-8.jar            | None                                     |
	| UCH   | baubles                 | 1.5.2                        | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCH   | bibliocraft             | 2.4.3                        | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCH   | guideapi                | 1.12-2.1.4-57                | Guide-API-1.12-2.1.4-57.jar                     | None                                     |
	| UCH   | bloodmagic              | @VERSION@                    | BloodMagic-1.12.2-2.2.1-83.jar                  | None                                     |
	| UCH   | codechickenlib          | 3.1.5.331                    | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux            | 2.0.1                        | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | brandonscore            | 2.3.7                        | BrandonsCore-1.12-2.3.7.140-universal.jar       | None                                     |
	| UCH   | chameleon               | 1.12-4.1.3                   | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCH   | chancecubes             | 1.12.2-3.1.0.217             | ChanceCubes-1.12.2-3.1.0.217.jar                | None                                     |
	| UCH   | chisel                  | MC1.12-0.1.1.26              | Chisel-MC1.12-0.1.1.26.jar                      | None                                     |
	| UCH   | chiselsandbits          | 14.13                        | chiselsandbits-14.13.jar                        | None                                     |
	| UCH   | cofhcore                | 4.3.10                       | CoFHCore-1.12.2-4.3.10.5-universal.jar          | None                                     |
	| UCH   | cofhworld               | 1.1.1                        | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCH   | cucumber                | 1.0.4                        | cucumber-1.12-1.0.4.jar                         | None                                     |
	| UCH   | densemetals             | 1.0.2                        | densemetals-1.12.2-1.0.2.jar                    | None                                     |
	| UCH   | thermalfoundation       | 2.3.10                       | ThermalFoundation-1.12.2-2.3.10.6-universal.jar | None                                     |
	| UCH   | draconicevolution       | 2.3.8                        | Draconic-Evolution-1.12-2.3.8.279-universal.jar | None                                     |
	| UCH   | enderstorage            | 2.4.2.126                    | EnderStorage-1.12.2-2.4.2.126-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | exnihilocreatio         | 1.12-0.1.7                   | exnihilocreatio-1.12-0.1.7.jar                  | None                                     |
	| UCH   | extracells              | 2.5.11                       | ExtraCells-1.12.2-2.5.11a48.jar                 | None                                     |
	| UCH   | jei                     | 4.8.5.147                    | jei_1.12.2-4.8.5.147.jar                        | None                                     |
	| UCH   | mantle                  | 1.12-1.3.1.21                | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCH   | tconstruct              | 1.12.2-2.9.0.55              | TConstruct-1.12.2-2.9.0.55.jar                  | None                                     |
	| UCH   | extrautils2             | 1.0                          | extrautils2-1.12-1.7.3.jar                      | None                                     |
	| UCH   | zerocore                | 1.12-0.1.1.0                 | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UCH   | bigreactors             | 1.12.2-0.4.5.46              | ExtremeReactors-1.12.2-0.4.5.46.jar             | None                                     |
	| UCH   | forgelin                | 1.6.0                        | Forgelin-1.6.0.jar                              | None                                     |
	| UCH   | cfm                     | 4.1.5                        | furniture-4.1.5-1.12.2.jar                      | None                                     |
	| UCH   | ic2                     | 2.8.53-ex112                 | industrialcraft-2-2.8.53-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | galacticraftcore        | 4.0.1.133                    | GalacticraftCore-1.12.2-4.0.1.133.jar           | None                                     |
	| UCH   | galacticraftplanets     | 4.0.1.133                    | Galacticraft-Planets-1.12.2-4.0.1.133.jar       | None                                     |
	| UCH   | ichunutil               | 7.1.4                        | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCH   | gravitygun              | 7.0.0                        | GravityGun-1.12.2-7.0.1.jar                     | None                                     |
	| UCH   | hammercore              | 1.9.6.5                      | HammerCore-1.12.2-1.9.6.5.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCH   | hatchery                | 2.1.2                        | hatchery-1.12.2-2.1.2.jar                       | None                                     |
	| UCH   | hats                    | 7.0.0                        | Hats-1.12.2-7.0.2.jar                           | None                                     |
	| UCH   | hatstand                | 7.0.0                        | HatStand-1.12.2-7.0.1.jar                       | None                                     |
	| UCH   | teslacorelib            | 1.0.12                       | tesla-core-lib-1.12-1.0.12.jar                  | None                                     |
	| UCH   | industrialforegoing     | 1.12.2-1.12.1                | Industrial-Foregoing-Mod-1.12.2.jar             | None                                     |
	| UCH   | inventorypets           | 1.4.9.9b                     | inventorypets-1.12-1.4.9.9b.jar                 | None                                     |
	| UCH   | inventorytweaks         | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironchest               | 1.12.2-7.0.34.820            | ironchest-1.12.2-7.0.34.820.jar                 | None                                     |
	| UCH   | leafdecay               | 1.0.0.2                      | leafdecay-1.0.0.2-mc1.12.2.jar                  | None                                     |
	| UCH   | shadowmc                | 3.8.0                        | ShadowMC-1.12-3.8.0.jar                         | None                                     |
	| UCH   | leveluphp               | 1.1.1                        | leveluphp-1.12.2-1.1.1.jar                      | None                                     |
	| UCH   | malisiscore             | 1.12.2-6.4.0                 | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
	| UCH   | malisisdoors            | 1.12.2-7.3.0                 | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| UCH   | mcmultipart             | 2.3.0                        | MCMultiPart-Mod-1.12.2.jar                      | None                                     |
	| UCH   | moreplanets             | 2.0.12                       | More-Planets-1.12.2-2.0.12-GC132.jar            | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UCH   | morph                   | 7.1.2                        | Morph-1.12.2-7.1.2.jar                          | None                                     |
	| UCH   | mysticalagriculture     | 1.6.2                        | Mystical-Agriculture-1.12.jar                   | None                                     |
	| UCE   | nethermetals            | 1.2.0-beta1                  | Nether-Metals-Mod-1.12.1.jar                    | None                                     |
	| UCH   | nei                     | 2.4.1                        | NotEnoughItems-1.12.2-2.4.1.233-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | harvestcraft            | 1.12.2o                      | Pam's+HarvestCraft+1.12.2o.jar                  | None                                     |
	| UCH   | portalgun               | 7.0.0                        | PortalGun-1.12.2-7.0.1.jar                      | None                                     |
	| UCH   | projecte                | 1.12-PE1.0.0                 | ProjectE-1.12-PE1.2.0.jar                       | None                                     |
	| UCH   | thermalexpansion        | 5.3.10                       | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None                                     |
	| UCH   | redstonearsenal         | 2.3.10                       | RedstoneArsenal-1.12.2-2.3.10.4-universal.jar   | None                                     |
	| UCH   | rftools                 | 7.27                         | rftools-1.12-7.27.jar                           | None                                     |
	| UCH   | secretroomsmod          | 5.2.7                        | secretroomsmod-1.12.2-5.2.7.jar                 | None                                     |
	| UCH   | simplyjetpacks          | 2.2.2.28                     | SimplyJetpacks2-1.12.2-2.2.2.28.jar             | None                                     |
	| UCH   | solarfluxreborn         | 3.42r                        | SolarFluxReborn_1.12.2-3.42r.jar                | None                                     |
	| UCH   | somanyenchantments      | 0.3.0                        | SoManyEnchantments+V0.3.1+(1.12.2).jar          | None                                     |
	| UCH   | soulshardstow           | 1.12-2.7.4-53                | SoulShards-TOW-1.12-2.7.4-53.jar                | None                                     |
	| UCH   | storagedrawers          | 1.12-5.2.5                   | StorageDrawers-1.12.2-5.3.4.jar                 | None                                     |
	| UCH   | sync                    | 7.0.0                        | Sync-1.12.2-7.0.1.jar                           | None                                     |
	| UCH   | trashslot               | 8.4.6                        | TrashSlot_1.12.1-8.4.6.jar                      | None                                     |
	| UCH   | twilightforest          | 3.6.345                      | twilightforest-1.12.2-3.6.345-universal.jar     | None                                     |
	| UCH   | veinminer               | 0.38.1                       | Vein-Miner-Mod-1.12.jar                         | None                                     |
	| UCH   | veinminermodsupport     | 0.38.1                       | Vein-Miner-Mod-1.12.jar                         | None                                     |
	| UCH   | xaerominimap            | 1.14.8                       | Xaeros_Minimap_1.14.8_Forge_1.12.jar            | None                                     |
	| UCH   | teslacorelib_registries | 1.0.12                       | tesla-core-lib-1.12-1.0.12.jar                  | None                                     |
	| UD    | solarfluxreborncore     | 3.42r                        | minecraft.jar                                   | None                                     |

	Loaded coremods (and transformers): 
HammerCoreCore (HammerCore-1.12.2-1.9.6.5.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.133.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
SFRCore (SolarFluxReborn_1.12.2-3.42r.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
SRM-Core (secretroomsmod-1.12.2-5.2.7.jar)
  com.wynprice.secretroomsmod.core.UVTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 6000'
	AE2 Version: stable rv5-stable-8 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
https://paste.ee/p/VRARM

Additional Info:
---------------------------

**Comment by peterix** [comment]
Check your dependencies again. Also, try to read the log please. It is telling you what's wrong with what mod. Look for letter `E`.
