### ISSUE TITLE
Crashing upon launch Mac OS High Sierra

### ISSUE THREAD

**Issue by dongledongs** [MultiMC/MultiMC5#2147]
System Information
-----------------------------
MultiMC version: MultiMC 5 - version 0.6.11-1118 on osx64

Operating System: Mac OS High Sierra version 10.13

Summary of the issue or suggestion: 
----------------------------------------------
I downloaded the mod-pack, updated java and downloaded the  newest JDK.  Tested everything, connected my account, everything said success and had a green check mark next to it.  However, when I launched the mod, this error came up in my minecraft log.  I don't really know what any of this stuff means, I just wanted to play with my boyfriend and his friends.  It looks like the problem is coming from Java?  But that's really all I can get from it.  I attached the log so I hope that helps.  I'm sorry I'm not really familiar with Java or any script stuff so if this could be explained as simply as possible, I would appreciate it, but I will try my best to follow along no matter what.  Thank you.

What should happen: 
------------------------------
The game should open

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Opened the game even after closing the application and reopening it

2. Vanilla ran just fine

3.

Suspected cause: 
---------------------------
Java (???)

Logs/Screenshots:
----------------------------
[//]: # MultiMC version: 0.6.1-1118

Minecraft folder is:
/Applications/MultiMC.app/Contents/MacOS/instances/Mod Quad V3.1/.minecraft

Java path is:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java

Java is version 9.0.4, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /Applications/MultiMC.app/Contents/MacOS/instances/Mod Quad V3.1/natives

Libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/realms/1.10.19/realms-1.10.19.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/minecraftforge/forge/1.12.2-14.23.2.2611/forge-1.12.2-14.23.2.2611-universal.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/jline/jline/2.13/jline-2.13.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /Applications/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar
  /Applications/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Mods:
  aether_legacy-1.12.2-v2.0
  astralsorcery-1.12.2-1.8.5
  Baubles-1.12-1.5.2
  BiblioCraft[v2.4.3][MC1.12.0]
  Chameleon-1.12-4.1.3
  chiselsandbits-14.13
  CookingForBlockheads_1.12.1-6.3.17
  CyclopsCore-1.12.2-0.11.4
  EvilCraft-1.12.2-0.10.47
  gravestone-1.10.1
  jei_1.12.2-4.8.5.147
  journeymap-1.12.2-5.5.2
  Mantle-1.12-1.3.1.21
  OptiFine_1.12.2_HD_U_C9
  Pam's+HarvestCraft+1.12.2p
  StorageDrawers-1.12.2-5.3.4
  TConstruct-1.12.2-2.9.1.65
  twilightforest-1.12.2-3.6.345-universal

Params:
  --username  --version MultiMC5 --gameDir /Applications/MultiMC.app/Contents/MacOS/instances/Mod Quad V3.1/.minecraft --assetsDir /Applications/MultiMC.app/Contents/MacOS/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: Mod Quad V3.1", -Xms2176m, -Xmx2176m, -Duser.language=en]

Minecraft process ID: 18097

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
Exiting with -1
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Process exited with code 255.
Clipboard copy at: 15 Feb 2018 20:33:17 -0600

Additional Info:
---------------------------

**Comment by dongledongs** [comment]
Got it!  I was using a newer version of Java than him.
