### ISSUE TITLE
Segmentation fault when launching MultiMC

### ISSUE THREAD

**Issue by NovaPhoenix** [MultiMC/MultiMC5#2164]
System Information
-----------------------------
MultiMC version: 0.6.1

Operating System: Fedora 27

Summary of the issue or suggestion:
----------------------------------------------
I downloaded the latest version of MultiMC, 0.6.1, and when I try to launch it, a segmentation fault happened

What should happen:
------------------------------
MultiMC should launch

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMC on Fedora 27 (`./MultiMC`)

Suspected cause:
---------------------------
I suspect it's a problem with QT

Logs/Screenshots:
----------------------------
https://gist.github.com/NovaPhoenix/82d9aec4cfae9ccd7f7c78601582c17a

Additional info
----------------------------
Same result on my other Fedora 27 machine

**Comment by Janrupf** [comment]
Thats weird... If you have a bit of experience you could try debugging with gdb or compiling MultiMC yourself. And please give some more information on your operating system. Architecture, Ram and CPU. 

I don't think that QT is causing this, maybe MultiMC is accesing stack variebles in illegal places or doing wrong memory management. If this is the case it has to do something which differs Fedora from Linux Mint...

**Comment by peterix** [comment]
Or it has problems with https...

Try the workaround from here: https://github.com/MultiMC/MultiMC5/issues/1784

Basically remove all the extra libraries and plugins MultiMC comes with and use the system Qt.

**Comment by NovaPhoenix** [comment]
After moving all QT libs to another folder, the issue is resolved. This is what I did in the bin directory: `mv libQt5* ~/Documents/qtmmc/`

**Comment by Janrupf** [comment]
Well, if moving the Qt libs helped, I don't really know... 

And why should https causd a segmentation fault?

**Comment by peterix** [comment]
Because the it was trying to use an incompatible version of OpenSSL (one it was not built with). If you look at the log, you'll see that it is failing to locate some functions in it... It probably found one, tried to call it in a different way than it's meant to be called and crashed.

**Comment by awmyhr** [comment]
For the record, I had the exact same problem on Fedora 27 (both with 6.1 and the last 5.x), and the exact same solution worked (i.e., removing the libQt5* files from MultiMC's bin directory)

**Comment by ScottDWebster** [comment]
I ran into the same problem. I created a new directory in the bin directory and moved all the libQt5* libraries into it and now it works fine.

**Comment by antofthy** [comment]
After updating to Fedora 28 (from fedora 25, and this skipping Fedora 26 and 27) I had the same fault
Removing all bin/libQt5* files resolved the issue.

**Comment by swedneck** [comment]
I just had the same issue on fedora 29, and removing bin/libQt5* worked like a charm for me as well.

**Comment by tmccombs** [comment]
I'm not sure if this is the same thing. But just starting today, I started getting segmentation faults when trying to start an instance. This is the stack trace (from gdb):

```
#0  0x00005555556584c4 in std::_Sp_counted_ptr_inplace<TextPrint, std::allocator<TextPrint>, (__gnu_cxx::_Lock_policy)2>::_M_get_deleter(std::type_info const&) ()
#1  0x00007ffff779c1c7 in MinecraftInstance::createLaunchTask(std::shared_ptr<AuthSession>) () from /usr/lib/libMultiMC_logic.so
#2  0x000055555565529d in LaunchController::launchInstance() ()
#3  0x000055555565670f in LaunchController::login() ()
#4  0x0000555555657e28 in LaunchController::executeTask() ()
#5  0x00007ffff7801828 in Task::start() () from /usr/lib/libMultiMC_logic.so
#6  0x0000555555619703 in MultiMC::launch(std::shared_ptr<BaseInstance>, bool, BaseProfilerFactory*) ()
#7  0x000055555563b2f3 in MainWindow::activateInstance(std::shared_ptr<BaseInstance>) ()
#8  0x000055555563bdc3 in MainWindow::instanceActivated(QModelIndex) ()
#9  0x0000555555643d5d in QtPrivate::QSlotObject<void (MainWindow::*)(QModelIndex), QtPrivate::List<QModelIndex const&>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#10 0x00007ffff6c1c980 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff7c81906 in QAbstractItemView::activated(QModelIndex const&) () from /usr/lib/libQt5Widgets.so.5
#12 0x0000555555709340 in GroupView::mouseDoubleClickEvent(QMouseEvent*) ()
#13 0x00007ffff7a6c78f in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff7b1386f in QFrame::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff7c8e50c in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff6bf1b0b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#17 0x00007ffff7a2ae14 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff7a32839 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff6bf1df9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#20 0x00007ffff7a31b18 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff7a86f53 in ?? () from /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff7a8a047 in ?? () from /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff7a2ae24 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff7a325f1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff6bf1df9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#26 0x00007ffff7178a50 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#27 0x00007ffff7179f16 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#28 0x00007ffff715375c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#29 0x00007ffff2f6d9ac in ?? () from /usr/lib/libQt5XcbQpa.so.5
#30 0x00007ffff56027bf in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#31 0x00007ffff5604739 in ?? () from /usr/lib/libglib-2.0.so.0
#32 0x00007ffff560477e in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#33 0x00007ffff6c47c99 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#34 0x00007ffff6bf0a8c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#35 0x00007ffff6bf8de6 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#36 0x0000555555603650 in main ()
```

**Comment by tmccombs** [comment]
huh. I tried using the multimc-git package in archlinux instead of multimc5, and got it to launch.

**Comment by JorgenHedlund** [comment]
Maybe same issue:
OS: Arch Linux
https://aur.archlinux.org/packages/multimc5/

SIGSEGV upon launch, right when main window show up.
```
Thread 1 "multimc" received signal SIGSEGV, Segmentation fault.
0x000055555571e3cd in QList<QModelIndex>::append(QModelIndex const&) ()
(gdb) bt
#0  0x000055555571e3cd in QList<QModelIndex>::append(QModelIndex const&) ()
#1  0x000055555571dd33 in VisualGroup::update() ()
#2  0x000055555571545e in GroupView::updateGeometries() ()
#3  0x00007ffff7a5950f in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#4  0x00007ffff7b09b1f in QFrame::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff7c90a40 in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff6bda6d3 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#7  0x00007ffff7a154c4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff7a1ea21 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff6bda9c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#10 0x00007ffff7a50274 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff7a51044 in QWidget::setGeometry(QRect const&) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff7b0af8f in QAbstractScrollAreaPrivate::layoutChildren_helper(bool*, bool*) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff7b0b45c in QAbstractScrollAreaPrivate::layoutChildren() () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff7b0cd01 in QAbstractScrollArea::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff7c908d4 in QAbstractItemView::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff7a154d5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff7a1ea21 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff6bda9c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#19 0x00007ffff7a50274 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () from /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff7a51044 in QWidget::setGeometry(QRect const&) () from /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff7a3946a in QWidgetItem::setGeometry(QRect const&) () from /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff7a2f1a8 in QBoxLayout::setGeometry(QRect const&) () from /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff7a35698 in QLayoutPrivate::doResize(QSize const&) () from /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff7a154b8 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff7a1ea21 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#26 0x00007ffff6bda9c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#27 0x00007ffff7a50274 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () from /usr/lib/libQt5Widgets.so.5
#28 0x00007ffff7a51044 in QWidget::setGeometry(QRect const&) () from /usr/lib/libQt5Widgets.so.5
#29 0x00007ffff7a58555 in ?? () from /usr/lib/libQt5Widgets.so.5
#30 0x00007ffff7a5ac5b in QWidget::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib/libQt5Widgets.so.5
#31 0x00007ffff69f9b0f in QPropertyAnimation::updateCurrentValue(QVariant const&) () from /usr/lib/libQt5Core.so.5
#32 0x00007ffff69f6658 in ?? () from /usr/lib/libQt5Core.so.5
#33 0x00007ffff69f6e50 in ?? () from /usr/lib/libQt5Core.so.5
#34 0x00007ffff69fa4da in QPropertyAnimation::updateState(QAbstractAnimation::State, QAbstractAnimation::State) () from /usr/lib/libQt5Core.so.5
#35 0x00007ffff69f490c in QAbstractAnimation::start(QAbstractAnimation::DeletionPolicy) () from /usr/lib/libQt5Core.so.5
#36 0x00007ffff7b0df97 in ?? () from /usr/lib/libQt5Widgets.so.5
#37 0x00007ffff7b48fc9 in ?? () from /usr/lib/libQt5Widgets.so.5
#38 0x00007ffff7b7a19c in ?? () from /usr/lib/libQt5Widgets.so.5
#39 0x00007ffff7b7e793 in ?? () from /usr/lib/libQt5Widgets.so.5
#40 0x00007ffff7a35698 in QLayoutPrivate::doResize(QSize const&) () from /usr/lib/libQt5Widgets.so.5
#41 0x00007ffff7a367c4 in QLayout::activate() () from /usr/lib/libQt5Widgets.so.5
#42 0x00007ffff7a58708 in QWidgetPrivate::setVisible(bool) () from /usr/lib/libQt5Widgets.so.5
#43 0x00007ffff7bf9dae in ?? () from /usr/lib/libQt5Widgets.so.5
#44 0x00007ffff7a35698 in QLayoutPrivate::doResize(QSize const&) () from /usr/lib/libQt5Widgets.so.5
#45 0x00007ffff7a154b8 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#46 0x00007ffff7a1ea21 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#47 0x00007ffff6bda9c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#48 0x00007ffff7a50274 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () from /usr/lib/libQt5Widgets.so.5
#49 0x00007ffff7a51044 in QWidget::setGeometry(QRect const&) () from /usr/lib/libQt5Widgets.so.5
#50 0x00007ffff7a58555 in ?? () from /usr/lib/libQt5Widgets.so.5
#51 0x00007ffff7a5ac5b in QWidget::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib/libQt5Widgets.so.5
#52 0x00007ffff7bf69b7 in QToolBar::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib/libQt5Widgets.so.5
#53 0x00007ffff69f9b0f in QPropertyAnimation::updateCurrentValue(QVariant const&) () from /usr/lib/libQt5Core.so.5
#54 0x00007ffff69f6658 in ?? () from /usr/lib/libQt5Core.so.5
#55 0x00007ffff69f6e50 in ?? () from /usr/lib/libQt5Core.so.5
#56 0x00007ffff69fa4da in QPropertyAnimation::updateState(QAbstractAnimation::State, QAbstractAnimation::State) () from /usr/lib/libQt5Core.so.5
#57 0x00007ffff69f490c in QAbstractAnimation::start(QAbstractAnimation::DeletionPolicy) () from /usr/lib/libQt5Core.so.5
#58 0x00007ffff7b0df97 in ?? () from /usr/lib/libQt5Widgets.so.5
#59 0x00007ffff7bfaefc in ?? () from /usr/lib/libQt5Widgets.so.5
#60 0x00007ffff7b7a18f in ?? () from /usr/lib/libQt5Widgets.so.5
#61 0x00007ffff7b7e793 in ?? () from /usr/lib/libQt5Widgets.so.5
#62 0x00007ffff7a35698 in QLayoutPrivate::doResize(QSize const&) () from /usr/lib/libQt5Widgets.so.5
#63 0x00007ffff7a154b8 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#64 0x00007ffff7a1ea21 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#65 0x00007ffff6bda9c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#66 0x00007ffff7a74a8f in ?? () from /usr/lib/libQt5Widgets.so.5
#67 0x00007ffff7a78264 in ?? () from /usr/lib/libQt5Widgets.so.5
#68 0x00007ffff7a154d5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#69 0x00007ffff7a1ea21 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#70 0x00007ffff6bda9c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#71 0x00007ffff712df19 in QGuiApplicationPrivate::processGeometryChangeEvent(QWindowSystemInterfacePrivate::GeometryChangeEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#72 0x00007ffff712e29b in QGuiApplicationPrivate::processWindowScreenChangedEvent(QWindowSystemInterfacePrivate::WindowScreenChangedEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#73 0x00007ffff7132f26 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#74 0x00007ffff710b37c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#75 0x00007ffff2e93fec in ?? () from /usr/lib/libQt5XcbQpa.so.5
#76 0x00007ffff551ccf4 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#77 0x00007ffff551eb11 in ?? () from /usr/lib/libglib-2.0.so.0
#78 0x00007ffff551eb51 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#79 0x00007ffff6c329a3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#80 0x00007ffff6bd95ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#81 0x00007ffff6be1326 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#82 0x0000555555604157 in main ()
```

Also, maybe relevant
```
qt5ct: using qt5ct plugin
    0.006 D MultiMC 5, (c) 2013-2019 MultiMC Contributors
    0.006 D Version                    :  "0.6.6-custom"
    0.006 D Git commit                 :  "7b254e673d1cbf3f7ecb20b7d8aeacce63212a04"
    0.006 D Git refspec                :  "refs/heads/master"
```

Also tried changing default JDK as suggested in AUR comments:
> Fuxy commented on 2019-07-13 08:47	
> just a friendly reminder even though this installs packages of jdk < 12 it will still attempt to use the default one which may be set to 12 like in my case.
> You need to use sudo archlinux-java status and sudo archlinux-java set java-11-openjdk to figure out what you have and set something lower than 12 as default before attempting to install.

**Comment by peterix** [comment]
Unrelated. Please post that in a new issue if you manage to replicate it.
