### ISSUE TITLE
Trying to use FTB SkyFactory 3 mod and it keeps crashing 

### ISSUE THREAD

**Issue by Matt15972** [MultiMC/MultiMC5#2177]
MultiMC version: 0.6.1-1177

Minecraft folder is:
C:/Users/Matthew/Desktop/MMC/MultiMC/instances/1.10.2/.minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_161, using 32-bit architecture.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Matthew/Desktop/MMC/MultiMC/instances/1.10.2/natives

Libraries:
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/mojang/realms/1.9.8/realms-1.9.8.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/net/minecraftforge/forge/1.10.2-12.18.3.2185/forge-1.10.2-12.18.3.2185-universal.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/com/mojang/minecraft/1.10.2/minecraft-1.10.2-client.jar

Native libraries:
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Matthew/Desktop/MMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Mods:
  Charset-mc1.10.2-0.3.5-fd38f2c944396214
  DragonMounts-r46-1.10.2
  foamfix-0.7.2-anarchy

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Matthew/Desktop/MMC/MultiMC/instances/1.10.2/.minecraft --assetsDir C:/Users/Matthew/Desktop/MMC/MultiMC/assets --assetIndex 1.10 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 6704

Using onesix launcher.

2018-03-09 11:48:37,214 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-03-09 11:48:37,232 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[11:48:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:48:37] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:48:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[11:48:37] [main/INFO] [FML]: Forge Mod Loader version 12.18.3.2185 for Minecraft 1.10.2 loading
[11:48:37] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_161, running on Windows 10:x86:10.0, installed at C:\Program Files (x86)\Java\jre1.8.0_161
[11:48:38] [main/WARN] [FML]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:48:38] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:48:38] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[11:48:38] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:48:38] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:48:38] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:48:46] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[11:48:46] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[11:48:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:48:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[11:48:48] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:48:48] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[11:48:48] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[11:48:48] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[11:48:50] [main/INFO] [STDOUT]: [pl.asie.foamfix.coremod.patches.ClassGetSimpleNamePatch$FFMethodVisitor:visitMethodInsn:49]: Replaced getSimpleName with getName
[11:48:50] [main/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:113]: Added METHOD: net.minecraft.world.World.func_191504_a
2018-03-09 11:48:50,442 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-03-09 11:48:50,508 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-03-09 11:48:50,520 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[11:48:51] [Client thread/INFO]: Setting user: <PROFILE NAME>
[11:48:54] [Client thread/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:103]: Spliced in METHOD: net.minecraft.block.state.BlockStateContainer.createState
[11:48:54] [Client thread/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:103]: Spliced in METHOD: net.minecraft.block.properties.PropertyEnum.hashCode
[11:48:54] [Client thread/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:136]: Added FIELD: net.minecraft.block.properties.PropertyEnum.foamfix_hashCode
[11:48:54] [Client thread/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:136]: Added FIELD: net.minecraft.block.properties.PropertyEnum.foamfix_hashCode_calced
[11:48:54] [Client thread/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:103]: Spliced in METHOD: net.minecraft.block.properties.PropertyBool.equals
[11:48:54] [Client thread/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:103]: Spliced in METHOD: net.minecraft.block.properties.PropertyBool.hashCode
[11:48:54] [Client thread/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:103]: Spliced in METHOD: net.minecraft.block.properties.PropertyInteger.hashCode
[11:48:54] [Client thread/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:136]: Added FIELD: net.minecraft.block.properties.PropertyInteger.foamfix_hashCode
[11:48:54] [Client thread/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:136]: Added FIELD: net.minecraft.block.properties.PropertyInteger.foamfix_hashCode_calced
[11:49:03] [Client thread/INFO]: LWJGL Version: 2.9.4
[11:49:06] [Client thread/INFO] [STDOUT]: [net.minecraftforge.fml.client.SplashProgress:start:219]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.2-anarchy.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 3/9/18 11:49 AM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 279552480 bytes (266 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 6310 Graphics'
[11:49:06] [Client thread/INFO] [FML]: MinecraftForge v12.18.3.2185 Initialized
[11:49:06] [Client thread/INFO] [FML]: Replaced 231 ore recipes
[11:49:08] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[11:49:08] [Client thread/INFO] [FML]: Searching C:\Users\Matthew\Desktop\MMC\MultiMC\instances\1.10.2\.minecraft\mods for mods
[11:49:13] [Client thread/WARN] [FML]: ****************************************
[11:49:13] [Client thread/WARN] [FML]: * The modid CharsetLib is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
[11:49:13] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:141)
[11:49:13] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:126)
[11:49:13] [Client thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:49:13] [Client thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[11:49:13] [Client thread/WARN] [FML]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[11:49:13] [Client thread/WARN] [FML]: *  at java.lang.reflect.Constructor.newInstance(Unknown Source)...
[11:49:13] [Client thread/WARN] [FML]: ****************************************
[11:49:13] [Client thread/WARN] [FML]: ****************************************
[11:49:13] [Client thread/WARN] [FML]: * The modid CharsetPipes is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
[11:49:13] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:141)
[11:49:13] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:126)
[11:49:13] [Client thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:49:13] [Client thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[11:49:13] [Client thread/WARN] [FML]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[11:49:13] [Client thread/WARN] [FML]: *  at java.lang.reflect.Constructor.newInstance(Unknown Source)...
[11:49:13] [Client thread/WARN] [FML]: ****************************************
[11:49:13] [Client thread/WARN] [FML]: ****************************************
[11:49:13] [Client thread/WARN] [FML]: * The modid CharsetWrench is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
[11:49:13] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:141)
[11:49:13] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:126)
[11:49:13] [Client thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:49:13] [Client thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[11:49:13] [Client thread/WARN] [FML]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[11:49:13] [Client thread/WARN] [FML]: *  at java.lang.reflect.Constructor.newInstance(Unknown Source)...
[11:49:13] [Client thread/WARN] [FML]: ****************************************
[11:49:13] [Client thread/WARN] [FML]: ****************************************
[11:49:13] [Client thread/WARN] [FML]: * The modid DragonMounts is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
[11:49:13] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:141)
[11:49:13] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:126)
[11:49:13] [Client thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:49:13] [Client thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[11:49:13] [Client thread/WARN] [FML]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[11:49:13] [Client thread/WARN] [FML]: *  at java.lang.reflect.Constructor.newInstance(Unknown Source)...
[11:49:13] [Client thread/WARN] [FML]: ****************************************
[11:49:14] [Client thread/INFO] [FML]: Forge Mod Loader has identified 9 mods to load
[11:49:14] [Client thread/ERROR] [FML]: The mod CharsetPipes (|) requires mods [mcmultipart] to be available
[11:49:14] [Client thread/ERROR] [FML]: Mod CharsetPipes (|) requires [mcmultipart@[1.3.0,)]
[11:49:14] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:?, FMLFileResourcePack:|, FMLFileResourcePack:/, FMLFileResourcePack:Dragon Mounts, FMLFileResourcePack:FoamFix
[11:49:14] [Client thread/WARN] [FML]: There were errors previously. Not beginning mod initialization phase
[11:49:20] [Sound Library Loader/INFO]: Starting up SoundSystem...
[11:49:20] [Client thread/INFO] [STDOUT]: [pl.asie.foamfix.coremod.patches.ReturnIfBooleanTruePatch:apply:63]: Added return if option true in net/minecraft/client/renderer/texture/TextureMap func_94248_c
[11:49:20] [Thread-8/INFO]: Initializing LWJGL OpenAL
[11:49:20] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[11:49:20] [Client thread/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:103]: Spliced in METHOD: net.minecraftforge.client.model.ModelLoader.func_177570_a
[11:49:20] [Thread-8/INFO]: OpenAL initialized.
[11:49:20] [Sound Library Loader/INFO]: Sound engine started
[11:49:21] [Client thread/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:103]: Spliced in METHOD: net.minecraftforge.client.model.ItemLayerModel.bake
[11:49:36] [Client thread/INFO] [FML]: Max texture size: 8192
[11:49:36] [Client thread/INFO]: Created: 16x16 textures-atlas
[11:49:36] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.2-anarchy.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 3/9/18 11:49 AM
Description: Initializing game

java.lang.NoSuchFieldError: firstLoad
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:61)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:61)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 247286360 bytes (235 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185-universal.jar) 
	U	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185-universal.jar) 
	U	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	U	CharsetLib{0.3.5} [?] (Charset-mc1.10.2-0.3.5-fd38f2c944396214.jar) 
	U	CharsetPipes{0.3.5} [|] (Charset-mc1.10.2-0.3.5-fd38f2c944396214.jar) 
	U	CharsetWrench{0.3.5} [/] (Charset-mc1.10.2-0.3.5-fd38f2c944396214.jar) 
	U	DragonMounts{r46-1.10.2} [Dragon Mounts] (DragonMounts-r46-1.10.2.jar) 
	U	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.2-anarchy.jar) 
	Loaded coremods (and transformers): 
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 6310 Graphics'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 6310 Graphics GL version 4.5.13399 Compatibility Profile Context 15.201.1151.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD E-300 APU with Radeon(tm) HD Graphics
[11:49:36] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Matthew\Desktop\MMC\MultiMC\instances\1.10.2\.minecraft\crash-reports\crash-2018-03-09_11.49.36-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

**Comment by peterix** [comment]
1. use 64bit java.

**Comment by peterix** [comment]
Hmm... actually, nevermind, this is some tiny non-modpack, not FTB SkyFactory 3.

**Comment by Matt15972** [comment]
I downloaded a zip file from FTB website. Then copied and pasted in the Instance file. I've never done anything like this before. Was trying to go off of some videos but I can't get it to work like their's do.

**Comment by peterix** [comment]
Drag and drop said zip on top of the main MultiMC window.

**Comment by peterix** [comment]
And this is the 64bit java installer:
http://javadl.oracle.com/webapps/download/AutoDL?BundleId=230542_2f38c3b165be4555a1fa6e98c45e0808

You will need it. And you will need to increase the amount of memory that Java can use (see MultiMC settings -> Java, Autodetect, increase the memory limit to something reasonable)

**Comment by peterix** [comment]
Assuming this got fixed, closing.
