### ISSUE TITLE
Sound won't work on release 1.0

### ISSUE THREAD

**Issue by fancymelonub** [MultiMC/MultiMC5#2179]
System Information
-----------------------------
MultiMC version: MultiMC 5 Version 0.6.1-develop-1997

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
When I run 1.0, audio doesn't work.

What should happen:
------------------------------
I would have audio.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Run MultiMC

2. Run 1.0

Suspected cause:
---------------------------
Not sure

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.1-develop-1197

Minecraft folder is:
C:/Users/Lazala Hane Fmly/Desktop/stuff related to audryck/Minecraft/MultiMC/instances/1.0/.minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_161, using 64-bit architecture.

Main Class:
  

Native path:
  C:/Users/Lazala Hane Fmly/Desktop/stuff related to audryck/Minecraft/MultiMC/instances/1.0/natives

Traits:
traits legacyLaunch
traits texturepacks

Libraries:
  C:/Users/Lazala Hane Fmly/Desktop/stuff related to audryck/Minecraft/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Lazala Hane Fmly/Desktop/stuff related to audryck/Minecraft/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Lazala Hane Fmly/Desktop/stuff related to audryck/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar
  C:/Users/Lazala Hane Fmly/Desktop/stuff related to audryck/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar
  C:/Users/Lazala Hane Fmly/Desktop/stuff related to audryck/Minecraft/MultiMC/instances/1.0/.minecraft/bin/minecraft.jar

Native libraries:
  C:/Users/Lazala Hane Fmly/Desktop/stuff related to audryck/Minecraft/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Lazala Hane Fmly/Desktop/stuff related to audryck/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-windows.jar

Jar Mods:
  OptiFine_1_0_0_HD_D3 (262868b8-7184-4a60-ab2e-d6a454244328.jar)

Params:
  

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 14920

Using onesix launcher.

Launching with applet wrapper...
27 achievements
174 recipes
Setting user: AudryckTAS, token:<ACCESS TOKEN>:<PROFILE ID>

OptiFine_1.0.0_HD_D3
Sat Mar 10 21:58:15 EST 2018
OS: Windows 10 (amd64) version 10.0
Java: 1.8.0_161, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
LWJGL: 2.9.0
OpenGL: AMD Radeon HD 7300 Series version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
OpenGL Version: 4.0
OpenGL Fancy fog: Not available (GL_NV_fog_distance)
setupTexture: "/title/mojang.png", id: 1
Mar 10, 2018 9:58:15 PM net.java.games.input.DefaultControllerEnvironment getControllers
WARNING: Found unknown Windows version: Windows 10
Mar 10, 2018 9:58:15 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Attempting to use default windows plug-in.
Mar 10, 2018 9:58:15 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

setupTexture: "/terrain.png", id: 7
TextureFX registered: yu@5a8cc7a6, texId: 7, index: 237
TextureFX registered: gk@32c22f2d, texId: 7, index: 205
TextureFX registered: vr@4b21a506, texId: 7, index: 14
setupTexture: "/gui/items.png", id: 8
TextureFX registered: aih@6ed4ff20, texId: 8, index: 54
TextureFX registered: at@3a4cd827, texId: 8, index: 70
TextureFX registered: va@18569103, texId: 7, index: 206
TextureFX registered: ss@5636c0ab, texId: 7, index: 238
TextureFX registered: agp@7477095, texId: 7, index: 31
TextureFX registered: agp@5b960dba, texId: 7, index: 47
setupTexture: "/title/bg/panorama0.png", id: 10
setupTexture: "/title/bg/panorama1.png", id: 11
setupTexture: "/title/bg/panorama2.png", id: 12
setupTexture: "/title/bg/panorama3.png", id: 13
setupTexture: "/title/bg/panorama4.png", id: 14
setupTexture: "/title/bg/panorama5.png", id: 15
setupTexture: "/title/mclogo.png", id: 16
setupTexture: "/gui/gui.png", id: 17
setupTexture: "/gui/particles.png", id: 18
TextureFX removed: yu@5a8cc7a6, texId: 7, index: 237
TextureFX registered: TextureHDLavaFX@4e3b6657, texId: 7, index: 237
TextureFX removed: gk@32c22f2d, texId: 7, index: 205
TextureFX registered: TextureHDWaterFX@536ca49e, texId: 7, index: 205
TextureFX removed: vr@4b21a506, texId: 7, index: 14
TextureFX registered: TextureHDPortalFX@4518a775, texId: 7, index: 14
TextureFX removed: va@18569103, texId: 7, index: 206
TextureFX registered: TextureHDWaterFlowFX@61fd330c, texId: 7, index: 206
TextureFX removed: ss@5636c0ab, texId: 7, index: 238
TextureFX registered: TextureHDLavaFlowFX@74e1f8ba, texId: 7, index: 238
TextureFX removed: agp@7477095, texId: 7, index: 31
TextureFX registered: TextureHDFlamesFX@421ffaec, texId: 7, index: 31
TextureFX removed: agp@5b960dba, texId: 7, index: 47
TextureFX registered: TextureHDFlamesFX@42bcded5, texId: 7, index: 47
TextureFX removed: aih@6ed4ff20, texId: 8, index: 54
TextureFX registered: TextureHDCompassFX@6d07c6a9, texId: 8, index: 54
TextureFX removed: at@3a4cd827, texId: 8, index: 70
TextureFX registered: TextureHDWatchFX@32c3e9ed, texId: 8, index: 70
Loading custom colors: /misc/grasscolor.png
Loading custom colors: /misc/foliagecolor.png
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave1.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave10.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave11.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave12.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave13.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave2.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
setupTexture: "/gui/background.png", id: 19
setupTexture: "/gui/icons.png", id: 20
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave3.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave4.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave5.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave6.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave7.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave8.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/cave/cave9.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/weather/rain1.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/weather/rain2.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/weather/rain3.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/weather/rain4.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/weather/thunder1.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/weather/thunder2.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/ambient/weather/thunder3.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/damage/fallbig1.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/damage/fallbig2.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/damage/fallsmall.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/damage/hurtflesh1.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/damage/hurtflesh2.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/damage/hurtflesh3.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/fire/fire.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/fire/ignite.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/liquid/lava.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/liquid/lavapop.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/liquid/splash.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/liquid/water.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/mob/blaze/breathe1.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
Stopping!

SoundSystem shutting down...
java.io.IOException: Server returned HTTP response code: 403 for URL: http://s3.amazonaws.com/MinecraftResources/newsound/mob/blaze/breathe2.ogg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at ng.a(SourceFile:104)
	at ng.a(SourceFile:93)
	at ng.run(SourceFile:42)
    Author: Paul Lamb, www.paulscode.com

Process exited with code 0.

Additional Info:
---------------------------
When I run 1.2.5, it has audio.

**Comment by Janrupf** [comment]
Please use the log upload or at least use any pasting site...

Anyway, the Mojang server answers 403 (Forbidden). Evtl sind die links tot

**Comment by QuImUfu** [comment]
duplicate/extension of #2151

**Comment by peterix** [comment]
And of #2209 -- I am going to use that one for gathering all the duplicates.
