### ISSUE TITLE
Crash on start with latest git build on Arch

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#2211]
```
Thread 1 "multimc" received signal SIGSEGV, Segmentation fault.
0x00007ffff730ab1b in ?? () from /usr/lib/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff730ab1b in ?? () from /usr/lib/libQt5Widgets.so.5
#1  0x00007ffff730b383 in QHeaderView::setSectionResizeMode(int, QHeaderView::ResizeMode) () from /usr/lib/libQt5Widgets.so.5
#2  0x00005555556cf4e4 in VersionSelectWidget::setResizeOn (this=0x555555b3a4a0, column=2) at /tmp/yaourt-tmp-mrazekp/aur-multimc-git/src/multimc-git/application/widgets/VersionSelectWidget.cpp:62
#3  0x00005555556bef43 in JavaSettingsWidget::setupUi (this=this@entry=0x555555c1e490) at /tmp/yaourt-tmp-mrazekp/aur-multimc-git/src/multimc-git/application/widgets/JavaSettingsWidget.cpp:45
#4  0x00005555556bfcb1 in JavaSettingsWidget::JavaSettingsWidget (this=0x555555c1e490, parent=<optimized out>)
    at /tmp/yaourt-tmp-mrazekp/aur-multimc-git/src/multimc-git/application/widgets/JavaSettingsWidget.cpp:27
#5  0x0000555555635790 in JavaWizardPage::setupUi (this=this@entry=0x555555ba8d10) at /tmp/yaourt-tmp-mrazekp/aur-multimc-git/src/multimc-git/application/setupwizard/JavaWizardPage.cpp:34
#6  0x0000555555635886 in JavaWizardPage::JavaWizardPage (this=0x555555ba8d10, parent=<optimized out>) at /tmp/yaourt-tmp-mrazekp/aur-multimc-git/src/multimc-git/application/setupwizard/JavaWizardPage.cpp:26
#7  0x00005555555fc98e in MultiMC::createSetupWizard (this=this@entry=0x7fffffffe360) at /tmp/yaourt-tmp-mrazekp/aur-multimc-git/src/multimc-git/application/MultiMC.cpp:769
#8  0x00005555556045a5 in MultiMC::MultiMC (this=0x7fffffffe360, argc=<optimized out>, argv=<optimized out>) at /tmp/yaourt-tmp-mrazekp/aur-multimc-git/src/multimc-git/application/MultiMC.cpp:710
#9  0x00005555555f9ea7 in main (argc=<optimized out>, argv=0x7fffffffe5d8) at /tmp/yaourt-tmp-mrazekp/aur-multimc-git/src/multimc-git/application/main.cpp:36
(gdb)
```

This is with Java not set up before the start.

**Comment by peterix** [comment]
Fixed in develop.
