### ISSUE TITLE
Need help dont know what to do Wont let me create new world-this is all i can put in and i dont know where else to put this thread

### ISSUE THREAD

**Issue by PercabethRomione** [MultiMC/MultiMC5#2255]
16:33:30] [Server thread/WARN]: Error looking up item: com.kentington.thaumichorizons.common.items.ItemGolemBellTH@5b46eeed
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.registry.GameRegistry$UniqueIdentifier.<init>(GameRegistry.java:389)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.registry.GameData.getUniqueName(GameData.java:239)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.registry.GameRegistry.findUniqueIdentifierFor(GameRegistry.java:462)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at factorization.servo.TileEntityParaSieve.classifyItems(TileEntityParaSieve.java:561)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at factorization.servo.TileEntityParaSieve.mappingsChanged(TileEntityParaSieve.java:547)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at factorization.shared.Core.mappingsChanged(Core.java:272)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.Loader.fireRemapEvent(Loader.java:984)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.registry.GameData.revertToFrozen(GameData.java:740)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.Loader.serverStopped(Loader.java:849)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:483)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:489)
[16:33:30] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[16:33:30] [Server thread/INFO]: Applying holder lookups
[16:33:30] [Server thread/INFO]: Holder lookups applied
[16:33:31] [pool-11-thread-1/INFO]: ServerChannelRegister: Dimensional Transceiver data saved to C:\Users\Grace\Documents\Curse\Minecraft\Instances\The UCC (1) (1)\saves\New World-\enderio\dimensionalTransceiver.json
[16:33:31] [Server thread/INFO]: Completed server-stop actions.
[16:33:32] [Netty IO #1/INFO]: GameProfile: com.mojang.authlib.GameProfile@7fcea47e[id=cd3bc404-a800-432c-906d-f9377a11b5f4,name=jimicroft,properties={},legacy=false]
[16:33:32] [Server thread/INFO]: RFTools: server is stopping. Shutting down gracefully
[16:33:32] [Server thread/INFO]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[16:33:32] [Server thread/INFO]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

**Comment by peterix** [comment]
I guess noone understood this... sorry.
