### ISSUE TITLE
Please Help with AL lib: (EE) alc_cleanup: 1 device not closed

### ISSUE THREAD

**Issue by Meisterpopeister** [MultiMC/MultiMC5#2293]
I've created a custom modpack for my private server using MultiMC, the problem is after the last bunch of mods i put in i could not start my game at the end of forge phase 5/7 i would appreciate some help (hte only mod i would not remove is orespawn because its the main one) here's the crashlog:

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 10/23/15 6:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: danger.orespawn.OreSpawnMain
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:502)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.ClassNotFoundException: danger.orespawn.OreSpawnMain
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:420)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	... 18 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.11.1
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 312819992 bytes (298 MB) / 672661504 bytes (641 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 4 mods loaded, 4 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed
	OreSpawn{1.7.10.20.3} [OreSpawn] (danger) Unloaded->Errored

heres some more from the console

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.13.4
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3492634136 bytes (3330 MB) / 4879024128 bytes (4653 MB) up to 4879024128 bytes (4653 MB)
	JVM Flags: 2 total; -Xms4999m -Xmx5000m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 81 mods loaded, 80 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHI	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCHI	modJ_StarMinerCore{0.9.7} [StarMinerCore] (minecraft.jar) 
	UCHI	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHI	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHI	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHI	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UCHI	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (Malisis' Core.jar) 
	UCHI	FastCraft{1.23} [FastCraft] (FastCraft-Mod-1.7.10.jar) 
	UCHI	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI.jar) 
	UCHI	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCHI	lightsabers{1.1.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-1.1.1 Kopie.jar) 
	UCHI	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHI	surpriseeggs{1.0.6} [Surprise Eggs] (Adventure Backpack.jar) 
	UCHI	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (Adventure Backpack.jar) 
	UCHI	modJ_StarMiner{0.9.7} [Starminer Mod] (Anti-Gravity-Mod-1.7.10 Kopie.jar) 
	UCHI	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHI	asielib{0.2.7} [asielib] (asielib.jar) 
	UCHE	BattleTowers{1.5.1} [Battle Towers] (Battle-Towers-Mod-1.7.10 Kopie.jar) 
	UCHI	chocolateQuest{1.0} [Chocolate Quest] (Better-Dungeons-Mod-1.7.10 Kopie.jar) 
	UCHI	BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft.jar) 
	UCHI	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5 Kopie.jar) 
	UCHI	Botania{r1.8-249} [Botania] (Botania r1.8-249 Kopie 2.jar) 
	UCHI	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks.jar) 
	UCHI	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2 Kopie.jar) 
	UCHI	chisel{2.3.10.37} [Chisel 2] (Chisel 2.jar) 
	UCHI	customnpcs{1.7.10d} [CustomNpcs] (CustomNpcs.jar) 
	UCHI	DamageIndicatorsMod{3.2.3} [Damage Indicators] (Damage Indicators.jar) 
	UCHI	darkcore{0.3} [Dark Core] (darkcore-0.3-86.jar) 
	UCHI	props{2.0.2} [Decocraft] (Decocraft.jar) 
	UCHI	dldungeonsjdg{1.9.2} [Doomlike Dungeons] (DoomlikeDungeons-1.9.2-MC1.7.10 Kopie.jar) 
	UCHI	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12 Kopie.jar) 
	UCHI	iChunUtil{4.2.2} [iChunUtil] (iChunUtil.jar) 
	UCHI	GraviGun{4.0.0-beta} [GraviGun] (GravityGun.jar) 
	UCHI	Hats{4.0.1} [Hats] (Hats.jar) 
	UCHI	HatStand{4.0.0} [HatStand] (HatStand-4.0.0.jar) 
	UCHI	InventoryPets{1.4.9.9b} [Inventory Pets] (inventorypets-1.7.10-1.4.9.9b-universal.jar) 
	UCHI	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152 Kopie.jar) 
	UCHI	IronChest{6.0.60.741} [Iron Chest] (Iron Chest.jar) 
	UCHI	pacman{1.0.7} [Killer Pacman] (Killer Pacman.jar) 
	UCHI	lasermod{v1.2.0a} [Laser Mod] (LaserMod-1.7.10-v1.2.0a-universal Kopie.jar) 
	UCHI	legends{1.7} [Legends Mod] (Legends Core-1.7.jar) 
	UCHI	lucky{5.1.0} [Lucky Block] (LuckyBlock.jar) 
	UCHI	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (Malisis' Doors.jar) 
	UCHI	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b Kopie.jar) 
	UCHI	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (Mine & Blade Battlegear 2 - Bullseye.jar) 
	UCHI	MobProperties{0.4.0} [Mob Properties] (Mob Properties.jar) 
	UCHI	Morph{0.9.1} [Morph] (Morph.jar) 
	UCHI	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfish's Furniture Mod.jar) 
	UCHI	MutantCreatures{1.4.8} [Mutant Creatures] (Mutant Creatures.jar) 
	UCHI	NEIAddons{1.12.10.33} [NEI Addons] (NEI Addons- Ex Nihilo.jar) 
	UCHI	NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2] (NEI Addons- Ex Nihilo.jar) 
	UCHI	NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany] (NEI Addons- Ex Nihilo.jar) 
	UCHI	NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry] (NEI Addons- Ex Nihilo.jar) 
	UCHI	NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables] (NEI Addons- Ex Nihilo.jar) 
	UCHI	NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo] (NEI Addons- Ex Nihilo.jar) 
	UCHI	nomorerain{0.0.1} [No More Rain] (No-More-Rain-Mod-1.7.10.jar) 
	UCHI	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10 Kopie.jar) 
	UCHI	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6 Kopie.jar) 
	UCHI	MapWriter{2.1.2} [MapWriter] (Opis.jar) 
	UCHI	Opis{1.2.5} [Opis] (Opis.jar) 
	UCHI	origin{3.3.0} [Origin] (Origin.jar) 
	UCHI	pandorasbox{2.0.1} [Pandora's Box] (Pandora's Box.jar) 
	UCHI	PortalGun{4.0.0-beta-4} [PortalGun] (PortalGun-4.0.0-beta-4.jar) 
	UCHI	ProjectE{1.7.10-PE1.10.1} [ProjectE] (ProjectE-1.7.10-PE1.10.1 Kopie.jar) 
	UCHI	SaintsCore{0.8} [Saintscore] (Saintscore.jar) 
	UCHI	securitycraft{v1.7.4.1} [SecurityCraft] (SecurityCraft.jar) 
	UCHE	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (Soul Shards- The Old Ways.jar) 
	UCHI	statues{2.1.3} [Statues] (Statues.jar) 
	UCHI	fiskheroes{1.0.13} [Fisk's Superheroes] (Superheroes-1.7.10-1.0.13 Kopie.jar) 
	UCHI	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8 Kopie.jar) 
	UCHI	OreSpawn{1.7.10.20.3} [OreSpawn] (The OreSpawn Mod.zip) 
	UCHI	secretroomsmod{4.7.1} [The SecretRoomsMod] (The SecretRoomsMod.jar) 
	UCHI	TrailMix{4.0.0} [TrailMix] (TrailMix.jar) 
	UCHI	transformers{${version}} [Transformers Mod] (Transformers Mod.jar) 
	UCHI	weepingangels{3.3.2} [Weeping Angels] (Weeping Angels.jar) 
	UCHI	witchery{0.24.1} [Witchery] (Witchery.jar) 
	UD	asielibcore{} [AsieLib CoreMod] (minecraft.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-10.4.14' Renderer: 'ATI Radeon HD 4850 OpenGL Engine'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: ARB, pool: internal, bits: 8
[13:48:13] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:-1]: #@!@# Game crashed! Crash report saved to: #@!@# /Users/Jim/MINECRAFT/MultiMC.app/Contents/MacOS/instances/orespawn1/minecraft/crash-reports/crash-2018-05-27_13.48.13-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.

Please make a comment if you need more information

**Comment by peterix** [comment]
Please use the upload button and post a link to the full log.

**Comment by Meisterpopeister** [comment]
ok here https://paste.ee/p/eW7O6

**Comment by peterix** [comment]
That's something I haven't seen in a while.

You have an ID conflict in `BattleTowers` and `Soul Shards: The Old Ways`:

```
[14:53:56] [Client thread/ERROR] [FML]: Caught exception from SSTOW
Caused by: java.lang.IllegalArgumentException: Duplicate enchantment id! class com.whammich.sstow.enchantment.EnchantmentSoulStealer and class com.chocolate.chocolateQuest.magic.EnchantmentMagicDefense Enchantment ID:52
	at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:53) ~[aft.class:?]
```

```
[14:53:56] [Client thread/ERROR] [FML]: Caught exception from BattleTowers
java.lang.IllegalArgumentException: ID is already registered: 186
```

So, enchantment ID 52 and entity ID 186 are conflicting.

**Comment by Meisterpopeister** [comment]
so i need to remove one of them? am i right

**Comment by peterix** [comment]
Or fix it somehow, back when this was a much bigger problem because of block IDs, mods had the ID numbers in their configs, and there were tools for resolving conflicts.

Maybe you just need to tweak some ID numbers in configs.

**Comment by Meisterpopeister** [comment]
ok thanks

**Comment by Meisterpopeister** [comment]
so i removed battletowers but it still doesnt work any other ideas?

**Comment by Meisterpopeister** [comment]
heres the new log https://paste.ee/p/bMLaW

**Comment by Meisterpopeister** [comment]
ok i just tried to disable both and it works now (imma try and fix it now thanks for your help)
