### ISSUE TITLE
icreated an another modpack and it crashes for some reason

### ISSUE THREAD

**Issue by ShadowPlayer12** [MultiMC/MultiMC5#2305]
System Information 
-----------------------------
MultiMC version:5

Operating System: windows 8.1

Summary of the issue or suggestion: crashes with code -1
----------------------------------------------

What should happen: it should start minecraft
------------------------------

Suspected cause: i have no idea
---------------------------

Logs/Screenshots: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.5.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal (1).jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 6/1/18 4:35 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from denseores (denseores)
Caused by: com.rwtema.denseores.ProxyClient$1: Dense Ores requires CompatLayer to run in Minecraft 1.10.2
	at com.rwtema.denseores.ProxyClient.wrap(ProxyClient.java:20)
	at com.rwtema.denseores.DenseOresMod.preInit(DenseOresMod.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: com.rwtema.denseores.DenseOresMod$1: Dense Ores requires CompatLayer to run in Minecraft 1.10.2
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 605105608 bytes (577 MB) / 1196949504 bytes (1141 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCH	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCH	openmodscore{0.11.5} [OpenModsLib Core] (minecraft.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.320-universal (1).jar) 
	UCH	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe (1).jar) 
	UCH	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UCH	BiomesOPlenty{5.0.0.2290} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2290-universal (1).jar) 
	UCH	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UCH	ChestTransporter{2.5.18} [Chest Transporter] (ChestTransporter-1.10.2-2.5.18 (1).jar) 
	UCH	chickens{4.3.2} [Chickens] (chickens-4.3.2.jar) 
	UCH	ctm{MC1.10.2-0.2.3.26} [CTM] (CTM-MC1.10.2-0.2.3.26.jar) 
	UCH	chisel{MC1.10.2-0.2.0.43} [Chisel] (Chisel-MC1.10.2-0.2.0.43.jar) 
	UCH	CodeChickenLib{2.5.9.320} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.320-universal (1).jar) 
	UCH	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCH	JEI{3.14.8.422} [Just Enough Items] (jei_1.10.2-3.14.8.422.jar) 
	UCH	MineTweaker3{3.0.26} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCH	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCH	csb_ench_table{1.1.3} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.10-1.1.3.jar) 
	UCH	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCH	gravestone{1.5.13} [Gravestone Mod] (gravestone-1.5.13 (1).jar) 
	UCH	ichunutil{6.5.0} [iChunUtil] (iChunUtil-1.10.2-6.5.0 (1).jar) 
	UCH	hats{6.0.0} [Hats] (Hats-1.10.2-6.0.0.jar) 
	UCH	hatstand{6.0.0} [HatStand] (HatStand-1.10.2-6.0.0.jar) 
	UCH	headcrumbs{2.0.2} [Headcrumbs] (Headcrumbs-2.0.3.jar) 
	UCH	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCH	ironbackpacks{1.10.2-2.2.33} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.33 (1).jar) 
	UCH	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804 (1).jar) 
	UCH	jeiintegration{1.2.0.19} [JEI Integration] (jeiintegration_1.10.2-1.2.0.19.jar) 
	UCH	kleeslabs{3.3.5} [KleeSlabs] (KleeSlabs_1.10.2-3.3.5.jar) 
	UCH	lootbags{2.5.0} [Loot Bags] (LootBags-1.10.2-2.5.0 (1).jar) 
	UCH	mysticalagriculture{1.5.10} [Mystical Agriculture] (mysticalagriculture-1.10.2-1.5.10 (1).jar) 
	UCH	mysticalagradditions{1.0.4} [Mystical Agradditions] (mysticalagradditions-1.10.2-1.0.4.jar) 
	UCH	openmods{0.11.5} [OpenModsLib] (OpenModsLib-1.10.2-0.11.5.jar) 
	UCH	openblocks{1.7.6} [OpenBlocks] (OpenBlocks-1.10.2-1.7.6 (1).jar) 
	UCH	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's+HarvestCraft+1.10.2j.jar) 
	UCH	progressiveautomation{1.7.4} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.7.4 (1).jar) 
	UCH	roguelike{1.5.9} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.9.jar) 
	UCH	tp{1.2.5} [Tiny Progressions] (tinyprogressions-1.10.2-1.2.6 (1).jar) 
	UCH	VeinMiner{0.38.2_1.9-127e28f} [Vein Miner] (VeinMiner-1.9-0.38.2.624+127e28f (1).jar) 
	UCH	VeinMinerModSupport{0.38.2_1.9-127e28f} [Mod Support] (VeinMiner-1.9-0.38.2.624+127e28f (1).jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4 (1).jar) 
	UCE	denseores{1.0} [denseores] (denseores-1.11-1.0.2.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal (1).jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics'
	OpenModsLib class transformers: [pre_world_render_hook:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	CodeChickenLib Invalid Fingerprint Reports: 
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
Install CompatLayer, and please take a look at the formatting before posting. Wrap logs and such in backtickes or upload them on some pastesite.
