### ISSUE TITLE
Multi MC 5 crashes when loading game. Please Help!

### ISSUE THREAD

**Issue by YigitVRD** [MultiMC/MultiMC5#2313]
-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:594)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:431)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by peterix** [comment]
This looks like a graphics driver issue.

Please attach the full dxdiag report so we can figure out what is wrong. You can do it like this:

## In Windows 7:

* Click on the `Start` Button.
* In the Search Box type `dxdiag` and press `<Enter>`. The DirectX Diagnostic Tool pop-up window should appear.
* Click on `Save all Information.`
* Save the information to your Desktop, keep the file name as is.
* Attach the file here.

## In Windows 8, Windows 10:
* Press the `[Windows]+[R]` keys on your keyboard to bring up the Run command.
* In the `Run` command box, type in `dxdiag` and press `<Enter>`. The DirectX Diagnostic Tool pop-up window should appear.
* Click on `Save all Information.`
* Save the information to your Desktop, keep the file name as is.
* Attach the file here.

Here is an example of what the DirectX Diagnostic Tool will look like:

![dxdiag example](https://user-images.githubusercontent.com/203326/34328124-4489aa8e-e8d6-11e7-9984-0f5e8561564b.png)

**Comment by YigitVRD** [comment]
"Attach the file here." Where?

**Comment by peterix** [comment]
Here. Look under the text box.

**Comment by YigitVRD** [comment]
It wasn't please help

**Comment by YigitVRD** [comment]
I save the file and ...

**Comment by YigitVRD** [comment]
What will happen?

**Comment by peterix** [comment]
Absolutely nothing if you don't post the file so I can look at it.

**Comment by YigitVRD** [comment]
[DxDiag.txt](https://github.com/MultiMC/MultiMC5/files/2095057/DxDiag.txt)

**Comment by YigitVRD** [comment]
This?

**Comment by YigitVRD** [comment]
File?

**Comment by peterix** [comment]
Yeah, I was just grabbing some groceries...

Anyway, that file. Good :)

**Comment by peterix** [comment]
If you use an older integrated Intel GPU (HD2000, HD3000), you will have to use an older version of Java.

Either one of those should work:
* https://files.multimc.org/downloads/jre-8u51-windows-x64.zip (64-bit)
* https://files.multimc.org/downloads/jre-8u51-windows-i586.zip (32-bit)

Download it, extract it into the MultiMC folder so it shows up like this:
![image](https://cloud.githubusercontent.com/assets/203326/24775694/31ee8d8a-1b1e-11e7-81d5-eff24add7de2.png)

Then set it up in MultiMc like this:
![image](https://cloud.githubusercontent.com/assets/203326/24775746/5c45fb22-1b1e-11e7-8615-e9ba6d667d7f.png)

Obviously only on Windows 10 :)

If you want the full background about this issue, see:
<details>
https://github.com/LWJGL/lwjgl/issues/119
https://github.com/MultiMC/MultiMC5/issues/1276 (and many other)

I tried contacting Intel about it, they said they will not fix their drivers because the hardware is unsupported on Windows 10:
http://www.intel.com/content/www/us/en/support/graphics-drivers/000005526.html
And Microsoft got an another person to boost their Windows 10 numbers, even though the hardware is not supported properly there.
</details>

**Comment by peterix** [comment]
Obviously, the above is a template. Your Intel GPU is even slightly older, but I think this applies. Try the older Java, if it doesn't work, we'll have to experiment some more.
