### ISSUE TITLE
enderio test lanch fail @ start with code 1

### ISSUE THREAD

**Issue by hermes3008** [MultiMC/MultiMC5#2332]
System Information
-----------------------------
MultiMC version:

Operating System:

Summary of the issue or suggestion:
----------------------------------------------
the game launches with error code 1

with log

MultiMC version: 0.6.2-1222

Minecraft folder is:
C:/Users/hermes/Downloads/mmc-stable-win32 (1)/MultiMC/instances/enderiotest_multimc/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 10.0.1, using 64-bit architecture.

Running Pre-Launch command: java -jar "C:/Users/hermes/Downloads/mmc-stable-win32 (1)/MultiMC/instances/enderiotest_multimc/.minecraft/UpdaterUpdater.jar" "https://server.enderio.com/enderiotestpack.cfg" "PackInfo.cfg" "C:/Users/hermes/Downloads/mmc-stable-win32 (1)/MultiMC/instances/enderiotest_multimc/.minecraft" "PackUpdate.jar"
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at at.chaosfield.updaterUpdater.JarRunner.addFile(JarRunner.java:13)
	at at.chaosfield.updaterUpdater.UpdaterUpdater.<init>(UpdaterUpdater.java:56)
	at at.chaosfield.updaterUpdater.UpdaterUpdater.main(UpdaterUpdater.java:24)
Process exited with code 1.
Pre-Launch command failed with code 1.

MultiMC: Log upload triggered at: 05 Jul 2018 11:34:41 -0500

What should happen:
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.download https://server.enderio.com/enderiotest_multimc.zip

2. import the zip file

3.launch the instance

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by peterix** [comment]
Use Java 8

**Comment by hermes3008** [comment]
tried that and still didn't work same error but with java 10.0.1 replaced with jre1.8.0_171

**Comment by hermes3008** [comment]
log 
MultiMC version: 0.6.2-1222


Minecraft folder is:
C:/Users/hermes/Desktop/MultiMC/instances/enderiotest_multimc/.minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_171/bin/javaw.exe


Checking Java version...
Java is version 1.8.0_171, using 64-bit architecture.


Running Pre-Launch command: java -jar "C:/Users/hermes/Desktop/MultiMC/instances/enderiotest_multimc/.minecraft/UpdaterUpdater.jar" "https://server.enderio.com/enderiotestpack.cfg" "PackInfo.cfg" "C:/Users/hermes/Desktop/MultiMC/instances/enderiotest_multimc/.minecraft" "PackUpdate.jar"
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at at.chaosfield.updaterUpdater.JarRunner.addFile(JarRunner.java:13)
	at at.chaosfield.updaterUpdater.UpdaterUpdater.<init>(UpdaterUpdater.java:56)
	at at.chaosfield.updaterUpdater.UpdaterUpdater.main(UpdaterUpdater.java:24)
Process exited with code 1.
Pre-Launch command failed with code 1.


MultiMC: Log upload triggered at: 05 Jul 2018 13:09:06 -0500

**Comment by peterix** [comment]
This is not a normal multimc instance and has been it together wrong. Ask whoever made it for support instead.

**Comment by peterix** [comment]
Also, they should talk here, if this is to be r solved quickly.

**Comment by QuImUfu** [comment]
the Pre-Launch command (that likely still uses Java 9) fails.

**Comment by peterix** [comment]
It is. It doesn't work with Java 9 and newer because of programming errors, and the prepaunch command doesn't use the same Java as the instance.

**Comment by peterix** [comment]
Contact the authors of this.

**Comment by QuImUfu** [comment]
https://github.com/XDjackieXD/PackUpdate this is the Updater used by this pack. 
It needs to be updated to work with java 9. Or you can change the prelaunch command to:
```
C:/Program Files/Java/jre1.8.0_171/bin/javaw.exe -jar "$INST_MC_DIR/UpdaterUpdater.jar" "https://server.enderio.com/enderiotestpack.cfg" "PackInfo.cfg" "$INST_MC_DIR" "PackUpdate.jar"
```

**Comment by peterix** [comment]
One more issue with the updater:
```
Running Pre-Launch command: "java" -jar "/home/peterix/.local/share/multimc/instances/enderiotest_multimc/.minecraft/UpdaterUpdater.jar" "https://server.enderio.com/enderiotestpack.cfg" "PackInfo.cfg" "/home/peterix/.local/share/multimc/instances/enderiotest_multimc/.minecraft" "PackUpdate.jar"
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at at.chaosfield.updaterUpdater.UpdaterUpdater.<init>(UpdaterUpdater.java:57)
	at at.chaosfield.updaterUpdater.UpdaterUpdater.main(UpdaterUpdater.java:24)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

It depends on javafx, which does not have to be present.

**Comment by peterix** [comment]
I don't think this is working even with javafx, the updater failed to update the instance properly: https://paste.ee/p/n5bLJ

There are broken files and duplicate files.

**Comment by peterix** [comment]
Anbd it doesn't redownload mods when you remove them...
