### ISSUE TITLE
[SOLVED] 1.7.10

### ISSUE THREAD

**Issue by Sitieno14** [MultiMC/MultiMC5#2364]
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:183)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
Il processo si è chiuso con codice 1.

**Comment by Sitieno14** [comment]
Solved starting first without offline... lol

**Comment by Janrupf** [comment]
Use the close button please
