### ISSUE TITLE
crash when i lunch 1.13

### ISSUE THREAD

**Issue by BlackDouug** [MultiMC/MultiMC5#2368]
Hello I have a problem when I lunch mmc in 1.13 only in 1.13 (sorry for my english I am french 

I start minecraft in 1.13 and my luncher crash 

I am on mac os 1.7.8 I have mmc in 5.3 (not shur) I use this version because with the last version I can't add my account I have protocol 99 

crash report 
Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Caused by: joptsimple.MissingRequiredOptionsException: Missing required option(s) [accessToken, version]
	at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
	at joptsimple.OptionParser.parse(OptionParser.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:69)

	... 8 more
Exiting with -1

Minecraft s'est arrété avec le code de d'arrêt 255.

**Comment by Janrupf** [comment]
I guess you need to update your system AND MultiMC. But here are the good news, updating OSX fixes error 99.

**Comment by BlackDouug** [comment]
I can't update my os my computer is too old

**Comment by S10MC2015** [comment]
Is your multinc cracked? joptsimple.MissingRequiredOptionsException: Missing required option(s) [accessToken, version]

**Comment by S10MC2015** [comment]
Oh your MMC is outdated

**Comment by Janrupf** [comment]
Upgrading your OS is the only way. Else you are stuck with the old versions.

**Comment by BlackDouug** [comment]
i said previusly i can't because my computer is too old

**Comment by tehbasshunter** [comment]
And that's where you have to make the choice:  
  
Play anything from 1.12 down with your current PC or upgrade your OS/PC and play after that.

**Comment by BlackDouug** [comment]
i had find the solution thx for your ansers 

for me the solution is to use winbottler to run minecraft.exe on a mac and i play in 1.13

**Comment by peterix** [comment]
Oh well... bundling updated openssl on macOS would fix this.

I'll count this as a +1 for doing that.
