### ISSUE TITLE
OptiFine 1.13.1 not working with MultiMC: "java.lang.ClassNotFoundException: optifine.OptiFineTweaker"

### ISSUE THREAD

**Issue by kamild1996** [MultiMC/MultiMC5#2402]
I tried getting OptiFine for 1.13.1 running, but I failed. 
This is the content of the .json file:
```
{
    "formatVersion": 1,
    "+libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "optifine:preview_OptiFine_1.13.1_HD_U_E3_beta5",
            "MMC-hint": "local",
            "MMC-filename": "preview_OptiFine_1.13.1_HD_U_E3_beta5.jar"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.13.1"
        }
    ],
    "name": "OptiFine",
    "version": "1.13.1_HD_U_E3_beta5"
}
```

When I try to run the game, this error occurs:
```
[19:16:51] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[19:16:51] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: optifine.OptiFineTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_172]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_172]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by jikuja** [comment]
`"name": "optifine:preview_OptiFine_1.13.1_HD_U_E3_beta5",` is not like in the wiki example. Missing at least on colon.

**Comment by kamild1996** [comment]
Oh now I see it, between "OptiFine" and "1.13.1" should should be a colon...
Sorry, I missed, although since it's so easy to miss it, having it mentioned on the wiki might be a good idea :)

**Comment by Moleculor** [comment]
After a bit more troubleshooting, it looks like the instructions on that page are wrong.

They say the path should look like `.../MultiMC/instances/<Instance>/libraries/OptiFine_1.13_HD_U_E3_beta4.jar`

but I ended up having to move the whole thing to

`...\MultiMC\libraries\optifine\preview_Optifine\1.13.1_HD_U_E3_pre4\preview_OptiFine_1.13.1_HD_U_E3_pre4.jar`, which is definitely NOT in the instances directory, and has several extra directories as well.

Either I missed some vital step in the instructions, or I'm misunderstanding something, or the instructions are incorrect.

**Comment by jikuja** [comment]
The guide works for me.

**Comment by InsaneJ** [comment]
I had the same issue as Moleculor. The wiki article is wrong. Also, there's a typo in Moleculor's solution. The path should include "preview_OptiFine" with capital "F". For me this path works:

> .../multimc/libraries/optifine/preview_OptiFine/1.13.1_HD_U_E3_pre4/preview_OptiFine_1.13.1_HD_U_E3_pre4.jar

**Comment by VampireMonkey** [comment]
I had a similar issue, i fixed it by changing the java version i used to "jre1.8.0_181"

My Path : ...\Minecraft\MultiMC\instances\1.13\libraries\OptiFine_1.13.2_HD_U_E4.jar
Note "1.13" is my instance name.

My json file :

{
    "formatVersion": 1,
    "+libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "optifine:optiFine:1.13.2_HD_U_E4",
            "MMC-hint": "local",
            "MMC-filename": "OptiFine_1.13.2_HD_U_E4.jar"
        }
    ],
    "+tweakers": ["optifine.OptiFineTweaker"],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.13.2"
        }
    ],
    "name": "OptiFine",
    "version": "1.13.2_HD_U_E4"
}

**Comment by peterix** [comment]
This seems like yet another catch-all issue related to Optifine... The page to look at is here: https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine

The instructions there are correct.
