### ISSUE TITLE
1.13.1 OptiFine beta7 doesn't work

### ISSUE THREAD

**Issue by hyperak** [MultiMC/MultiMC5#2404]
System Information
-----------------------------
MultiMC version: 0.6.2-1222 running on win32

Operating System: Windows 10 Ver. 1709

Summary of the issue or suggestion: 
----------------------------------------------

It doesn't work. No performance improvements, no additional options in Video Settings, no OptiFine thingy in F3, _nothing_. 

What should happen:
------------------------------

It should work?

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Do everything on the help article accurately

2. Boot Minecraft

3. Be met with dissapointment

Suspected cause:
---------------------------

The json file seems to be fine for me.

```
   "formatVersion": 1,
    "+libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "optifine:preview_OptiFine:1.13.1_HD_U_E3_beta7",
            "MMC-hint": "local",
            "MMC-filename": "preview_OptiFine_1.13.1_HD_U_E3_beta7"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.13.1"
        }
    ],
    "name": "OptiFine",
    "version": "preview_OptiFine_1.13.1_HD_U_E3_beta7"
}
```

This thing, though...

![2018-09-07_19-59-56](https://user-images.githubusercontent.com/29081800/45247885-0d902d00-b2d9-11e8-94e3-74638ba003a3.png)

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Above.

Additional Info:
---------------------------

none

**Comment by hyperak** [comment]
P.S.: I do have the .jar file in the instance's library folder. 

![explorer_2018-09-07_20-05-29](https://user-images.githubusercontent.com/29081800/45247941-8e4f2900-b2d9-11e8-8c2c-97ea93ea2a62.png)

P.S. 2: No console errors, either.

**Comment by jikuja** [comment]
Missing at least starting {

**Comment by hyperak** [comment]
now it crashes with
```
[23:33:47] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[23:33:47] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: optifine.OptiFineTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Process exited with code 1.
```

**Comment by jikuja** [comment]
jar is probably in the wrong folder. 
Post:
1. full log(using upload log button)
2. screenshot of the optifine jar's location(including full path).

**Comment by hyperak** [comment]
I posted the optifine jar's location earlier already.

This is the full log:
https://paste.ee/p/8lRsR

**Comment by jikuja** [comment]
Bad MMC-filename. Compare with `"MMC-filename": "preview_OptiFine_1.13_HD_U_E3_beta4.jar"`

**Comment by hyperak** [comment]
;ec

fixed, testing... it works now. thanks for the help.
