### ISSUE TITLE
lwjgl not working

### ISSUE THREAD

**Issue by CZHO404** [MultiMC/MultiMC5#2438]
[19:05:03] [Client thread/INFO]: Setting user: CZHO
[19:05:29] [Client thread/INFO]: LWJGL Version: 3.1.6 build 14
[19:05:29] [Client thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[19:05:29] [Client thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[19:05:29] [Client thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
---- Minecraft Crash Report ----
// Why did you do that?

Time: 10/28/18, 7:05 PM
Description: Initializing game

java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:61)
	at org.lwjgl.system.MemoryStack.<init>(MemoryStack.java:61)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:82)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:71)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at org.lwjgl.system.MemoryStack.stackGet(MemoryStack.java:628)
	at org.lwjgl.system.MemoryStack.stackPush(MemoryStack.java:637)
	at cgc.a(SourceFile:127)
	at cfs.an(SourceFile:557)
	at cfs.am(SourceFile:436)
	at cfs.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:61)
	at org.lwjgl.system.MemoryStack.<init>(MemoryStack.java:61)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:82)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:71)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at org.lwjgl.system.MemoryStack.stackGet(MemoryStack.java:628)
	at org.lwjgl.system.MemoryStack.stackPush(MemoryStack.java:637)
	at cgc.a(SourceFile:127)
	at cfs.an(SourceFile:557)
	at cfs.am(SourceFile:436)

-- Initialization --
Details:
Stacktrace:
	at cfs.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.13.1
	Operating System: Linux (i386) version 4.15.0-38-generic
	Java Version: 10.0.2, Oracle Corporation
	Java VM Version: OpenJDK Server VM (mixed mode), Oracle Corporation
	Memory: 452826344 bytes (431 MB) / 536870912 bytes (512 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	Launched Version: MultiMC5
	LWJGL: 3.1.6 build 14
	OpenGL: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.system.Library
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/czho/.local/share/multimc/instances/defalt/.minecraft/crash-reports/crash-2018-10-28_19.05.30-client.txt
Process exited with code 255.
MultiMC: Log upload triggered at: 28 Oct 2018 19:06:39 -0600
MultiMC: Log uploaded to: https://paste.ee/p/SeVdm

**Comment by peterix** [comment]
This seems to be an issue on Mojang side, because the 32bit files simply aren't included.

**Comment by peterix** [comment]
See:
* https://www.reddit.com/r/Minecraft/comments/8bujfe/psa_minecraft_113_wont_run_on_x86_linux_machines/
* https://bugs.mojang.com/browse/MC-130954
* https://github.com/LWJGL/lwjgl3/issues/162

**Comment by peterix** [comment]
From my point of view, this is unfortunated, but it also seems like something noone will fix (and I'm not eager to do so either).

**Comment by CZHO404** [comment]
I just downgrade the lwjl in the json

**Comment by peterix** [comment]
Anyway, proper fix is needed on Mojang side. I do not want to maintain workarounds here.
