### ISSUE TITLE
Minecraft 1.12.2 crashes when i use forge 

### ISSUE THREAD

**Issue by MexicanPerson** [MultiMC/MultiMC5#2471]
System Information
-----------------------------
MultiMC version:0.6.2

Operating System:Windows 10

Summary of the issue or suggestion:
----------------------------------------------

What should happen: Minecraft should launch
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.download minecraft 1.12.2

2.install forge

3.problem 

Suspected cause: No idea
---------------------------

Logs/Screenshots:
----------------------------
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.

Additional Info:
---------------------------

**Comment by peterix** [comment]
Use java 8
