### ISSUE TITLE
Cannot Launch anything in Multi MC

### ISSUE THREAD

**Issue by ryanparrott01** [MultiMC/MultiMC5#2481]
System Information
-----------------------------
MultiMC version: 0.6.2

Operating System: Windows 7 x64

Summary of the issue or suggestion: I cannot launch online or offline. It seems there are two separate
 issues causing that but I'm not really sure. I really don't know anything.

----------------------------------------------

What should happen: The game should launch
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. To be honest, I don't know. I've just been trying to launch the game.

Suspected cause: I thought it could have been my java, but I updated that and it didn't help.
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
Log for attempting to launch online:
MultiMC version: 0.6.2-develop-1269

Minecraft folder is:
D:/mmc-stable-win32/MultiMC/instances/First Mods/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_191, using 64-bit architecture.

Instance update failed because: Null jar is specified in the metadata, aborting.

Clipboard copy at: 02 Dec 2018 19:08:02 -0800

Log for attempting to launch offline:
MultiMC version: 0.6.2-develop-1269

Minecraft folder is:
D:/mmc-stable-win32/MultiMC/instances/First Mods/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_191, using 64-bit architecture.

Main Class:
  

Native path:
  D:/mmc-stable-win32/MultiMC/instances/First Mods/natives

Libraries:

Native libraries:

Mods:
  BiblioCraft[v2.4.5][MC1.12.2]
  BiomesOPlenty-1.12.2-7.0.1.2384-universal
  CodeChickenLib-1.12.2
  CustomMobSpawner-3.11.4
  Decocraft-2.6.0_1.12.2
  DrZharks MoCreatures Mod-12.0.4
  FastLeafDecay-v14
  Instant-Massive-Structures-Mod-1.12
  jei_1.12.2-4.10.0.198
  journeymap-1.12.2-5.5.2
  JurassiCraft-1.12.2-2.1.8
  llibrary-1.7.14-1.12.2
  Not-Enough-Items-1.12.2-Recommended
  Pam's+HarvestCraft+1.12.2u
  PTRLib-1.0.2
  worldedit-forge-mc1.12-6.1.8-dist

Params:
  

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4352m, -Xmx5888m, -Duser.language=en]

Minecraft process ID: 3676

Using onesix launcher.

Not enough arguments.
org.multimc.NotFoundException
	at org.multimc.ParamBucket.all(ParamBucket.java:43)
	at org.multimc.onesix.OneSixLauncher.processParams(OneSixLauncher.java:55)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:212)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with code -1.
Clipboard copy at: 02 Dec 2018 19:05:57 -0800

Additional Info:
---------------------------
I'm a total newbie. Please try to explain everything as simply as possible. I'm really sorry :/

**Comment by QuImUfu** [comment]
"D:/mmc-stable-win32/MultiMC/instances/First Mods/mmc-pack.json" is likely missing or corrupted. Have you full read and write rights in the instance folder?
Does this happen with a newly created and unmodified Instance?

**Comment by katubug** [comment]
Just tested, everything works as intended with the smeltery module disabled.

**Comment by Guspog** [comment]
Help pls, i am very stupied

MultiMC version: 0.6.7-1375



Minecraft folder is:
D:/Мульти Мс/MultiMC/instances/FTB Sky Odyssey/.minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_231/bin/javaw.exe


Версия Java 1.8.0_231, использующая 32-битную архитектуру.


Main Class:
  

Native path:
  D:/Мульти Мс/MultiMC/instances/FTB Sky Odyssey/natives

Libraries:

Native libraries:

Mods:
  [📁] 1.12 (folder)
  [✔️] ActuallyAdditions-1.12.2-r146
  [✔️] ActuallyBaubles-1.12-1.1
  [✔️] ae2stuff-0.7.0.4-mc1.12.2
  [✔️] AE2WTLib-1.12.2-1.0.6
  [✔️] AkashicTome-1.2-12
  [✔️] AppleSkin-mc1.12-1.0.9
  [✔️] appliedenergistics2-rv6-stable-6
  [✔️] architecturecraft-1.12-3.80
  [✔️] AttributeFix-1.12.2-1.0.7
  [✔️] AutoRegLib-1.3-26
  [✔️] badwithernocookiereloaded-1.12.2-3.3.16
  [✔️] Baubles-1.12-1.5.2
  [✔️] bdlib-1.14.3.12-mc1.12.2
  [✔️] bedpatch-2.2-1.12.2
  [✔️] BetterAdvancements-1.12.2-0.1.0.77
  [✔️] BetterBuildersWands-1.12.2-0.13.2.271+5997513
  [✔️] BetterFps-1.4.8
  [✔️] BloodMagic-1.12.2-2.4.0-102
  [✔️] BNBGamingCore-1.12.2-0.10.0
  [✔️] BNBGamingLib-1.12.2-2.17.5
  [✔️] BoneAppetit-1.0.0.4
  [✔️] bonsaitrees-1.1.2-b144
  [✔️] Bookshelf-1.12.2-2.3.577
  [✔️] Botania_r1.10-362-custom
  [✔️] BotanicBonsai-1.0.0.5
  [✔️] BrandonsCore-1.12.2-2.4.9.195-universal
  [✔️] BuildingGadgets-2.6.8
  [✔️] Chameleon-1.12-4.1.3
  [✔️] Charset-Lib-0.5.5.7
  [✔️] Charset-ToolsEngineering-0.5.5.2
  [✔️] ChestTransporter-1.12.2-2.8.8
  [✔️] chickens-6.1.0
  [✔️] Chisel-MC1.12.2-0.2.1.35
  [✔️] chiselsandbits-14.31
  [✔️] ClientTweaks_1.12.2-3.1.11
  [✔️] Clipboard-1.12-1.3.0
  [✔️] Clumps-3.1.2
  [✔️] CodeChickenLib-1.12.2-3.2.2.353-universal
  [✔️] CoFHCore-1.12.2-4.6.2.25-universal
  [✔️] CoFHWorld-1.12.2-1.3.0.6-universal
  [✔️] compacter-1.3.0.3-mc1.12.2
  [✔️] CompactSolars-1.12.2-5.0.18.341-universal
  [✔️] Controlling-3.0.6
  [✔️] CookingForBlockheads_1.12.2-6.4.70
  [✔️] CraftingTweaks_1.12.2-8.1.9
  [✔️] CraftTweaker2-1.12-4.1.17
  [✔️] CTM-MC1.12.2-0.3.3.22
  [✔️] Cucumber-1.12.2-1.1.3
  [✔️] CustomMainMenu-MC1.12.2-2.0.9
  [✔️] DarkUtils-1.12.2-1.8.226
  [✔️] deepmoblearning-1.12.2-2.4.2-universal
  [✔️] deepmoblearningbm-1.12.2-1.0.0-universal
  [✔️] DefaultOptions_1.12.2-9.2.8
  [✔️] diethopper-1.1
  [✔️] dirt2path-1.8.0
  [✔️] Draconic-Evolution-1.12.2-2.3.20.333-universal
  [✔️] ElecCore-1.12.2-1.9.452
  [✔️] EnableCheats-1.12.2-1.0.0
  [✔️] EnderCore-1.12.2-0.5.53
  [✔️] EnderIO-1.12.2-5.0.43
  [✔️] EnderStorage-1.12.2-2.4.5.135-universal
  [✔️] environmentaltech-1.12.2-2.0.20.1
  [✔️] Exchangers-1.12.2-2.8
  [✔️] ExtraBitManipulation-1.12.2-3.4.1
  [✔️] ExtraCells-1.12.2-2.6.2a
  [✔️] extrautils2-1.12-1.9.9
  [✔️] ExtremeReactors-1.12.2-0.4.5.65
  [✔️] FastFurnace-1.12.2-1.2.2
  [✔️] FastWorkbench-1.12.2-1.6.1
  [✔️] flatcoloredblocks-mc1.12-6.7
  [✔️] fluxnetworks-1.12.2-3.0.19-21
  [✔️] foamfix-0.10.5-1.12.2
  [✔️] Forgelin-1.8.2
  [✔️] ForgeMultipart-1.12.2-2.6.1.81-universal
  [✔️] framland-1.12.2-1.0.10
  [✔️] FTB-Beast-Coin-Miner-1.12.2-1.0.0.18
  [✔️] FTBGuides-2.0.0.34
  [✔️] FTBLib-5.4.1.94
  [✔️] FTBMoney-1.1.0.28
  [✔️] FTB-OdysseyWorld-1.12.2-1.1.0.11
  [✔️] FTBQuests-1.5.1.143
  [✔️] FTBUtilities-5.4.0.91
  [✔️] FTBUtilitiesBackups-1.0.0.3
  [✔️] Guide-API-1.12-2.1.8-63
  [✔️] HardCoreMapReset-4.2.3.39
  [✔️] Harvest-1.12-1.2.7-20
  [✔️] hatchery-1.12.2-2.2.1
  [✔️] hopperducts-mc1.12-1.5
  [✔️] ieclochecompat-2.1.7-dev.454
  [✔️] ImmersiveEngineering-0.12-89
  [✔️] industrialcraft-2-2.8.111-ex112
  [✔️] industrialforegoing-1.12.2-1.12.11-235
  [✔️] IndustrialRenewal_1.12.2-0.8.1
  [✔️] IntegrationForegoing-1.12.2-1.9
  [✔️] inventorypets-1.12-1.5.3.1
  [✔️] inventorysorter-1.12.2-1.13.3+57
  [✔️] ironchest-1.12.2-7.0.59.842
  [✔️] ItemFilters-1.0.3.11
  [✔️] jei_1.12.2-4.15.0.275
  [✔️] jeiintegration_1.12.2-1.5.1.36
  [✔️] JustEnoughReactors-1.12.2-1.1.3.61
  [✔️] JustEnoughResources-1.12.2-0.9.0.53
  [✔️] KleeSlabs_1.12.2-5.4.11
  [✔️] letsencryptcraft-1.10.2-1.2.0
  [✔️] LoadingTips-1.12.2-1.1.0
  [✔️] longfallboots-1.2.1b
  [✔️] LootTweaker-1.12.2-0.0.9
  [✔️] MarbleCraftingTable-1.0.2
  [✔️] mcjtylib-1.12-3.1.1
  [✔️] MCMultiPart-2.5.3
  [📁] memory_repo (folder)
  [✔️] minetogether-1.10.2-2.1.3
  [✔️] MobGrindingUtils-0.3.13
  [✔️] modnametooltip_1.12.2-1.10.0
  [✔️] Modpack Configuration Checker-1.12.2-v1.8
  [✔️] modtweaker-4.0.17
  [✔️] Modular Diversity-1.1
  [✔️] modularmachinery-1.12.2-1.10.0-v38
  [✔️] morechickens-1.12.2-3.2.0
  [✔️] moreoverlays-1.14-mc1.12.2
  [✔️] Morpheus-1.12.2-3.5.106
  [✔️] Morph-o-Tool-1.2-21
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] mpbasic-1.12.2-1.4.11
  [✔️] MPUtils-1.12.2-1.5.7
  [✔️] MTLib-3.0.6
  [✔️] mystagradcompat-1.2
  [✔️] MysticalAgradditions-1.12.2-1.3.1
  [✔️] MysticalAgriculture-1.12.2-1.7.3
  [✔️] NaturesCompass-1.12.2-1.5.1
  [✔️] Neat 1.4-17
  [✔️] NetherPortalFix_1.12.1-5.3.17
  [✔️] NoMatter-1.12.2-1.0.0.5
  [✔️] NoMobSpawningOnTrees-1.2.2-mc1.12.2
  [✔️] noRecipeBook_v1.2.2formc1.12.2
  [✔️] notenoughwands-1.12-1.7.3
  [✔️] OpenBlocks-1.12.2-1.8
  [✔️] OpenModsLib-1.12.2-0.12.1
  [✔️] OreExcavation-1.4.137
  [✔️] p455w0rdslib-1.12.2-2.0.36
  [✔️] Patchouli-1.0-18
  [✔️] petslow-0.1.3
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] ProjectE-1.12.2-PE1.4.0
  [✔️] ProjectEX-1.1.0.28
  [✔️] QuantumStorage-1.12-4.6.8
  [✔️] RandomThings-MC1.12.2-4.2.7
  [✔️] reauth-3.6.0
  [✔️] RebornCore-1.12.2-3.13.11.444-universal
  [✔️] RebornStorage-1.12.2-3.3.2.79
  [✔️] RedstoneArsenal-1.12.2-2.6.2.17-universal
  [✔️] RedstoneFlux-1.12-2.1.0.6-universal
  [✔️] refinedstorage-1.6.14
  [✔️] refinedstorageaddons-0.4.4
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] ResourceReloader-1.0.2.5
  [✔️] rftools-1.12-7.61
  [✔️] rftoolsctrl-1.12-1.9.3
  [✔️] rftoolspower-1.12-1.1.2
  [✔️] roost-1.12-1.3.0
  [✔️] ShadowMC-1.12-3.8.0
  [✔️] simpleharvest-1.08
  [✔️] SimpleLogic-Gates-0.5.5.7
  [✔️] SimpleLogic-Wires-0.5.5.7
  [✔️] SimplyJetpacks2-1.12.2-2.2.11.64
  [✔️] SmoothFont-mc1.12.2-2.0-alpha-9
  [✔️] Snad-1.12.1-1.7.09.16a
  [✔️] sonarcore-1.12.2-5.0.19-20
  [✔️] StorageDrawers-1.12.2-5.3.8
  [✔️] StructureUtils-1.1.0.4
  [✔️] Surge-1.12.2-2.0.77
  [✔️] TeamIslands-1.1.0.24
  [✔️] TechReborn-1.12.2-2.22.1.979-universal
  [✔️] tesla-core-lib-1.12.2-1.0.15
  [✔️] Tesslocator-1.0.0.5
  [✔️] Thaumcraft-1.12.2-6.1.BETA26
  [✔️] ThaumicGrid-1.0.11
  [✔️] ThaumicInventoryScanning_1.12.2-2.0.10
  [✔️] ThaumicJEI-1.12.2-1.5.8-26
  [✔️] ThaumicTerminal-1.0.10
  [✔️] theoneprobe-1.12-1.4.28
  [✔️] ThermalCultivation-1.12.2-0.3.2.11-universal
  [✔️] ThermalDynamics-1.12.2-2.5.4.18-universal
  [✔️] ThermalExpansion-1.12.2-5.5.3.41-universal
  [✔️] ThermalFoundation-1.12.2-2.6.2.26-universal
  [✔️] ThermalInnovation-1.12.2-0.3.2.11-universal
  [✔️] TipTheScales-1.12.2-1.0.4
  [✔️] Toast Control-1.12.2-1.8.0
  [✔️] TombManyGraves-1.12-4.2.0
  [✔️] topaddons-1.12.2-1.10.1
  [✔️] torchmaster_1.12.2-1.7.1.74
  [✔️] tramplestopper-1.12.2-1.2.0.5-universal
  [✔️] Translocators-1.12.2-2.5.1.77-universal
  [✔️] Triumph-1.12.2-3.16.0
  [✔️] TS2K16-1.2.10
  [✔️] UniDict-1.12.2-2.9.2
  [✔️] Uppers-0.0.6
  [✔️] valkyrielib-1.12.2-2.0.20.1
  [✔️] WanionLib-1.12.2-2.2
  [✔️] WirelessCraftingTerminal-1.12.2-3.11.88
  [✔️] woot-1.12.2-1.4.10
  [✔️] WR-CBE-1.12.2-2.3.1.30-universal
  [✔️] xnet-1.12-1.7.6
  [✔️] YABBA-1.1.2.46
  [✔️] zerocore-1.12.2-0.1.2.8

Params:
  

Window size: 854 x 480

Failed to reconstruct Minecraft assets.
Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


ID процесса Minecraft: 6468


Using onesix launcher.

Not enough arguments.
org.multimc.NotFoundException
	at org.multimc.ParamBucket.all(ParamBucket.java:43)
	at org.multimc.onesix.OneSixLauncher.processParams(OneSixLauncher.java:55)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:212)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Процесс завершился с кодом -1.

**Comment by Zetabite** [comment]
Use 64Bit Java 8 and allocate more RAM

**Comment by Heufneutje** [comment]
And put MultiMC in a folder that does not contain cyrillic characters. Java has a lot of issues with those.

**Comment by rmobis** [comment]
For me, the solution was to check my instance folder and replace the apparently corrupted and 0 bytes long `mmc-pack.json` with what appeared to be the backup `mmc-pack.json.WBd26` file.

**Comment by Scotsguy** [comment]
Closing due to inactivity.

**Comment by repetitiveblue** [comment]
i have a solution.
make sure you have this at the end of the mmc-pack.json
### the comma is very important.

```
        }
    ],
    "formatVersion": 1
}
```

### this is my whole mmc-pack.json for those who are still confused:
```
{
    "components": [
        {
            "cachedName": "LWJGL 3",
            "cachedVersion": "3.2.2",
            "cachedVolatile": true,
            "dependencyOnly": true,
            "uid": "org.lwjgl3",
            "version": "3.2.2"
        },
        {
            "cachedName": "Minecraft",
            "cachedRequires": [
                {
                    "equals": "3.2.2",
                    "suggests": "3.2.2",
                    "uid": "org.lwjgl3"
                }
            ],
            "cachedVersion": "1.18.1",
            "important": true,
            "uid": "net.minecraft",
            "version": "1.18.1"
        },
        {
            "cachedName": "Intermediary Mappings",
            "cachedRequires": [
                {
                    "equals": "1.18.1",
                    "uid": "net.minecraft"
                }
            ],
            "cachedVersion": "1.18.1",
            "cachedVolatile": true,
            "dependencyOnly": true,
            "uid": "net.fabricmc.intermediary",
            "version": "1.18.1"
        },
        {
            "cachedName": "Fabric Loader",
            "cachedRequires": [
                {
                    "uid": "net.fabricmc.intermediary"
                }
            ],
            "cachedVersion": "0.13.3",
            "uid": "net.fabricmc.fabric-loader",
            "version": "0.13.3"
        }
    ],
    "formatVersion": 1
}

```
once again, please pay attention to your commas, they are very important
