### ISSUE TITLE
Completely unable to install Optifine using the exact instructions

### ISSUE THREAD

**Issue by etsnyman** [MultiMC/MultiMC5#2491]
System Information
-----------------------------
MultiMC version: 0.6.2-1222

Operating System: Windows 10 Pro 64-bit

Summary of the issue or suggestion:
----------------------------------------------
I have followed the instructions on https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine about 10 times, and I am completely unable to get Minecraft working with OptiFine_1.13.2_HD_U_E5 or even OptiFine_1.13.1_HD_U_E4.

What should happen:
------------------------------
I follow the instructions, and Minecraft launches non problem.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I made a new instance, 1.13.2 vanilla.

2. I added Empty with uid `optifine.OptiFine` and name `OptiFine` (copied directly from the instructions to eliminate errors).

3. I copied the Optifine jar into \MultiMC\instances\1.13.2\libraries\

4. I edited the JSON file as per the intructions.

5. Get errors.

Suspected cause:
---------------------------
Is it incompatible with my version of Java? I'm running the latest 64-bit from Oracle's website:
1.8.0_191 (64-bit)

Logs/Screenshots:
----------------------------
Here is my log: https://paste.ee/p/gaHiR

Also, here:
```
MultiMC version: 0.6.2-1222


Minecraft folder is:
C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/instances/1.13.2/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_191, using 64-bit architecture.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/instances/1.13.2/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.14/brigadier-1.0.14.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/1.0.19/datafixerupper-1.0.19.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.13.9/realms-1.13.9.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/optifine/OptiFine/1.13.2_HD_U_E4/OptiFine_1.13.2_HD_U_E4.jar (missing)
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.13.2/minecraft-1.13.2-client.jar

Native libraries:
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6-natives-windows.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6-natives-windows.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-windows.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6-natives-windows.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6-natives-windows.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6-natives-windows.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/instances/1.13.2/.minecraft --assetsDir C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.13.1 --uuid  --accessToken  --userType  --versionType release --tweakClass optifine.OptiFineTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 6932


Using onesix launcher.

[13:23:54] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[13:23:54] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: optifine.OptiFineTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Process exited with code 1.
Clipboard copy at: 22 Dec 2018 13:23:57 +0200
Clipboard copy at: 22 Dec 2018 13:24:43 +0200
```

Additional Info:
---------------------------
Please help

**Comment by etsnyman** [comment]
Here is the Optifine .jar in WIndows Explorer, showing the file location: https://imgur.com/a/TMie8ob
![Screenshot]https://i.imgur.com/AcXYpV1.png)

And here is my JSON file:
```
{
    "formatVersion": 1,
    "+libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "optifine:OptiFine:1.13.2_HD_U_E4",
            "MMC-hint": "local",
            "MMC-filename": "OptiFine_1.13.2_HD_U_E4.jar"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.13.2"
        }
    ],
    "name": "OptiFine",
    "version": "1.13.2_HD_U_E4"
}
```

Did I do something wrong? I can't figure it out.

**Comment by kaeptmblaubaer1000** [comment]
Well, actually I *do* see a Optifine jar in your Libraries list, but that is pointing to the wrong location.
But AFAIK MultiMC would automatically remove the jar if you put it there, because it's not in the `metacache`.

**Comment by etsnyman** [comment]
What is the correct location? What do I need to change?

**Comment by peterix** [comment]
You are putting in an optifine version (the file) for Minecraft 1.13.1.

**Comment by peterix** [comment]
The location is correct, the file is not.

**Comment by etsnyman** [comment]
Ok, I got the latest Optifine OptiFine_1.13.2_HD_U_E5

Put it in the correct location, deleted the old one.

Still, errors:
```
MultiMC version: 0.6.2-1222


Minecraft folder is:
C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/instances/1.13.2/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_191, using 64-bit architecture.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/instances/1.13.2/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.14/brigadier-1.0.14.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/1.0.19/datafixerupper-1.0.19.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.13.9/realms-1.13.9.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/INVALID (missing)
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.13.2/minecraft-1.13.2-client.jar

Native libraries:
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6-natives-windows.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6-natives-windows.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-windows.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6-natives-windows.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6-natives-windows.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6-natives-windows.jar
  C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/instances/1.13.2/.minecraft --assetsDir C:/Users/etsny/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.13.1 --uuid  --accessToken  --userType  --versionType release --tweakClass optifine.OptiFineTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 9516


Using onesix launcher.

[13:55:42] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[13:55:42] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: optifine.OptiFineTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Process exited with code 1.
Clipboard copy at: 22 Dec 2018 13:55:45 +0200
Clipboard copy at: 22 Dec 2018 13:56:41 +0200
```

Here is my JSON file:
```
{
    "formatVersion": 1,
    "+libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "optifine:OptiFine_1.13.2_HD_U_E5",
            "MMC-hint": "local",
            "MMC-filename": "OptiFine_1.13.2_HD_U_E5"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "fileId": "optifine.OptiFine",
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.13.2"
        }
    ],
    "name": "OptiFine",
    "version": "1.13.2_HD_U_E5"
}
```

Something is still wrong...

**Comment by peterix** [comment]
Yes, now you removed the `:` in the library name.

**Comment by kaeptmblaubaer1000** [comment]
It's because not only the file itself is wrong, but also the location
MultiMC expects it. In the Libraries list in the log I saw that MultiMC
expects it in the global libraries folder instead of the instance one, and
the path inside the libraries folder is wrong too. Possibly instructions
are outdated?

Am Sa., 22. Dez. 2018, 12:57 hat etsnyman <notifications@github.com>
geschrieben:

**Comment by peterix** [comment]
Instructions are current and correct.

**Comment by etsnyman** [comment]
@peterix Thank you for the tip, but I seem to be missing where you are pointing to...

I looked at the libraries name but I still see the `:`
```
    "+libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "name": "optifine:OptiFine_1.13.2_HD_U_E5",
            "MMC-hint": "local",
            "MMC-filename": "OptiFine_1.13.2_HD_U_E5"
        }
```
Could you perhaps point out my mistake? I still see `:` everywhere where it should be, as far as I can see. 

Where is my mistake?

**Comment by peterix** [comment]
` "name": "optifine:OptiFine_1.13.2_HD_U_E5",` is wrong.
` "name": "optifine:OptiFine:1.13.2_HD_U_E5",` is correct.

**Comment by etsnyman** [comment]
Thank you, @peterix ... It works now!

Please take note, anyone else with the same problem, that I first had to exit MultiMC and go in again before it would work.

Thanks again to @peterix

**Comment by kaeptmblaubaer1000** [comment]
IMO something like automatic load of Optifine jars (automating creation of
this JSON based on an imported jar file) sould be added

Am Sa., 22. Dez. 2018, 13:09 hat etsnyman <notifications@github.com>
geschrieben:

**Comment by peterix** [comment]
Not automated on the client, not specific to optifine, and done completely differently... but sure.

**Comment by kaeptmblaubaer1000** [comment]
A server *like *Curseforge, not using Curseforge

Am Sa., 22. Dez. 2018, 13:27 hat Petr Mrázek <notifications@github.com>
geschrieben:

**Comment by QuImUfu** [comment]
Java >8 does not work for modded minecraft. Switch to java 8.

**Comment by etsnyman** [comment]
@QuImUfu Thank you, I switched to Java 8 and it did the trick. (However, on Linux it looks like Java 11, which was installed by default, gives better frame rates on my hardware. Oh well.)
