### ISSUE TITLE
MultiMC crash - The coremod am2.preloader.AM2PreloaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft

### ISSUE THREAD

**Issue by Mremenar** [MultiMC/MultiMC5#2566]
System Information
Afraid you'll have to be more specific.  My guess is you want this: 
3.20GHz Intel Pentium(R) CPU, 8 GB RAM, 1 GB Invidia Video Card

-----------------------------
MultiMC version:
0.6.4-1291

Operating System:
Windows 10

Summary of the issue or suggestion:
----------------------------------------------
crash when attempting to load Minecraft 1.7.10 with mods

What should happen:
------------------------------
Should load just like it does without mods

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMC

2. Watch it crash

3. Curse like a sailor because anything other than Vanilla Minecraft in the "One Microsoft Way" is always like pulling fucken teeth with a pair of tweezers and no anesthetic.

Suspected cause:
---------------------------
I suspect that necessary config files have not been generated/accessible to MultiMC.

"The coremod am2.preloader.AM2PreloaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft."

I can log in with the regular MC loader and all the mods load without issue.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

```
MultiMC version: 0.6.4-1291


Minecraft folder is:
C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/instances/1.7.10/.minecraft


Java path is:
C:/Program Files/Java/jre6/bin/javaw.exe


Java is version 1.6.0_45, using 64-bit architecture.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/instances/1.7.10/natives

Libraries:
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-universal.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  AnimationAPI-1.7.10-1.2.4
  Ars Magica2
  Back+In+Slime-1.7.10-3.1.6
  Better-Dungeons-Mod-1.7.10
  Chisel-2.9.5.11
  CoFHLib-%5b1.7.10%5d1.2.1-185
  Concrete-Mod-1.7.10
  FastCraft-Mod-1.7.10
  fossilsarcheology-for 1.7.10
  Gravity-Gun-Mod-1.7.10
  GrimoireOfGaia3-1.7.10-1.2.7
  iChunUtil-4.2.3
  JoypadMod-1.7.10-10.13.4.1558-1.7.10
  LLibrary-1.7.10
  Mapwriter-2-Mod-1.7.10
  MDXLib-1.7.10
  Morph-Beta-0.9.3
  MSM-SNAP-3.0.0e-For-MC-1.7.10
  Ore-Spawn-Mod-1.7.10
  PrehistoricSpawns-1.7.10-B0.2
  ruins
  ruins_log
  Ruins-1.7.10
  Waila-1.5.10_1.7.10
  worldedit-forge-mc1.7.10-6.1.1-dist

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/instances/1.7.10/.minecraft --assetsDir C:/Users/Sr and Jr/Desktop/mmc-stable-win32/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 960 x 540

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx3072m, -XX:PermSize=128m, -Duser.language=en]


Minecraft process ID: 2656


Using onesix launcher.

[10:45:37] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10:45:37] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10:45:37] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[10:45:37] [main/INFO] [FML]: Forge Mod Loader version 7.99.36.1558 for Minecraft 1.7.10 loading
[10:45:37] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_45, running on Windows 8:amd64:6.2, installed at C:\Program Files\Java\jre6
[10:45:37] [main/WARN] [FML]: The coremod am2.preloader.AM2PreloaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10:45:37] [main/INFO] [ArsMagica2]: Core initializing...stand back!  I'm going to try MAGIC!
[10:45:37] [main/INFO] [FML]: Loading tweaker fastcraft.Tweaker from FastCraft-Mod-1.7.10.jar
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: net/ilexiconn/llibrary/server/core/plugin/LLibraryPlugin : Unsupported major.minor version 52.0
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClassCond(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.access$000(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.AccessController.doPrivileged(Native Method)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName0(Native Method)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[10:45:37] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at C:\Users\Sr and Jr\Desktop\mmc-stable-win32\MultiMC\instances\1.7.10\.minecraft for Forge Mod Loader
java.lang.UnsupportedClassVersionError: net/ilexiconn/llibrary/server/core/plugin/LLibraryPlugin : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_45]
	at java.lang.ClassLoader.defineClassCond(Unknown Source) ~[?:1.6.0_45]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.6.0_45]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.6.0_45]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.6.0_45]
	at java.net.URLClassLoader.access$000(Unknown Source) ~[?:1.6.0_45]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.6.0_45]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_45]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.6.0_45]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.6.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.6.0_45]
	at java.lang.Class.forName0(Native Method) ~[?:1.6.0_45]
	at java.lang.Class.forName(Unknown Source) ~[?:1.6.0_45]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.6.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.6.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.6.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.6.0_45]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[10:45:37] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.reflect.InvocationTargetException
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:488]: Caused by: java.lang.UnsupportedClassVersionError: net/ilexiconn/llibrary/server/core/plugin/LLibraryPlugin : Unsupported major.minor version 52.0
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClassCond(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.access$000(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.security.AccessController.doPrivileged(Native Method)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.Class.forName0(Native Method)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.Class.forName(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:492]: 	... 8 more
[10:45:37] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.ArrayIndexOutOfBoundsException: 5
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Runtime.exit(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.System.exit(Unknown Source)
[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.
```

Additional Info:
---------------------------
We are wanting to use MultiMC so that my 6 year old son and I can play Java Edition Minecraft on the PC with mods and have the experience resembling console MC.
We have been able to achieve this in alll aspects with mods with the one exception that we cannot have individual skins.  By using two separate accounts on one PC,  we should be able to play with unique skins, hence the desire to use your product MultiMC.

**Comment by asiekierka** [comment]
>"The coremod am2.preloader.AM2PreloaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft."

That's not the error.

>[10:45:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: net/ilexiconn/llibrary/server/core/plugin/LLibraryPlugin : Unsupported major.minor version 52.0

That's the error.

>[10:45:37] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_45, running on Windows 8:amd64:6.2, installed at C:\Program Files\Java\jre6

And that's the reason. Please update to Java 8. (Exactly 8; Java 9+ won't do).

**Comment by Mremenar** [comment]
Dear Adrian,
Thank you for the prompt response.
Forge has pretty specific requirements about which version of Java is required for each version of Forge.
My concern is that changing the Java version may cause the game (as my six year old prefers to play it) to become inoperable.
I’m just confused about why the current Java edition works with our current Forge installation and current Minecraft loader but how a different version of Java will fix the issue with MultiMC.
Respectfully, can you help me understand this?

Many thanks
Marc


“Fall seven times; stand up eight.”
—Japanese proverb

**Comment by asiekierka** [comment]
>Forge has pretty specific requirements about which version of Java is required for each version of Forge.

That's not Forge; that's this specific mod (and a bunch of other mods).

>I’m just confused about why the current Java edition works with our current Forge installation and current Minecraft loader but how a different version of Java will fix the issue with MultiMC.

In very short terms:

* Minecraft, as of 1.12, requires Java 8. It did not require Java 8 before.
* Many mods, however, required Java 8 as early as 1.7.10 on their own. This is because it adds many language features which are very handy for software development - including mod development.
* The official Minecraft launcher comes with its own copy of Java 8, since the release of 1.12. As such, it will always use Java 8 for instances running on it.
* MultiMC, however, always relies on the version of Java installed on the user's computer - in this case, it is using Java 6, which is older.

**Comment by Mremenar** [comment]
Thank you, I will give it a try.

“Fall seven times; stand up eight.”
—Japanese proverb

**Comment by Mremenar** [comment]
Dear Adrian,

I installed the latest version of Java (1.8.0_201)
and rebooted my PC.  Multi MC pops up the error titled “No Java version selected” even tho’ it shows that version of Java on its selection window.

The error states “You didn’t select a Java version or selected something that doesn’t work. Multi MC will not be able to start Minecraft. Do you wish to proceed without any Java?
You can change the Java version in the settings later.”

Not sure what to do.

M


“Fall seven times; stand up eight.”
—Japanese proverb

**Comment by darthvader45** [comment]
You need to change the Java version being used by the instance you are running.  Go to 'Edit Instance' and  then down to 'Settings'.  There should be a button that says 'Auto detect'.  Click that and select the Java version with a star by it.  That's the most recent Java according to what's installed.

**Comment by peterix** [comment]
Well, hope this is fixed and you just forgot to close the issue :)
