### ISSUE TITLE
i launch the game and the game crash while charging my server

### ISSUE THREAD

**Issue by Zatzx** [MultiMC/MultiMC5#2577]
log mc 1.12;2 modded https://paste.ee/p/ReO73

**Comment by GeorgeWilson96** [comment]
```
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Float
	at com.github.alexthe666.iceandfire.entity.EntityDeathWorm.getScale(EntityDeathWorm.java:313) ~[EntityDeathWorm.class:?]
	at com.github.alexthe666.iceandfire.entity.EntityDeathWorm.getScaleForAge(EntityDeathWorm.java:317) ~[EntityDeathWorm.class:?]
	at com.github.alexthe666.iceandfire.entity.EntityDeathWorm.func_98054_a(EntityDeathWorm.java:146) ~[EntityDeathWorm.class:?]
	at net.minecraft.entity.EntityAgeable.func_184206_a(EntityAgeable.java:170) ~[vd.class:?]
```
Have you tried removing this Ice and Fire Mod? as it seems to be the source of your error.

**Comment by peterix** [comment]
Mod bug.
