### ISSUE TITLE
Exit Code 255

### ISSUE THREAD

**Issue by chxngeling** [MultiMC/MultiMC5#2593]
System Information
-----------------------------
MultiMC version: 0.6.5- 1234

Operating System: MacOSX

Summary of the issue or suggestion: 
----------------------------------------------
Can't boot the game via multimc.

What should happen:
------------------------------
I should be able to play my modpacks. 

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
I don't know what to say for this. I'm new to modding, and have no idea how to read code.
Suspected cause:
---------------------------
No clue.

Logs/Screenshots:
----------------------------

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: FTBPresentsStoneblock2-1.10.0-1.12.2", -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 843

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code 255.
![Screen Shot 2019-04-08 at 9 25 36 pm](https://user-images.githubusercontent.com/48876407/55721771-8dd16900-5a47-11e9-8e87-6ab9a6344c7b.png)

**Comment by QuImUfu** [comment]
you are seem to be using Java >8 . 
This does not work with modded minecraft. Downgrade to Java 8.

**Comment by stellarspire** [comment]
Hi, I have the same problem yet I downloaded Java 8??
I'm not very skilled with computers and coding so maybe I did something wrong??

**Comment by Heufneutje** [comment]
Please don't necropost an issue that's a year old. You should create a new issue and follow the issue template.
