### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by KuzuCevirme** [MultiMC/MultiMC5#2600]
MultiMC version: latest

Operating System:Win10 Pro

Suspected cause:Probably the Libs 

After the first launch ,few mods requested few libs and i just installed them than its happen

the libs and extra mods after i installed 
-bdlib-1.14.3.12 mc1.12.2
-Binnie+Patcher+1.8
-BrandonsCore-1.12.2-2.4.10.198-universal
-Chamelon-1.12-4.1.3
-Codechickenlib-1.12-3.2.2.353
-forgelin-1.8.9-1.0.0-1.0.0-beta-4584
-ForgeMultipart-2.6.1.81-universal
-Guide api -2.1.8-63
-ichunutil-7.2.1
-mcjtylib-3.1.1
-RebornCore-3.13.12.447
-Teslacorelib-1.0.15
-valkyrielib-2.0.20.1
-Wanionlib-2.2 
---------------------------

Logs/Screenshots:

----------------------------
MultiMC version: 0.6.5-1302

Minecraft folder is:
C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/instances/KuzuCevirme Pack/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_201, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/instances/KuzuCevirme Pack/natives

Libraries:
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2835/forge-1.12.2-14.23.5.2835-universal.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  ae2stuff-0.7.0.4-mc1.12.2
  angelRingToBauble-1.12-0.3.1.50+d4e654e
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv6-stable-6
  Aroma1997Core-1.12.2-2.0.0.2
  Aroma1997s-Dimensional-World-1.12.2-2.0.0.2
  badwithernocookiereloaded-1.12.2-3.3.16
  Baubles-1.12-1.5.2
  bdlib-1.14.3.12-mc1.12.2
  BiblioCraft[v2.4.5][MC1.12.2]
  Binnie+Patcher+1.8
  binnie-mods-1.12.2-2.5.1.188
  BloodMagic-1.12.2-2.4.0-102
  Bookshelf-1.12.2-2.3.577
  Botania+r1.10-361
  BrandonsCore-1.12.2-2.4.10.198-universal
  buildcraft-all-7.99.23
  Chameleon-1.12-4.1.3
  Chisel-MC1.12.2-0.2.1.35
  Clumps-3.1.2
  CodeChickenLib-1.12.2-3.2.2.353-universal
  CoFHCore-1.12.2-4.6.2.25-universal
  CoFHWorld-1.12.2-1.3.0.6-universal
  compactmachines3-1.12.2-3.0.16-b263
  CTM-MC1.12.2-0.3.3.22
  Draconic-Evolution-1.12.2-2.3.21.342-universal
  EnchantingPlus-1.12.2-5.0.176
  EnchantmentDescriptions-1.12.2-1.1.13
  EnderCore-1.12.2-0.5.56
  EnderIO-1.12.2-5.0.43
  EnderStorage-1.12.2-2.4.5.135-universal
  engineers_doors-1.12.2-0.8.0
  Exchangers-1.12.2-2.8
  extrautils2-1.12-1.9.9
  ExtremeReactors-1.12.2-0.4.5.65
  forestry_1.12.2-5.8.1.322
  forgelin-1.8.9-1.0.0-1.0.0-beta-4584
  ForgeMultipart-1.12.2-2.6.1.81-universal
  FTBLib-5.4.1.95
  FTBUtilities-5.4.0.92
  FTBUtilitiesBackups-1.0.0.3
  gendustryjei-1.0.2
  gravestone-1.10.1
  Gravitation+Suite-3.1.0
  gregtech-1.12.2-1.7.0.387
  Guide-API-1.12-2.1.8-63
  Hwyla-1.8.26-B41_1.12.2
  iChunUtil-1.12.2-7.2.1
  ImmersiveCables-1.12.2-1.3.2
  ImmersiveEngineering-0.12-89
  immersivetech-1.12-1.3.10
  industrialcraft-2-2.8.109-ex112
  industrialforegoing-1.12.2-1.12.11-235
  IntegrationForegoing-1.12.2-1.9
  InventoryTweaks-1.63
  ironchest-1.12.2-7.0.59.842
  jei_1.12.2-4.15.0.268
  jeibees-0.9.0.5-mc1.12.2
  journeymap-1.12.2-5.5.4
  JustEnoughEnergistics-1.12.2-1.0.6
  JustEnoughResources-1.12.2-0.8.5.27
  llibrary-1.7.18-1.12.2
  longfallboots-1.2.1b
  MagicBees-1.12.2-3.1.10
  Mantle-1.12-1.3.3.49
  mcjtylib-1.12-3.1.1
  MFFS-1.12.2-4.0.1.0_1.12_cc3a5aa
  morebees-1.12.2-2.0.1
  MouseTweaks-2.10-mc1.12.2
  neiaddons-1.12.14.40-mc1.7.10
  Netherending-Ores-1.12.2-1.3
  Pam's+HarvestCraft+1.12.2zc+The+7mm+Kidney+Stone+Update
  plustic-7.0.5.2
  PortalGun-1.12.2-7.1.0
  railcraft-12.0.0
  reauth-3.6.0
  RebornCore-1.12.2-3.13.12.447-universal
  RedstoneFlux-1.12-2.1.0.6-universal
  refinedstorage-1.6.14
  rftools-1.12-7.61
  secretroomsmod-1.12.2-5.6.4
  simplegenerators-1.12.2-2.0.20.2
  SimplyJetpacks2-1.12.2-2.2.11.64
  StevesCarts-1.12.2-2.4.30.134
  StorageDrawers-1.12.2-5.3.8
  StorageDrawersExtras-1.12-3.1.0
  supersoundmuffler-1.12.2-1.0.2.10
  TConstruct-1.12.2-2.12.0.135
  tesla-core-lib-1.12.2-1.0.15
  Thaumcraft-1.12.2-6.1.BETA26
  thaumicenergistics-2.2.1
  ThaumicJEI-1.12.2-1.5.8-26
  ThaumicTerminal-1.0.10
  thaumictinkerer-1.12.2-5.0-353c71c
  ThermalDynamics-1.12.2-2.5.4.18-universal
  ThermalExpansion-1.12.2-5.5.3.41-universal
  ThermalFoundation-1.12.2-2.6.2.26-universal
  tinkersjei-1.1
  torchmaster_1.12.2-1.7.1.74
  Translocators-1.12.2-2.5.1.77-universal
  twilightforest-1.12.2-3.8.689-universal
  UniDict-1.12.2-2.9.2
  valkyrielib-1.12.2-2.0.20.1
  WanionLib-1.12.2-2.2
  WorldControl-1.0.31
  zerocore-1.12.2-0.1.2.8

Params:
  --username  --version MultiMC5 --gameDir C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/instances/KuzuCevirme Pack/.minecraft --assetsDir C:/Users/KURT/Desktop/mmc-stable-win32/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2000m, -Xmx3000m, -Duser.language=en]

Minecraft process ID: 3404

Using onesix launcher.

[23:39:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:39:57] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:39:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:39:57] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2835 for Minecraft 1.12.2 loading
[23:39:57] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_201, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_201
[23:39:58] [main/INFO] [FML]: Searching C:\Users\KURT\Desktop\mmc-stable-win32\MultiMC\instances\KuzuCevirme Pack\.minecraft\mods for mods
[23:39:58] [main/INFO] [FML]: Searching C:\Users\KURT\Desktop\mmc-stable-win32\MultiMC\instances\KuzuCevirme Pack\.minecraft\mods\1.12.2 for mods
[23:39:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Aroma1997Core-1.12.2-2.0.0.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:39:58] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:39:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Binnie+Patcher+1.8.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:39:58] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\Users\KURT\Desktop\mmc-stable-win32\MultiMC\instances\KuzuCevirme Pack\.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	... 13 more
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	... 13 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2835-universal.jar:?]
	... 13 more
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Runtime.exit(Unknown Source)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.System.exit(Unknown Source)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:39:58] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[23:39:58] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[23:39:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:39:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[23:39:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[23:39:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[23:39:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[23:39:58] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.
Clipboard copy at: 13 Apr 2019 23:40:35 +0300

----------------------------

**Comment by QuImUfu** [comment]
Binnie+Patcher+1.8  
forgelin-1.8.9-1.0.0-1.0.0-beta-4584  
are not for minecraft 1.12.2   
Binnie Patcher should be removed.   
Newer versions of forgelin are available here:  
https://minecraft.curseforge.com/projects/shadowfacts-forgelin

**Comment by KuzuCevirme** [comment]
Thankyou for your answer after i changed these jars it seems okey but when i launch the game there is an error with loading screen 
i think i saw someting about out of memory erro but is not it 3gb of ram enoung to launch the game ? 
right now i am on different computer and i just want to make this modpack not playing yet 

Thankyou.

[crash-2019-04-14_17.35.12-client.txt](https://github.com/MultiMC/MultiMC5/files/3077687/crash-2019-04-14_17.35.12-client.txt)

**Comment by QuImUfu** [comment]
seems like 3GB is not enough.
