### ISSUE TITLE
MultiMC crash

### ISSUE THREAD

**Issue by rafaelf2014** [MultiMC/MultiMC5#2611]
MultiMC version: 0.6.5-1302

Minecraft folder is:
C:/Users/Admin/Desktop/MultiMC/instances/1.12.2/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_201/bin/javaw.exe

Java is version 1.8.0_201, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Admin/Desktop/MultiMC/instances/1.12.2/natives

Libraries:
  C:/Users/Admin/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2825/forge-1.12.2-14.23.5.2825-universal.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/Admin/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/Admin/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  ActuallyAdditions-1.12.2-r146
  Advanced+Solar+Panels-4.3.0
  AdvancedRocketry-1.7.10-1.0.19b
  ae2stuff-0.7.0.4-mc1.12.2
  AE2WTLib-1.12.2-1.0.6 (1)
  AE2WTLib-1.12.2-1.0.6
  AkashicTome-1.2-12
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv6-stable-6
  Aroma1997Core-1.12.2-2.0.0.2
  Aroma1997s-Dimensional-World-1.12.2-2.0.0.2
  astralsorcery-1.12.2-1.10.15
  AutoRegLib-1.3-26
  Avaritia-1.12.2-3.3.0.33-universal
  base-1.12.2-3.12.0
  Baubles-1.12-1.5.2
  bdlib-1.14.3.12-mc1.12.2
  BetterAdvancements-1.12.2-0.1.0.77
  BetterBuildersWands-1.12-0.11.1.245+69d0d70
  binnie-mods-1.7.10-2.0.22.7
  blockcraftery-1.12.2-1.2.0
  Bookshelf-1.12.2-2.3.577
  BrandonsCore-1.12.2-2.4.10.198-universal
  Chameleon-1.12-4.1.3
  Chisel-MC1.12.2-0.2.1.35
  Clumps-3.1.2
  CodeChickenLib-1.12.2-3.2.2.353-universal
  CoFHCore-1.12.2-4.6.2.25-universal
  CoFHWorld-1.12.2-1.3.0.6-universal
  compactmachines3-1.12.2-3.0.17-b267
  CompactSolars-1.12.2-5.0.18.341-universal
  Controlling-3.0.6
  CookingForBlockheads_1.12.2-6.4.70
  CraftTweaker2-1.12-4.1.17
  CTM-MC1.12.2-0.3.3.22
  DankNull-1.12-1.4.46
  DarkUtils-1.12.2-1.8.223
  diethopper-1.1
  Draconic-Evolution-1.12.2-2.3.21.342-universal
  ElecCore-1.12.2-1.9.452
  EnderCore-1.12.2-0.5.57
  EnderIO-1.12.2-5.0.43
  EnderStorage-1.12.2-2.4.5.135-universal
  enderutilities-1.12.2-0.7.12
  environmentaltech-1.12.2-2.0.20.1
  etlunar-1.12.2-2.0.20.1
  ExtraCells-1.12.2-2.6.2a
  extrautils2-1.12-1.9.9
  ExtremeReactors-1.12.2-0.4.5.65
  FastFurnace-1.12.2-1.2.3
  FastLeafDecay-v14
  FastWorkbench-1.12.2-1.6.1
  fluxnetworks-1.12.2-3.0.19-21
  foamfix-0.10.5-1.12.2
  forestry_1.12.2-5.8.1.322
  forgelin-1.8.9-1.0.0-1.0.0-beta-4584
  ForgeMultipart-1.12.2-2.6.1.81-universal
  FTBGuides-1.0.2.33
  FTBLib-5.4.1.96
  FTBUtilities-5.4.0.94
  gendustry-1.6.5.8-mc1.12.2
  Guide-API-1.12-2.1.8-63
  ImmersiveCables-1.12.2-1.3.2
  ImmersiveEngineering-0.12-89
  immersivepetroleum-1.12.2-1.1.9
  industrialcraft-2-2.8.109-ex112
  industrialforegoing-1.12.2-1.12.11-235
  IntegrationForegoing-1.12.2-1.9
  InventoryTweaks-1.63
  IronBackpacks-1.12.2-3.0.8-12
  ironchest-1.12.2-7.0.59.842
  jei_1.12.2-4.15.0.268
  jeiintegration_1.12.2-1.5.1.36
  journeymap-1.12.2-5.5.4
  JustEnoughResources-1.12.2-0.8.5.27
  LibVulpes-1.10.2-0.1.19-universal
  Mantle-1.12-1.3.3.49
  mcjtylib-1.12-3.1.1
  MCMultiPart-2.5.3
  Mekanism-1.12.2-9.7.1.371
  MekanismGenerators-1.12.2-9.7.1.371
  modtweaker-4.0.17
  Morpheus-1.12.2-3.5.106
  Morph-o-Tool-1.2-21
  MouseTweaks-2.10-mc1.12.2
  MrTJPCore-1.12.2-2.1.3.35-universal
  MTLib-3.0.6
  MysticalAgradditions-1.12.2-1.3.1
  MysticalAgriculture-1.12.2-1.7.3
  mysticallib-1.12.2-1.1.1
  natura-1.12.2-4.3.2.66
  NaturesCompass-1.12.2-1.5.1
  NetherPortalFix_1.12.1-5.3.17
  notenoughwands-1.12-1.7.3
  OpenBlocks-1.12.2-1.8.1
  OpenModsLib-1.12.2-0.12.2
  p455w0rdslib-1.12.2-2.1.44
  Pam's+HarvestCraft+1.12.2zc+The+7mm+Kidney+Stone+Update
  Placebo-1.12.2-1.6.0
  ProjectRed-1.12.2-4.9.1.92-Base
  Quark-r1.5-146
  rangedpumps-0.5
  RebornCore-1.12.2-3.13.12.447-universal
  RebornStorage-1.12.2-3.3.2.79
  RedstoneArsenal-1.12.2-2.6.2.17-universal
  RedstoneFlux-1.12-2.1.0.6-universal
  refined_avaritia-1.12.2-2.6
  refinedstorage-1.6.14
  refinedstorageaddons-0.4.4
  rftools-1.12-7.61
  rftoolsctrl-1.12-1.9.3
  ShadowMC-1.12-3.8.0
  Signals-1.12.2-1.4.1-30-universal
  SimplyJetpacks2-1.12.2-2.2.11.64
  Snad-1.12.1-1.7.09.16a
  sonarcore-1.12.2-5.0.19-20
  SoulShardsRespawn-1.12.2-1.1.0-12
  tesla-core-lib-1.12.2-1.0.15
  ThermalCultivation-1.12.2-0.3.2.11-universal
  ThermalDynamics-1.12.2-2.5.4.18-universal
  ThermalExpansion-1.12.2-5.5.3.41-universal
  ThermalFoundation-1.12.2-2.6.2.26-universal
  ThermalInnovation-1.12.2-0.3.2.11-universal
  Traverse-1.12.2-1.6.0-69
  UniDict-1.12.2-2.9.2
  valkyrielib-1.12.2-2.0.20.1
  WanionLib-1.12.2-2.2
  WirelessCraftingTerminal-1.12.2-3.11.88
  xnet-1.12-1.7.6
  Xtones-1.12-1.0.8-11
  zerocore-1.12.2-0.1.2.8

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Admin/Desktop/MultiMC/instances/1.12.2/.minecraft --assetsDir C:/Users/Admin/Desktop/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx6016m, -Duser.language=en]

Minecraft process ID: 15308

Using onesix launcher.

[19:02:35] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:02:35] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:02:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:02:35] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2825 for Minecraft 1.12.2 loading
[19:02:35] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_201, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_201
[19:02:35] [main/INFO] [FML]: Searching C:\Users\Admin\Desktop\MultiMC\instances\1.12.2\.minecraft\mods for mods
[19:02:35] [main/INFO] [FML]: Searching C:\Users\Admin\Desktop\MultiMC\instances\1.12.2\.minecraft\mods\1.12.2 for mods
[19:02:35] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AdvancedRocketry-1.7.10-1.0.19b.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:02:35] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\Users\Admin\Desktop\MultiMC\instances\1.12.2\.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	... 13 more
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	... 13 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2825-universal.jar:?]
	... 13 more
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Runtime.exit(Unknown Source)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.System.exit(Unknown Source)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:02:35] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[19:02:35] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[19:02:35] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[19:02:35] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[19:02:35] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[19:02:35] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[19:02:35] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[19:02:35] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.

**Comment by QuImUfu** [comment]
Those mods are not for 1.12.2:  
AdvancedRocketry-1.7.10-1.0.19b  
binnie-mods-1.7.10-2.0.22.7  
Install the correct versions of these.
