### ISSUE TITLE
 exited with code 1?

### ISSUE THREAD

**Issue by ashylab** [MultiMC/MultiMC5#2613]
MultiMC version: MultiMc 5 version 0.6.5-develop-1308- on win32

 Windows 10 64-bit 

Opening the modpack opens the console and I see process exited with code 1.

I dont know if its the modpack or Multimc but I can launch Stoneblock 2 just fine.

the log 
MultiMC version: 0.6.5-develop-1308

Minecraft folder is:
C:/Users/ashto/Desktop/MultiMC/instances/Awakening-2.28.2-FINAL3-Lite (1)/minecraft

Java path is:
C:/Program Files/AdoptOpenJDK/jdk-8.0.212.03-openj9/jre/bin/javaw.exe

Java is version 1.8.0_212, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/ashto/Desktop/MultiMC/instances/Awakening-2.28.2-FINAL3-Lite (1)/natives

Libraries:
  C:/Users/ashto/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Users/ashto/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1-natives-windows.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/ashto/Desktop/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [1.7.10]ArmorStatusHUD-client-1.28
  [1.7.10]FloatingRuins-universal-1.7.10.r02
  [1.7.10]StatusEffectHUD-client-1.27
  [MC1.7.X]Hearts-2.0.0
  accidentallycircumstantialevents-1.12.11
  ActuallyAdditions-1.7.10-r21
  Additional Compression-1.7.10-3.0
  ae2stuff-rv3-0.5.1.9-mc1.7.10
  AgriCraft-1.7.10-1.5.0
  AIImprovements-1.7.10-0.0.1b19-dev
  AncientTrees-1.7.10-1.6.4
  AOBD-2.9.2
  AOBDsingularities-1.0.4
  AppleCore-mc1.7.10-3.1.1
  appliedenergistics2-rv3-beta-6
  ArchitectureCraft-1.7.2-mc1.7.10
  Armor Overlay 2.0
  Aroma1997Core-1.7.10-1.0.2.16
  AromaBackup-1.7.10-0.1.0.0
  autooredictconv-1.7.10-1.3.1
  Avaritia-1.13
  Avaritiaddons-1.4b
  backpacks 1.7.10 - 3.5.2
  Barkifier_v0.5
  bdlib-1.9.4.109-mc1.7.10
  BetterBoat-1.7.10-1.1.0
  BetterBuildersWands-0.8.1-1.7.10r92+aec06c3
  BetterFps-1.0.1
  BetterLoadingScreen-1.3.10
  BetterSprinting  MC-1.7.10  v1.1.3
  BigDoors-1.7.10-1.1.0
  bigtrees-0.2-1.7.10
  BiomesOPlenty-1.7.10-2.1.0.2027-universal
  BlockProperties-1.7.10-0.1.5
  Bookshelf-1.7.10-1.0.4.187
  Born in a Barn 1.7.x
  Botania r1.8-249
  BrandonsCore-1.0.0.12
  Carpenter's Blocks v3.3.8.1 - MC 1.7.10
  ChanceCubes-1.7.10-2.4.1.182
  ChatFlow-1.1
  ChestTransporter-1.7.10-2.0.6
  Chicken Chunk Patcher 1.1
  Chisel-2.9.5.11
  Chunk Pregenerator V1.7.10-1.8.1
  ChunkPurge-1.7.10-2.1
  ClimateControl-0.8.2
  ClockHUD-1.7.10-1.1
  CodeChickenCore-1.7.10-1.0.7.47-universal
  CoFHCore-[1.7.10]3.1.4-329
  CoFHLib-[1.7.10]1.2.1-185
  compacter-1.2.1.15-mc1.7.10
  compactmachines-1.7.10-1.21
  cookingbook-mc1.7.10-1.0.140
  craftingtweaks-mc1.7.10-1.0.88
  CraftTweaker-1.7.10-3.0.13
  CreativeCore v1.3.24 mc1.7.10
  CustomChestLoot-1.7.10-2.0.1
  CustomMainMenu-MC1.7.10-1.9.2
  D3Core-1.7.10-1.1.2.41
  Damage-Indicators-Mod-1.7.10
  DeathQuotes-1.2.0-mc1.7.10-forge
  Decocraft-2.4.2_1.7.10
  DecorativeStyles-1.7.10-0.0.6
  DefaultWorldGenerator-1.7.10-0.1-b13-universal
  DoomlikeDungeons-1.8.10-MC1.7.10
  Draconic-Evolution-1.7.10-1.0.2h
  Dungeon Mobs v4.1.3
  EnderCore-1.7.10-0.2.0.39_beta
  EnderIO-1.7.10-2.3.0.429_beta
  EnderIOAddons-1.7.10-2.3.0.427_beta-0.10.13.56_beta
  EnderStorage-1.7.10-1.4.7.37-universal
  EternalSingularity-1.7.10-1.0.4b
  ExtraCells-1.7.10-2.3.14b200
  ExtraTiC-1.7.10-1.4.6
  extrautilities-1.2.12
  Farseek-1.7.10-2.0.1
  fastcraft-1.25
  FoodDetails-1.7.10-1.0.0
  Forbidden Magic-1.7.10-0.575
  FpsReducer-1.7.10-1.10.1
  FTBLib-1.7.10-1.0.18.3
  FTBTweaks-1.0.2
  FTBUtilities-1.7.10-1.0.18.3
  gadomancy-1.7.10-1.0.7.3
  GardenStuff-1.7.10-1.7.0
  gearswap-1.2.3
  gemsplus-1.7-mc1.7.10
  generators-0.9.20.123-mc1.7.10
  gud_thaumicnei-1.2.3
  Highlands-1.7.2-v-2.2.3
  HQM-The Journey-4.4.4
  HungerOverhaul-1.7.10-1.0.0.jenkins104
  iChunUtil-4.2.3
  IguanaTinkerTweaks-1.7.10-2.1.6
  ImmersiveEngineering-0.7.7
  immersiveintegration-0.6.8
  Improving Minecraft-1.12.3 for Minecraft 1.7.10
  InfiniBows-1.7.10-universal-coremod-1.3.0.20
  Infini-TiC-1.7.10-0.1.5.DEV.324b697
  InsiderTrading-1.7.10-1.0.2.10
  InventoryTweaks-1.59-dev-156
  ironchest-1.7.10-6.0.62.742-universal
  itlt-1.7.10-0.0.8
  JAPTA-0.7.5
  journeymap-1.7.10-5.1.4p2-unlimited
  JustAnotherSpawner-0.17.8
  KoreSample-1.7.10-1.3.2
  LavaMonsters-1.7.10-2.2.1
  legiblenei_1.7.10-1.6.7.6
  LightTweaks-0.21
  LittleTiles v1.2.0 mc1.7.10
  LLOverlayReloaded-1.0.7-mc1.7.10
  LootBags-1.7.10-2.0.17
  LumySkinPatch
  LunatriusCore-1.7.10-1.1.2.21-universal
  magicalcrops-4.0.0_PUBLIC_BETA_5
  magicalcropsarmoury-4.0.0_PUBLIC_BETA_4
  magicalcropsdeco-4.0.0_PUBLIC_BETA_4a
  Magmaox 1.0 Version 1.7.10
  malisiscore-1.7.10-0.14.3
  malisisdoors-1.7.10-1.13.2
  Mantle-1.7.10-0.3.2b
  mcjtylib-1.8.1
  mdecore-1.0
  Metallurgy-1.7.10-4.0.9.148
  MetallurgyChisel-1.7.10-1.0.0.11
  MetallurgyCore-1.7.10-4.0.5.30
  MineFactoryReloaded-[1.7.10]2.8.1-174
  MiscTweaks-1.7.10-1.0.3
  MobProperties-1.7.10-1.0.2
  Modpack Configuration Checker-1.7.10-v1.5
  ModTweaker2-0.9.6
  Morpheus-1.7.10-1.6.21
  MouseTweaks-2.4.4-mc1.7.10
  mpbasic-1.7.10-1.0.0
  mputils-1.7.10-1.0.8
  mysticalmobs-0.1.1
  MyWorldGen-1.7.10-1.4.1
  neiaddons-1.12.14.40-mc1.7.10
  NEIIntegration-MC1.7.10-1.1.2
  NEIlootbags-1.7.10-1.1.3
  netherportalfix-mc1.7.10-1.1.0
  NightmareCreatures-1.7.10.-2.0.0
  NMA-1.7.10-1.1
  NodalMechanics-1.7-1.0-7
  NonUpdate-AllMCVersion-Final-2.0.1build1-universal
  NotEnoughIDs-1.4.3.4
  NotEnoughItems-1.7.10-1.0.5.120-universal
  NotEnoughKeys-1.7.10-3.0.0b45-dev-universal
  NotEnoughThaumcraftTabs-1.0.2
  NuclearCraft-1.9g--1.7.10
  omlib-1.11.2-3.0.0-100
  OmniOcular-1.7.10-1.0build103
  OpenBlocks-1.7.10-1.6
  OpenModsLib-1.7.10-0.10
  OpenModularTurrets-1.7.10-2.2.11-245
  p455w0rdslib-1.7.10-1.0.4
  Pam's HarvestCraft 1.7.10Lb
  PickBlockPlus-1.7.10-1.1.1
  PortalGun-4.0.0-beta-6-fix-1
  practicalities-1.7.10-0.6.2
  Practical-Logistics-1.7.10-0.2.4
  ProjectE-1.7.10-PE1.10.1
  ProjectRed-1.7.10-4.7.0pre12.95-Base
  ProjectRed-1.7.10-4.7.0pre12.95-Compat
  ProjectRed-1.7.10-4.7.0pre12.95-Integration
  ProjectRed-1.7.10-4.7.0pre12.95-Lighting
  ProjectZulu-1.7.10-1.4c2
  qCraft-1.7.10-1.2.2
  Quadrum-1.7.10-1.2.0.B13-universal
  RandomThings-2.2.4
  ReAuth-3.5.0
  ResourceLoader-MC1.7.10-1.3
  Revamp-1.3.1
  rftools-4.23
  Schematica-1.7.10-1.7.6.131-universal
  sdnf-1.0
  SimplyJetpacks-MC1.7.10-1.5.3
  SonarCore-1.7.10-1.1.3
  SpiceOfLife-mc1.7.10-1.3.11
  sprinklesforvanilla-1.7.10-1.6.0
  StorageDrawers-1.7.10-1.10.9
  Streams-1.7.10-0.3.3
  TabbyChat-1.7.10-1.11.2.2-fml
  Tainted-Magic-r7.82
  tcinventoryscan-mc1.7.10-1.0.11
  TConstruct-1.7.10-1.8.8.build991
  TextureGeneratorLib-1.7.10_vBeta2
  Thaumaturgical Knowledge-0.1.5.2 - 1.7.10
  Thaumcraft-1.7.10-4.2.3.5
  thaumicenergistics-1.1.3.0
  ThaumicEquivalence-1.7.10-1.0.4
  Thaumic-Exploration-[1.7.10] 1.1.73-0
  ThermalExpansion-[1.7.10]4.1.5-248
  ThermalFoundation-[1.7.10]1.2.6-118
  ThermalSingularities-1.7.10-1.2
  TiConAutoToolStation-1.7.10-1.1.2
  TiCTooltips-mc1.7.10-1.2.5
  Translocator-1.7.10-1.1.2.16-universal
  TravellersGear-1.7.10-1.16.6
  True Invisibility - 0.1.0
  UBCOres-1.7.10-0.2.9.4
  UndergroundBiomesConstructs-1.7.10-0.8-beta49
  underphangables-1.7.10-1.0.1
  UniDict-1.7.10-2.9.2
  Universal Singularities [Version 8]-1.7.10
  vending-v1.2.3
  ViewEMC-1.7.10-v4
  VillagerMetaFix-0.3
  Waila-1.5.10_1.7.10
  waila-blacklist-1.7.10-0.1
  WailaEvents-1.0.0
  WAILA-features-1.7.10-0.1.0
  WailaHarvestability-mc1.7.10-1.1.6
  WAILAPlugins-MC1.7.10-0.2.0-25
  WallpaperCraft-1.7.10-1.03
  WanionLib-1.7.10-1.8
  waterhooks-1.2.1
  Wawla-1.0.5.120
  webshooter-1.7.10-1.0.0
  WirelessCraftingTerminal-1.7.10-rv3-1.8.7.9b
  WitchingGadgets-1.7.10-1.1.10
  WR-CBE-1.7.10-1.4.1.9-universal
  WTFCaveBiomes-1.7.10_v1.6
  WTFCore-1.7.10_v1.7
  WTFOres-1.7.10v1.5
  Ztones-1.7.10-2.2.1

Params:
  --username  --version MultiMC5 --gameDir C:/Users/ashto/Desktop/MultiMC/instances/Awakening-2.28.2-FINAL3-Lite (1)/minecraft --assetsDir C:/Users/ashto/Desktop/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:+UseG1GC, -Dsun.rmi.dgc.server.gcInterval=2147483646, -XX:+UnlockExperimentalVMOptions, -XX:G1NewSizePercent=24, -XX:G1ReservePercent=22, -XX:MaxGCPauseMillis=50, -XX:G1HeapRegionSize=32M, -XX:+UseStringDeduplication, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms502m, -Xmx5024m, -Duser.language=en]

Minecraft process ID: 6092

Using onesix launcher.

[04:12:50] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[04:12:50] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[04:12:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[04:12:50] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[04:12:50] [main/INFO] [FML]: Java is Eclipse OpenJ9 VM, version 1.8.0_212, running on Windows 10:amd64:10.0, installed at C:\Program Files\AdoptOpenJDK\jdk-8.0.212.03-openj9\jre
[04:12:50] [main/INFO] [FML]: [AppEng] Core Init
[04:12:50] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:12:50] [main/INFO] [FML]: Loading tweaker me.guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.0.1.jar
[04:12:50] [main/WARN] [FML]: The coremod com.chocohead.biab.BornInABarn does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:12:50] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:12:51] [main/INFO] [STDERR]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of CodeChickenLib, 1.1.3.140 is newer than request 1.1.3.138
[04:12:51] [main/INFO] [STDERR]: [codechicken.core.launch.DepLoader$DepLoadInst:checkExisting:436]: Warning: version of bspkrsCore, 6.16 is newer than request 6.15
[04:12:51] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:12:51] [main/WARN] [FML]: The coremod farseek.core.FarseekCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:12:51] [main/INFO] [FML]: Loading tweaker fastcraft.Tweaker from fastcraft-1.25.jar
[04:12:51] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:12:51] [main/WARN] [FML]: The coremod makeo.gadomancy.coremod.GadomancyCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:12:51] [main/WARN] [FML]: The coremod net.doubledoordev.insidertrading.asm.AsmCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:12:51] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:12:51] [main/WARN] [FML]: The coremod net.thecondemned.LumySkinPatch.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:12:51] [main/WARN] [FML]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:12:51] [main/WARN] [FML]: The coremod mrtjp.core.handler.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:12:51] [main/INFO] [NonUpdate]: Load file: nu-whitelist.txt
[04:12:51] [main/INFO] [NonUpdate]: minecraft.net
[04:12:51] [main/INFO] [NonUpdate]: mojang.com
java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137)
	at nonupdate.forge.NonUpdate.<clinit>(NonUpdate.java:85)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:89)
	at java.lang.Class.forName(Class.java:419)
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: java.lang.Class#getDeclaredFields0
	at nonupdate.forge.ReflectionHelper.getMethod(ReflectionHelper.java:105)
	at nonupdate.forge.ReflectionHelper.resetReflection(ReflectionHelper.java:37)
	at nonupdate.forge.ReflectionHelper.<clinit>(ReflectionHelper.java:12)
	... 21 more
Caused by: java.lang.NoSuchMethodException: java.lang.Class#getDeclaredFields0
	... 24 more
[04:12:51] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at C:\Users\ashto\Desktop\MultiMC\instances\Awakening-2.28.2-FINAL3-Lite (1)\minecraft for Forge Mod Loader
java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148) ~[?:1.8.0_212]
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137) ~[?:1.8.0_212]
	at nonupdate.forge.NonUpdate.<clinit>(NonUpdate.java:85) ~[NonUpdate-AllMCVersion-Final-2.0.1build1-universal.jar:?]
	at sun.misc.Unsafe.ensureClassInitialized(Native Method) ~[?:1.8.0_212]
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:89) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:419) ~[?:1.8.0_212]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: java.lang.Class#getDeclaredFields0
	at nonupdate.forge.ReflectionHelper.getMethod(ReflectionHelper.java:105) ~[ReflectionHelper.class:?]
	at nonupdate.forge.ReflectionHelper.resetReflection(ReflectionHelper.java:37) ~[ReflectionHelper.class:?]
	at nonupdate.forge.ReflectionHelper.<clinit>(ReflectionHelper.java:12) ~[ReflectionHelper.class:?]
	... 21 more
Caused by: java.lang.NoSuchMethodException: java.lang.Class#getDeclaredFields0
	at nonupdate.forge.ReflectionHelper.getMethod(ReflectionHelper.java:105) ~[ReflectionHelper.class:?]
	at nonupdate.forge.ReflectionHelper.resetReflection(ReflectionHelper.java:37) ~[ReflectionHelper.class:?]
	at nonupdate.forge.ReflectionHelper.<clinit>(ReflectionHelper.java:12) ~[ReflectionHelper.class:?]
	... 21 more
[04:12:51] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137)
	at nonupdate.forge.NonUpdate.<clinit>(NonUpdate.java:85)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:89)
	at java.lang.Class.forName(Class.java:419)
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: java.lang.Class#getDeclaredFields0
	at nonupdate.forge.ReflectionHelper.getMethod(ReflectionHelper.java:105)
	at nonupdate.forge.ReflectionHelper.resetReflection(ReflectionHelper.java:37)
	at nonupdate.forge.ReflectionHelper.<clinit>(ReflectionHelper.java:12)
	... 21 more
Caused by: java.lang.NoSuchMethodException: java.lang.Class#getDeclaredFields0
	... 24 more
[04:12:51] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 5
	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:344)
	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Process exited with code 1.

sorry if its already a solved one but I have no experience in this

**Comment by Heufneutje** [comment]
Have you tried updating Forge and/or the mods you're using?

**Comment by ashylab** [comment]
sorry but can you tell me how to do that?
