### ISSUE TITLE
Failure to launch selected instance.

### ISSUE THREAD

**Issue by Dr-Dobbs** [MultiMC/MultiMC5#2619]
System Information
-----------------------------
MultiMC version:
Version 0.6.5-1217

Operating System:
Ubuntu Disco Dingo 19.04

Summary of the issue or suggestion:
----------------------------------------------
Failure to launch Minecraft instance

What should happen:
------------------------------
The MineCraft should go through the startup stages, and give the option to look for servers.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Select Instance

2.Click "launch"

Suspected cause:
---------------------------
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
"Unable to init SSL content"

Additional Info:
---------------------------
```
MultiMC version: 0.6.5-1217


Minecraft folder is:
/home/rjnorton/.local/share/multimc/instances/Enigmatica2-1.59/minecraft


Java path is:
/usr/lib/jvm/java-11-openjdk-amd64/bin/java


Java is version 11.0.3, using 64-bit architecture.


Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)

Subsystem: ASUSTeK Computer Inc. Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller

Kernel driver in use: i915

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/rjnorton/.local/share/multimc/instances/Enigmatica2-1.59/natives

Libraries:
  /home/rjnorton/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/rjnorton/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/rjnorton/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/rjnorton/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/rjnorton/.local/share/multimc/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /home/rjnorton/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/rjnorton/.local/share/multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/rjnorton/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/rjnorton/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/rjnorton/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/rjnorton/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/rjnorton/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/rjnorton/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/rjnorton/.local/share/multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/rjnorton/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/rjnorton/.local/share/multimc/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /home/rjnorton/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/rjnorton/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/rjnorton/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/rjnorton/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/rjnorton/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/rjnorton/.local/share/multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /home/rjnorton/.local/share/multimc/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /home/rjnorton/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/rjnorton/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/rjnorton/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/rjnorton/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/rjnorton/.local/share/multimc/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /home/rjnorton/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /home/rjnorton/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /home/rjnorton/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /home/rjnorton/.local/share/multimc/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2781/forge-1.12.2-14.23.5.2781-universal.jar
  /home/rjnorton/.local/share/multimc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /home/rjnorton/.local/share/multimc/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  /home/rjnorton/.local/share/multimc/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  /home/rjnorton/.local/share/multimc/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /home/rjnorton/.local/share/multimc/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /home/rjnorton/.local/share/multimc/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /home/rjnorton/.local/share/multimc/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /home/rjnorton/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /home/rjnorton/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /home/rjnorton/.local/share/multimc/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /home/rjnorton/.local/share/multimc/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /home/rjnorton/.local/share/multimc/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /home/rjnorton/.local/share/multimc/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /home/rjnorton/.local/share/multimc/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /home/rjnorton/.local/share/multimc/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /home/rjnorton/.local/share/multimc/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /home/rjnorton/.local/share/multimc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/rjnorton/.local/share/multimc/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  /home/rjnorton/.local/share/multimc/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /home/rjnorton/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/rjnorton/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar
  /home/rjnorton/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar

Mods:
  ActuallyAdditions-1.12.2-r145
  ActuallyBaubles-1.12-1.1
  AdvancedRocketry-1.12.2-1.5.0-128-universal
  ae2stuff-0.7.0.4-mc1.12.2
  AE2WTLib-1.12.2-1.0.6
  AIImprovements-1.12-0.0.1b3
  AkashicTome-1.2-12
  ancientwarfare-1.12.2-2.7.0.574
  animania-1.12.2-1.6.2
  AppleCore-mc1.12.2-3.1.4
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv6-stable-6
  architecturecraft-1.12-3.80
  astralsorcery-1.12.2-1.10.11
  AutoRegLib-1.3-24
  backpack-3.0.2-1.12.2
  badwithernocookiereloaded-1.12.2-3.3.16
  Baubles-1.12-1.5.2
  bdlib-1.14.3.12-mc1.12.2
  BetterAdvancements-1.12.2-0.0.17.74
  BetterBuildersWands-1.12.2-0.13.0.267+dc89c58
  BetterFps-1.4.8
  BetterQuesting-3.5.291
  BiblioCraft[v2.4.5][MC1.12.2]
  binnie-mods-1.12.2-2.5.1.186
  BiomesOPlenty-1.12.2-7.0.1.2425-universal
  blockcraftery-1.12.2-1.1.0
  blockdrops-1.12.2-1.4.0
  BloodMagic-1.12.2-2.4.0-102
  Bookshelf-1.12.2-2.3.574
  Botania r1.10-359
  BrandonsCore-1.12.2-2.4.9.195-universal
  BuildingGadgets-2.6.3
  capabilityadapter-1.0.1
  careerbees-0.4.0
  CarryOn MC1.12.2 v1.12.1
  cc-tweaked-1.80pr1.14
  Chameleon-1.12-4.1.3
  Chisel-MC1.12.2-0.2.1.35
  chiselsandbits-14.30
  Chunk Pregenerator V1.12-2.0
  Clumps-3.1.2
  CodeChickenLib-1.12.2-3.2.2.353-universal
  CoFHCore-1.12.2-4.6.2.25-universal
  CoFHWorld-1.12.2-1.3.0.6-universal
  colytra-1.12.2-1.1.0.3
  CommonCapabilities-1.12.2-2.0.2
  compactmachines3-1.12.2-3.0.13-b236
  conarm-1.12.2-1.2.3
  Controlling-3.0.6
  CookingForBlockheads_1.12.2-6.4.69
  CosmeticArmorReworked-1.12.2-v4
  CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
  CraftTweaker2-1.12-4.1.14
  CTM-MC1.12.2-0.3.3.22
  CustomBackgrounds-MC1.12-1.1.1
  CustomMainMenu-MC1.12.2-2.0.9
  Cyclic-1.12.2-1.17.16
  CyclopsCore-1.12.2-1.0.3
  DankNull-1.12-1.4.43
  DarkUtils-1.12.2-1.8.223
  DefaultOptions_1.12.2-9.2.8
  demagnetize-1.12.2-1.0.1
  diethopper-1.1
  Ding-1.12.1-1.0.1
  dirt2path-1.8.0
  DiscordSuite-2.2.4
  Draconic-Evolution-1.12.2-2.3.18.329-universal
  EmbersRekindled-1.12
  EnderCore-1.12.2-0.5.45
  EnderIO-1.12.2-5.0.40
  EnderStorage-1.12.2-2.4.5.135-universal
  engineers_doors-1.12.2-0.8.0
  environmentalmaterials-1.12.2-1.0.19.1
  environmentaltech-1.12.2-2.0.19.1
  Exchangers-1.12.2-2.8
  ExtraBitManipulation-1.12.2-3.4.1
  ExtraCells-1.12.2-2.6.2a
  ExtraRails-1.12-1.3.0
  extrautils2-1.12-1.9.8
  ExtremeReactors-1.12.2-0.4.5.50
  FarmingForBlockheads_1.12.2-3.1.26
  Farseek-1.12-2.3.1
  FastFurnace-1.12.2-1.2.1
  FastWorkbench-1.12.2-1.6.0
  fencejumper-1.12-1.0.5
  flatcoloredblocks-mc1.12-6.7
  foamfix-0.10.3-1.12.2
  forestry_1.12.2-5.8.2.382
  Forgelin-1.8.2
  FpsReducer-mc1.12.2-1.10.3
  FTBLib-5.4.1.76
  FTBUtilities-5.3.0.73
  funky-locomotion-1.12.2-1.1.2
  GardenStuff-1.12-2.1.1
  gendustry-1.6.5.8-mc1.12.2
  gendustryjei-1.0.2
  generators-0.9.20.12-mc1.12.2
  grassburner-0.1.0
  Guide-API-1.12-2.1.8-63
  HorseTweaks_1.12.2-1.0.4
  Hwyla-1.8.26-B41_1.12.2
  ImmersiveEngineering-0.12-88
  immersivepetroleum-1.12.2-1.1.9
  immersivetech-1.12-1.3.10
  industrialcraft-2-2.8.111-ex112
  industrialforegoing-1.12.2-1.12.5-229
  IntegratedDynamics-1.12.2-1.0.4
  IntegratedTunnels-1.12.2-1.6.5
  IntegrationForegoing-1.12.2-1.8.2
  InventoryTweaks-1.64+dev.146
  IronBackpacks-1.12.2-3.0.8-12
  ironchest-1.12.2-7.0.59.842
  IvToolkit-1.3.3-1.12
  JAOPCA-1.12.2-2.2.8.100
  JEHC-1.12.2-1.6.2.0
  jei_1.12.2-4.14.4.264
  jeibees-0.9.0.5-mc1.12.2
  jeivillagers-1.12-1.0.2
  jepb-1.12-1.2.1
  jetif-1.12.2-1.3.0
  journeymap-1.12.2-5.5.3
  JustEnoughEnergistics-1.12.2-1.0.6
  JustEnoughPetroleum-0.1
  JustEnoughReactors-1.12.2-1.1.1.47
  JustEnoughResources-1.12.2-0.8.10.50
  KleeSlabs_1.12.2-5.4.11
  librarianlib-1.12.2-4.15
  LibVulpes-1.12.2-0.4.0-51-universal
  lostcities-1.12-2.0.14
  LunatriusCore-1.12.2-1.2.0.42-universal
  MagicBees-1.12.2-3.1.10
  malisiscore-1.12.2-6.4.0
  malisisdoors-1.12.2-7.3.0
  Mantle-1.12-1.3.3.42
  mcjtylib-1.12-3.1.1
  MCMultiPart-2.5.3
  meecreeps-1.12-1.2.3
  Mekanism-1.12.2-9.4.13.349
  MekanismGenerators-1.12.2-9.4.13.349
  MekanismTools-1.12.2-9.4.13.349
  MemoryTester-0.3.3
  minecolonies-1.12.2-0.10.68-RELEASE-universal
  modtweaker-4.0.16
  modular-routers-1.12.2-3.2.1
  moreoverlays-1.14-mc1.12.2
  Morph-o-Tool-1.2-21
  MouseTweaks-2.10-mc1.12.2
  MTLib-3.0.5
  mysticallib-1.12.2-1.0.0
  natura-1.12.2-4.3.2.66
  NaturesCompass-1.12.2-1.5.1
  Neat 1.4-17
  NoMobSpawningOnTrees-1.2.2-mc1.12.2
  NoNVFlash-1.12.2-1.2.0.3-universal
  NotEnoughIDs-1.5.4.3
  notenoughwands-1.12-1.7.2
  NuclearCraft-2.13e--1.12.2
  Nutrition-1.12.2-4.0.0
  OldJavaWarning-1.12.2-1.0.9
  OpenBlocks-1.12.2-1.8
  OpenComputers-MC1.12.2-1.7.4.153
  OpenModsLib-1.12.2-0.12.1
  OreExcavation-1.4.133
  p455w0rdslib-1.12.2-2.0.36
  Pam's HarvestCraft 1.12.2zb
  Patchouli-1.0-16
  Placebo-1.12.2-1.5.1
  playersdropheads-1.12.x-1.1.0
  plustic-7.0.4.0
  pneumaticcraft-repressurized-1.12.2-0.9.1-317
  PrettyBeaches_1.12.2-1.0.4
  ProjectIntelligence-1.12.2-1.0.2.13-universal
  Psi-r1.1-70
  Quark-r1.5-145
  questbook-3.1.EXP_NET2-1.12
  QuickLeafDecay-MC1.12.1-1.2.4
  randompatches-1.12.2-1.13.0.1
  reauth-3.6.0
  RecurrentComplex-1.4.7
  RedstoneArsenal-1.12.2-2.6.2.17-universal
  RedstoneFlux-1.12-2.1.0.6-universal
  ResourceLoader-MC1.12.1-1.5.3
  rftools-1.12-7.60
  rftoolsctrl-1.12-1.9.3
  rftoolsdim-1.12-5.64
  roots-2-0.104
  rustic-1.1.0
  Scannable-MC1.12.2-1.6.3.24
  Schematica-1.12.2-1.8.0.169-universal
  ShadowMC-1.12-3.8.0
  solcarrot-1.12.2-1.3.3
  StandardExpansion-3.4.151
  stg-1.12.2-1.2.3
  StorageDrawers-1.12.2-5.3.8
  Streams-1.12-0.4.4
  supersoundmuffler-1.12.2-1.0.2.10
  TConstruct-1.12.2-2.12.0.115
  Tesla-1.12.2-1.0.63
  tesla-core-lib-1.12.2-1.0.15
  Thaumcraft-1.12.2-6.1.BETA26
  ThaumicInventoryScanning_1.12.2-2.0.10
  ThaumicJEI-1.12.2-1.5.5-23
  thaumictinkerer-1.12.2-5.0-353c71c
  ThermalCultivation-1.12.2-0.3.2.11-universal
  ThermalDynamics-1.12.2-2.5.4.18-universal
  ThermalExpansion-1.12.2-5.5.3.41-universal
  ThermalFoundation-1.12.2-2.6.2.26-universal
  ThermalInnovation-1.12.2-0.3.2.11-universal
  TinkerToolLeveling-1.12.2-1.1.0
  Tips-1.12.2-1.0.6
  TipTheScales-1.12.2-1.0.3
  Toast Control-1.12.2-1.8.0
  TombManyGraves-1.12-4.2.0
  torchmaster_1.12.2-1.7.1.74
  torohealth-1.12.2-11
  twilightforest-1.12.2-3.8.689-universal
  UniDict-1.12.2-2.9.2
  UnlimitedChiselWorks-0.2.0
  unloader-1.2.0
  valkyrielib-1.12.2-2.0.19.1
  villager-market-1.12.2-1.0.0
  WanionLib-1.12.2-2.2
  Wawla-1.12.2-2.5.270
  WirelessCraftingTerminal-1.12.2-3.11.88
  wizardry-0.9.9
  WrapUp-1.12-1.1.3
  xnet-1.12-1.7.6
  YNot-0.2.3
  zerocore-1.12-0.1.2.3

Params:
  --username  --version MultiMC5 --gameDir /home/rjnorton/.local/share/multimc/instances/Enigmatica2-1.59/minecraft --assetsDir /home/rjnorton/.local/share/multimc/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 1024 x 768

Java Arguments:
[-Xms1024m, -Xmx10112m, -Duser.language=en]


Minecraft process ID: 12752


Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code 255.
MultiMC: Log upload triggered at: 22 Apr 2019 18:04:29 -0500
MultiMC: Log upload failed!
MultiMC: Log upload triggered at: 22 Apr 2019 18:05:15 -0500
MultiMC: Log upload failed!
Clipboard copy at: 22 Apr 2019 18:05:34 -0500
```

**Comment by Heufneutje** [comment]
Use Java 8. Java 11 does not work with modded Minecraft until 1.13.

**Comment by Dr-Dobbs** [comment]
Thank you for your advice.  I have installed Java 8u211 in its own folder on my Ubuntu 19.04 machine.  I have clicked on the MultiMC "settings" button, chosen the "Java" topic, and navigated to the Java executable at "/usr/lib/jvm/java-8u211/jdk1.8.0_211/bin/java".  I press the "Test" button, and it shows Success.  
"Java test succeeded!
Platform reported: amd64
Java version reported: 1.8.0_211"
I then had to edit the instance file to match the new Java location.  Launch seems okay so far!
Thank you very much.

**Comment by Dr-Dobbs** [comment]
Oh, so close!  The MineCraft launch went all the way through and I was able to click on select a multiplayer server.  I chose the proper server, that I have been using for weeks.  Then I get this message:
![image](https://user-images.githubusercontent.com/5567339/56608457-6c888500-65d0-11e9-97af-b35b4f78c642.png)
Any further advice?

**Comment by SapuSeven** [comment]
Make sure you launch the game in online mode.

**Comment by sigma-1402** [comment]
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
I'm trying to launch 1.12.2 with Java 21 and Forge, but it shows this message
