### ISSUE TITLE
Erro somente no multimc launch mojang normal

### ISSUE THREAD

**Issue by heliomoreno** [MultiMC/MultiMC5#2622]
```
MultiMC version: 0.6.5-1302


Minecraft folder is:
C:/jogos/MultiMC/instances/1.12.2/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


O Java é da versão 1.8.0_201, usando arquitetura de 64-bits


Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/jogos/MultiMC/instances/1.12.2/natives

Libraries:
  C:/jogos/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/jogos/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/jogos/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/jogos/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/jogos/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/jogos/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/jogos/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/jogos/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/jogos/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/jogos/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/jogos/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/jogos/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/jogos/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/jogos/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/jogos/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/jogos/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/jogos/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/jogos/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/jogos/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/jogos/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/jogos/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/jogos/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/jogos/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/jogos/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/jogos/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/jogos/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/jogos/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/jogos/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/jogos/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/jogos/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/jogos/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/jogos/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/jogos/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/jogos/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/jogos/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/jogos/MultiMC/instances/1.12.2/.minecraft --assetsDir C:/jogos/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


ID do Processo do Minecraft: 9224


Using onesix launcher.

[21:41:28] [Client thread/INFO]: Setting user: heliomoreno
[21:41:42] [Client thread/INFO]: LWJGL Version: 2.9.4
[21:41:43] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at bib.at(SourceFile:622) [minecraft-1.12.2-client.jar:?]
	at bib.aq(SourceFile:458) [minecraft-1.12.2-client.jar:?]
	at bib.a(SourceFile:404) [minecraft-1.12.2-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [minecraft-1.12.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 4/23/19 9:41 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bib.at(SourceFile:635)
	at bib.aq(SourceFile:458)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bib.at(SourceFile:635)
	at bib.aq(SourceFile:458)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 428615576 bytes (408 MB) / 514850816 bytes (491 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\jogos\MultiMC\instances\1.12.2\.minecraft\crash-reports\crash-2019-04-23_21.41.44-client.txt
Minecraft foi fechado com o código de saída -1.
```

**Comment by QuImUfu** [comment]
You are likely using an unsupported Intel iGPU. See:  
https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs
