### ISSUE TITLE
1.6 snapshots up 13w23b fail to start because of window size options

### ISSUE THREAD

**Issue by peterix** [MultiMC/MultiMC5#2638]
Log:
```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: joptsimple.UnrecognizedOptionException: 'version' is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:89)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:493)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:433)
	at net.minecraft.client.main.Main.main(SourceFile:35)
	... 8 more
Exiting with -1
```

Long live the legacy support.

**Comment by peterix** [comment]
- [ ] Determine when were the various options added, and what flags are needed to launch the versions correctly.

**Comment by Scotsguy** [comment]
13w22a fails when setting a window size, but works fine when not.
Stacktrace:
```java
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: joptsimple.UnrecognizedOptionException: 'width' is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:89)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:445)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:54)
	at joptsimple.OptionParser.parse(OptionParser.java:385)
	at net.minecraft.client.main.Main.main(SourceFile:35)
	... 8 more
Exiting with -1
```
