### ISSUE TITLE
Process exited with code 1.

### ISSUE THREAD

**Issue by LabgrownLorax** [MultiMC/MultiMC5#2648]
System Information
-----------------------------
MultiMC version: MultiMC 5

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
Instance won't boot up minecraft launcher.

What should happen:
------------------------------
Boot up minecraft launcher

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.5-1302

Minecraft folder is:
C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/instances/New Hole/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_201, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/instances/New Hole/natives

Libraries:
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2768/forge-1.12.2-14.23.5.2768-universal.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  Apotheosis-1.12.2-1.10.0
  AppleCore-mc1.12.2-3.2.0
  AppleSkin-mc1.12-1.0.9
  Artifacts-1.12.2-1.1.0
  Baubles-1.12-1.5.2 (1)
  BetterFoliage-MC1.12-2.2.0
  BetterFps-1.4.8
  BiomesOPlenty-1.12.2-7.0.1.2438-universal
  blockcraftery-1.12.2-1.2.0
  bonsaitrees-1.1.2-b144
  Bountiful-2.2.0
  CarryOn+MC1.12.2+v1.12.1
  Cathedral-1.12.2-1.9.7k
  Chameleon-1.12-4.1.3
  Chisel-MC1.12.2-0.2.1.35
  chiselsandbits-14.32
  comforts-1.12.2-1.4.1.2
  Controlling-3.0.6
  cosmeticbeds-1.12.2-1.0.2.2
  CreativeCore_v1.9.45_mc1.12.2
  CTM-MC1.12.2-0.3.3.22
  dirt2path-1.8.0
  DynamicLights-1.12.2
  Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2
  fairylights-2.1.6-1.12.2
  FamiliarFauna-1.12.2-1.0.11
  FastFurnace-1.12.2-1.3.1
  FastWorkbench-1.12.2-1.7.1
  foamfix-0.10.5-1.12.2
  hopperducts-mc1.12-1.5
  Hwyla-1.8.26-B41_1.12.2
  Inspirations-1.12.2-0.2.4
  InventoryTweaks-1.64+dev.146
  jei_1.12.2-4.15.0.278
  journeymap-1.12.2-5.5.4
  JustEnoughResources-1.12.2-0.8.9.48
  LittleTiles_v1.5.0-pre135_mc1.12.2
  lostquiver-1.0
  Magical+Map-1.12.2-3.3.2
  Mantle-1.12-1.3.3.49
  Morpheus-1.12.2-3.5.106
  MouseTweaks-2.10-mc1.12.2
  NaturesAura-r17
  NetherPortalFix_1.12.1-5.3.17
  NoMoreRecipeConflict-0.13(1.12.2)
  OpenBlocks-1.12.2-1.8.1
  OpenModsLib-1.12.2-0.12.2
  Patchouli-1.0-19
  PotionCore-1.6_for_1.12.2
  QuarkOddities-1.12.2
  Quark-r1.5-146
  QuickLeafDecay-MC1.12.1-1.2.4
  roots-2-0.104
  SaltyMod-1.12.2-1.12.6.0
  SeedsForWizardry+1.0+For+MC+Forge+1.12.2
  stg-1.12.2-1.2.3
  StorageDrawers-1.12.2-5.3.8
  StorageDrawersExtras-1.12-3.1.0
  TConstruct-1.12.2-2.12.0.135
  TreeChopper-1.12.2-1.2.4
  twilightforest-1.12.2-3.8.689-universal
  WaterStrainer-1.12-3.2.0
  WearableBackpacks-1.12.2-3.1.3

Params:
  --username  --version MultiMC5 --gameDir C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/instances/New Hole/.minecraft --assetsDir C:/Users/tamcd/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4224m, -Duser.language=en]

Minecraft process ID: 23432

Using onesix launcher.

[21:52:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:52:23] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:52:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:52:23] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2768 for Minecraft 1.12.2 loading
[21:52:23] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_201, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_201
[21:52:23] [main/INFO] [FML]: Searching C:\Users\tamcd\Downloads\mmc-stable-win32\MultiMC\instances\New Hole\.minecraft\mods for mods
[21:52:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Apotheosis-1.12.2-1.10.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:52:23] [main/WARN] [FML]: The coremod ApotheosisCore (shadows.ApotheosisCore) is not signed!
[21:52:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:52:23] [main/WARN] [FML]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[21:52:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in BetterFoliage-MC1.12-2.2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:52:23] [main/WARN] [FML]: The coremod BetterFoliageLoader (mods.betterfoliage.loader.BetterFoliageLoader) is not signed!
[21:52:23] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[21:52:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CreativeCore_v1.9.45_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:52:23] [main/WARN] [FML]: The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:52:23] [main/WARN] [FML]: The coremod CreativePatchingLoader (com.creativemd.creativecore.core.CreativePatchingLoader) is not signed!
[21:52:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.3.22.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:52:23] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:52:23] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[21:52:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in DynamicLights-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:52:23] [main/WARN] [FML]: The coremod atomicstryker.dynamiclights.common.DLFMLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:52:23] [main/WARN] [FML]: The coremod DLFMLCorePlugin (atomicstryker.dynamiclights.common.DLFMLCorePlugin) is not signed!
[21:52:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.5-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:52:23] [main/WARN] [FML]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:52:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.64+dev.146.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:52:23] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:52:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in LittleTiles_v1.5.0-pre135_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:52:23] [main/WARN] [FML]: The coremod com.creativemd.littletiles.LittlePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:52:23] [main/WARN] [FML]: The coremod LittlePatchingLoader (com.creativemd.littletiles.LittlePatchingLoader) is not signed!
[21:52:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.12.2-0.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:52:23] [main/WARN] [FML]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:52:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.5-146.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:52:23] [main/WARN] [FML]: The coremod vazkii.quark.base.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:52:23] [main/WARN] [FML]: The coremod LoadingPlugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[21:52:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:52:23] [main/INFO] [LaunchWrapper]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[21:52:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:52:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:52:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:52:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:52:25] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[21:52:25] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[21:52:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:52:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:52:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:52:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:52:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:52:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:52:25] [main/INFO] [LaunchWrapper]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
[21:52:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:52:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:52:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:52:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:52:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:52:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.lang.NoClassDefFoundError: kotlin/reflect/KDeclarationContainer
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at mods.betterfoliage.loader.Refs.<clinit>(Refs.kt:13)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at mods.betterfoliage.loader.BetterFoliageTransformer.<init>(BetterFoliageCore.kt:13)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Class.newInstance(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at $wrapper.mods.betterfoliage.loader.BetterFoliageTransformer.<init>(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Class.newInstance(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:131)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:52:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[21:52:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: kotlin.reflect.KDeclarationContainer
[21:52:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[21:52:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 26 more
[21:52:25] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[21:52:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[21:52:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[21:52:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[21:52:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.
MultiMC: Log upload triggered at: 09 May 2019 21:55:50 -0500
MultiMC: Log uploaded to: https://paste.ee/p/nThqJ
Clipboard copy at: 09 May 2019 22:04:32 -0500
Clipboard copy at: 09 May 2019 22:12:59 -0500

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
you are missing https://minecraft.curseforge.com/projects/shadowfacts-forgelin .
Install it.
