### ISSUE TITLE
process ended with code -1

### ISSUE THREAD

**Issue by ziggeop** [MultiMC/MultiMC5#2659]
System Information
-----------------------------
MultiMC version: 0.6.5-1302 on win32

Operating System: windows 10 64 bit

Summary of the issue or suggestion: crashing when trying to launch
----------------------------------------------

What should happen: game should lauch, only 1 mod installed of my knowledge
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.latest version of fabric loader and latest version of multi mc

2. download voxelmaps latest version and install it in multimc

3.attempt to launch then crash

Suspected cause:
---------------------------
might be different bits (32-64) or a java issue (although i checked and both multimc and java were on the same version)

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.5-1302

Minecraft folder is:
C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/instances/going/.minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_211, using 32-bit architecture.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/instances/going/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/com/mojang/realms/1.14.15/realms-1.14.15.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/net/fabricmc/fabric-loader/0.4.7+build.147/fabric-loader-0.4.7+build.147.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/net/fabricmc/yarn/1.14.1+build.10/yarn-1.14.1+build.10.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.1.1.8/tiny-mappings-parser-0.1.1.8.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.30/sponge-mixin-0.7.11.30.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/net/fabricmc/tiny-remapper/0.1.0.33/tiny-remapper-0.1.0.33.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/ow2/asm/asm/7.1/asm-7.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/ow2/asm/asm-analysis/7.1/asm-analysis-7.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/ow2/asm/asm-commons/7.1/asm-commons-7.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/ow2/asm/asm-tree/7.1/asm-tree-7.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/ow2/asm/asm-util/7.1/asm-util-7.1.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/com/mojang/minecraft/1.14.1/minecraft-1.14.1-client.jar

Native libraries:
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1-natives-windows.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1-natives-windows.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1-natives-windows.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1-natives-windows.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1-natives-windows.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1-natives-windows.jar
  C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  VoxelMap-1.9.1_for_1.14(.1)

Params:
  --username  --version MultiMC5 --gameDir C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/instances/going/.minecraft --assetsDir C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 4996

Using onesix launcher.

[18:57:54] [main/INFO]: Loading for game Minecraft 1.14.1
[18:57:54] [main/INFO]: [FabricLoader] Loading 2 mods: voxelmap@1.9.1, fabricloader@0.4.7+build.147
[18:57:54] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/mattg/AppData/Roaming/.minecraft/mods/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.30/sponge-mixin-0.7.11.30.jar Service=Knot/Fabric Env=CLIENT
[18:57:54] [main/INFO]: Compatibility level set to JAVA_8
[18:57:55] [main/INFO]: Setting user: zigg419
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 5/19/19 6:57 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/resource/IdentifiableResourceReloadListener
		at com.mamiyaotaru.voxelmap.fabricmod.FabricModVoxelMapBootstrapper.onInitializeClient(FabricModVoxelMapBootstrapper.java:10)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at java.util.ArrayList.forEach(Unknown Source)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 19 more
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.resource.IdentifiableResourceReloadListener
		at java.net.URLClassLoader.findClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.14.1
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 262722000 bytes (250 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	Launched Version: MultiMC5
	LWJGL: 3.2.1 build 12
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\mattg\AppData\Roaming\.minecraft\mods\MultiMC\instances\going\.minecraft\crash-reports\crash-2019-05-19_18.57.59-client.txt
Process exited with code -1.
Clipboard copy at: 19 May 2019 18:58:11 -0400
Clipboard copy at: 19 May 2019 19:03:29 -0400

Additional Info: no idea how to code, so i have no idea what i'm doing, haven't modded anything with multimc before
---------------------------

**Comment by QuImUfu** [comment]
You need to install [fabric-api](https://minecraft.curseforge.com/projects/fabric)
