### ISSUE TITLE
Linux Modded Minecraft not starting

### ISSUE THREAD

**Issue by Amjad50** [MultiMC/MultiMC5#2669]
System Information
-----------------------------
MultiMC version: 0.6.5-custom

Operating System: Antergos Linux x86_64

Kernel: 5.1.4-arch1-1-ARCH

Summary of the issue or suggestion:
----------------------------------------------
When opening a modded minecraft (maybe forge is the issue) the game crashes in OneSix launcher.
Tried with PO3 and Enigmatica2 Expert.
Maybe as other similar issues suggest. it is because of forge.
In here I'm using java openjdk 8.
I think this problem happened after I made nvidia my primary graphics driver.

What should happen:
------------------------------
The game should start normally, as if there is no forge.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. launch the game

Suspected cause:
---------------------------
Nvidia and openGL problems with forge

Logs/Screenshots:
----------------------------
This is the log of the run:
https://paste.ee/p/Y89Gn

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
For some reason you are running Minecraft on the Internal GPU. Du you have the required drivers installed?

**Comment by Amjad50** [comment]
Yes, I recently I installed nvidia drivers.
Then, I encountered an issue with low resolution screen, so I looked for a solution and found this.
`xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync
+vsync`
`xrandr --addmode eDP-1-1  "1920x1080_60.00"`
`xrandr --output eDP-1-1 --mode "1920x1080_60.00"`

putting this in .xprofile, to run on start fixed the issue.

**Comment by Amjad50** [comment]
I found something.
If I changed the display to 960x540, from Arandr(xrandr). which result in low res, then started minecraft **it works**.
Then, I can get back to 1080 and it still works.

This resolves the issue.
Thank you.

But can you tell me why it works?

**Comment by QuImUfu** [comment]
Somehow LWJGL is not able to get your current primary resolution (it gets an empty list and then tries to access the first value). That also explains why you solution works. Whatever bugs on your default resolution and causes that crash does not happen on the other resolution.  
You could try what happens if you disable full screen. Maybe it does not try to get that information then.  
This is likely a bug in Nvidias driver or maybe LWJGL.  
It seems to be an issue someone else had on vanilla minecraft as well (https://bugs.mojang.com/browse/MC-123286) You could try to provide the missing data on that bug report, but you should do so with a pure vanilla setup (launcher and game).

**Comment by Amjad50** [comment]
> You could try what happens if you disable full screen.
What do you mean by disabling full screen?
Minecraft is default to fullscreen off.

I found something, in version 1.14.1 the game starts normally, version 1.12 have problems even without mods or forge.

**Comment by QuImUfu** [comment]
The newer versions of minecraft (1.13+) use a wildly different version of LWJGL that does not have this issue. 

The old version does a dirty hack that does (for some reason) not work on your system.  
Could you post the output of ``xrandr -q``  
and the log of the game launched with ``-Dorg.lwjgl.util.Debug=true`` as java argument.

**Comment by Amjad50** [comment]
This is the output of `xrandr -q`
```Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
eDP-1-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   960x540       59.82  
   864x486       59.92    59.57  
   640x480       59.94  
   480x270       59.82  
   432x243       59.92    59.57  
   320x240       60.05  
   1920x1080_60.00  59.96* 
DP-1-1 disconnected (normal left inverted right x axis y axis)
HDMI-1-1 disconnected (normal left inverted right x axis y axis)
HDMI-1-2 disconnected (normal left inverted right x axis y axis)
  1920x1080_60.00 (0x210) 173.000MHz -HSync +VSync
        h: width  1920 start 2048 end 2248 total 2576 skew    0 clock  67.16KHz
        v: height 1080 start 1083 end 1088 total 1120           clock  59.96Hz
```
This is the log with the debug flag
https://paste.ee/p/nxxoV

**Comment by Amjad50** [comment]
I have fixed the issue.
The issue is from LWJGL side.
in `org.lwjgl.opengl.XRandR.java` it performs `xrandr -q` and does some regex with the entries to find the screen.
It uses 
```java
private static final Pattern SCREEN_MODELINE_PATTERN = Pattern.compile("^(\\d+)x(\\d+)$");
...
...
Matcher m = SCREEN_MODELINE_PATTERN.matcher(sa[0]);
```
to find the mode's width and height.


I got the mode I'm using now from Arch wiki by using `cvt 1920 1080` and I got
```
Modeline "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
```
The above mode does not match the regex, thus it was not discovered by `XRandR.java::populate()`

The solution is just to edit `SCREEN_MODELINE_PATTERN` to something like `"^(\\d+)x(\\d+).*$"`

I tried to edit `lwjgl-2.9.4-nightly-20150209.jar` that MultiMC uses and it worked. (Even though it require change of hashes in the modpack settings, and only works in offline because I think on each run MultiMC will try to update LWJGL library and it finds the version on the net is different from the version currently using).

**Comment by Janrupf** [comment]
That sounds bad. The LWJGL version is probably not maintained anymore and implementing a fix in MultiMC would be a horrible hack...

**Comment by peterix** [comment]
Cool. LWJGL 2 is basically unmaintained at this point, so it may be necessary to fork it and fix it.

**Comment by Amjad50** [comment]
Minecraft uses a nightly built 2.9.4.xxxxxx, I don't know who is contributing to it because legacy LWJGL lastest version is 2.9.3

If we made a repo for LWJGL I think it's best if we can get the code of the nightly build.

**Comment by peterix** [comment]
The commits are there, it's just that they were never put in an actual release.

**Comment by Amjad50** [comment]
We now know how to solve this issue, even though the solution is not applicable now as of stopping support to LWJGL2.

should we close this issue?

**Comment by asanetargoss** [comment]
CC: https://github.com/LWJGL/lwjgl/issues/147

I managed to get LWJGL 2 to compile on Linux Mint [here](https://github.com/asanetargoss/lwjgl/releases/tag/nightly-20161208). The new build of the non-native lwjgl jar fixed a bug I was having with sneak and hotbar controls. I am not sure what other bugs it has fixed.

To use a version of LWJGL locally for a MultiMC instance, I needed to:

- Copy the non-native LWJGL jar to `[instance folder]/libraries`
- Edit the instance
- Under "Version" tab, click on LWJGL 2, and on the right-hand side select "customize"
- Edit the newly created file `[instance folder]/patches/org.lwjgl.json` using the guidance provided on the [MultiMC wiki section on JSON patches](https://github.com/MultiMC/MultiMC5/wiki/JSON-Patches)
  - In particular, the JSON sub-object for the LWJGL jar needed the property `"MMC-hint": "local"`, and the name of the file adjusted accordingly. This allows the dependency to be used locally, even when online.

**Comment by Rybec** [comment]
I'm also having  a problem with 1.12.2 crashing during startup.  It does not seem to be related to video stuff though.  My error appears to be caused by something trying to cast an object to an incompatible object type.

Following is the console output for my 1.12.2, Forge 14.23.5.2847 instance, with no mods.  I get a different error when I try to run 1.12.2 vanilla, which I will post in a separate message.

```
MultiMC version: 0.6.13-2519


Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [13.224.4.75]

session.minecraft.net resolves to:
    [34.192.50.106, 3.234.0.54, 52.44.210.220]

textures.minecraft.net resolves to:
    [13.224.7.28, 13.224.7.102, 13.224.7.29, 13.224.7.109]

api.mojang.com resolves to:
    [99.86.32.78]


Minecraft folder is:
/home/rybec/.local/share/multimc/instances/1.12.2 TerrariaCraft/.minecraft


Java path is:
/usr/lib/jvm/java-17-openjdk-amd64/bin/java


Checking Java version...
Java is version 17-ea, using 64-bit architecture, from Debian.


Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Intel Corporation CometLake-H GT2 [UHD Graphics] (rev 05)

DeviceName: Onboard - Video

Subsystem: Dell UHD Graphics

Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] (rev c1)

Subsystem: Dell Navi 14 [Radeon RX 5500/5500M / Pro 5500M]

Kernel modules: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.3.5

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/rybec/.local/share/multimc/instances/1.12.2 TerrariaCraft/natives

Libraries:
  /home/rybec/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/rybec/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/rybec/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/rybec/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/rybec/.local/share/multimc/libraries/com/mojang/patchy/1.2.3/patchy-1.2.3.jar
  /home/rybec/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/rybec/.local/share/multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/rybec/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/rybec/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/rybec/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/rybec/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/rybec/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/rybec/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/rybec/.local/share/multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/rybec/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/rybec/.local/share/multimc/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /home/rybec/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/rybec/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/rybec/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/rybec/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/rybec/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/rybec/.local/share/multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /home/rybec/.local/share/multimc/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /home/rybec/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/rybec/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/rybec/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/rybec/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/rybec/.local/share/multimc/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /home/rybec/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /home/rybec/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /home/rybec/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /home/rybec/.local/share/multimc/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-universal.jar
  /home/rybec/.local/share/multimc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /home/rybec/.local/share/multimc/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  /home/rybec/.local/share/multimc/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  /home/rybec/.local/share/multimc/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /home/rybec/.local/share/multimc/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /home/rybec/.local/share/multimc/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /home/rybec/.local/share/multimc/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /home/rybec/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /home/rybec/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /home/rybec/.local/share/multimc/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /home/rybec/.local/share/multimc/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /home/rybec/.local/share/multimc/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /home/rybec/.local/share/multimc/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /home/rybec/.local/share/multimc/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /home/rybec/.local/share/multimc/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /home/rybec/.local/share/multimc/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /home/rybec/.local/share/multimc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/rybec/.local/share/multimc/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  /home/rybec/.local/share/multimc/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /home/rybec/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/rybec/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar
  /home/rybec/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar

Params:
  --username  --version MultiMC5 --gameDir /home/rybec/.local/share/multimc/instances/1.12.2 TerrariaCraft/.minecraft --assetsDir /home/rybec/.local/share/multimc/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 600702


Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code 255.
Clipboard copy at: 13 Nov 2021 16:16:08 -0900
```

**Comment by Rybec** [comment]
Here's my error log  for 1.12.2 vanilla, in case it helps:

```MultiMC version: 0.6.13-2519


Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [13.224.4.75]

session.minecraft.net resolves to:
    [34.192.50.106, 52.44.210.220, 3.234.0.54]

textures.minecraft.net resolves to:
    [13.224.7.29, 13.224.7.28, 13.224.7.102, 13.224.7.109]

api.mojang.com resolves to:
    [99.86.32.78]


Minecraft folder is:
/home/rybec/.local/share/multimc/instances/1.12.2/.minecraft


Java path is:
/usr/lib/jvm/java-17-openjdk-amd64/bin/java


Checking Java version...
Java is version 17-ea, using 64-bit architecture, from Debian.


Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Intel Corporation CometLake-H GT2 [UHD Graphics] (rev 05)

DeviceName: Onboard - Video

Subsystem: Dell UHD Graphics

Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] (rev c1)

Subsystem: Dell Navi 14 [Radeon RX 5500/5500M / Pro 5500M]

Kernel modules: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.3.5

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/rybec/.local/share/multimc/instances/1.12.2/natives

Libraries:
  /home/rybec/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/rybec/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/rybec/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/rybec/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/rybec/.local/share/multimc/libraries/com/mojang/patchy/1.2.3/patchy-1.2.3.jar
  /home/rybec/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/rybec/.local/share/multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/rybec/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/rybec/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/rybec/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/rybec/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/rybec/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/rybec/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/rybec/.local/share/multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/rybec/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/rybec/.local/share/multimc/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /home/rybec/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/rybec/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/rybec/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/rybec/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/rybec/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/rybec/.local/share/multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /home/rybec/.local/share/multimc/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /home/rybec/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/rybec/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/rybec/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/rybec/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/rybec/.local/share/multimc/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /home/rybec/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /home/rybec/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /home/rybec/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /home/rybec/.local/share/multimc/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /home/rybec/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/rybec/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar
  /home/rybec/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar

Params:
  --username  --version MultiMC5 --gameDir /home/rybec/.local/share/multimc/instances/1.12.2/.minecraft --assetsDir /home/rybec/.local/share/multimc/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 601636


Using onesix launcher.

[16:22:25] [Client thread/INFO]: Setting user: LordRybec
[16:22:26] [Client thread/INFO]: LWJGL Version: 2.9.4
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
Process exited with code 127.
Clipboard copy at: 13 Nov 2021 16:22:33 -0900
```

**Comment by Zetabite** [comment]
your issue is unrelated to LWJGL. dont use java 17 on versions below 1.17. And not, we dont need to change lwjgl either. All working as intended.

**Comment by Rybec** [comment]
I tried with Java 11 as well (on both of those).  I'm not sure why MultiMC5 was defaulting to 17 in the first place.  I'm pretty sure when I set it up in the beginning, I told it to default to Java 11.

Should I open a new report for this then?  Or is crashing what is intended running 1.12.2 with Java 11 as well?

**Comment by Zetabite** [comment]
yes you should. either way, we dont need to spam the issue tracker, if you have an issues, contact us on discord or make another issue, but dont append to issues that arent connected to yoru issue. your issue is, that you are using the wrong java, use java 8. if you need help setting up, you know where to find us

**Comment by Rybec** [comment]
I wasn't sure if it was related, and I didn't want to duplicate an issue.  Sorry.  I'll try Java 8.  (I should be able to handle setting it up, assuming Debian still has Java 8 on its repos...)

Anyhow, thanks.  If that doesn't fix it, I'll open a new issue.
