### ISSUE TITLE
Having trouble launching project ozone 3

### ISSUE THREAD

**Issue by brianop123** [MultiMC/MultiMC5#2720]
System Information
-----------------------------
MultiMC version:

MultiMC 5 - Version 0.6.5-1302 on win32

Operating System: 

Windows 10 

Summary of the issue or suggestion:

Whenever I try to run PO3-3.0.40 I get the error that I will provide in the "log" section below. I am pretty sure that it is a problem with either MMC or my computer as the same mod pack works fine on my brother's laptop.

----------------------------------------------

What should happen:

My minecraft should launch.

------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download PO3.0.40.zip

2. Add the Instance

3. And the java path that I have used is :C/Program Files/Java/bin/javaw.exe

4. I have maximized the RAM at 4096 MB

Suspected cause:

I don't know.

---------------------------

Logs/Screenshots:

Here is what the log outputted when I tried to launch PO3:

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.

----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by tehbasshunter** [comment]
Need the full log. Hit the upload button in the top right after you try to run it and experience the issue.

**Comment by brianop123** [comment]
https://paste.ee/p/SjZEp is this it?

**Comment by tehbasshunter** [comment]
That would definitely be it.

You have java 12 installed which isn't compatable with modded minecraft.  Grab Java 8 and you'll be good.

**Comment by brianop123** [comment]
thx
tehbasshunter
