### ISSUE TITLE
Data not loading???

### ISSUE THREAD

**Issue by FabulousAliya** [MultiMC/MultiMC5#2741]
System Information
-----------------------------
MultiMC version: 0.6.6-1341

Operating System: Java

Summary of the issue or suggestion: 
When I launch it's fine but the moment I try to create or enter a world, it loads but stays at zero percent and the log tell me my data packs didn't load. Did I accidentally add/ delete something or...?
----------------------------------------------

What should happen:
My minecraft loads/ creates world like normal.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. N/A, specific to me.

Suspected cause:
Added/ deleted something.
---------------------------

Logs/Screenshots:
----------------------------
(This is what it says when it stops.)

[19:15:58] [Server thread/ERROR]: Failed to reload data packs
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1462) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:449) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_1132.method_3735(class_1132.java:79) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.class_1132.method_3823(class_1132.java:104) [intermediary-minecraft-1.14.3-client.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:604) [intermediary-minecraft-1.14.3-client.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at io.github.cottonmc.libcd.tweaker.RecipeTweaker.applyReload(RecipeTweaker.java:65) ~[129ea593-7154-4c4b-b5b1-5fbc3f2a6867.jar:?]
	at io.github.cottonmc.libcd.tweaker.TweakerLoader.lambda$apply$3(TweakerLoader.java:87) ~[129ea593-7154-4c4b-b5b1-5fbc3f2a6867.jar:?]
	at io.github.cottonmc.libcd.tweaker.TweakerLoader$$Lambda$2671/10601276.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_31]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_31]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_31]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:1.8.0_31]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_31]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_31]

Additional Info:
---------------------------

**Comment by tehbasshunter** [comment]
We need the entire log. Do it again but hit the upload button in the top right of console.

**Comment by peterix** [comment]
Some mod issue, impossible to identify based on the log fragment.
