### ISSUE TITLE
MultiMc is not launching

### ISSUE THREAD

**Issue by KualaBear** [MultiMC/MultiMC5#2750]
System Information
-----------------------------
MultiMC version: Latest (Download Yesterday)

Operating System: Window 10

Summary of the issue or suggestion:
----------------------------------------------
After having it install forge/mods/resources pack my Mc can't even launch

What should happen:
------------------------------
After I add all my mods which are working fine when I use it in the normal launcher
they should be able to work fine and launch my Mc normally as in the normal launcher

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMc
2. Create New Instance (1.8.9)
3. Launching the vanilla is ok
4. Install Forge, Add Mods, and resources pack
5. Launch Mc
6.  Error launching

Suspected cause:
---------------------------
I really don't know what causes this

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.6-1341

Minecraft folder is:
C:/Users/khualpi/Desktop/MultiMC/instances/1.8.9/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_211, using 32-bit architecture.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/khualpi/Desktop/MultiMC/instances/1.8.9/natives

Libraries:
  C:/Users/khualpi/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.8.9-11.15.1.1722/forge-1.8.9-11.15.1.1722-universal.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/com/mojang/minecraft/1.8.9/minecraft-1.8.9-client.jar

Native libraries:
  C:/Users/khualpi/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-32.jar
  C:/Users/khualpi/Desktop/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-32.jar

Mods:
  (1.8.9) IngameServerSwitcher
  [1.8.9] BlockOverlay - 2.0
  [1.8.9] Powns Coords HUD - 1.0
  [1.8+] Sk1er MouseBindFix-1.1
  AutoGG-2.0.4 (1.8.9)
  Autotip-3.0 [1.8-1.12.2]
  AutoWho-1.0
  Frames+ 2.0 BETA Build 16 [1.8.9]
  MemoryFix-0.3
  MouseDelayFix-1.0
  oof-1.2
  OptiFine 1.8.9 HD U I7
  Orange's1.7Animations
  Orange'sSimpleMods
  PvPParticles-1.7
  Quickplay-1.8.9-2.0.3
  ReplayMod
  SimpleAfk
  The 5zig Mod v3.12.5 for Minecraft 1.8.9
  TimeChanger-1.0 (1.8.9)
  ToggleChat-3.0.0-BETA-SNAPSHOT
  Vanilla Enhancements-7.7

Params:
  --username  --version MultiMC5 --gameDir C:/Users/khualpi/Desktop/MultiMC/instances/1.8.9/.minecraft --assetsDir C:/Users/khualpi/Desktop/MultiMC/assets --assetIndex 1.8 --uuid  --accessToken  --userProperties  --userType  --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 1270 x 720

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 47528

Using onesix launcher.

2019-07-15 19:07:33,517 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2019-07-15 19:07:33,518 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[19:07:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:07:33] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:07:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:07:33] [main/INFO] [FML]: Forge Mod Loader version 11.15.1.1722 for Minecraft 1.8.9 loading
[19:07:33] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_211, running on Windows 10:x86:10.0, installed at C:\Program Files (x86)\Java\jre1.8.0_211
[19:07:33] [main/WARN] [FML]: The coremod club.sk1er.mods.mousefix.forge.FMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:07:33] [main/WARN] [FML]: The coremod io.framesplus.forge.FMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:07:33] [main/WARN] [FML]: The coremod io.prplz.mousedelayfix.FMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:07:33] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine 1.8.9 HD U I7.jar
[19:07:33] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from ReplayMod.jar
[19:07:33] [main/INFO] [FML]: Loading tweaker eu.the5zig.mod.asm.ClassTweaker from The 5zig Mod v3.12.5 for Minecraft 1.8.9.jar
[19:07:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:07:33] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[19:07:33] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[19:07:33] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.6.8 Source=file:/C:/Users/khualpi/Desktop/MultiMC/instances/1.8.9/.minecraft/mods/ReplayMod.jar Env=CLIENT
[19:07:33] [main/WARN] [FML]: The coremod com.replaymod.core.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:07:33] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[19:07:34] [main/INFO] [LaunchWrapper]: Loading tweak class name eu.the5zig.mod.asm.ClassTweaker
[19:07:34] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:07:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:07:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:07:34] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[19:07:34] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[19:07:34] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[19:07:34] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[19:07:34] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\khualpi\Desktop\MultiMC\instances\1.8.9\.minecraft\mods\OptiFine 1.8.9 HD U I7.jar
[19:07:34] [main/INFO] [LaunchWrapper]: Calling tweak class eu.the5zig.mod.asm.ClassTweaker
[19:07:34] [main/INFO] [LaunchWrapper]: Minecraft Version: MultiMC5
[19:07:34] [main/INFO] [LaunchWrapper]: Forge detected!
[19:07:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:07:36] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[19:07:36] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[19:07:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:07:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
2019-07-15 19:07:36,737 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2019-07-15 19:07:36,753 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2019-07-15 19:07:36,754 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[19:07:36] [main/INFO] [ASM]: Starting Frames+ library v3
[19:07:39] [main/INFO] [STDOUT]: [io.framesplus.util.NativeUtil:<clinit>:-1]: Loading C:/Users/khualpi/Desktop/MultiMC/instances/1.8.9/natives/frames_plus.dll
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.lang.UnsatisfiedLinkError: C:\Users\khualpi\Desktop\MultiMC\instances\1.8.9\natives\frames_plus.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.ClassLoader.loadLibrary(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Runtime.load0(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.System.load(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at io.framesplus.util.NativeUtil.<clinit>(NativeUtil.java)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at io.framesplus.forge.ClassTransformer.<init>(ClassTransformer.java)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Class.newInstance(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:218)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at $wrapper.io.framesplus.forge.ClassTransformer.<init>(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Class.newInstance(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:124)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:07:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[19:07:39] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[19:07:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.ArrayIndexOutOfBoundsException: 5
[19:07:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[19:07:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[19:07:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.
Clipboard copy at: 15 Jul 2019 19:08:52 -0500
MultiMC: Log upload triggered at: 15 Jul 2019 19:08:55 -0500

Additional Info:
---------------------------
If I don't install forge/mods, it's launching fine but as soon as I install those its got an error

**Comment by madokaorimura** [comment]
Install Forge (no mods), check if the game launch

**Comment by QuImUfu** [comment]
Install 64 bit Java or remove Frames+.  
This is (most likely) a bug in their mod.  

remark:
The authors of the Frames+ illegally (according to Mojangs EULA) sell their mod (at least they do not mention that they got a permission). Even if that EULA should not be legally binding in their case, i think it is an bad idea that could damage the minecraft community and should not be supported because of that.

**Comment by peterix** [comment]
Let's not provide support for this kind of thing.

**Comment by KualaBear** [comment]
> Install Forge (no mods), check if the game launch
> Try this : sfc /scannow ([Source](https://bugs.mojang.com/browse/MCL-1297))

Do I need to type that inside the command of the MultiMC?

**Comment by KualaBear** [comment]
> Install 64 bit Java or remove Frames+.
> This is (most likely) a bug in their mod.
> 
> remark:
> The authors of the Frames+ illegally (according to Mojangs EULA) sell their mod (at least they do not mention that they got a permission). Even if that EULA should not be legally binding in their case, i think it is an bad idea that could damage the minecraft community and should not be supported because of that.

Good News!: I try what you have told me, and it works, I really thank you.

**Comment by KualaBear** [comment]
Thank you guys for helping it really help my problem and it's SOLVED IT!!!
