### ISSUE TITLE
Exepction in thread main error with close as code 1

### ISSUE THREAD

**Issue by scarletspider34** [MultiMC/MultiMC5#2753]
System Information
-----------------------------
MultiMC version: 0.6.6-1341

Operating System: java 1.8.0_211

Summary of the issue or suggestion:
----------------------------------------------
making new mod pack and I think I have the requirements but this message comes up and I don't know what it means

-----------------------------------------------------------------------------------------------
MultiMC version: 0.6.6-1341

Minecraft folder is:
C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/instances/1.12/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_211, using 32-bit architecture.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/instances/1.12/natives

Libraries:
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/realms/1.10.17/realms-1.10.17.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/minecraftforge/forge/1.12-14.21.1.2387/forge-1.12-14.21.1.2387-universal.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/minecraft/1.12/minecraft-1.12-client.jar

Native libraries:
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  AkashicTome-1.2-12
  Animalium-0.3.8
  AppleCore-mc1.12.2-3.2.0
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv6-stable-6
  astralsorcery-1.12.2-1.10.12
  BiblioCraft[v2.4.5][MC1.12.2]
  Botania r1.10-360
  Chisel-MC1.12.2-0.2.1.35
  chiselsandbits-14.31
  CMDCam_v1.4.3_mc1.12.2
  CookingForBlockheads_1.12.2-6.4.71
  Hwyla-fabric-1.14.2-1.9.17-66
  ImprovedBackpacks-1.12.2-1.4.0.0
  jei_1.12.2-4.15.0.275
  jeiintegration_1.12.2-1.5.1.36
  modmenu-1.6.3+build.101
  OptiFine_1.12.2_HD_U_E3
  OreExcavation-1.4.140
  Pam's HarvestCraft 1.12.2zc The 7mm Kidney Stone Update
  pamscookables-1.1
  QuickLeafDecay-MC1.12.1-1.2.4
  refinedstorage-1.6.14
  refinedstorageaddons-0.4.4
  simpleharvest-1.08
  StevesCarts-1.12.2-2.4.30.134
  Thaumcraft-1.12.2-6.1.BETA26
  ThaumicInventoryScanning_1.12.2-2.0.10
  ThaumicJEI-1.12.2-1.5.8-26
  tinker_io-1.12.2-rw2.7.1
  TinkerToolLeveling-1.12.2-1.1.0
  TreeChopper-1.12.2-1.2.4
  XenCraft-1.0.0.4

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/instances/1.12/.minecraft --assetsDir C:/Users/Becky/Downloads/mmc-stable-win32 (1)/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms500m, -Xmx1000m, -Duser.language=en]

Minecraft process ID: 15244

Using onesix launcher.

2019-07-16 16:30:22,664 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2019-07-16 16:30:22,666 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:30:22] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:30:22] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:30:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:30:22] [main/INFO] [FML]: Forge Mod Loader version 14.21.1.2387 for Minecraft 1.12 loading
[16:30:22] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_211, running on Windows 10:x86:10.0, installed at C:\Program Files (x86)\Java\jre1.8.0_211
2019-07-16 16:30:22,849 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2019-07-16 16:30:22,857 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2019-07-16 16:30:22,857 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:30:22] [main/ERROR] [FML]: The coremod squeek.applecore.AppleCore is requesting minecraft version 1.12.2 and minecraft is 1.12. It will be ignored.
[16:30:22] [main/WARN] [FML]: The coremod hellfirepvp.astralsorcery.core.AstralCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:30:22] [main/INFO] [Astral Core]: [AstralCore] Initialized.
[16:30:22] [main/WARN] [FML]: The coremod com.creativemd.cmdcam.transform.CamPatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:30:22] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_E3.jar
[16:30:22] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:30:22] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[16:30:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:30:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:30:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:30:23] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[16:30:23] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[16:30:23] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[16:30:23] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[16:30:23] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\Becky\Downloads\mmc-stable-win32 (1)\MultiMC\instances\1.12\.minecraft\mods\OptiFine_1.12.2_HD_U_E3.jar
[16:30:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:30:24] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[16:30:24] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[16:30:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:30:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.lang.NoClassDefFoundError: com/creativemd/cmdcam/transform/CamTransformer
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at com.creativemd.cmdcam.transform.CamPatchingLoader.getASMTransformerClass(CamPatchingLoader.java:16)
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:130)
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:30:24] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: com.creativemd.cmdcam.transform.CamTransformer
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 12 more
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/transformer/CreativeTransformer
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 14 more
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.transformer.CreativeTransformer
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:30:24] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	... 18 more
[16:30:24] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[16:30:24] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[16:30:24] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[16:30:24] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[16:30:24] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[16:30:24] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[16:30:24] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.
MultiMC: Log upload triggered at: 16 Jul 2019 16:30:31 +0100
MultiMC: Log uploaded to: https://paste.ee/p/GTjZq
Clipboard copy at: 16 Jul 2019 16:30:58 +0100

**Comment by QuImUfu** [comment]
CMDCam requires [CreativeCore](https://www.curseforge.com/minecraft/mc-mods/creativecore). install it.

**Comment by scarletspider34** [comment]
Is that all that caused it to crash?

**Comment by peterix** [comment]
We don't know. Assuming fixed tho.
