### ISSUE TITLE
Crash on launch minecraft 1.14.4

### ISSUE THREAD

**Issue by Fiskpung** [MultiMC/MultiMC5#2759]
System Information
-----------------------------
MultiMC version: 0.6.5

Operating System: Win10 64-Bit Pro

Summary of the issue or suggestion:Crashing when trying to launch.
Log:
MultiMC version: 0.6.6-1341

Minecraft folder is:
C:/Users/plh98/Documents/MultiMC/instances/1.14.4/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_201, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/plh98/Documents/MultiMC/instances/1.14.4/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/plh98/Documents/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/plh98/Documents/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/plh98/Documents/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/plh98/Documents/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/plh98/Documents/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/plh98/Documents/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/plh98/Documents/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/plh98/Documents/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/plh98/Documents/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/plh98/Documents/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/plh98/Documents/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/plh98/Documents/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/plh98/Documents/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/plh98/Documents/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/plh98/Documents/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/plh98/Documents/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/plh98/Documents/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/plh98/Documents/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/plh98/Documents/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/plh98/Documents/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/plh98/Documents/MultiMC/instances/1.14.4/libraries/OptiFine_1.14.4_HD_U_F2_pre1.jar
  C:/Users/plh98/Documents/MultiMC/libraries/com/mojang/minecraft/1.14.4/minecraft-1.14.4-client.jar

Native libraries:
  C:/Users/plh98/Documents/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/plh98/Documents/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/plh98/Documents/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/plh98/Documents/MultiMC/instances/1.14.4/.minecraft --assetsDir C:/Users/plh98/Documents/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release --tweakClass optifine.OptiFineTweaker

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms409m, -Xmx6144m, -Duser.language=en]

Minecraft process ID: 14624

Using onesix launcher.

[01:14:37] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[01:14:37] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[01:14:37] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions
OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine ZIP file: C:\Users\plh98\Documents\MultiMC\instances\1.14.4\libraries\OptiFine_1.14.4_HD_U_F2_pre1.jar
OptiFineTweaker: getLaunchArguments
OptiFineTweaker: getLaunchTarget
[01:14:38] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[01:14:38] [main/INFO]: [OptiFine] *** Reflector Forge ***
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.Attributes
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.BrandingControl
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.capabilities.ICapabilityProvider
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.capabilities.CapabilityProvider
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.ClientModLoader
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.world.ChunkEvent$Load
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.ClientHooks
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.CrashReportExtender
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Pre
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Post
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.EntityViewRenderEvent$FogColors
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.EntityViewRenderEvent$RenderFogEvent
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.entity.EntityJoinWorldEvent
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.IEventBus
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeBlock
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: dnv.getTexture
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: dpt.getModelData
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.addDestroyEffects
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.addHitEffects
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.canRenderInLayer
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.getLightValue
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.getStateAtViewpoint
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.hasTileEntity
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.isAir
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeFluidState
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEntity
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: ais.getTags
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Field not present: aix.NAMETAG_DISTANCE
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.ForgeEventFactory
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: clj.getTags
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeConfig
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeConfig$Client
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeConfigSpec$ConfigValue
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeItem
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeItemStack
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.ForgeI18n
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.IModel
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: cxz.setKeyConflictContext
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: cxz.setKeyModifierAndCode
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: cxz.getKeyModifier
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeMod
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: dof.fromJson
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEffect
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEffectInstance
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.registries.ForgeRegistryEntry
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeTileEntity
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: cvd$b.preDraw
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Method not present: cvd$b.postDraw
[01:14:38] [main/WARN]: [OptiFine] Field not found: tileEntitiesToBeRemoved
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeDimension
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.gui.GuiModList
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.IRenderHandler
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ItemModelMesherForge
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyConflictContext
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyModifier
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.pipeline.LightUtil
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.Loader
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.MinecraftForge
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.MinecraftForgeClient
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.gui.NotificationModUpdateScreen
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.entity.PlaySoundAtEntityEvent
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderBlockOverlayEvent$OverlayType
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.registry.RenderingRegistry
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderItemInFrameEvent
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Pre
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Post
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Specials$Pre
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Specials$Post
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.ScreenshotEvent
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.server.ServerLifecycleHooks
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.SplashProgress
[01:14:38] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.world.WorldEvent$Load
[01:14:38] [main/INFO]: [OptiFine] *** Reflector Vanilla ***
[01:14:38] [main/INFO]: Setting user: Fiskpung
[01:14:41] [main/WARN]: Skipping bad option: lastServer:
[01:14:41] [main/INFO]: LWJGL Version: 3.2.2 build 10
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 7/22/19 1:14 AM
Description: Initializing game

java.lang.NoClassDefFoundError: com/mojang/blaze3d/platform/TextureUtil
	at cuo.a(MainWindow.java:213)
	at cuo.a(MainWindow.java:172)
	at cyc.au(SourceFile:469)
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: com.mojang.blaze3d.platform.TextureUtil
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more
Caused by: java.lang.SecurityException: class "com.mojang.blaze3d.platform.TextureUtil"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cuo.a(MainWindow.java:213)
	at cuo.a(MainWindow.java:172)
	at cyc.au(SourceFile:469)

-- Initialization --
Details:
Stacktrace:
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 465840160 bytes (444 MB) / 1934098432 bytes (1844 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms409m -Xmx6144m
	Launched Version: MultiMC5
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\plh98\Documents\MultiMC\instances\1.14.4\.minecraft\crash-reports\crash-2019-07-22_01.14.43-client.txt
Process exited with code -1.

----------------------------------------------

**Comment by peterix** [comment]
Yes, OptiFine is broken.

Run its installer, make it `extract` the real jar, the use that as a jar mod (`add to Minecraft.jar` on the Version page of the instance).
