### ISSUE TITLE
Issue starting Minecraft version 1.12.2 with the mod WorldDownloader

### ISSUE THREAD

**Issue by SoloMaker** [MultiMC/MultiMC5#2875]
System Information
-----------------------------
MultiMC version: 0.6.7-1375

Operating System: Windows 7 Professional

Summary of the issue or suggestion: Issue when starting Minecraft version 1.12.2 with the mod WorldDownloader 
----------------------------------------------

What should happen: The game should start normally.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.

2.

3.

Suspected cause:
---------------------------

Logs:

```
MultiMC version: 0.6.7-1375


Minecraft folder is:
D:/MultiMC/instances/1.12.2_WDL1/.minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_201/bin/javaw.exe


Java is version 1.8.0_201, using 64-bit architecture.


Main Class:
  net.minecraft.client.main.Main

Native path:
  D:/MultiMC/instances/1.12.2_WDL1/natives

Libraries:
  D:/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  D:/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  D:/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  D:/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  D:/MultiMC/libraries/com/mojang/realms/1.10.17/realms-1.10.17.jar
  D:/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  D:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  D:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  D:/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  D:/MultiMC/instances/1.12.2_WDL1/.minecraft/bin/minecraft.jar

Native libraries:
  D:/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  D:/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Jar Mods:
  mod-worlddownloader-baseedit-4.0.5.3-mc1.12.2 (c0834ab1-1e98-4b1b-b3c2-494fabf45cca.jar)

Params:
  --username  --version MultiMC5 --gameDir D:/MultiMC/instances/1.12.2_WDL1/.minecraft --assetsDir D:/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 4500


Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:38)
	... 8 more
Exiting with -1
Process exited with code -1.
```

----------------------------

**Comment by peterix** [comment]
Seems to work fine. Make sure you are actually using 1.12.2 as the base version.
