### ISSUE TITLE
OpenGL Error When Starting an Instance. HELP

### ISSUE THREAD

**Issue by Etomic-Studios** [MultiMC/MultiMC5#2898]
System Information
-----------------------
GTX 750
8GB ram
i5 2300
300GB SSD
MultiMC version:
0.6.7-1375
Operating System:
Windows 10 64 bit
Summary of the issue or suggestion:
------------------------------------------
An OpenGL Error that I keep getting

What should happen:
--------------------------
Well it should start up minecraft but ends with the same output message.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1) Just start an instance

Suspected cause:
---------------------------
OpenGL Error that I can't Fix

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/Joshua/Desktop/MultiMC/instances/hi/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_231, using 32-bit architecture.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/Joshua/Desktop/MultiMC/instances/hi/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/com/mojang/minecraft/1.14.4/minecraft-1.14.4-client.jar

Native libraries:
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/Joshua/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Joshua/Desktop/MultiMC/instances/hi/.minecraft --assetsDir C:/Users/Joshua/Desktop/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 14552

Using onesix launcher.

[09:35:39] [Client thread/INFO]: Setting user: Etomic
[09:35:43] [Client thread/INFO]: LWJGL Version: 3.2.2 build 10
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2019/10/22 9:35 AM
Description: Initializing game

java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL
	at cuo.b(SourceFile:199)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuo.<init>(SourceFile:81)
	at dnr.a(SourceFile:19)
	at cyc.au(SourceFile:464)
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cuo.b(SourceFile:199)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cuo.<init>(SourceFile:81)
	at dnr.a(SourceFile:19)
	at cyc.au(SourceFile:464)

-- Initialization --
Details:
Stacktrace:
	at cyc.b(SourceFile:394)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 298668936 bytes (284 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	Launched Version: MultiMC5
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Joshua\Desktop\MultiMC\instances\hi\.minecraft\crash-reports\crash-2019-10-22_09.35.43-client.txt
Process exited with code -1.
Clipboard copy at: 22 Oct 2019 09:35:46 +0200

Additional Info:
---------------------------
I am unable to fix the issue. I re-installed Java, and the drivers I can't touch.

**Comment by Etomic-Studios** [comment]
Nvm I fixed the issue... Why does this keep happening, I ask for help and then my pc just fixes it's self.
