### ISSUE TITLE
[Linux] No instances launching

### ISSUE THREAD

**Issue by 2haloes** [MultiMC/MultiMC5#2920]
System Information
-----------------------------
MultiMC version: 1.6.7

Operating System: Solus OS

Summary of the issue or suggestion: 
----------------------------------------------
No instances are loading, vanilla or modded (Tested Minecraft 1.12.2)

Modpacks become frozen when trying to load and need to be killed

Vanilla exits by itself

What should happen:
------------------------------
All instances should load

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMC

2. Try to load an instance

Suspected cause:
---------------------------
Either an update to do with Java

Or my system locked up while playing MC before this occurred and I had to force shut down my system

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Modpack log (Awakening: Sky of Diamonds): https://paste.ee/p/ILrWG

Vanilla log (Vanilla 1.12.2): https://paste.ee/p/foXvM

Additional Info:
---------------------------

Java version is: OpenJDK 1.8.0_232_solus

Solus has a Java 8 package so I believe that the issue is not to do with the java version. 

I only have one version of Java on my system and MultiMC detects it fine

**Comment by Janrupf** [comment]
Mhhm, looks like one of those Xrandr hacks is failing in LWJGL.
```
[06:58:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
[06:58:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.lwjgl.opengl.XRandR.findPrimary(XRandR.java:326)
[06:58:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.lwjgl.opengl.XRandR.ScreentoDisplayMode(XRandR.java:315)
[06:58:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:746)
[06:58:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:743)
[06:58:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at java.security.AccessController.doPrivileged(Native Method)
[06:58:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:743)
[06:58:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
[06:58:43] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	... 35 more
```
This is probably the same as #2669
