### ISSUE TITLE
multimc error while loading fabric mods

### ISSUE THREAD

**Issue by antoniprzybylik** [MultiMC/MultiMC5#2929]
I'm trying to install some fabric mods on multimc. I tried both
options of getting fabric. By copying multimc instance URL from here - https://fabricmc.net/use/
and by just clicking install fabric in 1.14.4 multimc minecraft instance. It worked in both cases.

Then I wanted to install some mods. All ( even fabric API ) produced this error:

net.fabricmc.loader.discovery.ModResolutionException: Mod resolution took too long!
at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:596)
at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:176)
at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:166)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
at org.multimc.EntryPoint.listen(EntryPoint.java:143)
at org.multimc.EntryPoint.main(EntryPoint.java:34)

full log ( java 13, 1GB ) - https://paste.ee/p/l9ChC
another log ( java 8, 1GB ) - https://paste.ee/p/X1I4k
another log ( java 8, 2GB ) - https://paste.ee/p/yAvHB

I also tried adding and removing fabric API and adding it to minecraft.jar. It don't changed anything so I don't pasted its logs. I also tried voxelmap mod. 

I remember that I used modmenu and voxelmap mods on multimc in the past and they worked. Now I can't set up them.

I tried installing multimc5 and multimc-git packages from AUR. I tried uninstalling and reinstalling multimc.

**Comment by Frontear** [comment]
This isn't a MultiMC specific issue, rather, its a fabric issue. As such, please report it at [fabric-loader](https://github.com/FabricMC/fabric-loader/issues).
