### ISSUE TITLE
unknown error for launch

### ISSUE THREAD

**Issue by Xiang990293** [MultiMC/MultiMC5#2972]
System Information
-----------------------------
MultiMC version:0.6.7-develop-1415

Operating System:windows 10

Summary of the issue or suggestion: the game crashed after launched (any instance)
----------------------------------------------

What should happen: the game will open
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.I add the instance by using zip

2.I set the Xmx:6144mb Xms:512mb

3.I launch the instance but failed

Suspected cause: unknown
---------------------------

Logs/Screenshots:
----------------------------
[//]: WARNING: coremods are present:
  ApotheosisCore (Apotheosis-1.12.2-1.10.5.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  SqueezerCore (SqueezerPatch-1.12.2-1.0.0.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  BNBGamingCore (BNBGamingCore-1.12.2-0.11.0.jar)
  AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.0.381.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b165.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 1/19/20 10:25 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1731258464 bytes (1651 MB) / 2049966080 bytes (1955 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6144m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
ApotheosisCore (Apotheosis-1.12.2-1.10.5.jar)
  shadows.ApotheosisTransformer
BedPatch (bedpatch-2.2-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
CorePlugin (SmoothFont-mc1.12.2-2.1.jar)
  bre.smoothfont.asm.Transformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
SqueezerCore (SqueezerPatch-1.12.2-1.0.0.jar)
  shadows.squeezer.Transformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
BNBGamingCore (BNBGamingCore-1.12.2-0.11.0.jar)
  com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCoreClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.0.381.jar)
  mekanism.coremod.KeybindingMigrationHelper
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b165.jar)
  
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>

Additional Info: I also tried the vanilla 1.14.4(without any of mod) but either fail.
---------------------------
[crash-2020-01-19_22.15.32-client.txt](https://github.com/MultiMC/MultiMC5/files/4082849/crash-2020-01-19_22.15.32-client.txt)

**Comment by Zetabite** [comment]
could you please upload the log multimc generates, by clicking the upload button in the mmc console and pasting the link here?

**Comment by QuImUfu** [comment]
Does it work with the vanilla launcher?  
This might be another instance of an [Unsupported Intel GPU](https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs).

**Comment by Xiang990293** [comment]
https://paste.ee/p/1PwtW

**Comment by Zetabite** [comment]
seems to be the case, use that fix @QuImUfu suggested

**Comment by Xiang990293** [comment]
It worked when I use elder Java version
https://files.multimc.org/downloads/jre-8u51-windows-x64.zip
Thanks!

**Comment by sTiKyt** [comment]
@Xiang990293 Close here if solved
