### ISSUE TITLE
issues crash

### ISSUE THREAD

**Issue by italoxf1** [MultiMC/MultiMC5#2991]
**How do I solve this problem?**

MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/ITALO/Downloads/MultiMC/instances/teste/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Versão do Java 1.8.0_241, usando arquitetura de 64 bits.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/ITALO/Downloads/MultiMC/instances/teste/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/com/mojang/minecraft/1.15.2/minecraft-1.15.2-client.jar

Native libraries:
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/ITALO/Downloads/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/ITALO/Downloads/MultiMC/instances/teste/.minecraft --assetsDir C:/Users/ITALO/Downloads/MultiMC/assets --assetIndex 1.15 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en]

ID do processo do Minecraft: 2464

Using onesix launcher.

[00:24:40] [Render thread/INFO]: Setting user: mago_da_redstone
[00:24:49] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2/5/20 12:24 AM
Description: Initializing game

java.lang.NoClassDefFoundError: org/lwjgl/util/tinyfd/TinyFileDialogs
	at cxx.b(SourceFile:214)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cxx.<init>(SourceFile:90)
	at drh.a(SourceFile:21)
	at dbn.<init>(SourceFile:417)
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.util.tinyfd.TinyFileDialogs
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cxx.b(SourceFile:214)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
	at cxx.<init>(SourceFile:90)
	at drh.a(SourceFile:21)
	at dbn.<init>(SourceFile:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 488152792 bytes (465 MB) / 1053294592 bytes (1004 MB) up to 1908932608 bytes (1820 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\ITALO\Downloads\MultiMC\instances\teste\.minecraft\crash-reports\crash-2020-02-05_00.24.50-client.txt
O processo foi encerrado com o código -1.
Clipboard copy at: 05 Feb 2020 00:24:54 -0300

**Comment by spannerman79** [comment]
> CPUs: 4
> Operating System: Windows 10 (amd64) version 10.0
> Backend library: LWJGL version 3.2.2 build 10
> Backend API: NO CONTEXT

I suspect https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs
Next time - follow https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs
