### ISSUE TITLE
Cant start minecraft.

### ISSUE THREAD

**Issue by ilyhasp** [MultiMC/MultiMC5#3023]
MultiMC version: 0.6.8-1419

Minecraft folder is:
D:/Games/MultiMC/instances/1.7.10/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Версия Java 1.8.0_241, использующая 64-битную архитектуру.

Main Class:
  net.minecraft.client.main.Main

Native path:
  D:/Games/MultiMC/instances/1.7.10/natives

Libraries:
  D:/Games/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/Games/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/Games/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  D:/Games/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  D:/Games/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Games/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Games/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Games/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Games/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  D:/Games/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  D:/Games/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/Games/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  D:/Games/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/Games/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/Games/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/Games/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/Games/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/Games/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  D:/Games/MultiMC/libraries/com/google/guava/guava/15.0/guava-15.0.jar
  D:/Games/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  D:/Games/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  D:/Games/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  D:/Games/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  D:/Games/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  D:/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  D:/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  D:/Games/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  D:/Games/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  D:/Games/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  D:/Games/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  D:/Games/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Params:
  --username  --version MultiMC5 --gameDir D:/Games/MultiMC/instances/1.7.10/.minecraft --assetsDir D:/Games/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType 

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms500m, -Xmx3000m, -Duser.language=en]

ID процесса Minecraft: 2740

Using onesix launcher.

[17:28:29] [main/INFO]: Setting user: johnbourke
[17:28:29] [main/INFO]: (Session ID is token:<КЛЮЧ ДОСТУПА>:<ID ПРОФИЛЯ>)
[17:28:31] [Client thread/INFO]: LWJGL Version: 2.9.4
[17:28:31] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at bao.ag(SourceFile:327) [minecraft-1.7.10-client.jar:?]
	at bao.f(SourceFile:713) [minecraft-1.7.10-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [minecraft-1.7.10-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 3/3/20 5:28 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bao.ag(SourceFile:340)
	at bao.f(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bao.ag(SourceFile:340)

-- Initialization --
Details:
Stacktrace:
	at bao.f(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 417373000 bytes (398 MB) / 502792192 bytes (479 MB) up to 2796552192 bytes (2667 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms500m -Xmx3000m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
#@!@# Game crashed! Crash report saved to: #@!@# D:\Games\MultiMC\instances\1.7.10\.minecraft\crash-reports\crash-2020-03-03_17.28.32-client.txt
Процесс завершился с кодом -1.
MultiMC: Загрузка журнала запущена: 03 Mar 2020 17:28:51 +0100
© 2020 Paste.eeBack to top - AUP`

**Comment by Scotsguy** [comment]
Closing due to inactivity.
For the record, see https://github.com/MultiMC/MultiMC5/wiki/Unsupported-Intel-GPUs
