### ISSUE TITLE
Failed to start Minecraft

### ISSUE THREAD

**Issue by meowmeoe** [MultiMC/MultiMC5#3065]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Windows 10

Summary of the issue or suggestion:
----------------------------------------------
After fixing "Failed to find Minecraft main class" (thanks Zetabite) I got yet another error message. >:(
This one tells me that it "Failed to reconstruct Minecraft assets", then tells me "Failed to start Minecraft"

What should happen:
------------------------------
Minecraft launches with Forge

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  Upload Forge

2.  Launch Normally (online)

3.  Get error message

Suspected cause:
---------------------------
*shrugs*

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
Full Logs:

https://paste.ee/p/dO4xI

Just the error:

Failed to reconstruct Minecraft assets.
Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms204m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 2996

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: cpw/mods/modlauncher/Launcher
	at io.github.zekerzhayard.forgewrapper.installer.Main.getLibrariesDir(Main.java:44)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:22)
	... 8 more
Caused by: java.lang.ClassNotFoundException: cpw.mods.modlauncher.Launcher
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 10 more
Exiting with -1
Process exited with code -1.

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
hm. you might need to launch 1.13+ forge online everytime, seems to be an issue how the installer is currently implemented. not sure if its fixable

**Comment by meowmeoe** [comment]
:/
sucks to be me i guess?

**Comment by Zetabite** [comment]
IDK. I rather wait on a response by someone who knows more about that matter than me

**Comment by meowmeoe** [comment]
ok thanks

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
