### ISSUE TITLE
If I start minecraft 1.12 with Forge, it crash. (mac)

### ISSUE THREAD

**Issue by FedeRio-Biscotto** [MultiMC/MultiMC5#3198]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: MacOs High Sierra version 10.13.6

Summary of the issue or suggestion: crash
----------------------------------------------

What should happen: 
It should starts minecraft normally
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I install forge (the last version) on my istance

2. I start minecraft with forge 

3. It crash with code 255

Suspected cause:
---------------------------

Logs/Screenshots:
Using onesix launcher.

Failed to start Minecraft:
Exiting with -1
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Il processo si è chiuso con codice 255.
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
