### ISSUE TITLE
Process exited with code 1

### ISSUE THREAD

**Issue by LabgrownLorax** [MultiMC/MultiMC5#3208]
My MultiMC5 1.12 instance refuses to load. Process exited with code 1. Crash log below

System Information
-----------------------------
MultiMC version: 5

Operating System: windows 10

Logs/Screenshots:
----------------------------
MultiMC version: 0.6.11-1430

Minecraft folder is:
C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/instances/1.12.2/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_251, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/instances/1.12.2/natives

Libraries:
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] AdChimneys-1.12.2-3.5.14.0-build.0505
  [✔️] Advanced-Fishing-1.12.2-1.3.3
  [✔️] Apotheosis-1.12.2-1.12.5
  [✔️] AppleCore-mc1.12.2-3.4.0
  [✔️] AppleSkin-mc1.12-1.0.9
  [✔️] Arcane+Essentials-0.9
  [✔️] ArtemisLib-1.12.2-v1.0.6
  [✔️] Artifacts-1.12.2-1.1.0
  [✔️] AutoRegLib-1.3-32
  [✔️] Baubles-1.12-1.5.2
  [✔️] BetterAdvancements-1.12.2-0.1.0.77
  [✔️] BetterFoliage-MC1.12-2.3.1
  [✔️] BetterFps-1.4.8
  [✔️] BeyondTheVeil-1.12.2-0.2.2
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2441-universal
  [✔️] Bloodmoon-MC1.12.2-1.5.3
  [✔️] bonsaitrees-1.1.4-b170
  [✔️] candyworld-1.1.5
  [✔️] Chameleon-1.12-4.1.3
  [✔️] Chisel-MC1.12.2-1.0.2.45
  [✔️] conarm-1.12.2-1.2.5.9
  [✔️] CTM-MC1.12.2-1.0.2.31
  [✔️] culinaryconstruct-1.3.3
  [✔️] DynamicLights-1.12.2
  [✔️] DynamicSurroundings-1.12.2-3.6.1.0
  [✔️] DynamicTrees-1.12.2-0.9.8
  [✔️] DynamicTreesBOP-1.12.2-1.4.1e
  [✔️] Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2
  [✔️] extraalchemy-forge-1.12-build11-0.5.4
  [✔️] ExtraSpells-1.12.2-1.0.7
  [✔️] extrautils2-1.12-1.9.9
  [✔️] fairylights-2.1.10-1.12.2
  [✔️] FishingMadeBetter-1.12.2-1.1.3
  [✔️] Forgelin-1.8.4
  [✔️] furnaceoverhaul-1.12.2-2.2.2
  [✔️] furniture-6.3.1-1.12.2
  [✔️] GiacomosFoundry-1.12.2-1.3.13
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] ImprovedBackpacks-1.12.2-1.5.0.0
  [✔️] Inspirations-1.12.2-0.2.9
  [✔️] InventoryTweaks-1.63
  [✔️] jei_1.12.2-4.15.0.291
  [✔️] journeymap-1.12.2-5.7.1
  [✔️] journeymaptools-0.3
  [✔️] JustAFewFish-1.7_for_1.12
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] mcw-bridges-1.0.4-mc1.12.2
  [📁] memory_repo (folder)
  [✔️] MistWorld_1.12.2_alpha_c_09
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] NaturesCompass-1.12.2-1.8.3
  [✔️] OpenBlocks-1.12.2-1.8.1
  [✔️] OpenModsLib-1.12.2-0.12.2
  [✔️] OreLib-1.12.2-3.6.0.1
  [✔️] parry-1.0-hotfix
  [✔️] Patchouli-1.0-20
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] PotionCore-1.9_for_1.12.2
  [✔️] Quark-r1.6-178
  [✔️] RoguelikeDungeons-1.12.2-1.8.0
  [✔️] ropebridge-1.12-2.0.7
  [✔️] rustic-1.1.4
  [✔️] SeedsForWizardry+1.0+For+MC+Forge+1.12.2
  [✔️] StorageDrawers-1.12.2-5.4.2
  [✔️] StorageDrawersExtras-1.12-3.1.0
  [✔️] TConstruct-1.12.2-2.13.0.183
  [✔️] TFSpellPack-1.0.1-MC1.12.2
  [✔️] TheBetweenlands-3.4.9-universal
  [✔️] TinkerToolLeveling-1.12.2-1.1.0
  [✔️] twilightforest-1.12.2-3.10.1013-universal
  [✔️] Useful+Interior+-+0.13.1+[1.12.2]
  [✔️] WaterStrainer-1.12-3.2.0
  [✔️] xpfromharvest-1.12.2-1.1.0

Params:
  --username  --version MultiMC5 --gameDir C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/instances/1.12.2/.minecraft --assetsDir C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 10188

Using onesix launcher.

[00:07:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[00:07:57] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[00:07:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[00:07:57] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[00:07:57] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_251, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_251
[00:07:58] [main/INFO] [FML]: Searching C:\Users\dmak4\Downloads\mmc-stable-win32\MultiMC\instances\1.12.2\.minecraft\mods for mods
[00:07:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AdChimneys-1.12.2-3.5.14.0-build.0505.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:07:58] [main/WARN] [FML]: The coremod com.endertech.minecraft.mods.adchimneys.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:07:58] [main/WARN] [FML]: The coremod LoadingPlugin (com.endertech.minecraft.mods.adchimneys.LoadingPlugin) is not signed!
[00:07:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Apotheosis-1.12.2-1.12.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:07:58] [main/WARN] [FML]: The coremod ApotheosisCore (shadows.ApotheosisCore) is not signed!
[00:07:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.4.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:07:58] [main/WARN] [FML]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[00:07:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in BetterFoliage-MC1.12-2.3.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:07:58] [main/WARN] [FML]: The coremod BetterFoliageLoader (mods.betterfoliage.loader.BetterFoliageLoader) is not signed!
[00:07:58] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[00:07:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Bloodmoon-MC1.12.2-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:07:58] [main/WARN] [FML]: The coremod lumien.bloodmoon.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:07:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.2.31.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:07:58] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:07:58] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[00:07:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in DynamicLights-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:07:58] [main/WARN] [FML]: The coremod atomicstryker.dynamiclights.common.DLFMLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:07:58] [main/WARN] [FML]: The coremod DLFMLCorePlugin (atomicstryker.dynamiclights.common.DLFMLCorePlugin) is not signed!
[00:07:58] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from DynamicSurroundings-1.12.2-3.6.1.0.jar
[00:07:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:07:58] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:07:58] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[00:07:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:07:58] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:07:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.12.2-0.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:07:58] [main/WARN] [FML]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:07:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-178.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:07:58] [main/WARN] [FML]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[00:07:58] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:07:58] [main/INFO] [LaunchWrapper]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[00:07:58] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[00:07:58] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/dmak4/Downloads/mmc-stable-win32/MultiMC/instances/1.12.2/.minecraft/mods/DynamicSurroundings-1.12.2-3.6.1.0.jar Service=LaunchWrapper Env=CLIENT
[00:07:58] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[00:07:58] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[00:07:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:07:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:07:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:07:59] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[00:07:59] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[00:07:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:07:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.lang.NoClassDefFoundError: com/endertech/minecraft/mods/adchimneys/world/WorldData$BlockRandomTick
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at com.endertech.minecraft.mods.adchimneys.LoadingPlugin.getASMTransformerClass(LoadingPlugin.java:17)
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129)
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[00:07:59] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 12 more
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoClassDefFoundError: com/endertech/minecraft/forge/coremod/hooks/BlockRandomTickHook
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 14 more
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: com.endertech.minecraft.forge.coremod.hooks.BlockRandomTickHook
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:07:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	... 18 more
[00:07:59] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[00:07:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[00:07:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[00:07:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[00:07:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[00:07:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[00:07:59] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.
Clipboard copy at: 21 Jun 2020 00:10:40 -0500

Additional Info:
---------------------------

**Comment by QuImUfu** [comment]
Advanced Chimneys requires ForgeEndertech. Install it.

**Comment by Forkk** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's discord, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
