### ISSUE TITLE
i can't start the game

### ISSUE THREAD

**Issue by sss880303** [MultiMC/MultiMC5#3214]
System Information
-----------------------------
MultiMC version:5

Operating System:windows 10

Logs/Screenshots:
----------------------------
[//]: MultiMC version: 0.6.11-1430

Minecraft folder is:
C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/instances/1.15.2/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java 版本為 1.8.0_241，使用64位元架構.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/instances/1.15.2/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.15.2/minecraft-1.15.2-client.jar

Native libraries:
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/instances/1.15.2/.minecraft --assetsDir C:/Users/user/Desktop/MINECRAFT/mmc-stable-win32/MultiMC/assets --assetIndex 1.15 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx6144m, -Duser.language=en]

Minecraft 處理序 ID: 2160

Using onesix launcher.

Exception in thread "main" java.lang.InternalError: java.util.zip.ZipException: zip file is empty
	at sun.misc.URLClassPath$JarLoader.getResource(Unknown Source)
	at sun.misc.URLClassPath.getResource(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.util.ResourceBundle$RBClassLoader.loadClass(Unknown Source)
	at java.util.ResourceBundle$Control.newBundle(Unknown Source)
	at java.util.ResourceBundle.loadBundle(Unknown Source)
	at java.util.ResourceBundle.findBundle(Unknown Source)
	at java.util.ResourceBundle.findBundle(Unknown Source)
	at java.util.ResourceBundle.getBundleImpl(Unknown Source)
	at java.util.ResourceBundle.getBundle(Unknown Source)
	at java.util.logging.Logger$1.run(Unknown Source)
	at java.util.logging.Logger$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.Logger.findSystemResourceBundle(Unknown Source)
	at java.util.logging.Logger.findResourceBundle(Unknown Source)
	at java.util.logging.Logger.setupResourceInfo(Unknown Source)
	at java.util.logging.Logger.<init>(Unknown Source)
	at java.util.logging.LogManager$SystemLoggerContext.demandLogger(Unknown Source)
	at java.util.logging.LogManager.demandSystemLogger(Unknown Source)
	at java.util.logging.Logger.getPlatformLogger(Unknown Source)
	at java.util.logging.LoggingProxyImpl.getLogger(Unknown Source)
	at sun.util.logging.LoggingSupport.getLogger(Unknown Source)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.<init>(Unknown Source)
	at sun.util.logging.PlatformLogger.redirectToJavaLoggerProxy(Unknown Source)
	at sun.util.logging.PlatformLogger.redirectPlatformLoggers(Unknown Source)
	at java.util.logging.LogManager$3.run(Unknown Source)
	at java.util.logging.LogManager$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.readPrimordialConfiguration(Unknown Source)
	at java.util.logging.LogManager.access$800(Unknown Source)
	at java.util.logging.LogManager$2.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.ensureLogManagerInitialized(Unknown Source)
	at java.util.logging.LogManager.getLogManager(Unknown Source)
	at java.util.logging.Logger.demandLogger(Unknown Source)
	at java.util.logging.Logger.getLogger(Unknown Source)
	at com.sun.jmx.remote.util.ClassLogger.<init>(Unknown Source)
	at javax.management.NotificationBroadcasterSupport.<clinit>(Unknown Source)
	at javax.management.MBeanServerDelegate.<init>(Unknown Source)
	at com.sun.jmx.mbeanserver.MBeanServerDelegateImpl.<init>(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.newMBeanServerDelegate(Unknown Source)
	at javax.management.MBeanServerBuilder.newMBeanServerDelegate(Unknown Source)
	at javax.management.MBeanServerFactory.newMBeanServer(Unknown Source)
	at javax.management.MBeanServerFactory.createMBeanServer(Unknown Source)
	at javax.management.MBeanServerFactory.createMBeanServer(Unknown Source)
	at java.lang.management.ManagementFactory.getPlatformMBeanServer(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:139)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:556)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:537)
	at net.minecraft.client.main.Main.<clinit>(SourceFile:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at sun.misc.URLClassPath$JarLoader.getJarFile(Unknown Source)
	at sun.misc.URLClassPath$JarLoader.access$800(Unknown Source)
	at sun.misc.URLClassPath$JarLoader$1.run(Unknown Source)
	at sun.misc.URLClassPath$JarLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath$JarLoader.ensureOpen(Unknown Source)
	... 70 more
程序已退出，代碼:1。
Clipboard copy at: 25 Jun 2020 00:14:50 +0800

Additional Info:
---------------------------

**Comment by Janrupf** [comment]
Try re-creating the instance, something got corrupted

**Comment by Forkk** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
