### ISSUE TITLE
My modpack worked fine, i didnt play in it for some time but now, it just crashes.

### ISSUE THREAD

**Issue by Marreta1** [MultiMC/MultiMC5#3220]
MultiMC version: 0.6.12-develop-1456

Minecraft folder is:
D:/MultiMC/instances/JP_Modpack/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_251, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  D:/MultiMC/instances/JP_Modpack/natives

Libraries:
  D:/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  D:/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  D:/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  D:/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  D:/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  D:/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  D:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  D:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  D:/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  D:/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-universal.jar
  D:/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  D:/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  D:/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  D:/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  D:/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  D:/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  D:/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  D:/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  D:/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  D:/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  D:/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  D:/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  D:/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  D:/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  D:/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  D:/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  D:/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  D:/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  D:/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  D:/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  D:/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] [1.12.2]+SecurityCraft+v1.8.17
  [✔️] [1.12]bspkrsCore-universal-7.6.0.1
  [✔️] [1.12]TreeCapitator-client-1.43.0
  [📁] 1.12 (folder)
  [✔️] ae2stuff-0.7.0.4-mc1.12.2
  [✔️] AmbientSounds_v3.0.12_mc1.12.2
  [✔️] AppleSkin-mc1.12-1.0.9
  [✔️] appliedenergistics2-rv6-stable-7
  [✔️] AutoRegLib-1.3-32
  [✔️] Baubles-1.12-1.5.2
  [✔️] BetterFoliage-MC1.12-2.2.0
  [✔️] Blur-1.0.4-14
  [✔️] Chisel-MC1.12.2-1.0.1.44
  [✔️] chiselsandbits-14.33
  [✔️] Clumps-3.1.2
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal
  [✔️] CoFHCore-1.12.2-4.6.3.27-universal
  [✔️] CoFHWorld-1.12.2-1.3.1.7-universal
  [✔️] CookingForBlockheads_1.12.2-6.4.71
  [✔️] CosmeticArmorReworked-1.12.2-v4a
  [✔️] CosmicLib-1.12.2-0.4.0.BETA
  [✔️] CreativeCore_v1.10.10_mc1.12.2
  [✔️] CTM-MC1.12.2-0.3.3.22
  [✔️] CustomMainMenu-MC1.12.2-2.0.9.1
  [✔️] cxlibrary-1.12.1-1.6.1
  [✔️] DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA
  [✔️] ElevatorMod-1.12.2-1.3.12
  [❌] EnderCore-1.12.2-0.5.73.jar (disabled)
  [❌] EnderIO-1.12.2-5.1.55.jar (disabled)
  [❌] EnderStorage-1.12.2-2.4.6.137-universal.jar (disabled)
  [❌] Flan's Mod-1.12.2-5.5.1.jar (disabled)
  [✔️] foamfix-0.12.1
  [✔️] fossilsarcheology-8.0.4
  [✔️] FpsReducer-mc1.12.2-1.12.4
  [✔️] furniture-6.3.1-1.12.2
  [✔️] Guide-API-1.12-2.1.8-63
  [✔️] InventoryTweaks-1.63
  [✔️] ironchest-1.12.2-7.0.72.847
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] jei_1.12.2-4.15.0.291
  [✔️] JurassiCraft-1.12.2-2.1.23
  [✔️] JustSleep-1.0.0.1
  [✔️] KleeSlabs_1.12.2-5.4.12
  [✔️] Level+Up!+2-1.1.23-1.12
  [✔️] llibrary-1.7.19-1.12.2
  [✔️] Mantle-1.12-1.3.3.55
  [📁] memory_repo (folder)
  [✔️] MobController-1.12.2-1.1
  [✔️] MoreFurnaces-1.12.2-1.10.6
  [✔️] MrTJPCore-1.12.2-2.1.4.43-universal
  [✔️] mw-1.11.7.7_mc1.12.2
  [❌] NuclearCraft-2.18q-1.12.2.jar (disabled)
  [✔️] OptiFine_1.12.2_HD_U_F5
  [✔️] OreLib-1.12.2-3.5.2.2
  [✔️] ProjectE-1.12.2-PE1.4.1
  [✔️] randomtweaks-1.12.2-2.5.0.3
  [✔️] RebornCore-1.12.2-3.19.3.524-universal
  [✔️] RedstoneArsenal-1.12.2-2.6.3.18-universal
  [✔️] RedstoneFlux-1.12-2.1.0.6-universal
  [✔️] SleepingOverhaul-1.12.2-1.0.0
  [❌] ThermalDynamics-1.12.2-2.5.5.21-universal.jar (disabled)
  [❌] ThermalExpansion-1.12.2-5.5.4.43-universal.jar (disabled)
  [❌] ThermalFoundation-1.12.2-2.6.3.27-universal.jar (disabled)
  [❌] ThermalInnovation-1.12.2-0.3.3.12-universal.jar (disabled)
  [✔️] TickrateChanger-1.0.14
  [✔️] TravellersBackpack-1.12.2-1.0.20.20
  [✔️] trumpetskeleton-1.12-1.0.2.1

Params:
  --username  --version MultiMC5 --gameDir D:/MultiMC/instances/JP_Modpack/.minecraft --assetsDir D:/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx6800m, -Duser.language=en]

Minecraft process ID: 13080

Using onesix launcher.

[20:57:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:57:11] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:57:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:57:11] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[20:57:11] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_251, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_251
[20:57:13] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[20:57:13] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[20:57:13] [main/INFO] [FML]: Searching D:\MultiMC\instances\JP_Modpack\.minecraft\mods for mods
[20:57:13] [main/INFO] [FML]: Searching D:\MultiMC\instances\JP_Modpack\.minecraft\mods\1.12.2 for mods
[20:57:14] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in BetterFoliage-MC1.12-2.2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:57:14] [main/WARN] [FML]: The coremod BetterFoliageLoader (mods.betterfoliage.loader.BetterFoliageLoader) is not signed!
[20:57:14] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Blur-1.0.4-14.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:57:14] [main/WARN] [FML]: The coremod com.tterrag.blur.BlurPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:57:14] [main/WARN] [FML]: The coremod BlurPlugin (com.tterrag.blur.BlurPlugin) is not signed!
[20:57:14] [main/INFO] [FML]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[20:57:14] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CosmicLib-1.12.2-0.4.0.BETA.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:57:14] [main/WARN] [FML]: The coremod com.cosmicdan.cosmiclib.asm.FakeCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:57:14] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CreativeCore_v1.10.10_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:57:14] [main/WARN] [FML]: The coremod com.creativemd.creativecore.core.CreativePatchingLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:57:14] [main/WARN] [FML]: The coremod CreativePatchingLoader (com.creativemd.creativecore.core.CreativePatchingLoader) is not signed!
[20:57:14] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.3.22.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:57:14] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:57:14] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[20:57:14] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in cxlibrary-1.12.1-1.6.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:57:14] [main/WARN] [FML]: The coremod cubex2.cxlibrary.CoreModLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:57:14] [main/WARN] [FML]: The coremod CXLibraryCore (cubex2.cxlibrary.CoreModLoader) is not signed!
[20:57:14] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:57:14] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:57:14] [main/WARN] [FML]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:57:14] [main/WARN] [FML]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
[20:57:14] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in mw-1.11.7.7_mc1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:57:14] [main/WARN] [FML]: The coremod weaponlib (com.vicmatskiv.weaponlib.core.WeaponlibCorePlugin) is not signed!
[20:57:14] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_F5.jar
[20:57:14] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in TickrateChanger-1.0.14.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:57:14] [main/WARN] [FML]: The coremod me.guichaguri.tickratechanger.TickrateChanger does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:57:14] [main/WARN] [FML]: The coremod TickrateChanger (me.guichaguri.tickratechanger.TickrateChanger) is not signed!
[20:57:14] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:57:14] [main/INFO] [LaunchWrapper]: Loading tweak class name codechicken.asm.internal.Tweaker
[20:57:14] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[20:57:14] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:57:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:57:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:57:14] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[20:57:14] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[20:57:14] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[20:57:14] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[20:57:14] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: D:\MultiMC\instances\JP_Modpack\.minecraft\mods\OptiFine_1.12.2_HD_U_F5.jar
[20:57:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:57:16] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[20:57:16] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[20:57:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:57:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:57:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:57:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:57:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:57:16] [main/INFO] [LaunchWrapper]: Calling tweak class codechicken.asm.internal.Tweaker
[20:57:16] [main/INFO] [STDOUT]: [codechicken.asm.internal.Tweaker:injectIntoClassLoader:30]: false
[20:57:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:57:16] [main/INFO] [CosmicLib/FakeCoreMod]: [i] FakeCoreMod loading ASM helper classes...
[20:57:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:57:16] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:57:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:57:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:57:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.lang.NoClassDefFoundError: kotlin/reflect/KDeclarationContainer
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at mods.betterfoliage.loader.Refs.<clinit>(Refs.kt:13)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at mods.betterfoliage.loader.BetterFoliageTransformer.<init>(BetterFoliageCore.kt:13)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Class.newInstance(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at $wrapper.mods.betterfoliage.loader.BetterFoliageTransformer.<init>(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Class.newInstance(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:57:17] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[20:57:17] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: kotlin.reflect.KDeclarationContainer
[20:57:17] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[20:57:17] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 26 more
[20:57:17] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[20:57:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[20:57:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[20:57:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[20:57:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.
Clipboard copy at: 27 Jun 2020 21:25:42 +0100

**Comment by peterix** [comment]
Either remove BetterFoliage or add Forgelin.
