### ISSUE TITLE
BLood N bones not launching

### ISSUE THREAD

**Issue by dablade11577** [MultiMC/MultiMC5#3226]
MultiMC version: 0.6.11-1430

Minecraft folder is:
C:/Users/aaron/Desktop/game launchers/MultiMC/instances/BloodNBones-1.1.5-1.6.4/minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_251, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/aaron/Desktop/game launchers/MultiMC/instances/BloodNBones-1.1.5-1.6.4/natives

Libraries:
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/argo/argo/2.25_fixed/argo-2.25_fixed.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/com/google/guava/guava/14.0/guava-14.0.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/net/minecraftforge/forge/1.6.4-9.11.1.965/forge-1.6.4-9.11.1.965-universal.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/net/minecraft/launchwrapper/1.8/launchwrapper-1.8.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/org/scala-lang/scala-compiler/2.10.2/scala-compiler-2.10.2.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/com/mojang/minecraft/1.6.4/minecraft-1.6.4-client.jar

Native libraries:
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/aaron/Desktop/game launchers/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Mods:
  [✔️] [1.6.4]ArmorStatusHUDv1.15
  [✔️] [1.6.4]bspkrsCorev5.2
  [✔️] [1.6.4]StatusEffectHUDv1.19
  [📁] 1.6 (folder)
  [✔️] appeng-rv14-finale3-mc16x
  [✔️] backpack-1.28.37-1.6.x
  [✔️] bigReactors-0.3.3A
  [✔️] biomesOPlenty-universal-1.6.4-1.2.1.416
  [✔️] Blood Magic v1.0.1g
  [✔️] BnBTweaks-mc1.6.4-0.1.4
  [✔️] CaveControl 1.6 v25z
  [✔️] chickenChunks 1.3.3.4
  [✔️] CodeChickenCore-1.6.4-0.9.0.9-universal
  [✔️] CoFHCore-2.0.0.5
  [✔️] computerCraft1.63
  [✔️] configMod for MC v1.6.4
  [✔️] coroAI for MC v1.6.4
  [✔️] creeperCollateral-1.6.4-3.0.3
  [✔️] customChestLoot 1.1 for MC 1.6.2
  [✔️] damageIndicatorsv2.9.2.4
  [✔️] deadlyWorld 1.0.2 for MC 1.6.2
  [📁] denLib (folder)
  [✔️] denLib-1.6.4-3.2.6
  [✔️] DragonAPI 1.6 v25z
  [✔️] dynamicLights_1.6.4
  [✔️] dynamicTanks2_v0.0.8a
  [✔️] EnderForest 1.6 v25z
  [✔️] enhancedPortals-1.6.4-3.0.0b5e
  [✔️] Evoc_1.0.0a
  [✔️] extendedRenderer for MC v1.6.4
  [✔️] ExtraTiC-1.6.4-0.8.4
  [✔️] extrautils-1.0.3c
  [✔️] flatsigns-1.6.2-universal-1.4.0.15
  [✔️] gases-1.4.4.3-1.6.4
  [✔️] gasesCore-1.4.4.3-1.6.4
  [✔️] gasesFramework-1.0.3.1-1.6.4
  [✔️] gasesFrameworkCore-1.0.3.1-1.6.4
  [✔️] HardcoreEnderExpansion 1.6.1
  [✔️] HarvestCraftWaila-mc1.6.4-1.0.4
  [✔️] hostile Worlds v0.4 Alpha Mod for MC v1.6.4
  [✔️] hungeroverhaul-1.6.X-2l-build3
  [✔️] iguanatweaks-1.6.X-1i-build4
  [✔️] inventoryTweaks-MC1.6.2-1.56-b77
  [✔️] JABBA_1.1.4
  [✔️] KeithyUtils-1.6.4-1.3.30
  [✔️] LycanitesMobsComplete 1.5.1h [1.6.4]
  [✔️] magical_crops_1.6.4_3.2.0_BETA_15a
  [✔️] Metallurgy-1.6.4-3.4.0.29
  [✔️] MineFactoryReloaded-2.7.9-final
  [✔️] MobiusCore_1.2.2_1.6.4
  [✔️] modBuild for MC v1.6.4
  [✔️] ModTweaker-1.6.4-0.3
  [✔️] Natura_mc1.6.X_2.1.14
  [✔️] naturalAbsorption 1.2 for MC 1.6.4
  [✔️] neiaddons-mc164-1.10.4.64
  [✔️] neiplugins-1.1.0.6
  [✔️] NetherOres-2.2.3-final
  [✔️] notEnoughItems 1.6.1.9
  [✔️] obsidiplates-1.6.2-universal-2.0.0.15
  [✔️] Opis_1.2.2
  [✔️] pam's HarvestCraft 1.6.4 v1.1.4
  [✔️] particle Man v1.4 Mod for MC v1.6.4
  [✔️] PowerCrystalsCore-1.1.8-9
  [✔️] projectRedBase-1.6.4-4.3.5.30
  [✔️] projectRedCompat-1.6.4-4.3.5.30
  [✔️] projectRedIntegration-1.6.4-4.3.5.30
  [✔️] projectRedLighting-1.6.4-4.3.5.30
  [✔️] projectRedMechanical-BETA-1.6.4-4.3.5.30
  [✔️] projectRedWorld-1.6.4-4.3.5.30
  [✔️] Random_Things_v._1.9__MC_1.6.4_
  [✔️] remoteIO-universal-1.6.4-1.11
  [✔️] roguelike-v1.3.3-forge-1.6.4
  [✔️] sortFix-1.0
  [✔️] specialAI 1.0 PRE for MC 1.6.4
  [✔️] specialMobs 3.0 PRE for MC 1.6.2
  [✔️] SpiceOfLife-mc1.6.4-1.1.1
  [✔️] TConstruct_mc1.6.4_1.5.5.7
  [✔️] ThermalExpansion-3.0.0.7
  [✔️] TiCTooltips-mc1.6.4-1.1.8a
  [✔️] tictweaks-1.6.4-1.0.3
  [✔️] TSteelworks-mc1.6.4_0.0.4.2-fix2
  [✔️] utilityMobs 2.1 for MC 1.6.2
  [✔️] Waila_1.5.2a
  [✔️] WailaHarvestability-mc1.6.4-1.1.0
  [✔️] witchery-1.6.4-0.19.2
  [✔️] zMineTweaker-1.6.4-2.3.1
  [✔️] zombie Awareness v1.9 Mod for MC v1.6.4

Params:
  --username  --session  --version MultiMC5 --gameDir C:/Users/aaron/Desktop/game launchers/MultiMC/instances/BloodNBones-1.1.5-1.6.4/minecraft --assetsDir C:/Users/aaron/Desktop/game launchers/MultiMC/assets/virtual/legacy --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 1600 x 900

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1536m, -Xmx12544m, -Duser.language=en]

Minecraft process ID: 10668

Using onesix launcher.

Jul 01, 2020 12:46:58 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
Jul 01, 2020 12:46:58 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
Jul 01, 2020 12:46:58 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
2020-07-01 12:46:59 [INFO] [ForgeModLoader] Forge Mod Loader version 6.4.49.965 for Minecraft 1.6.4 loading
2020-07-01 12:46:59 [INFO] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_251, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_251
2020-07-01 12:46:59 [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:00 [WARNING] [ForgeModLoader] The coremod worldcore.asm.WCFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:00 [WARNING] [ForgeModLoader] The coremod appeng.transformer.AppEngCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:00 [INFO] [ForgeModLoader] [AppEng] Core Init
2020-07-01 12:47:00 [WARNING] [ForgeModLoader] The coremod biomesoplenty.asm.BOPFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [INFO] [STDERR] Warning: version of ForgeMultipart-universal-1.6.4-, 1.0.1.268 is newer than request 1.0.0.244
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod eyamaz.bnbtweaks.asm.ASMPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod denoflionsx.CreeperCollateral.CoreMod.CCCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod denoflionsx.denLib.CoreMod.denLibCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod atomicstryker.dynamiclights.common.DLFMLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod mcp.mobius.evoc.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod glenn.gases.core.EDFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod glenn.gasesframework.core.EDFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod mcp.mobius.mobiuscore.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod mrtjp.projectred.compatibility.CompatibilityCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod lumien.randomthings.Transformer.RTLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod squeek.spiceoflife.asm.ASMPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [WARNING] [ForgeModLoader] The coremod tconstruct.preloader.TConstructLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2020-07-01 12:47:03 [INFO] [TCon-Preloader] Scalpel. Suction. Lumber axe. CLEAR! *zap*
2020-07-01 12:47:03 [INFO] [TCon-Preloader] Constructing preloader (Modules: [tconstruct.preloader.AccessTransformers, tconstruct.preloader.ASMInterfaceRepair])
2020-07-01 12:47:03 [INFO] [TCon-Preloader] Found a properties file. Attempting load...
2020-07-01 12:47:03 [INFO] [TCon-Preloader] Loaded properties successfully. Using specified settings.
2020-07-01 12:47:03 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2020-07-01 12:47:03 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
2020-07-01 12:47:03 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2020-07-01 12:47:03 [SEVERE] [ForgeModLoader] Unable to launch
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.remove(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with code 0.
MultiMC: Log upload triggered at: 01 Jul 2020 12:49:01 -0600

**Comment by Zetabite** [comment]
please upload your log properly: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by dablade11577** [comment]
[fix] cant run the game online you have to launch offline

**Comment by Forkk** [comment]
This issue is being closed for inactivity, and the issue template is not filled out properly. If you're still having trouble with this, please re-open it with your log uploaded correctly.
