### ISSUE TITLE
Failed to start minecraft with mods

### ISSUE THREAD

**Issue by litch0** [MultiMC/MultiMC5#3327]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: Arch linux

Summary of the issue or suggestion:
----------------------------------------------
Falied to start minecraft
```Console
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

What should happen:
------------------------------
Open Minrcraft

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download FTB Infinity Lite with the modpack manager

2. Launch the profile

3. Issue Happens

Suspected cause:
---------------------------
Don't know, I never programed with java

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/57605930/91992983-36522e00-ed0b-11ea-845e-788ff517b1b0.png)

Additional Info:
---------------------------
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12)
OpenJDK 64-Bit Server VM (build 14.0.2+12, mixed mode)

**Comment by litch0** [comment]
Also, I have minecraft in flatpack

**Comment by litch0** [comment]
I tried the normal installation with aur package, same error

**Comment by litch0** [comment]
ok thanks

**Comment by litch0** [comment]
Update, I installed the OpenJDK 8 and every thing worked fine

**Comment by eternaldensity** [comment]
Ohhhhhh.  I shouldn't have clicked that Java update notification.
