### ISSUE TITLE
fabrc mod loader doesent work, is says: Process exited with code 255.

### ISSUE THREAD

**Issue by giukio06** [MultiMC/MultiMC5#3364]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: macOS X el captain

Summary of the issue or suggestion: the process exited with code 255 when i used fabric mod loader to load a mod
----------------------------------------------

What should happen: the game should run 
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. add a new instance (doesn't matter the game version)

2. edit it and install fabric and forge mod loader

3. launch the game

Suspected cause: java.lang.SecurityException
---------------------------

Logs/Screenshots: 
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.SecurityException: class "org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:891)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.initializeTransformers(KnotClassDelegate.java:76)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:136)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
[mExiting with -1
Process exited with code 255.
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by jamierocks** [comment]
The crash here is caused by Fabric using a fork of Mixin, and MMC doesn't detect them as the same artefact - so Fabric's classloader, which supports code signing, trips when a class specific to their fork is loaded but since the original is higher in the classpath, the code signing classes when classes in the same package are loaded from the original.

On a practical note, the further Fabric deviates from standard Mixin - the more unlikely an environment supporting Fabric Loader on FML becomes.

---

Anyhow, your environment wouldn't work as you expect anyhow.

> edit it and install fabric and forge mod loader

Neither support the other - even if there weren't collision such as the above, you would only ever get into game with 1 loader working.

**Comment by peterix** [comment]
This is not intended to work. Only one mod loader can be installed at one time.
