### ISSUE TITLE
Multimc refuses to launch minecraft

### ISSUE THREAD

**Issue by TheStarfishMan** [MultiMC/MultiMC5#3366]
System Information
-----------------------------
MultiMC version:
MultiMC5
Operating System:
Windows 10
Summary of the issue or suggestion:
----------------------------------------------
MultiMC gives an error when I try to launch mc using Roguelike Dungeons and adventures modpack.

What should happen:
------------------------------
It should launch.

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.

 
Additional Info:
---------------------------

**Comment by TheStarfishMan** [comment]
K Sorry about that, how do I upload log?

**Comment by TheStarfishMan** [comment]
I used the 64 bit versiona nd it worked! Sry for the trouble!
