### ISSUE TITLE
Cannot join Minecraft Alpha server due to "Player is null"

### ISSUE THREAD

**Issue by compu42** [MultiMC/MultiMC5#3454]
System Information
-----------------------------
MultiMC version: 0.6.11-1344

Operating System: Fedora Linux 33

Summary of the issue or suggestion: When attempting to connect to an Alpha Minecraft server (server 0.2.8 and client a1.2.6), it cases a java.lang.NullPointerException and reports that the "Player is null" Running the game in offline mode, so that a custom username can be chosen, does not fix this issue.
----------------------------------------------

What should happen: The client should be able to connect to the server using the custom username selected in offline mode.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Run MultiMC and create a new instance for Minecraft Alpha 1.2.6
2. Run a Minecraft Server with version 0.2.8. [Can be found here](https://minecraft.gamepedia.com/Java_Edition_Alpha_server_0.2.8)
3. press Launch Offline and choose any username (I chose "yuri")
4. Attempt to connect to your running server.
5. See this
![image](https://user-images.githubusercontent.com/56663749/99927936-0aa97780-2d3f-11eb-8819-7afe5c25ca99.png)
6. You cannot join.
Suspected cause: Something is causing the name to not change, or to change to null/nothing.
---------------------------

Logs/Screenshots:
```
MultiMC version: 0.6.11-1344


Minecraft folder is:
/home/yuri/Games/minecraft/instances/a1.2.6/.minecraft


Java path is:
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.272.b10-0.fc33.x86_64/jre/bin/java


Java is version 1.8.0_272, using 64-bit architecture.


AMD FX(tm)-8350 Eight-Core Processor
Advanced Micro Devices, Inc. [AMD/ATI] Tonga XT / Amethyst XT [Radeon R9 380X / R9 M295X] (rev f1)

Subsystem: Tul Corporation / PowerColor Radeon R9 380X

Kernel driver in use: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.2.2

Main Class:
  

Native path:
  /home/yuri/Games/minecraft/instances/a1.2.6/natives

Traits:
traits legacyLaunch
traits texturepacks

Libraries:
  /home/yuri/Games/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/yuri/Games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/yuri/Games/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/yuri/Games/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/yuri/Games/minecraft/libraries/com/mojang/minecraft/a1.2.6/minecraft-a1.2.6-client.jar

Native libraries:
  /home/yuri/Games/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/yuri/Games/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
  

Window size: max (if available)

Java Arguments:
[-Xms512m, -Xmx2048m, -Duser.language=en]


Minecraft process ID: 92020


Using onesix launcher.

Launching with applet wrapper...
28
Setting user: yuri, -
Nov 22, 2020 9:49:46 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.LinuxEnvironmentPlugin
Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event0): Failed to open device /dev/input/event0 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event1): Failed to open device /dev/input/event1 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event10): Failed to open device /dev/input/event10 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event11): Failed to open device /dev/input/event11 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event12): Failed to open device /dev/input/event12 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event13): Failed to open device /dev/input/event13 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event14): Failed to open device /dev/input/event14 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event15): Failed to open device /dev/input/event15 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event16): Failed to open device /dev/input/event16 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event17): Failed to open device /dev/input/event17 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event18): Failed to open device /dev/input/event18 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event19): Failed to open device /dev/input/event19 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event2): Failed to open device /dev/input/event2 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event20): Failed to open device /dev/input/event20 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event3): Failed to open device /dev/input/event3 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event4): Failed to open device /dev/input/event4 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event5): Failed to open device /dev/input/event5 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event6): Failed to open device /dev/input/event6 (13)



Starting up SoundSystem...
Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event7): Failed to open device /dev/input/event7 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event8): Failed to open device /dev/input/event8 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event9): Failed to open device /dev/input/event9 (13)


Nov 22, 2020 9:49:46 PM net.java.games.input.ControllerEnvironment log
INFO: Linux plugin claims to have found 0 controllers

Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

Player is null
java.net.SocketException: Socket closed
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at java.net.Socket.<init>(Socket.java:452)
	at java.net.Socket.<init>(Socket.java:262)
	at ib.<init>(SourceFile:32)
	at oy.run(SourceFile:20)
Player is null
java.lang.NullPointerException
	at ib.a(SourceFile:314)
	at hw.a(SourceFile:24)
	at jq.a(SourceFile:223)
	at ib.a(SourceFile:39)
	at og.g(SourceFile:40)
	at net.minecraft.client.Minecraft.i(SourceFile:1004)
	at net.minecraft.client.Minecraft.run(SourceFile:595)
	at java.lang.Thread.run(Thread.java:748)
Player is null
```
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
There doesn't seem to be anything wrong with the server, as the server just says:
```
[INFO] /[ip address here]:[port here] lost connection
```
---------------------------

**Comment by QuImUfu** [comment]
This may be an issue with your system blocking connections or closing Sockets, that server/client combi works for me.

**Comment by compu42** [comment]
This might be true, but socket exception error only happens on the first try. All subsequent tries result in a nullPointerException.I'll try it without a firewall later.

**Comment by compu42** [comment]
After testing this with the firewall service entirely disabled (allowing any and all connections to the computer to be made), it still results in the `java.lang.nullPointerException` error.

```
java.lang.NullPointerException
	at ib.a(SourceFile:314)
	at hw.a(SourceFile:24)
	at jq.a(SourceFile:223)
	at ib.a(SourceFile:39)
	at og.g(SourceFile:40)
	at net.minecraft.client.Minecraft.i(SourceFile:1004)
	at net.minecraft.client.Minecraft.run(SourceFile:595)
	at java.lang.Thread.run(Thread.java:748)
Player is null
```

**Comment by QuImUfu** [comment]
Still no idea why that SocketException would happen, if not because of outside influences, but the NullPointerException can be worked around by disabling online mode in `server.properties`.  
It happens because Mojang doesn't support the way of authentication used in these ancient minecraft versions any more, resulting in a null string if authentication is used.

**Comment by peterix** [comment]
This appears to be a game specific problem, not a launcher problem... Please bring these to our discord #minecraft channel next time.

**Comment by compu42** [comment]
Hey! changing server.properties fixes it! Thanks

**Comment by Xiarno** [comment]
> Hey! changing server.properties fixes it! Thanks

I'm trying to find a fix to this problem. Changing what in server.properties ? Thanks !

**Comment by AverageComet250** [comment]
@Xiarno I think he set `online-mode` to `false` in `server.properties`. By doing that, he basically disabled the server's user authentication, so you don't actually need a Minecraft account to play.

**Comment by ToruTheRedFox** [comment]
the "Player is null" is just a debug log that logs what class the player reference is set to, which at that time was currently set to null, which is completely normal
