### ISSUE TITLE
Trying to install Fabric on MultiMC, but game is not opening at all even without mods

### ISSUE THREAD

**Issue by fishburgerr** [MultiMC/MultiMC5#3484]
System Information
-----------------------------
MultiMC version:
0.6.11-1370

Operating System:
MacOS

Summary of the issue or suggestion: I am unable to launch Minecraft with Fabric installed, although there are currently no Fabric mods installed. The regular launcher with Forge mods loaded runs fine.
----------------------------------------------

What should happen: Being able to launch Minecraft through MultiMC with Fabric loaded.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. I added a new instance, and selected "Install Fabric" for the latest version of MC.

2. The intermediary mappings and fabric loader appeared to be installed by MultiMC (all latest versions)

3. When I select launch, the process is exited with error code 255

Suspected cause: Someone on the Fabric discord mentioned a possible problem with "the crypto module in the java runtime"
---------------------------
Logs/Screenshots: https://paste.ee/p/Vc9Nn
----------------------------

**Comment by Zetabite** [comment]
provide a new log: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by Scotsguy** [comment]
Closing due to inactivity. (Paste expired)

**Comment by littleblack111** [comment]
MultiMC version: 0.6.14-3001


Launched instance in online mode

authserver.mojang.com resolves to:
    [13.227.55.75]

session.minecraft.net resolves to:
    [18.210.95.126, 34.231.157.213, 52.1.29.34]

textures.minecraft.net resolves to:
    [54.192.73.47, 54.192.73.90, 54.192.73.58, 54.192.73.86]

api.mojang.com resolves to:
    [54.192.16.140]


Minecraft folder is:
C:/Users/JJ/AppData/Roaming/MultiMC/instances/1.17.1/.minecraft


Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe


Checking Java version...
Java is version 16.0.2, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Users/JJ/AppData/Roaming/MultiMC/instances/1.17.1/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Using system OpenAL.
Using system GLFW.

Libraries:
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/com/mojang/blocklist/1.0.5/blocklist-1.0.5.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/com/github/oshi/oshi-core/5.7.5/oshi-core-5.7.5.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/net/java/dev/jna/jna-platform/5.8.0/jna-platform-5.8.0.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/com/mojang/javabridge/1.1.23/javabridge-1.1.23.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/com/mojang/authlib/2.3.31/authlib-2.3.31.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/net/fabricmc/intermediary/1.17.1/intermediary-1.17.1.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/net/fabricmc/tiny-remapper/0.6.0/tiny-remapper-0.6.0.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/net/fabricmc/access-widener/2.0.1/access-widener-2.0.1.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/net/fabricmc/fabric-loader/0.12.11/fabric-loader-0.12.11.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/com/mojang/minecraft/1.17.1/minecraft-1.17.1-client.jar

Native libraries:
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/JJ/AppData/Roaming/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/JJ/AppData/Roaming/MultiMC/instances/1.17.1/.minecraft --assetsDir C:/Users/JJ/AppData/Roaming/MultiMC/assets --assetIndex 1.17 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 28704


Using onesix launcher.

[10:47:21] [main/INFO]: Loading Minecraft 1.17.1 with Fabric Loader 0.12.11
[10:47:21] [main/INFO]: Loading 3 mods:
	- fabricloader 0.12.11
	- java 16
	- minecraft 1.17.1
[10:47:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/JJ/AppData/Roaming/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[10:47:28] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:47:29] [Render thread/INFO]: Setting user: littleblack111
[10:47:29] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[10:47:29] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[10:47:29] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[10:47:30] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:604) ~[fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
	at com.mojang.blaze3d.platform.GLX.getOpenGLVersionString(GLX.java:35) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.getApiDescription(RenderSystem.java:770) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2418) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2412) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:187) ~[minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602) ~[fabric-loader-0.12.11.jar:?]
	... 10 more
进程退出，代码：1。
Clipboard copy at: 27 Jan 2022 10:47:32 +0800

**Comment by littleblack111** [comment]
what about this
