### ISSUE TITLE
multimc just keep crash at initialize stage

### ISSUE THREAD

**Issue by kingdom84521** [MultiMC/MultiMC5#3534]
I'm trying to import some modpacks which i download from curseforge ( import via .zip )
and it just keep crashing at the initialize stage
I'm not really sure if it is the modpack's problem or multimc's
cause i have been tried many different packs and the error respond is similar
this log below is generated when i import "Life in the village 2" modpack
if you need the link of the modpack, its right here: [Link](https://www.curseforge.com/minecraft/modpacks/life-in-the-village-2/files/3165195)
and here is the log

----------------------------------------------
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/17/21, 1:08 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at doggytalents.ModBlocks.registerBlockColours(ModBlocks.java:46) ~[?:1.15.2.3] {re:classloading,pl:object_holder_definalize:A}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.2] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1338) ~[?:?] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:smoothboot.mixins.json:ModListMixin,pl:mixin:A}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:419) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[minecraft-1.15.2-client.jar:?] {re:classloading,re:mixin,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.45-launcher.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {re:classloading}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97)
	at doggytalents.ModBlocks.registerBlockColours(ModBlocks.java:46)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
	at java.base/java.util.HashMap.forEach(HashMap.java:1338)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207)
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:419)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --

Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 13.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 954620624 bytes (910 MB) / 1400897536 bytes (1336 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx5120m
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.45-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.45-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.15.2-31.2.45-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.45-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.45-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.45
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		enchantedbookredesign-2.0a.jar Enchanted Book Redesign {enchantedbookredesign@2.0a CREATE_REGISTRIES}
		clayconversion-1.15-v1.5.jar Clay Conversion {clayconversion@1.5 CREATE_REGISTRIES}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 CREATE_REGISTRIES}
		Uppers-0.2.12.jar Uppers {uppers@0.2.12 CREATE_REGISTRIES}
		mcws-win-1.15.2-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 CREATE_REGISTRIES}
		TextDamageIndicators-1.15.2-1.0.1.jar TextDamageIndicators {textdamageindicators@1.0.1 CREATE_REGISTRIES}
		CTM-MC1.15.2-1.1.2.14.jar ConnectedTexturesMod {ctm@MC1.15.2-1.1.2.14 CREATE_REGISTRIES}
		CookingForBlockheads_1.15.2-8.0.3.jar Cooking for Blockheads {cookingforblockheads@8.0.3 CREATE_REGISTRIES}
		Controlling-6.1.5.6.jar Controlling {controlling@6.1.5.6 CREATE_REGISTRIES}
		ReAuth-1.14-1.15-3.8.1.jar ReAuth {reauth@3.8.1 CREATE_REGISTRIES}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 CREATE_REGISTRIES}
		ftb-gui-library-1.0.0.14.jar FTB GUI Library {ftbguilibrary@1.0.0.14 CREATE_REGISTRIES}
		jumbofurnace-1.15.2-1.0.0.2.jar Jumbo Furnace {jumbofurnace@1.15.2-1.0.0.2 CREATE_REGISTRIES}
		gemsnjewels-1.15.2-0.16.1.jar Gems & Jewels {gemsnjewels@0.13.1 CREATE_REGISTRIES}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 CREATE_REGISTRIES}
		guardvillagers-1.15.2-1.0.8.jar Guard Villagers {guardvillagers@1.0.7 ERROR}
		randompatches-1.15.2-1.22.1.1.jar RandomPatches {randompatches@1.15.2-1.22.1.1 CREATE_REGISTRIES}
		buildinggadgets-3.4.1.jar Building Gadgets {buildinggadgets@3.4.1 CREATE_REGISTRIES}
		Apotheosis-1.15.2-3.3.8.jar Apotheosis {apotheosis@3.3.8 CREATE_REGISTRIES}
		mcw-doors-1.0.1fix-mc1.15.1-2.jar Macaw's Doors {mcwdoors@1.0.1 CREATE_REGISTRIES}
		JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 CREATE_REGISTRIES}
		Bundles-1.3.jar Bundles! {bundles@1.3 CREATE_REGISTRIES}
		supplementaries-0.9.15_1.15.jar Supplementaries {supplementaries@0.9.15_1.15 CREATE_REGISTRIES}
		structure-gel-api-1.15.2-1.1.0.jar Structure Gel API {structure_gel@1.1.0 CREATE_REGISTRIES}
		PackMenu-1.15.2-1.2.8.jar Pack Menu {packmenu@1.2.8 CREATE_REGISTRIES}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 CREATE_REGISTRIES}
		finallyfarmabledyes-1.15.2-1.1.0.0.jar Finally Farmable Dyes {finallyfarmabledyes@1.1.0.0 CREATE_REGISTRIES}
		projectvibrantjourneys-1.15.2-2.0.4.jar Project: Vibrant Journeys {projectvibrantjourneys@1.15.2-2.0.4 CREATE_REGISTRIES}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 CREATE_REGISTRIES}
		thatched-1.0.jar Thatched Roof Villages {thatched@version CREATE_REGISTRIES}
		dungeons-plus-1.15.2-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 CREATE_REGISTRIES}
		edibles_1.15.2-2.0.jar Edibles {edibles@2.0 CREATE_REGISTRIES}
		fairylights-3.0.15-1.15.2.jar Fairy Lights {fairylights@3.0.15 CREATE_REGISTRIES}
		villagespawnpoint_1.15-1.2.jar Village Spawn Point {villagespawnpoint@1.2 CREATE_REGISTRIES}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 CREATE_REGISTRIES}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 CREATE_REGISTRIES}
		randomite-1.15.2-1.0.0.jar Randomite Classic {randomite@1.0.0 CREATE_REGISTRIES}
		collective-1.15.2-1.53.jar Collective {collective@1.53 CREATE_REGISTRIES}
		extlights-2.1.jar Extended Lights {extlights@2.1 CREATE_REGISTRIES}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 CREATE_REGISTRIES}
		blockcarpentry-1.15-0.8.2.jar BlockCarpentry {blockcarpentry@1.15-0.8.2 CREATE_REGISTRIES}
		SpawnInVillage-1.15.2-1.2.jar Spawn in Village {spawnvillage@1.2 CREATE_REGISTRIES}
		EndReborn [0.6.1].jar End: Reborn {endreborn@0.6.1 CREATE_REGISTRIES}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 CREATE_REGISTRIES}
		ftb-ultimine-1.0.8.5.jar FTB Ultimine {ftbultimine@1.0.8.5 CREATE_REGISTRIES}
		travelers_index-1.15.2-1.0.1.jar Traveler's Index {travelers_index@1.15.2-1.0.1 CREATE_REGISTRIES}
		starterkit_1.15.2-2.1.jar Starter Kit {starterkit@2.1 CREATE_REGISTRIES}
		mcws-roofs-1.15.2-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 CREATE_REGISTRIES}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 CREATE_REGISTRIES}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 CREATE_REGISTRIES}
		mcw-furniture-2.0.0-mc1.15.2.jar Macaw's Furniture {mcwfurnitures@2.0.0 CREATE_REGISTRIES}
		productivebees-1.15.2-0.5.2.9.jar Productive Bees {productivebees@1.15.2-0.5.2.9 CREATE_REGISTRIES}
		incubation-1.0.4-1.15.2.jar Incubation {incubation@1.0.4 CREATE_REGISTRIES}
		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 CREATE_REGISTRIES}
		BetterMineshaftsForge-1.15.2-1.3.1.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3.1 CREATE_REGISTRIES}
		DarkPaintings-1.15.2-1.0.6.jar DarkPaintings {darkpaintings@1.0.6 CREATE_REGISTRIES}
		cullparticles-1.0.jar Cull Particles {cullparticles@1.0 CREATE_REGISTRIES}
		BetterAdvancements-1.15.2-0.1.0.99.jar Better Advancements {betteradvancements@0.1.0.99 CREATE_REGISTRIES}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 CREATE_REGISTRIES}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 CREATE_REGISTRIES}
		SoundControl-1.15.2-1.0.0.2.jar §3Dynamic Surroundings: §eSound Control {sndctrl@1.15.2-1.0.0.1 CREATE_REGISTRIES}
		Cucumber-1.15.2-3.0.9.jar Cucumber Library {cucumber@3.0.9 CREATE_REGISTRIES}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 CREATE_REGISTRIES}
		item-filters-2.2.0.15.jar Item Filters {itemfilters@2.2.0.15 CREATE_REGISTRIES}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 CREATE_REGISTRIES}
		JEIEnchantmentInfo-1.16.4-1.2.1.jar JEI Enchantment Info {jeienchantmentinfo@1.16.4-1.2.1 CREATE_REGISTRIES}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 CREATE_REGISTRIES}
		Bamboo-Blocks-1.15.2-1.4.1.jar Bamboo Blocks {bambooblocks@NONE CREATE_REGISTRIES}
		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 CREATE_REGISTRIES}
		caelus-FORGE-1.15.2-2.0-beta3.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta3 CREATE_REGISTRIES}
		Upgrade-Aquatic-1.15.2-1.7.1.jar Upgrade Aquatic {upgrade_aquatic@1.7.1 CREATE_REGISTRIES}
		extraboats-1.3.6-1.15.2.jar Extra Boats {extraboats@1.3.6 CREATE_REGISTRIES}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 CREATE_REGISTRIES}
		Clumps-5.0.2.6.jar Clumps {clumps@5.0.2.6 CREATE_REGISTRIES}
		light-overlay-4.7.2.jar Light Overlay Forge {lightoverlay-forge@NONE CREATE_REGISTRIES}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 CREATE_REGISTRIES}
		comforts-FORGE-1.15.2-2.0.0.4.jar Comforts {comforts@FORGE-1.15.2-2.0.0.4 CREATE_REGISTRIES}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 CREATE_REGISTRIES}
		FruitTrees-1.15.2-1.7.0.jar Fruit Trees {fruittrees@1.7.0 CREATE_REGISTRIES}
		Kiwi-1.15.2-2.8.5.jar Kiwi {kiwi@2.8.5 CREATE_REGISTRIES}
		decorative_blocks-1.15.2-1.7.jar Decorative Blocks {decorative_blocks@1.7 CREATE_REGISTRIES}
		BotanyPots-1.15.2-2.0.29.jar BotanyPots {botanypots@2.0.29 CREATE_REGISTRIES}
		DungeonCrawl-1.15.2-2.2.4.jar Dungeon Crawl {dungeoncrawl@2.2.4 CREATE_REGISTRIES}
		betteranimalsplus-1.15.2-10.1.0.jar Better Animals Plus {betteranimalsplus@10.1.0 CREATE_REGISTRIES}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 CREATE_REGISTRIES}
		mapperbase-1.15.2-1.1.1.0.jar Mapper Base {mapperbase@1.15.2-1.1.1.0 CREATE_REGISTRIES}
		embellishcraft-1.15.2-2.2.1.0.jar EmbellishCraft {embellishcraft@1.15.2-2.2.1.0 CREATE_REGISTRIES}
		ftb-chunks-1.1.1.17.jar FTB Chunks {ftbchunks@1.1.1.17 CREATE_REGISTRIES}
		forge-1.15.2-31.2.45-universal.jar Forge {forge@31.2.45 CREATE_REGISTRIES}
		CraftingTweaks_1.15.2-11.0.1.jar Crafting Tweaks {craftingtweaks@11.0.1 CREATE_REGISTRIES}
		forge-1.15.2-31.2.45-client.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 CREATE_REGISTRIES}
		logprot-1.15.1-1.2.jar Logprot {logprot@1.2 CREATE_REGISTRIES}
		Environs-1.15.2-1.0.0.0.jar §3Dynamic Surroundings: §eEnvirons {environs@1.15.2-1.0.0.0 CREATE_REGISTRIES}
		theoneprobe-1.15-2.0.7.jar The One Probe {theoneprobe@1.15-2.0.7 CREATE_REGISTRIES}
		swingthroughgrass-1.15.2-1.4.1.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.1 CREATE_REGISTRIES}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 CREATE_REGISTRIES}
		ftb-quests-1502.0.2.252.jar FTB Quests {ftbquests@1502.0.2.252 CREATE_REGISTRIES}
		pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version CREATE_REGISTRIES}
		smoothboot-forge-1.15.2-1.2.0.jar Smooth Boot {smoothboot@1.15.2-1.2.0 CREATE_REGISTRIES}
		Savage-and-Ravage-1.15.2-1.1.4.jar Savage & Ravage {savageandravage@1.1.4 CREATE_REGISTRIES}
		pamhc2foodcore-1.15.2-1.1.0.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version CREATE_REGISTRIES}
		gravestone-1.17.6.jar Gravestone Mod {gravestone@1.17.6 CREATE_REGISTRIES}
		polymorph-FORGE-1.15.2-0.10.jar Polymorph {polymorph@FORGE-1.15.2-0.10 CREATE_REGISTRIES}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 CREATE_REGISTRIES}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 CREATE_REGISTRIES}
		Charm-1.15.2-1.5.9.jar Charm {charm@1.15.2-1.5.9 CREATE_REGISTRIES}
		Charmonium-1.15.2-1.0.1.jar Charmonium {charmonium@1.15.2-1.0.1 CREATE_REGISTRIES}
		Enhanced-Mushrooms-1.15.2-v1.2.2.jar Enhanced Mushrooms {enhanced_mushrooms@$1.1.0 CREATE_REGISTRIES}
		Strange-1.15.2-1.0.0-beta.5.hotfix1.jar Strange {strange@1.15.2-1.0.0-beta.5 CREATE_REGISTRIES}
		StorageDrawers-1.15.2-7.0.3.jar Storage Drawers {storagedrawers@1.15.2-7.0.3 CREATE_REGISTRIES}
		backpacked-1.7.0-1.15.2.jar Backpacked {backpacked@1.7.0 CREATE_REGISTRIES}
		simplytea-1.15.2-2.2.1.jar Simply Tea {simplytea@1.15.2-2.2.1 CREATE_REGISTRIES}
		structurize-0.13.105-ALPHA-universal.jar Structurize {structurize@0.13.105-ALPHA CREATE_REGISTRIES}
		floormats-1.1.1.jar Floor Mats {floormats@1.1.1 CREATE_REGISTRIES}
		PickleTweaks-1.15.2-4.0.4.jar Pickle Tweaks {pickletweaks@4.0.4 CREATE_REGISTRIES}
		minecolonies-0.13.562-ALPHA-universal.jar Minecolonies {minecolonies@0.13.562-ALPHA CREATE_REGISTRIES}
		cobbler-1.5.1.jar Cobbler {cobbler@1.5.1 CREATE_REGISTRIES}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 CREATE_REGISTRIES}
		Aquaculture-1.15.2-2.0.23.jar Aquaculture 2 {aquaculture@1.15.2-2.0.23 CREATE_REGISTRIES}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a CREATE_REGISTRIES}
		SoundFilters-0.14_for_1.15.2.jar Sound Filters {soundfilters@0.14_for_1.15.2 CREATE_REGISTRIES}
		overloadedarmorbar-4.0.0.jar Overloaded Armor Bar {overloadedarmorbar@4.0.0 CREATE_REGISTRIES}
		OresAboveDiamonds-1.15.2-v6.3.1.jar Ores Above Diamonds {oresabovediamonds@6.3.1 CREATE_REGISTRIES}
		healingcf_1.15.2-3.1.jar Healing Campfire {healingcf@3.1 CREATE_REGISTRIES}
		ExtendedNetherBackport-1.15.2-Beta-4.3.2.jar Extended Nether Backport {extendednether@4.3.2 CREATE_REGISTRIES}
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 1030/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7 CPU 950 @ 3.07GHz

---

The solutions i have been tried:
Update my Graphics card's driver
Update my java version and change java path in multimc
Change Forge version
 
Solution above are, sadly, didn't work at all.

Also i tried to create a instance without any mod but only forge and minecraft 1.15.2
and it works well.

**Comment by spannerman79** [comment]
> Update my java version and change java path in multimc

IF that was the case the above log would show you would be using Java 8, not;

> Java Version: **13.0.1**, Oracle Corporation

https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

As this isn't an issue with MultiMC this would have been solved within 5 seconds after you supplying an instance log on the discord server

**Comment by kingdom84521** [comment]
Thank you, the problem has been solved
and sorry about i didn't notice there is a discord server of multimc
