### ISSUE TITLE
Upon quitting Minecraft 1.0 from the in-game main menu, the window does not close.

### ISSUE THREAD

**Issue by Polyinsecure** [MultiMC/MultiMC5#3548]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: **Manjaro Linux (Arch Linux)**

Summary of the issue or suggestion:
----------------------------------------------
Upon quitting Minecraft 1.0 from the in-game main menu, the window does not close.

What should happen:
------------------------------
Upon quitting Minecraft 1.0 from the in-game main menu, **the window should close.**

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Create an instance of Minecraft 1.0

2. Run the instance.

3. Quit from the in-game menu.

Suspected cause:
---------------------------

```
Exception in thread "Minecraft main thread" org.lwjgl.LWJGLException: X Error - disp: 0x7f571002cd10 serial: 394 error: GLXBadWindow request_code: 153 minor_code: 32
	at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
	at org.lwjgl.opengl.LinuxDisplay.nDestroyWindow(Native Method)
	at org.lwjgl.opengl.LinuxDisplay.destroyWindow(LinuxDisplay.java:592)
	at org.lwjgl.opengl.Display.destroyWindow(Display.java:351)
	at org.lwjgl.opengl.Display.access$400(Display.java:65)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:835)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.d(SourceFile:514)
	at net.minecraft.client.Minecraft.run(SourceFile:675)
	at java.lang.Thread.run(Thread.java:748)
```

Logs/Screenshots:
----------------------------

https://paste.ee/p/a46bN

![Screenshot_MultiMC](https://user-images.githubusercontent.com/77704723/105427753-667d7780-5c80-11eb-9b7f-11ae5089f05f.png)

Additional Info:
---------------------------

**Comment by Zetabite** [comment]
please provide the full log: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by Polyinsecure** [comment]
https://paste.ee/p/a46bN

**Comment by Zetabite** [comment]
seems to be a driver issue

**Comment by Forkk** [comment]
Closing due to inactivity.

**Comment by Lassebq** [comment]
For anyone still interested the issue happens on XDestroyWindow specifically when exiting the game. This code also runs when toggling fullscreen but doesn't appear to be prone to this error in that scenario.

src/native/linux/opengl/org_lwjgl_opengl_Display.c
```c
static void destroyWindow(JNIEnv *env, Display *disp, Window window) {
	if (glx_window != None) {
		lwjgl_glXDestroyWindow(disp, glx_window);
		glx_window = None;
	}
	XDestroyWindow(disp, window);
	XFreeColormap(disp, cmap);
}
```
Commenting out
```c
//	if (glx_window != None) {
//		lwjgl_glXDestroyWindow(disp, glx_window);
//		glx_window = None;
//	}
```
fixes the issue.

And if you're curious why you can't comment out `XDestroyWindow` instead: toggling fullscreen does not destroy fullscreen window.

**Comment by Lassebq** [comment]
I should also note that mojang's launch wrapper doesn't exit politely, which is why in most cases the window closes regardless. Otherwise it would be frozen

**Comment by Lassebq** [comment]
I am able to semi-consistently reproduce this issue with a [custom launch wrapper implementation](https://github.com/MCPHackers/LaunchWrapper) across all LWJGL versions. It was randomly exiting successfully sometimes.

**Comment by Lassebq** [comment]
After closer inspection, it looks like MultiMC's launch wrapper does exact same thing to avoid this.
https://github.com/MultiMC/Launcher/blob/develop/libraries/launcher/org/multimc/LegacyFrame.java#L162
