### ISSUE TITLE
I can't play on minecraft servers...

### ISSUE THREAD

**Issue by TheSusp3ct** [MultiMC/MultiMC5#3555]
When I opened MultiMC in the past, I've noticed that I could not join any Minecraft servers.
At that time, I wasn't using any Minecraft mods.
The only thing that worked was survival.

I already tried to re-install MultiMC 3 time now.

What I just noticed is that on the bottom right side of MultiMC, I noticed that session was red.
The rest of the things (Auth, Skins and API) was green.

So I clicked on Sessions and it just lead me to Mojang Services Status without any ways to fix it or anything like that.
If someone reads this, please can you find a way to fix the problem?

**Comment by Zetabite** [comment]
The session problem is unrelated. please provide log when the error occurs and fill out the issue template properly

**Comment by TheSusp3ct** [comment]
> The session problem is unrelated. please provide log when the error occurs and fill out the issue template properly

alright gonna do that

**Comment by TheSusp3ct** [comment]
sent this [18:18:59] [Server Connector #1/ERROR]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: hypixel.net/104.17.71.15:25565
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_241]
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:1.8.0_241]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:612) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_241]
Caused by: java.net.ConnectException: Connection timed out: no further information
	... 10 more

**Comment by TheSusp3ct** [comment]
All of that was in red

**Comment by Zetabite** [comment]
please upload your log like this: https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png

**Comment by AverageComet250** [comment]
Use the upload log button on the log tab and paste the link here. We need the whole log, not just the error.

Thanks,
Shravan Mandava

________________________________

**Comment by TheSusp3ct** [comment]
https://paste.ee/p/I3SG1

**Comment by jotoho** [comment]
The log says you attempted to connect to `hypixel.net` but https://hypixel.net/play/ says the URL is `mc.hypixel.net`. Does that make a difference?

If not: Does MC have trouble finding the server when on the server-selection screen or does the timeout only happen when joining? 

If MC detects the server on the selection screen: How high is the ping response time?

**Comment by AverageComet250** [comment]
Also, can you connect to other servers `eu.hivemc.com` or `play.hivemc.com`

If yes, then multimc is fine and this issue can be closed.
