### ISSUE TITLE
incorrect invalid credentiials error

### ISSUE THREAD

**Issue by bubbelbadHD** [MultiMC/MultiMC5#3590]
I am new and i downloaded the launcher today but when i try to login it says invalid or incorrect login credentials. But it is correct and works in minecraft.net please fix this issue or make an option which we can add offline account

**Comment by Zetabite** [comment]
Offline account: Never
Microsoft Account: Soon tm
Mojang Account: Currently
So guessing you bought your account sometime between December last year and this year, you will have Microsoft Account, which arent supported yet

**Comment by bubbelbadHD** [comment]
no i bought it in september

**Comment by bubbelbadHD** [comment]
ok it logged in but when i try to open verson 1.8.9 it gives an error

**Comment by spannerman79** [comment]
> ok it logged in but when i try to open verson 1.8.9 it gives an error

That doesn't tell anyone anything @bubbelbadHD 

Share your log - https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs

Hit the upload button and paste that link into here.

**Comment by AverageComet250** [comment]
@bubbelbadHD what about in 1.16 +

**Comment by bubbelbadHD** [comment]
no in 1.8.9 it started working. It was storage error.But now when i try to launch forge 1.8.9, it says
:java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path, There is not enough space on the disk]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at org.fusesource.jansi.internal.Kernel32.<clinit>(Kernel32.java:37)
	at org.fusesource.jansi.WindowsAnsiOutputStream.<clinit>(WindowsAnsiOutputStream.java:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.logging.log4j.core.appender.ConsoleAppender.getOutputStream(ConsoleAppender.java:128)
	at org.apache.logging.log4j.core.appender.ConsoleAppender.getManager(ConsoleAppender.java:104)
	at org.apache.logging.log4j.core.appender.ConsoleAppender.createAppender(ConsoleAppender.java:99)
	at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:53)
	at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:63)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:217)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:114)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:81)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:83)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:34)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:387)
	at net.minecraft.launchwrapper.LogWrapper.configureLogging(LogWrapper.java:14)
	at net.minecraft.launchwrapper.LogWrapper.log(LogWrapper.java:28)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.

**Comment by jotoho** [comment]
>` There is not enough space on the disk`

That sounds pretty self-explanatory to me.

**Comment by AverageComet250** [comment]
Go buy a bigger hard drive.

Or delete the vanilla launcher and its .Minecraft folder

**Comment by spannerman79** [comment]
This is no longer a MultiMC issue.

This issue tracker is to track **actual** issues with MultiMC.

This **exact** same issue would happen if you would use the Vanilla Launcher - hence now an invalid issue.

**Comment by bubbelbadHD** [comment]
guys i have 490gb hdd and i dont have any vanila .minecraft folder

**Comment by jotoho** [comment]
> guys i have 490gb hdd and i dont have any vanila .minecraft folder

@bubbelbadHD And how much of that is free? Having 490GB capacity doesn't help when 489GB are in use.

**Comment by bubbelbadHD** [comment]
i have total of 500 gb hdd

**Comment by bubbelbadHD** [comment]
now when i again try to open forge it says this


MultiMC version: 0.6.11-1430


Minecraft folder is:
E:/multimc/TechnicE/MultiMC/instances/1.8.9/.minecraft


Java path is:
E:/minecraft launcher/runtime/jre-x86/bin/javaw.exe


Checking Java version...
Java is version 1.8.0_51, using 32-bit architecture.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  E:/multimc/TechnicE/MultiMC/instances/1.8.9/natives

Libraries:
  E:/multimc/TechnicE/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  E:/multimc/TechnicE/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/mojang/netty/1.6/netty-1.6.jar
  E:/multimc/TechnicE/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  E:/multimc/TechnicE/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  E:/multimc/TechnicE/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  E:/multimc/TechnicE/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  E:/multimc/TechnicE/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  E:/multimc/TechnicE/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  E:/multimc/TechnicE/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  E:/multimc/TechnicE/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  E:/multimc/TechnicE/MultiMC/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  E:/multimc/TechnicE/MultiMC/libraries/net/minecraftforge/forge/1.8.9-11.15.1.1722/forge-1.8.9-11.15.1.1722-universal.jar
  E:/multimc/TechnicE/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  E:/multimc/TechnicE/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  E:/multimc/TechnicE/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  E:/multimc/TechnicE/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  E:/multimc/TechnicE/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  E:/multimc/TechnicE/MultiMC/libraries/com/mojang/minecraft/1.8.9/minecraft-1.8.9-client.jar

Native libraries:
  E:/multimc/TechnicE/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  E:/multimc/TechnicE/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  E:/multimc/TechnicE/MultiMC/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-32.jar
  E:/multimc/TechnicE/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-32.jar

Params:
  --username  --version MultiMC5 --gameDir E:/multimc/TechnicE/MultiMC/instances/1.8.9/.minecraft --assetsDir E:/multimc/TechnicE/MultiMC/assets --assetIndex 1.8 --uuid  --accessToken  --userProperties  --userType  --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1013m, -Duser.language=en]


Minecraft process ID: 3572


Using onesix launcher.

2021-02-12 17:04:33,687 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2021-02-12 17:04:33,687 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[17:04:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:04:34] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:04:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:04:34] [main/INFO] [FML]: Forge Mod Loader version 11.15.1.1722 for Minecraft 1.8.9 loading
[17:04:34] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_51, running on Windows XP:x86:5.1, installed at E:\minecraft launcher\runtime\jre-x86
[17:04:34] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:04:34] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:04:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:04:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:04:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:04:42] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:04:42] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[17:04:42] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:04:42] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:04:43] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:04:43] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:04:44] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
2021-02-12 17:04:45,437 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2021-02-12 17:04:45,500 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2021-02-12 17:04:45,515 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[17:04:46] [Client thread/INFO]: Setting user: BubbelBadHD
[17:04:58] [Client thread/INFO]: LWJGL Version: 2.9.4
[17:05:00] [Client thread/WARN] [FML]: =============================================================
[17:05:00] [Client thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[17:05:00] [Client thread/WARN] [FML]: Offendor: com/sun/jna/Native.main([Ljava/lang/String;)V
[17:05:00] [Client thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[17:05:00] [Client thread/WARN] [FML]: =============================================================
[17:05:02] [Client thread/INFO] [FML]: Could not load splash.properties, will create a default one
[17:05:02] [Client thread/INFO] [STDOUT]: [net.minecraftforge.fml.client.SplashProgress:start:246]: ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/12/21 5:05 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 293552664 bytes (279 MB) / 519110656 bytes (495 MB) up to 1027866624 bytes (980 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1013m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '1.4.0 - Build 7.15.10.5029' Renderer: 'Intel Bear Lake B'
[17:05:03] [Client thread/INFO] [FML]: MinecraftForge v11.15.1.1722 Initialized
[17:05:03] [Client thread/INFO] [FML]: Replaced 204 ore recipies
[17:05:07] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[17:05:07] [Client thread/INFO] [FML]: Searching E:\multimc\TechnicE\MultiMC\instances\1.8.9\.minecraft\mods for mods
[17:05:35] [Client thread/INFO] [FML]: Forge Mod Loader has identified 3 mods to load
[17:05:38] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at CLIENT
[17:05:38] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[17:05:40] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[17:05:41] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[17:05:41] [Client thread/INFO] [FML]: Found 384 ObjectHolder annotations
[17:05:41] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[17:05:41] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[17:05:41] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[17:05:42] [Client thread/INFO] [FML]: Applying holder lookups
[17:05:42] [Client thread/INFO] [FML]: Holder lookups applied
[17:05:42] [Client thread/INFO] [FML]: Injecting itemstacks
[17:05:42] [Client thread/INFO] [FML]: Itemstack injection complete
[17:05:42] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[17:05:44] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Found status: UP_TO_DATE Target: null
[17:05:44] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:05:44] [Thread-8/INFO]: Initializing LWJGL OpenAL
[17:05:44] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:05:46] [Thread-8/INFO]: OpenAL initialized.
[17:05:46] [Sound Library Loader/INFO]: Sound engine started
[17:05:49] [Client thread/ERROR]: ########## GL ERROR ##########
[17:05:49] [Client thread/ERROR]: @ Pre startup
[17:05:49] [Client thread/ERROR]: 1282: Invalid operation
[17:06:06] [Client thread/INFO] [FML]: Max texture size: -1
[17:06:06] [Client thread/INFO] [FML]: Unable to fit: missingno - size: 16x16 - Maybe try a lowerresolution resourcepack?
[17:06:06] [Client thread/INFO] [FML]:   Holder{width=16, height=16, name=missingno}
[17:06:06] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2/12/21 5:06 PM
Description: Initializing game

net.minecraft.client.renderer.StitcherException: Unable to fit: missingno - size: 16x16 - Maybe try a lowerresolution resourcepack?
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:72)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:258)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:94)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:129)
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:120)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:478)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:72)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:258)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:94)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:129)
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:120)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:478)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 321908896 bytes (306 MB) / 519110656 bytes (495 MB) up to 1027866624 bytes (980 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1013m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722-universal.jar) 
	UCH	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '1.4.0 - Build 7.15.10.5029' Renderer: 'Intel Bear Lake B'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: Intel Bear Lake B GL version 1.4.0 - Build 7.15.10.5029, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is supported, EXT_blend_func_separate is supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is not supported, and EXT_framebuffer_object is not supported.
Shaders are not available because OpenGL 2.1 is not supported, ARB_shader_objects is not supported, ARB_vertex_shader is not supported, and ARB_fragment_shader is not supported.
VBOs are available because ARB_vertex_buffer_object is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Pentium(R) D CPU 2.80GHz
[17:06:06] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: #@!@# Game crashed! Crash report saved to: #@!@# E:\multimc\TechnicE\MultiMC\instances\1.8.9\.minecraft\crash-reports\crash-2021-02-12_17.06.06-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
 
this launcher sucks >:c

**Comment by bubbelbadHD** [comment]
please fix this error peterix

**Comment by jotoho** [comment]
@bubbelbadHD You are using Windows XP but Minecraft Java Edition officially requires at least Windows 7. 

See: https://help.minecraft.net/hc/en-us/articles/360035131371-Minecraft-Java-Edition-system-requirements-

**Comment by bubbelbadHD** [comment]
Yes but 1.8.9 works fine on real launcher. The problem was I couldn't install forge in it

**Comment by jotoho** [comment]
What makes you think that just because minecraft tolerates WinXP, minecraft forge does too? It could be that MCForge itself is incompatible with XP. 

```
net.minecraft.client.renderer.StitcherException: Unable to fit: missingno - size: 16x16 - Maybe try a lowerresolution resourcepack?
```
Do you have any texturepacks installed? Some googling implies that, this error message means the textures could not be transferred to the graphics cards memory. 

Regardless if it is an issue with your graphics card or your **unsupported** operating system: This is an issue between the game and your system. MultiMC has nothing to do with it.

**Comment by kb-1000** [comment]
So it looks like you've been reusing the same issue for 3 different problems, 1 of them apparently not a problem anymore, and 2 of them not problems with MultiMC itself at all. This is not Minecraft customer support or anything like that, it's a _bugtracker_.
And this issue is closed.

**Comment by bubbelbadHD** [comment]
> So it looks like you've been reusing the same issue for 3 different problems, 1 of them apparently not a problem anymore, and 2 of them not problems with MultiMC itself at all. This is not Minecraft customer support or anything like that, it's a _bugtracker_.
> And this issue is closed.

I am not any bugtracker and i thought there would be any solution for it but i think no solutions can help so i think i have to quit multimc. I am very dissapointed.

**Comment by bubbelbadHD** [comment]
> What makes you think that just because minecraft tolerates WinXP, minecraft forge does too? It could be that MCForge itself is incompatible with XP.
> 
> ```
> net.minecraft.client.renderer.StitcherException: Unable to fit: missingno - size: 16x16 - Maybe try a lowerresolution resourcepack?
> ```
> 
> Do you have any texturepacks installed? Some googling implies that, this error message means the textures could not be transferred to the graphics cards memory.
> 
> Regardless if it is an issue with your graphics card or your **unsupported** operating system: This is an issue between the game and your system. MultiMC has nothing to do with it.

Ok thank you but minecraft legacy launcher forge,optifine,mods etc. Work there
