### ISSUE TITLE
i try to load minecraft 1.16.5 and every time it crashes and tells me The game crashed whilst mouseclicked event handler Error: java.lang.IllegalStateException: failed to create a child event loop Exit Code: -1

### ISSUE THREAD

**Issue by zedmasteridk** [MultiMC/MultiMC5#3610]
and if anyone is wondering the crash report is here it is:
---- Minecraft Crash Report ----
// There are four lights!

Time: 2/17/21 9:09 AM
Description: mouseClicked event handler

java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at aax.f(SourceFile:56)
	at aax$$Lambda$4077/1950626628.get(Unknown Source)
	at afi.a(SourceFile:16)
	at aax.a(SourceFile:138)
	at djz.a(SourceFile:1891)
	at djz.a(SourceFile:1748)
	at dsm$a.e(SourceFile:407)
	at dsm$a.a(SourceFile:317)
	at dsm$a.a(SourceFile:259)
	at dlf.a(SourceFile:345)
	at dmh.a(SourceFile:27)
	at dka.b(SourceFile:92)
	at dka$$Lambda$3031/278109121.run(Unknown Source)
	at dot.a(SourceFile:435)
	at dka.a(SourceFile:92)
	at dka.c(SourceFile:162)
	at dka$$Lambda$3030/1437100457.run(Unknown Source)
	at aob.execute(SourceFile:94)
	at dka.b(SourceFile:162)
	at dka$$Lambda$2382/1707947963.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102)
	at dez.e(SourceFile:308)
	at djz.e(SourceFile:1068)
	at djz.e(SourceFile:681)
	at net.minecraft.client.main.Main.main(SourceFile:215)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:177)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:151)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 34 more
Caused by: java.io.IOException: Unable to establish loopback connection
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:101)
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:68)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:170)
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50)
	at java.nio.channels.Pipe.open(Pipe.java:155)
	at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:127)
	at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
	... 38 more
Caused by: java.net.SocketException: Unrecognized Windows Sockets error: 10107: socket
	at sun.nio.ch.Net.socket0(Native Method)
	at sun.nio.ch.Net.serverSocket(Net.java:420)
	at sun.nio.ch.ServerSocketChannelImpl.<init>(ServerSocketChannelImpl.java:88)
	at sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(SelectorProviderImpl.java:56)
	at java.nio.channels.ServerSocketChannel.open(ServerSocketChannel.java:108)
	at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(PipeImpl.java:123)
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:83)
	... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at aax.f(SourceFile:56)
	at aax$$Lambda$4077/1950626628.get(Unknown Source)
	at afi.a(SourceFile:16)
	at aax.a(SourceFile:138)
	at djz.a(SourceFile:1891)
	at djz.a(SourceFile:1748)
	at dsm$a.e(SourceFile:407)
	at dsm$a.a(SourceFile:317)
	at dsm$a.a(SourceFile:259)
	at dlf.a(SourceFile:345)
	at dmh.a(SourceFile:27)
	at dka.b(SourceFile:92)
	at dka$$Lambda$3031/278109121.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: dsj
Stacktrace:
	at dot.a(SourceFile:435)
	at dka.a(SourceFile:92)
	at dka.c(SourceFile:162)
	at dka$$Lambda$3030/1437100457.run(Unknown Source)
	at aob.execute(SourceFile:94)
	at dka.b(SourceFile:162)
	at dka$$Lambda$2382/1707947963.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102)
	at dez.e(SourceFile:308)
	at djz.e(SourceFile:1068)
	at djz.e(SourceFile:681)
	at net.minecraft.client.main.Main.main(SourceFile:215)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1401617912 bytes (1336 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1660 Ti with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.09, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

**Comment by spannerman79** [comment]
That is **not** the correct way to share the log.

Read https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs
