### ISSUE TITLE
No modpack works !!  :(

### ISSUE THREAD

**Issue by Abdullah3553** [MultiMC/MultiMC5#3614]
System Information
-----------------------------
MultiMC version: 0.6.12

Operating System: arch linux 

Summary of the issue or suggestion: 
i have tried more than 1 minecraft modpack and the same result every time, all of them don't work...
----------------------------------------------

What should happen:
the modpack should work just fine but a big java error appear.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.download sky factory modpack from at launcher

2.launch the modpack

Suspected cause:
java error.
---------------------------

Logs/Screenshots:
```
MultiMC version: 0.6.12-custom


Minecraft folder is:
/home/abdullah/.local/share/multimc/instances/Sky Factory 4/minecraft


Java path is:
/usr/bin/java


Checking Java version...
Java is version 15.0.2, using 64-bit architecture, from N/A.


Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)

Subsystem: Lenovo Device 3829

Kernel driver in use: i915

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/abdullah/.local/share/multimc/instances/Sky Factory 4/natives

Libraries:
  /home/abdullah/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/abdullah/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/abdullah/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/abdullah/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/abdullah/.local/share/multimc/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /home/abdullah/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/abdullah/.local/share/multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/abdullah/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/abdullah/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/abdullah/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/abdullah/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/abdullah/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/abdullah/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/abdullah/.local/share/multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/abdullah/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/abdullah/.local/share/multimc/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /home/abdullah/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/abdullah/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/abdullah/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/abdullah/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/abdullah/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/abdullah/.local/share/multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /home/abdullah/.local/share/multimc/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /home/abdullah/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/abdullah/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/abdullah/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/abdullah/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/abdullah/.local/share/multimc/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /home/abdullah/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /home/abdullah/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /home/abdullah/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /home/abdullah/.local/share/multimc/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar
  /home/abdullah/.local/share/multimc/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  /home/abdullah/.local/share/multimc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /home/abdullah/.local/share/multimc/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  /home/abdullah/.local/share/multimc/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /home/abdullah/.local/share/multimc/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /home/abdullah/.local/share/multimc/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /home/abdullah/.local/share/multimc/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /home/abdullah/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  /home/abdullah/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  /home/abdullah/.local/share/multimc/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /home/abdullah/.local/share/multimc/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /home/abdullah/.local/share/multimc/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /home/abdullah/.local/share/multimc/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /home/abdullah/.local/share/multimc/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /home/abdullah/.local/share/multimc/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /home/abdullah/.local/share/multimc/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /home/abdullah/.local/share/multimc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/abdullah/.local/share/multimc/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  /home/abdullah/.local/share/multimc/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /home/abdullah/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/abdullah/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar
  /home/abdullah/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar

Mods:
  [✔️] Advancement_Book-1.12-1.0.3
  [✔️] ae2stuff-0.7.0.4-mc1.12.2
  [✔️] AnimalCrops-1.12.2-0.2.0
  [✔️] Apotheosis-1.12.2-1.12.5
  [✔️] AppleSkin-mc1.12-1.0.14
  [✔️] appliedenergistics2-rv6-stable-7
  [✔️] Aroma1997Core-1.12.2-2.0.0.2.b167
  [✔️] AromaBackup-1.12.2-3.0.0.0.b132
  [✔️] astralsorcery-1.12.2-1.10.24
  [✔️] BarrelsDrumsStorageAndMore-0.0.24
  [✔️] base-1.12.2-3.13.0
  [✔️] Baubles-1.12-1.5.2
  [✔️] bdlib-1.14.3.12-mc1.12.2
  [✔️] bedpatch-2.2-1.12.2
  [✔️] BetterAdvancements-1.12.2-0.1.0.77
  [✔️] BiblioCraft[v2.4.5][MC1.12.2]
  [✔️] BNBGamingCore-1.12.2-0.12.0
  [✔️] BNBGamingLib-1.12.2-2.17.6
  [✔️] bonsaitrees-1.1.4-b170
  [✔️] Bookshelf-1.12.2-2.3.590
  [✔️] BouncyCreepers-0.0.4
  [✔️] BuildingGadgets-2.8.3
  [✔️] CalmDownZombieGuy-1.12.2-1.0.0
  [✔️] CarryOn MC1.12.2 v1.12.3
  [✔️] Ceramics-1.12-1.3.7
  [✔️] Chargers-1.12.2-1.2.0.4
  [✔️] ChineseWorkshop-1.12.2_1.2.6
  [✔️] Chisel-MC1.12.2-1.0.2.45
  [✔️] chiselsandbits-14.33
  [✔️] ClickMachine-1.12.2-1.2.0
  [✔️] ClientTweaks_1.12.2-3.1.11
  [✔️] Clumps-3.1.2
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal
  [✔️] CoFHCore-1.12.2-4.6.6.1-universal
  [✔️] CoFHWorld-1.12.2-1.4.0.1-universal
  [✔️] ColouredTooltips-1.12.2-1.0.7
  [✔️] CommonCapabilities-1.12.2-2.4.6
  [✔️] compactmachines3-1.12.2-3.0.18-b278
  [✔️] CompactStorage-3.1-12
  [✔️] ComPatchedStorage-1.12.2-1.6.0
  [✔️] conarm-1.12.2-1.2.5.9
  [✔️] ContentTweaker-1.12.2-4.9.1
  [✔️] Controlling-3.0.9
  [✔️] CookingForBlockheads_1.12.2-6.5.0
  [✔️] CraftTweaker2-1.12-4.1.20.574
  [✔️] CTM-MC1.12.2-1.0.2.31
  [✔️] Cucumber-1.12.2-1.1.3
  [✔️] culinaryconstruct-1.3.4
  [✔️] CustomMainMenu-MC1.12.2-2.0.9.1
  [✔️] Cyclic-1.12.2-1.20.3
  [✔️] CyclopsCore-1.12.2-1.6.4
  [✔️] DarkUtils-1.12.2-1.8.230
  [✔️] deepmoblearning-1.12.2-2.5.4-universal
  [✔️] DefaultOptions_1.12.2-9.2.8
  [✔️] DimensionStages-1.12.2-2.0.23
  [✔️] DragonMurder-1.12.2-1.0.1
  [✔️] ElevatorMod-1.12.2-1.4.2
  [✔️] EnchantmentDescriptions-1.12.2-1.1.15
  [✔️] EnderCore-1.12.2-0.5.76
  [✔️] endercrop-1.12.2-1.6.0
  [✔️] EnderStorage-1.12.2-2.4.6.137-universal
  [✔️] enderutilities-1.12.2-0.7.15
  [✔️] ExtendedCrafting-1.12.2-1.5.6
  [✔️] ExtraCells-1.12.2-2.6.5
  [✔️] FancyBlockParticles-1.12.x-2.4.1
  [✔️] FarmingForBlockheads_1.12.2-3.1.28
  [✔️] FastFurnace-1.12.2-1.3.1
  [✔️] FastWorkbench-1.12.2-1.7.3
  [✔️] FenceOverhaul-1.3.4
  [✔️] findme-1.12.2-1.1.0-8
  [✔️] fluxnetworks-1.12.2-4.0.14-31
  [✔️] foamfix-0.10.10-1.12.2
  [✔️] Forgelin-1.8.4
  [✔️] ForgeMultipart-1.12.2-2.6.2.83-universal
  [✔️] ForgivingVoid_1.12.2-1.1.0
  [✔️] GameStages-1.12.2-2.0.123
  [✔️] Guide-API-1.12-2.1.8-63
  [✔️] Headcrumbs-1.12.2-2.0.5.17
  [✔️] HorsePower-1.12.2-2.6.4.74
  [✔️] HuntingDimension-1.12.2-1.0.42
  [✔️] HurtAnimationRemover-1.12.2-1.0.0
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] HydroGel-1.12.2-1.1.0
  [✔️] iChunUtil-1.12.2-7.1.4
  [✔️] incontrol-1.12-3.9.16
  [✔️] industrialforegoing-1.12.2-1.12.13-237
  [✔️] Inspirations-1.12.2-0.2.9
  [✔️] IntegratedDynamics-1.12.2-1.1.6
  [✔️] IntegratedTunnels-1.12.2-1.6.11
  [✔️] inventorysorter-1.12.2-1.13.357
  [✔️] IronJetpacks-1.12-2-1.1.0
  [✔️] ItemStages-1.12.2-2.0.51
  [✔️] jei_1.12.2-4.15.0.295
  [✔️] journeymap-1.12.2-5.7.1
  [✔️] KleeSlabs_1.12.2-5.4.12
  [✔️] LimitlessStructureBlocks-1.12.2-1.1.0
  [✔️] LoadingScreens-1.12.2-0.3.1
  [✔️] lostcities-1.12-2.0.22
  [✔️] malisiscore-1.12.2-6.5.1
  [✔️] malisisdoors-1.12.2-7.3.0
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] MatterOverdrive-1.12.2-0.7.1.0-universal
  [✔️] mcjtylib-1.12-3.5.4
  [✔️] MCMultiPart-2.5.3
  [✔️] Mekanism-1.12.2-9.8.3.390
  [✔️] MekanismGenerators-1.12.2-9.8.3.390
  [✔️] Mercurius-1.12.2
  [✔️] MobGrindingUtils-0.3.13
  [✔️] MobStages-1.12.2-2.0.13
  [✔️] modtweaker-4.0.18
  [✔️] More-Cauldrons-1.4.6
  [✔️] MoreBuckets-1.12.2-1.0.4
  [✔️] moreoverlays-1.15.1-mc1.12.2
  [✔️] Morpheus-1.12.2-3.5.106
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] mpbasic-1.12.2-1.4.11
  [✔️] MPUtils-1.12.2-1.5.7
  [✔️] MTLib-3.0.6
  [✔️] mystcraft-1.12.2-0.13.7.06
  [✔️] MysticalAgradditions-1.12.2-1.3.2
  [✔️] MysticalAgriculture-1.12.2-1.7.5
  [✔️] Neat 1.4-17
  [✔️] NuclearCraft-2.18u-1.12.2
  [✔️] ocxnetdriver-1.0.3-b17
  [✔️] ogdragon-1.12.2-0.1.4
  [✔️] OpenComputers-MC1.12.2-1.7.5.192
  [✔️] OreExcavation-1.4.150
  [✔️] Parabox-1.12.2-2.0.0
  [✔️] Patchouli-1.0-20
  [✔️] PickleTweaks-1.12.2-2.1.3
  [✔️] PipeMaster-1.0.2-b8
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] PlaneFix-1.12.2-1.0.0
  [✔️] PortalGun-1.12.2-7.1.0
  [✔️] practicallogistics2-1.12.2-3.0.8-11
  [✔️] Prestige-1.12.2-1.1.58
  [✔️] primitivecrafting-1.12.2-1.4.3.6
  [✔️] ProjectE-1.12.2-PE1.4.1
  [✔️] ProportionalDestructionParticles-1.12.2-1.2.4
  [✔️] rangedpumps-0.5
  [✔️] realfilingcabinet-1.12-0.2.0.21
  [✔️] reauth-3.6.0
  [✔️] RecipeStages-1.1.3
  [✔️] RedstoneFlux-1.12-2.1.1.1-universal
  [✔️] ResourceHogs-1.12.2-1.0.14
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] rftoolspower-1.12-1.2.0
  [✔️] rustic-1.1.4
  [✔️] simplegenerators-1.12.2-2.0.20.2
  [✔️] SimpleStorageNetwork-1.12.2-1.7.10
  [✔️] SkyBonsais-1.0.1
  [✔️] SkyGrid-1.1.7
  [✔️] SkyOrchards-0.0.12
  [✔️] Slab_Machines-1.0.7
  [✔️] SlimyBoyos-1.0.0
  [✔️] SmoothFont-mc1.12.2-2.1.2
  [✔️] Snad-1.12.1-1.7.09.16a
  [✔️] sonarcore-1.12.2-5.0.19-20
  [✔️] SqueezerPatch-1.12.2-1.0.0
  [✔️] statues-1.12.X-0.8.9.2
  [✔️] stg-1.12.2-1.2.3
  [✔️] StuffASockInIt-1.12.2-1.1.30
  [✔️] supersoundmuffler-revived_1.12.2_1.0.2.10
  [✔️] Surge-1.12.2-2.0.77
  [✔️] Sync-1.12.2-7.1.0
  [✔️] TallGates-1.12.2-1.0.0.1
  [✔️] TConstruct-1.12.2-2.13.0.183
  [✔️] TelePastries-0.3.4
  [✔️] tesla-core-lib-1.12.2-1.0.17
  [✔️] ThermalDynamics-1.12.2-2.5.6.1-universal
  [✔️] ThermalFoundation-1.12.2-2.6.7.1-universal
  [✔️] ThermalInnovation-1.12.2-0.3.6.1-universal
  [✔️] TinkersComplement-1.12.2-0.4.3
  [✔️] TinkerToolLeveling-1.12.2-1.1.0
  [✔️] tinyprogressions-1.12.2-3.3.34-Release
  [✔️] TipTheScales-1.12.2-1.0.4
  [✔️] Toast Control-1.12.2-1.8.1
  [✔️] togetherforever-1.12.2-1.0.12-22
  [✔️] tombstone-4.0.1-3
  [✔️] Topography-1.12.2-1.14.2
  [✔️] torchmaster_1.12.2-1.8.1.81
  [✔️] Translocators-1.12.2-2.5.2.81-universal
  [✔️] TreeGrowingSimulator2017-1.0.1
  [✔️] Triumph-1.12.2-3.19.2
  [✔️] twilightforest-1.12.2-3.10.1013-universal
  [✔️] Twitchcrumbs_1.12.2-3.0.4
  [✔️] Uppers-0.0.6
  [✔️] valkyrielib-1.12.2-2.0.20.1
  [✔️] ViesCraft-1.12.2-5.9.16
  [✔️] Waddles-1.12.2-0.6.0
  [✔️] WailaStages-1.12.2-2.0.24
  [✔️] walljump-1.12.2-1.3.2
  [✔️] Wawla-1.12.2-2.6.275
  [✔️] weirdinggadget-1.12.2-2.1.16-universal
  [✔️] witherCrumbs-1.12.2-0.11
  [✔️] WorldBook-1.0.0
  [✔️] worldutils-1.12.2-0.4.2
  [✔️] XL-Food-Mod-1.12.2-1.9.2
  [✔️] xnet-1.12-1.8.2
  [✔️] YNot-0.2.4
  [✔️] yoyos_1.12.2-1.3.3.25
  [✔️] zenstages-0.5.0

Params:
  --username  --version MultiMC5 --gameDir /home/abdullah/.local/share/multimc/instances/Sky Factory 4/minecraft --assetsDir /home/abdullah/.local/share/multimc/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 15134


Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Process exited with code 255.
Clipboard copy at: 18 Feb 2021 16:05:51 +0200
Clipboard copy at: 18 Feb 2021 16:05:52 +0200
Clipboard copy at: 18 Feb 2021 16:07:45 +0200

```
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by phit** [comment]
You can't use Java 15 for most modded Minecraft versions, see
https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java

**Comment by AverageComet250** [comment]
You also incorrectly uploaded your log. See the below link.

https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs#uploading-logs

**Comment by Abdullah3553** [comment]
it worked ! thanks <3 and here is the log : https://paste.ee/p/tVkYR
