### ISSUE TITLE
multimc wont load a specific world I made

### ISSUE THREAD

**Issue by OverJive** [MultiMC/MultiMC5#3721]
### Operating System

Windows

### Description of bug

whenever I try to load a world I've been playing for a couple weeks it stops responding and then crashes.
the launcher comes up fine then it just wont load the world I've been playing.

Mod list 
absentbydesign-1.16.5-1.4.1
AkashicTome-1.4-16
alexsmobs-1.8.1
AmbientSounds_v3.1.5_mc1.16.5
AppleSkin-mc1.16.2-forge-1.0.14
architectury-1.10.138-forge
AutoRegLib-1.6-47
BiomesOPlenty-1.16.4-13.0.0.432-universal
Botania-1.16.4-414
carryon-1.16.5-1.15.3.13
citadel-1.6.2
Clumps-6.0.0.17
Craftable+Saddles+[1.16+All]-1.3
create-mc1.16.3_v0.3e
CreativeCore_v2.1.0_mc1.16.5
curios-forge-1.16.5-4.0.5.0
Ding-1.16.3-1.2.0
ftb-gui-library-1605.2.1.41-forge
gravestone-1.16.5-1.0.1
Hwyla-forge-1.10.11-B78_1.16.2
iceandfire-2.1.6-1.16.4
inventoryprofiles-forge-1.16.2-0.4.2
jei-1.16.4-7.6.1.71
JRFTL+[1.16.5]-1.2
Mekanism-1.16.5-10.0.21.448
MekanismGenerators-1.16.5-10.0.21.448
MekanismTools-1.16.5-10.0.21.448
MixinBootstrap-1.0.5
MouseTweaks-2.14-mc1.16.2
NaturesCompass-1.16.5-1.8.6
Patchouli-1.16.4-50
ratlantis-1.0.0-1.16.3
rats-7.1.1-1.16.5
ReAuth-1.16-Forge-3.9.3
secretrooms-1.16.5-1.0.1
shutupexperimentalsettings-1.0.3
ToolStats-1.16.5-6.0.1
Waystones_1.16.5-7.4.0
Wyrmroost-1.16.3-1.2.11
Xaeros_Minimap_21.4.0_Forge_1.16.5
XaerosWorldMap_1.12.0.2_Forge_1.16.5

### Steps to reproduce

kept trying to load the world did not work. tried to copy it did not work.

### Suspected cause

[17:01:16] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file curios-server.toml of type SERVER for modid curios
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:61) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:104) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[?:?] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_121] {}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062) ~[?:1.8.0_121] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:95) ~[?:?] {re:classloading}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:59) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121] {}
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.2.jar:?] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:57) ~[?:?] {re:classloading}
	... 10 more
[17:01:16] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 4c58faa2-00a8-400c-b053-3bc9e16586d7
Process crashed with exitcode -805306369.

### This issue is unique

I have searched the issue tracker and did not find an issue describing my bug.

**Comment by spannerman79** [comment]
This is not an issue with MultiMC as you would have the same issue if using the Vanilla Launcher.

Invalid Issue.
Incorrectly filled out issue.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by OverJive** [comment]
oh ok sorry I didn't quite know who to take this to.
