### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by Reactorcorefan213** [MultiMC/MultiMC5#3775]
### Operating System

Windows, Other

### Description of bug

IT CANT LET ME LOAD MINECRAFT

### Steps to reproduce

HERE IT IS STOPCODE ---- Minecraft Crash Report ----
// Shall we play a game?

Time: 09/05/21 14:38
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/multipart/BlockMultipart
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: codechicken/multipart/BlockMultipart
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: codechicken.multipart.BlockMultipart
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 200083976 bytes (190 MB) / 536870912 bytes (512 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UC	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UC	OpenComputers|Core{1.7.4.1265} [OpenComputers (Core)] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UC	BigReactors{0.4.0A} [Big Reactors] (BigReactors-0.4.0A.jar) 
	UC	hbm{1.0.27 BETA (3654)} [Hbm's Nuclear Tech] (hbm_1.0.27_X3654.jar) 
	UE	Mekanism{9.1.1} [Mekanism] (Mekanism-Mod-Core-1.7.10.jar) 
	UE	MekanismGenerators{6.0.5} [MekanismGenerators] (Mekanism-Mod-Generators-1.6.4.jar) 
	UE	MekanismTools{9.1.1} [MekanismTools] (Mekanism-Mod-Tools-1.7.10.jar) 
	UC	OpenComputers{1.7.4.1265} [OpenComputers] (OpenComputers-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14830 Compatibility Profile Context 21.4.1 27.20.21002.112' Renderer: 'AMD Radeon R9 200 / HD 7900 Series'
	CoFHCore: -[1.7.10]3.1.4-329

### Suspected cause

i dont knowwwwwwwwww and DONT CLOSE ITTTTTTTTTT

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Reactorcorefan213** [comment]
PLEASE HELP

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by Reactorcorefan213** [comment]
WHY U CLOSED IT

**Comment by Reactorcorefan213** [comment]
shit

**Comment by jamierocks** [comment]
> WHY U CLOSED IT

For the exact same reason your previous issue GH-3754 was closed. Please don't spam this bug tracker again.

Duplicate of GH-3754.

**Comment by Reactorcorefan213** [comment]
> > WHY U CLOSED IT
> 
> For the exact same reason your previous issue [GH-3754](https://github.com/MultiMC/MultiMC5/issues/3754) was closed. Please don't spam this bug tracker again.

stop
