### ISSUE TITLE
MultiMC Not Launching New Version 1.17, or Many of the Previous Snapshots

### ISSUE THREAD

**Issue by seanawesome** [MultiMC/MultiMC5#3844]
### Operating System

Windows

### Description of bug

`Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:171)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with code 1.`

### Steps to reproduce

Installing and launching Minecraft 1.17 via the MultiMC client. Launching Minecraft 1.17 through the official Minecraft launcher, however, functions just fine.

### Suspected cause

Java version mismatch.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedbackFox** [comment]
You did not search the issue tracker. Your java version is java 8. You need java 16. Install java 16 (https://www.oracle.com/java/technologies/javase-jdk16-downloads.html) and then select its javaw.exe for your instances that require it.

**Comment by jamierocks** [comment]
This issue tracker is for MultiMC, not game support.
