### ISSUE TITLE
Game crashes with previously working mod patch format due to new Java version

### ISSUE THREAD

**Issue by rdragonz** [MultiMC/MultiMC5#3854]
### Operating System

Windows 10

### Description of bug

When launching the game version 1.17 using a previously working method of patches, the game crashes.

Note: This is a custom mod that I made, it is not available for download

Here is the patch in question:

```{
    "+tweakers": [
        "net.simple-coords.loader.RedTweaker"
    ],
    "formatVersion": 1,
    "libraries": [
        {
            "name": "net.minecraft:launchwrapper:1.12"
        },
        {
            "MMC-filename": "simple-coords-117.jar",
            "MMC-hint": "local",
            "name": "net.simple-coords:coords:117"
        }
    ],
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "name": "coords",
    "requires": [
        {
            "equals": "1.17",
            "uid": "net.minecraft"
        }
    ],
    "uid": "coords",
    "version": "117"
}
```

And when launching the game this is the error message

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
```

This does not happen when using the default Minecraft launcher with the mod installed, the game launches normally and the mod functions properly,

### Steps to reproduce

1. Install and configure a mod that requires launching using library hints and tweakers
2. Launch the game

### Suspected cause

Certain aspects of the patch format are no longer compatible with the updated Java version used in Minecraft 1.17

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment]
Launchwrapper requires Java 8.

**Comment by sr1canskhsia** [comment]
Encountered the same problem when installing OptiFine 1.17 with launchwrapper tweaker. I believe this is because the launchwrapper jar was targeted at Java 8 only so it's incompatible with Java 16.
You probably need to build a launchwrapper jar targeting Java 16 yourself.
