### ISSUE TITLE
What does this crash-log mean and how can I fix it?

### ISSUE THREAD

**Issue by ThaFeeesh** [MultiMC/MultiMC5#3879]
### Operating System

macOS

### Description of bug

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 59.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:825)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:723)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:646)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:171)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

### Steps to reproduce

It happened after I updated to 1.17, that's all I can really say.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefor not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.

**Comment by RDKRACZ** [comment]
@ThaFeeesh You have Java 15 installed and MC 1.17 needs Java 16 to run.
