### ISSUE TITLE
Clean install on Arch Linux getting code 255 exit code.

### ISSUE THREAD

**Issue by SaltySpectrum** [MultiMC/MultiMC5#3882]
### Operating System

Linux

### Description of bug

When I try to launch an instance without any mods or settings changed I would get this error code 255. In suspected cause, I put the crash log there. 

### Steps to reproduce

Installed from AUR package with makepkg. Selected Java 8 in the dependency options, selected it in MultiMC settings, and set Java 8 as default in archlinux-java script. Removed other versions of java incase it was hooking into it.

### Suspected cause

Here is the crash log and what I could see as errors.
~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
Current Language: ~~ERROR~~ NullPointerException: null
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/20/21 12:55 AM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ave.ar(SourceFile:560)
	at ave.am(SourceFile:361)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 5.12.11-arch1-1
	Java Version: 1.8.0_292, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 575167616 bytes (548 MB) / 649592832 bytes (619 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ImperatorStorm** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefor not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.

**Comment by kb-1000** [comment]
Honestly, it's not: that's a packaging issue.
What MultiMC AUR package are you using?

**Comment by SaltySpectrum** [comment]
Thanks for correcting my post, its the official AUR package that is linked on the MultiMC website. https://aur.archlinux.org/packages/multimc5

**Comment by Zetabite** [comment]
That package is known to have issues and is only semi official. Best experience atm is either multimc-git and multimc-bin

**Comment by phit** [comment]
though even that requires `xorg-xrandr`, install it then your game will work

**Comment by SaltySpectrum** [comment]
Doing sudo pacman -S xorg-xrandr worked! Thanks everyone!
