### ISSUE TITLE
Impossible To run Minecraft 1.17

### ISSUE THREAD

**Issue by Qyuzux** [MultiMC/MultiMC5#3924]
### Description of bug

Even if I reinstall the whole MultiMC (i used to reinstall Java too) It's impossible o run it

Crash Report :
`Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:171)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)`

### Steps to reproduce

You create a new instance wirh minecraft 1.17

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefor not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.
