### ISSUE TITLE
Crash upon startup 

### ISSUE THREAD

**Issue by Shoes4Clues** [MultiMC/MultiMC5#4000]
### Operating System

Windows

### Description of bug

![image](https://user-images.githubusercontent.com/63887849/129217464-9fb73745-9e9d-4a74-bada-534bc98a14f1.png)
I have the latest Java version, I can launch it completely fine via the normal launcher, but I still get this error:
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:171)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

### Steps to reproduce

Launch version 1.17 or later using the most recent Java version

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by arthomnix** [comment]
1.17 requires Java 16 or above. For some reason the official Java website still has java 8 as the latest version. You can get Java 16 from [https://www.azul.com/downloads/?version=java-16-sts&os=windows&architecture=x86-64-bit&package=jre](https://www.azul.com/downloads/?version=java-16-sts&os=windows&architecture=x86-64-bit&package=jre) (download the .msi and run it). Then change your Java version to 16 in edit instance > settings > java > auto-detect (do this for all 1.17 instances, but not for older versions as they require java 8). You may need to switch to the development channel for the new java to be detected.

**Comment by arthomnix** [comment]
(The reason it works on the stock launcher is because that uses its own built-in version of java)
