### ISSUE TITLE
Failed to start minecraft, but runs with forge not installed.

### ISSUE THREAD

**Issue by BigPoggersInChat** [MultiMC/MultiMC5#4061]
### Description of bug

I was installing MultiMC to play MC Eternal Lite with friends, but i cannot start it up. Every time i try to, it says,
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more

I use a onesix launcher, and when i deactivate forge, it works fine, but there's no mods. My friends haven't had this problem, and i don't know what's going on. I've also uninstalled and reinstalled it.

### Steps to reproduce

I don't know how to replicate this, since i've looked around, and it appears that nobody else has had this problem, and neither have my friends. 

### Suspected cause

It's most likely forge, but i could be wrong.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Zetabite** [comment]
provide the actual full instance log

**Comment by NeRdTheNed** [comment]
@BigPoggersInChat MC Eternal Lite appears to be a modpack running on Forge for 1.12.2. The error message you have posted likely indicates that you're running the modpack instance on Java 9+, which is probably the cause of your issue, as Forge for 1.12.2 does not support running on Java 9+. Try installing Java 8, and changing the Java installation setting for your instance to the Java 8 installation. This is probably not an issue with MultiMC.

**Comment by phit** [comment]
as @NeRdTheNed said, use Java 8 https://github.com/MultiMC/MultiMC5/wiki/Using-the-right-Java
