### ISSUE TITLE
Minecraft 1.18 experimental snapshot 6 crashes before startup when run through MultiMC

### ISSUE THREAD

**Issue by James103** [MultiMC/MultiMC5#4072]
### Operating System

Windows

### Description of bug

The Minecraft version `1.18_experimental-snapshot-6` crashes before it starts, with the following error:
```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: jdk.jfr.FlightRecorderListener
	at net.minecraft.client.main.Main.main(SourceFile:52)
	... 8 more
Caused by: java.lang.ClassNotFoundException: jdk.jfr.FlightRecorderListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:822)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1111)
	... 9 more
Exiting with -1
Process exited with code -1.
```
The full log for this crash can be found at https://gist.github.com/James103/c7395f134b119ed5bbc9e255cf82c87b.

### Steps to reproduce

1. Add a new instance of version `1.18_experimental-snapshot-6` to MultiMC, or import this instance: [1.18_experimental-snapshot-6.zip](https://github.com/MultiMC/MultiMC5/files/7110616/1.18_experimental-snapshot-6.zip)
2. Start the instance.
3. Notice that the game crashes before it starts.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by peterix** [comment]
Do not use OpenJ9 Java.

**Comment by peterix** [comment]
It does not and will not work.
