### ISSUE TITLE
Help Me!  i can't start forge 1.12.2

### ISSUE THREAD

**Issue by LucaGugli** [MultiMC/MultiMC5#4146]
### Operating System

Windows

### Description of bug

**When I try to start MultiMC / Forge 1.12.2 with any mod I get this error**

```bash
 Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Il processo si è chiuso con codice -1.
```

### Steps to reproduce

1. Create an instance 1.12.2
2. Add ForgeMC
3. Add Pixelmon and Optifine Mod
4. Start Minecraft

### Suspected cause

maybe pixelmon doesn't support multimc (I don't think)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
use java 8

**Comment by LucaGugli** [comment]
how thx

**Comment by IMADETHISTOCOMMENT2313** [comment]
> use java 8

THANK YOU SO MUCHH I HAVE BEEN TRYING TO FRIKIN DOTHIS FOR A MONTH THANK UUU
