### ISSUE TITLE
Minecraft 1.5.2 Forge Nonsense

### ISSUE THREAD

**Issue by phdanielli** [MultiMC/MultiMC5#439]
Creators of multimc, pleasse consider giving me multimc 3 or look at this:

```
MultiMC version: 0.5-dev335

Minecraft folder is:
C:/Users/user/Desktop/MultiMC/instances/Craft Of Duty 1.5.21/minecraft

Java path is:
C:/Program Files/Java/jre7/bin/javaw.exe

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms16384m, -Xmx16384m, -XX:PermSize=4096m, -Duser.language=en, -jar, C:/Users/user/Desktop/MultiMC/jars/NewLaunch.jar]

Using onesix launcher.

Main Class:
net.minecraft.launchwrapper.Launch

Native path:
C:/Users/user/Desktop/MultiMC/instances/Craft Of Duty 1.5.21/natives

Traits:
[texturepacks, legacyLaunch, legacyFML]

Libraries:
C:/Users/user/Desktop/MultiMC/libraries/com/mumfrey/liteloader/1.5.2_01/liteloader-1.5.2_01.jar
C:/Users/user/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
C:/Users/user/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
C:/Users/user/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
C:/Users/user/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
C:/Users/user/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.5/launchwrapper-1.5.jar
C:/Users/user/Desktop/MultiMC/instances/Craft Of Duty 1.5.21/jarmods/minecraftforge-universal-1.5.2-7.8.1.738.zip
C:/Users/user/Desktop/MultiMC/versions/1.5.2/1.5.2-stripped.jar

Params:
[<PROFILE NAME>, <SESSION ID>, --tweakClass, com.mumfrey.liteloader.launch.LiteLoaderTweaker]

Preparing native libraries...
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
at java.lang.Class.getDeclaredFields0(Native Method)
at java.lang.Class.privateGetDeclaredFields(Unknown Source)
at java.lang.Class.getDeclaredFields(Unknown Source)
at org.multimc.Utils.getMCPathField(Utils.java:144)
at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:139)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:366)
at org.multimc.EntryPoint.listen(EntryPoint.java:165)
at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
at java.net.URLClassLoader$1.run(Unknown Source)
at java.net.URLClassLoader$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 8 more
Minecraft exited with exitcode 1.
```

**Comment by peterix** [comment]
Sorry for the mess.
