### ISSUE TITLE
Launching with forge and legacyjavafixer got this error 1.7.2

### ISSUE THREAD

**Issue by deuceman2008** [MultiMC/MultiMC5#749]
```
MultiMC version: 0.4.5

Minecraft folder is:
C:/Users/T laptop/AppData/Roaming/MultiMC/instances/1.7.2/minecraft

Java path is:
java

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/T laptop/AppData/Roaming/MultiMC/jars/NewLaunch.jar]

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/T laptop/AppData/Roaming/MultiMC/instances/1.7.2/natives

Traits:
  []

Libraries:
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/net/minecraftforge/forge/1.7.2-10.12.2.1161-mc172/forge-1.7.2-10.12.2.1161-mc172-universal.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/net/minecraft/launchwrapper/1.9/launchwrapper-1.9.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/org/scala-lang/scala-compiler/2.10.2/scala-compiler-2.10.2.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/com/google/guava/guava/15.0/guava-15.0.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/com/mojang/authlib/1.3/authlib-1.3.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/instances/1.7.2/jarmods/e2e983ef-6bba-46ab-bd3f-5d14576798ec.jar
  C:/Users/T laptop/AppData/Roaming/MultiMC/versions/1.7.2/1.7.2-stripped.jar

Params:
  [--username, <PROFILE NAME>, --version, 1.7.2, --gameDir, C:/Users/T laptop/AppData/Roaming/MultiMC/instances/1.7.2/minecraft, --assetsDir, C:/Users/T laptop/AppData/Roaming/MultiMC/assets/virtual/legacy, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[17:02:25] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[17:02:26] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[17:02:26] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[17:02:26] [main/INFO] [FML]: Forge Mod Loader version 7.2.217.1161 for Minecraft 1.7.2 loading
[17:02:26] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_31, running on Windows 7:x86:6.1, installed at C:\Program Files\Java\jre1.8.0_31
[17:02:26] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.2_HD_U_D4.jar
[17:02:26] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:02:26] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[17:02:26] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:02:26] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:02:26] [main/ERROR] [LaunchWrapper]: Unable to launch
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_31]
	at java.util.ArrayList$Itr.remove(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:117) [launchwrapper-1.9.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Minecraft exited with exitcode 0.
```

**Comment by 02JanDal** [comment]
Are you sure you installed LegacyJavaFixer correctly? It should be put into the mods folder (Loader Mods if you're using the MultiMC interface)

**Comment by RegisDeVallis** [comment]
Don't use Java 8 ever for minecraft. Ever. to change this go to multimc settings, under java click the button auto-detect, then select java 7 64 bit if aviable. If there is no java 7, go to the java website and download it. 

https://java.com/en/download/manual_java7.jsp

**Comment by robotbrain** [comment]
@regisdevallis wrong. mojang is trying to enforce java 8 only and java 7 will be discontinued soon.

**Comment by RegisDeVallis** [comment]
@robotbrain It still causes problems with permagen, which is something mods have issues with.

**Comment by Heufneutje** [comment]
Mods shouldn't be affected by the removal of permgen in Java 8. If they are, it's up to the mod author to fix that.

**Comment by robotbrain** [comment]
if you mean the permgen warning, that can be safely ignored

**Comment by peterix** [comment]
Probably won't be in java 9, but once java 7 is dead/out of support, er can just remove the permgen option entirely.

**Comment by RegisDeVallis** [comment]
@robotbrain Some FTB modpacks like FTB Ultimate is not compatible, so you would need to force Java 7. @peterix maybe after quickmods support for automatically using Java 7 for minecraft 1.5.2 or lower could be implemented. Just a thought.

**Comment by peterix** [comment]
1. java 8 is actually supported. Everything older, NOT.
2. the PermGen stuff is sorted out.
3. Don't use dead/silly versions like 1.7.2... Please. It had no significant mod support. And if you play vanilla, you are on latest.
