### ISSUE TITLE
Does not run MultiMc

### ISSUE THREAD

**Issue by microlab123** [MultiMC/MultiMC5#819]
What to do, I have not started the build, writes: 
```
 java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.remove(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
```

**Comment by peterix** [comment]
You most likely need this mod:
http://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar

**Comment by peterix** [comment]
Some versions of forge do not work with java 8 without it.

**Comment by microlab123** [comment]
Thank you, you helped me
