### ISSUE TITLE
error on MultiMc 5 Cracked version

### ISSUE THREAD

**Issue by TrollNation** [MultiMC/MultiMC5#822]
i installed forge then put pixlecraft where it needed to go then started after i did my account and i got this

```
MultiMC version: 0.4

Minecraft folder is:
C:/Users/Jonathan/Desktop/MultiMC/instances/PixelMon/minecraft

Java path is:
java

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/Jonathan/Desktop/MultiMC/jars/NewLaunch.jar]

Using onesix launcher.

Main Class:
net.minecraft.launchwrapper.Launch

Native path:
C:/Users/Jonathan/Desktop/MultiMC/instances/PixelMon/natives

Libraries:
C:/Users/Jonathan/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.2.1307-1.7.10/forge-1.7.10-10.13.2.1307-1.7.10.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.11/launchwrapper-1.11.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/com/google/guava/guava/15.0/guava-15.0.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.16/authlib-1.5.16.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
C:/Users/Jonathan/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
C:/Users/Jonathan/Desktop/MultiMC/versions/1.7.10/1.7.10.jar

Params:
[--username, <PROFILE NAME>, --version, 1.7.10, --gameDir, C:/Users/Jonathan/Desktop/MultiMC/instances/PixelMon/minecraft, --assetsDir, C:/Users/Jonathan/Desktop/MultiMC/assets, --assetIndex, 1.7.10, --uuid, <CLIENT TOKEN>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-32.jar
Extracting twitch-external-platform-4.5-natives-windows-32.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[06:37:12] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[06:37:12] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[06:37:12] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[06:37:12] [main/INFO] [FML]: Forge Mod Loader version 7.10.88.1307 for Minecraft 1.7.10 loading
[06:37:12] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_31, running on Windows 8.1:x86:6.3, installed at C:\Program Files (x86)\Java\jre1.8.0_31
[06:37:12] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:37:12] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[06:37:12] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:37:12] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:37:12] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[06:37:15] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[06:37:15] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[06:37:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[06:37:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[06:37:15] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:217]: Failed to start Minecraft:
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.reflect.Method.invoke(Unknown Source)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:214)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.multimc.EntryPoint.listen(EntryPoint.java:165)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.multimc.EntryPoint.main(EntryPoint.java:54)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoSuchMethodError: com.google.common.io.CharSource.readLines(Lcom/google/common/io/LineProcessor;)Ljava/lang/Object;
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cpw.mods.fml.common.asm.transformers.AccessTransformer.processATFile(AccessTransformer.java:125)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cpw.mods.fml.common.asm.transformers.AccessTransformer.readMapFile(AccessTransformer.java:120)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:101)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:97)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.reflect.Constructor.newInstance(Unknown Source)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.Class.newInstance(Unknown Source)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cpw.mods.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:32)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: ... 7 more
[06:37:15] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:57]: Exiting with -1
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArrayIndexOutOfBoundsException: 5
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.SecurityManager.checkExit(Unknown Source)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.Runtime.exit(Unknown Source)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.System.exit(Unknown Source)
[06:37:15] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.multimc.EntryPoint.main(EntryPoint.java:58)
Exception in thread "main"
Minecraft exited with exitcode 1.
```

**Comment by 02JanDal** [comment]
Cracked... right... just don't expect us to support it in anyway, and don't be surprised if you get any viruses, malware, or similar.

**Comment by peterix** [comment]
This is a very old version, cracked or not.

A similar problem has been found and fixed, almos t a year ago:
https://github.com/MultiMC/MultiMC5/issues/396

Upgrading could help.

**Comment by Kilobyte22** [comment]
Err, mistapped. On topic: i am pretty sure that the cracked version he uses is just based on an old as fuck version. That's why you should use the official version. And tbh, Minecraft isn't that expensive.

**Comment by Heufneutje** [comment]
What worries me more is that there's modified versions of MultiMC going around the internet...

**Comment by Kilobyte22** [comment]
Well, we can't do much against it, even though this very one probably violates the license (as it contains MultiMC in its name) and we might be able to do something against that.

**Comment by 4rz0** [comment]
You can see it like that: 
If people like something, there will be illegal copies of it ;D

**Comment by TrollNation** [comment]
theres over 5 different cracked versions. and i dont wana waste $20 on a
game i can get free so i can use the money on something i can actually use.
and i got it working just a java error

**Comment by TheDoctorsLife** [comment]
Umm, that's like saying I don't want to waste $20 on this new pizza when I can get free pizza from the trash

**Comment by TrollNation** [comment]
no you are just being a smart ass. why pay for a game i can play online
when i can get it free and play online. no point in wasting money on
something virtual when i can save my money and buy real things instead of a
no life that uses money on things that arent actually real. im not guna pay
for a virtual reality. that would be stupid and a waste of money.

**Comment by KamranMackey** [comment]
@TrollNation please. Stop being such a jerk to everyone. Anyway, the MultiMC Devs shouldn't support cracked versions anyway. Buy the game, or don't play it at all, because with a cracked version, you won't get much support. So please, buy the game. It's only $20.

**Comment by peterix** [comment]
You could probably tweak some files somewhere and get it to work.

I'm not supporting a year old version of MultiMC that you got from someone else. I do not want to touch that stuff. I would be opening the project (myself and other involved people) to possible legal attacks from Microsoft. The fact that it doesn't happen doesn't mean it wouldn't or can't.

The error is basically that: you can't update, because the cracked versions are terrible and outdated and you don't have a license for the game. I can't help you.

It's $27, btw. The 20 is in euros.

But that is enough.
