### ISSUE TITLE
help me bug Minecraft exited with exitcode 0.

### ISSUE THREAD

**Issue by kawazoeritsu** [MultiMC/MultiMC5#832]
```
MultiMC version: 0.4.5
 
Minecraft folder is:
C:/Users/Desktop/MultiMC/instances/1.6.4/minecraft
 
Java path is:
java
 
Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms3072m, -Xmx3072m, -Duser.language=en, -jar, C:/Users/Desktop/MultiMC/jars/NewLaunch.jar]
 
Using onesix launcher.
 
Main Class:
  net.minecraft.launchwrapper.Launch
 
Native path:
  C:/Users/kevin/Desktop/MultiMC/instances/1.6.4/natives
 
Traits:
  []
 
Libraries:
  C:/Users/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.6.4-9.11.1.965/forge-1.6.4-9.11.1.965-universal.jar
  C:/Users/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.8/launchwrapper-1.8.jar
  C:/Users/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar
  C:/Users/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.jar
  C:/Users/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.10.2/scala-compiler-2.10.2.jar
  C:/Users/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Desktop/MultiMC/libraries/argo/argo/2.25_fixed/argo-2.25_fixed.jar
  C:/Users/Desktop/MultiMC/libraries/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar
  C:/Users/Desktop/MultiMC/libraries/com/google/guava/guava/14.0/guava-14.0.jar
  C:/Users/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  C:/Users/Desktop/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar
  C:/Users/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/Desktop/MultiMC/versions/1.6.4/1.6.4.jar
 
Params:
  [--username, <PROFILE NAME>, --session, <SESSION ID>, --version, 1.6.4, --gameDir, C:/Users/kevin/Desktop/MultiMC/instances/1.6.4/minecraft, --assetsDir, C:/Users/Desktop/MultiMC/assets/virtual/legacy, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]
 
Window size: 854 x 480
 
Preparing native libraries...
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar
 
Mar 19, 2015 1:10:52 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
Mar 19, 2015 1:10:52 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
Mar 19, 2015 1:10:52 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
2015-03-19 13:10:52 [INFO] [ForgeModLoader] Forge Mod Loader version 6.4.49.965 for Minecraft 1.6.4 loading
2015-03-19 13:10:52 [INFO] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_40, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_40
2015-03-19 13:10:52 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2015-03-19 13:10:52 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
2015-03-19 13:10:52 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2015-03-19 13:10:52 [SEVERE] [ForgeModLoader] Unable to launch
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.remove(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Minecraft exited with exitcode 0.
```

**Comment by kawazoeritsu** [comment]
http://paste.ee/p/qUYE4

**Comment by Kilobyte22** [comment]
Are you using Java 8? If so, please install this mod: http://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar

**Comment by kawazoeritsu** [comment]
sorry , i tried but it doesn't work

**Comment by Heufneutje** [comment]
Did you put it in the right folder? Because I'm 99% certain it should.

**Comment by Kilobyte22** [comment]
yeah, for clarification: put it in the mods directory (Right Click instance -> `Edit Instance` -> `Loader Mods`)
