### ISSUE TITLE
Further sanitation of instance names

### ISSUE THREAD

**Issue by bopaloni** [MultiMC/MultiMC5#847]
```
MultiMC version: 0.4.5

Minecraft folder is:
C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/instances/( ͡° ͜ʖ ͡°)/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_31/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/jars/NewLaunch.jar]

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/instances/( ?° ?? ?°)/natives

Traits:
  []

Libraries:
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/minecraftforge/forge/1.7.10-10.13.2.1343-1.7.10/forge-1.7.10-10.13.2.1343-1.7.10-universal.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/minecraft/launchwrapper/1.11/launchwrapper-1.11.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/google/guava/guava/16.0/guava-16.0.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/commons/commons-lang3/3.2.1/commons-lang3-3.2.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/mojang/authlib/1.5.16/authlib-1.5.16.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/versions/1.7.10/1.7.10.jar

Params:
  [--username, <PROFILE NAME>, --version, 1.7.10, --gameDir, C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/instances/( ?° ?? ?°)/minecraft, --assetsDir, C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {"twitch_access_token":["<TWITCH_ACCESS_TOKEN>"]}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[13:30:05] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[13:30:05] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[13:30:05] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[13:30:05] [main/INFO] [FML]: Forge Mod Loader version 7.10.97.1343 for Minecraft 1.7.10 loading
[13:30:05] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_31, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_31
[13:30:06] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:30:07] [main/INFO] [FML]: Loading tweaker net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer from legacyjavafixer-1.0.jar
[13:30:07] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:30:07] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:30:07] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer
[13:30:07] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker@7920ba90
[13:30:07] [main/INFO] [FML]: [LegacyJavaFixer] Replacing tweaker cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker@7920ba90 with net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement@6b419da
[13:30:07] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: FMLCorePlugin {[]}
[13:30:07] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: FMLForgePlugin {[]}
[13:30:07] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: CCCDeobfPlugin {[]}
[13:30:07] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: CodeChickenCorePlugin {[]}
[13:30:07] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: NEICorePlugin {[]}
[13:30:07] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker@7920ba90
[13:30:07] [main/INFO] [FML]: [LegacyJavaFixer] Replacing tweaker cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker@7920ba90 with net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement@6b419da
[13:30:07] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[13:30:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement
[13:30:07] [main/INFO] [FML]: [LegacyJavaFixer] Replacing sort
[13:30:07] [main/INFO] [FML]: [LegacyJavaFixer] Detected TerminalTweaker
[13:30:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement
[13:30:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer
[13:30:07] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:30:14] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[13:30:14] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[13:30:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:30:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:30:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:30:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:30:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
```

**Comment by 02JanDal** [comment]
Try renaming the instance to something that doesn't include special characters (only letters and digits to be sure)

**Comment by bopaloni** [comment]
renamed it. still crashed

**Comment by 02JanDal** [comment]
Log please

**Comment by bopaloni** [comment]
heres the new log
MultiMC version: 0.4.5

Minecraft folder is:
C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/instances/( ͡° ͜ʖ ͡°)/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_31/bin/javaw.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -jar, C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/jars/NewLaunch.jar]

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/instances/( ?° ?? ?°)/natives

Traits:
  []

Libraries:
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/minecraftforge/forge/1.7.10-10.13.2.1343-1.7.10/forge-1.7.10-10.13.2.1343-1.7.10-universal.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/minecraft/launchwrapper/1.11/launchwrapper-1.11.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/google/guava/guava/16.0/guava-16.0.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/commons/commons-lang3/3.2.1/commons-lang3-3.2.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/com/mojang/authlib/1.5.16/authlib-1.5.16.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/versions/1.7.10/1.7.10.jar

Params:
  [--username, <PROFILE NAME>, --version, 1.7.10, --gameDir, C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/instances/( ?° ?? ?°)/minecraft, --assetsDir, C:/Users/penka_000/AppData/Roaming/.minecraft/MMC/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {"twitch_access_token":["<TWITCH_ACCESS_TOKEN>"]}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-windows-64.jar
Extracting twitch-external-platform-4.5-natives-windows-64.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[13:36:10] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[13:36:10] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[13:36:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[13:36:10] [main/INFO] [FML]: Forge Mod Loader version 7.10.97.1343 for Minecraft 1.7.10 loading
[13:36:10] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_31, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_31
[13:36:10] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:36:11] [main/INFO] [FML]: Loading tweaker net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer from legacyjavafixer-1.0.jar
[13:36:11] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:36:11] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:36:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer
[13:36:11] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker@7920ba90
[13:36:11] [main/INFO] [FML]: [LegacyJavaFixer] Replacing tweaker cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker@7920ba90 with net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement@6b419da
[13:36:11] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: FMLCorePlugin {[]}
[13:36:11] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: FMLForgePlugin {[]}
[13:36:11] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: CCCDeobfPlugin {[]}
[13:36:11] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: CodeChickenCorePlugin {[]}
[13:36:11] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: NEICorePlugin {[]}
[13:36:11] [main/INFO] [FML]: [LegacyJavaFixer] Tweaker: cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker@7920ba90
[13:36:11] [main/INFO] [FML]: [LegacyJavaFixer] Replacing tweaker cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker@7920ba90 with net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement@6b419da
[13:36:11] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[13:36:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement
[13:36:11] [main/INFO] [FML]: [LegacyJavaFixer] Replacing sort
[13:36:11] [main/INFO] [FML]: [LegacyJavaFixer] Detected TerminalTweaker
[13:36:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer$SortReplacement
[13:36:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.lex.legacyjavafixer.LegacyJavaFixer
[13:36:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:36:14] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[13:36:14] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[13:36:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:36:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:36:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:36:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:36:15] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[13:36:16] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[13:36:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[13:36:16] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[13:36:17] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\penka_000\AppData\Roaming\.minecraft\MMC\instances\( ?° ?? ?°)\natives\lwjgl.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadLibrary0(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.8.0_31]
	at java.lang.Runtime.load0(Unknown Source) ~[?:1.8.0_31]
	at java.lang.System.load(Unknown Source) ~[?:1.8.0_31]
	at org.lwjgl.Sys$1.run(Sys.java:70) ~[lwjgl-2.9.1.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.Sys.loadLibrary(Sys.java:95) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.Sys.<clinit>(Sys.java:112) ~[lwjgl-2.9.1.jar:?]
	at net.minecraft.client.Minecraft.func_71386_F(Minecraft.java:2659) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 14 more
Minecraft exited with exitcode 0.

**Comment by 02JanDal** [comment]
Oh right, you'll probably have to create a new instance, instances keep the folder name (#176)

**Comment by peterix** [comment]
Just rename the instance folder, that's easier.

**Comment by bopaloni** [comment]
ok thanks guys :)

**Comment by peterix** [comment]
We will need to make sure the instance folder name is actually usable - more characters that java can't understand have to be replaced.
