### ISSUE TITLE
MultiMC crash with FML - MOD HAS DIRECT REFERENCE System.exit()

### ISSUE THREAD

**Issue by Novasae** [MultiMC/MultiMC5#875]
Trying to assemble a private pack to play with friends and after fixing mod incompatibilities I'm getting this crash that appears to be due to MultiMC not playing nice with Forge.

Mod List:
http://paste.ee/p/cwbvt

MultiMC Log:
http://paste.ee/p/SwJRW

**Comment by dmodoomsirius** [comment]
That is not your issue your issue is 
```java
java.lang.NoClassDefFoundError: cpw/mods/fml/common/network/IPacketHandler
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:420)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.common.network.IPacketHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more
Caused by: java.lang.NullPointerException
```

**Comment by Kilobyte22** [comment]
MultiMC works fine with Forge. Probaby thousands of people use it with forge each day. It likely is 2 mods not playing together nicely.

**Comment by coffeeherostat13** [comment]
MultiMC version: 0.4.5

Minecraft folder is:
/Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/minecraft

Java path is:
java

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -Xdock:icon=icon.png, -Xdock:name="MultiMC: MilleniaMine", -Xms896m, -Xmx2176m, -XX:PermSize=256m, -Duser.language=en, -jar, /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/jars/NewLaunch.jar]

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/natives

Traits:
  []

Libraries:
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/minecraftforge/forge/1.7.10-10.13.3.1374-1.7.10/forge-1.7.10-10.13.3.1374-1.7.10-universal.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/minecraft/launchwrapper/1.11/launchwrapper-1.11.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/16.0/guava-16.0.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.2.1/commons-lang3-3.2.1.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/8df8936f-0d43-47a8-89b3-e75a7a12bf97.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/7b305878-290f-4f8e-95ac-1a68efe43fe4.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/b5ea32dc-559f-42e3-a6e1-4a38cdf1bcea.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/19b5ec85-1bc9-4535-89bf-310552faa6eb.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/a2ad5e94-cea1-4d1d-aefb-f024a17c5f09.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/0dffacf5-f2b9-4e4b-9746-d6b2edf8a01b.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/c27a0b2b-c20c-4cf0-b209-556b71f28ddb.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/32bfb1b0-bf55-44c0-97d8-ae913f622508.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/3e498638-b735-4ea6-b5eb-9257b07cf283.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/70a152c5-d25f-4115-a7d7-dd196139490c.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/07c386c9-cef6-4b2f-af5a-cd7a51b08e3a.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/26cd464d-0b6f-4511-94b2-67b30e7ab9b2.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/cf08c30e-018d-440c-aa0e-958978ff6691.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/129d1ccd-e130-49b9-86bc-acf4f456ee62.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/6ae86a57-5dea-43f1-8498-7e3a5950a604.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/b2838306-5fc1-4081-8393-0de5e7259cb5.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/75374a2c-b15d-461c-86b4-12e8ebe280e5.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/c7285df4-d605-49a2-a004-e97ddb874c23.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/18206b78-7650-4cce-b44f-ff34e84fcc7a.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/0e61e3b4-3c67-4b71-b876-5e140bd9d129.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/6287b5e3-7ae4-4fdb-93c0-577f74c45caf.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/694aa2ba-9da2-4a83-b68b-2db068caf8cb.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/802e0d61-b8d5-4ff4-9f7d-a4ecc7bc9310.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/c67054ed-27f7-4b3f-9233-9f39dd9fb5c7.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/a84c1e4d-7d7d-41b8-b41e-d32f95761d31.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/jarmods/7c10b136-c9e1-49c2-a315-c434c293751d.jar
  /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/versions/1.7.10/1.7.10-stripped.jar

Params:
  [--username, <PROFILE NAME>, --version, 1.7.10, --gameDir, /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/instances/KrackKraft/minecraft, --assetsDir, /Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/assets, --assetIndex, 1.7.10, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userProperties, {}, --userType, mojang, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting twitch-platform-5.16-natives-osx.jar
Extracting jinput-platform-2.0.5-natives-osx.jar
Extracting lwjgl-platform-2.9.1-natives-osx.jar

[08:12:46] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[08:12:47] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[08:12:47] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[08:12:47] [main/INFO] [FML]: Forge Mod Loader version 7.10.112.1374 for Minecraft 1.7.10 loading
[08:12:47] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_79, running on Mac OS X:x86_64:10.9.3, installed at /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre
[08:12:48] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:12:48] [main/WARN] [FML]: The coremod mekanism.common.asm.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:12:55] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:12:56] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:12:56] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[08:12:56] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:12:56] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:12:56] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:13:14] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[08:13:14] [main/ERROR] [FML]: The minecraft jar file:/Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/versions/1.7.10/1.7.10-stripped.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!
[08:13:14] [main/ERROR] [FML]: FML has been ordered to ignore the invalid or missing minecraft certificate. This is very likely to cause a problem!
[08:13:14] [main/ERROR] [FML]: Technical information: ClientBrandRetriever was at jar:file:/Users/mikhaelpaykin/Downloads/MultiMC/MultiMC.app/Contents/MacOS/versions/1.7.10/1.7.10-stripped.jar!/net/minecraft/client/ClientBrandRetriever.class, there were 0 certificates for it
[08:13:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:13:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:13:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:13:14] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:13:15] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:102]: Successfully Registered Transformer
[08:13:20] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[08:13:21] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[08:13:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[08:13:29] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:13:29] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[08:13:29] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[08:13:29] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[08:13:32] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1763]: Galacticraft successfully injected bytecode into: sa (1 / 1)
[08:13:35] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1763]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[08:13:38] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1763]: Galacticraft successfully injected bytecode into: bdi (1 / 1)
[08:13:46] [main/INFO]: Setting user: <PROFILE NAME>
[08:13:49] [main/INFO] [STDOUT]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1763]: Galacticraft successfully injected bytecode into: xk (1 / 1)

I am trying to assemble a pack, and i don't know if it's the same problem but it crashes and i need help.

**Comment by Loetkolben** [comment]
@coffeeherostat13 I'm not sure if you have the same problem, as your log does not contain a crash (no stacktrace, etc.)
Please post the complete log using the "*Upload Log*" Button in the Console window and give us the link. Please make a new issuse if your stacktrace does not begin with
> java.lang.NoClassDefFoundError: cpw/mods/fml/common/network/IPacketHandler

Please do not post crash logs in GH comments, as it makes them harder to read and makes the page unnecessarily long.

**Comment by peterix** [comment]
Ok. the linked logs are now gone and the stuff here doesn't have enough information.

Looked like a problem with having mods meant for a different version of Minecraft/Forge than you use.
