### ISSUE TITLE
Failed to extract native library

### ISSUE THREAD

**Issue by madboy77** [MultiMC/MultiMC5#890]
plz help when i open multimc launcher and download version 1.7.10 say :
```
Failed to extract native library:
java.io.FileNotFoundException: E:\saeed\MultiMC\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-32.jar (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at java.util.zip.ZipFile.<init>(ZipFile.java:159)
	at org.multimc.Utils.unzipNatives(Utils.java:235)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:337)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54) 
```

And the game does not run

**Comment by madboy77** [comment]
sorry for Duplicate

**Comment by madboy77** [comment]
Please answer

**Comment by peterix** [comment]
Complete log would help. Please use the upload button instead of copypasting parts of it.
