### ISSUE TITLE
Insert resources/assets into instances of MC < 1.6.4

### ISSUE THREAD

**Issue by Tycitron6000** [MultiMC/MultiMC5#957]
i had this problem since the start i start 1.6.4 but it has no sound pls help me i want too go back too older versions AND HAVE MUSIC!

**Comment by peterix** [comment]
The old versions handle their own assets/resources downloads. It takes a bit (about 100MB download) and happens while you play. So all you have to do is wait a bit with the game open.

**Comment by peterix** [comment]
Anyway, it's definitely possible to just stick the resources into the instance. So we'll do exactly that.

**Comment by Tycitron6000** [comment]
the resources folder is in the instances but theres nothing in the resources folder. What do i do?

**Comment by peterix** [comment]
Oh. Derp. You mean 1.6.4. I read that completely wrong >_<

That should work without any significant issues.

**Comment by Tycitron6000** [comment]
derp and i mean beta/alpha and anything below 1.6.4

**Comment by peterix** [comment]
Ok.

Tested 1.6.4, works. You actually wouldn't be able to start the game if it couldn't download all the assets files. So the problem must be something else.

**Comment by peterix** [comment]
And the versions before that handle their own sound/music asset downloads.

**Comment by peterix** [comment]
When you open assets/objects/4d/4d03069c0e14794b463f563044da46433776da60 in something like vlc as an ogg file, it should play a skeleton sound. Does it?

**Comment by Tycitron6000** [comment]
ill try it

**Comment by Tycitron6000** [comment]
im playing alpha i dont see a assets folder

**Comment by peterix** [comment]
OK. Aplha apparently can't follow redirects:
![no-redirect](https://cloud.githubusercontent.com/assets/203326/7668208/aef5d054-fc2b-11e4-95b5-8a039ffe70d6.png)

Tries to list the resources and fails.

**Comment by peterix** [comment]
a1.1.2 is broken (doesn't download resources)
a1.1.2_01 works (does download)

So you are playing one of the alphas before a1.1.2_01 versions?

As a workaround, you might be able to create an instance of a1.1.2_01, let it run for a while and when it's done grabbing the resource/asset files, change the version to whatever you want it to be.

**Comment by Tycitron6000** [comment]
thats what im playing

**Comment by Tycitron6000** [comment]
1.1.2_01

**Comment by peterix** [comment]
This one actually works here, unlike the previous ones.

**Comment by peterix** [comment]
Can you access this in a web browser?
http://s3.amazonaws.com/MinecraftResources/

**Comment by Tycitron6000** [comment]
i already downloaded the resrces folder

**Comment by Tycitron6000** [comment]
it still didnt download its been an hour

**Comment by peterix** [comment]
Which is why I ask if you can access that link. It should be a bunch of XML, like this:
```
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Name>MinecraftResources</Name>
<Prefix/>
<Marker/>
<MaxKeys>1000</MaxKeys>
<IsTruncated>false</IsTruncated>
<Contents>
<Key>lang/</Key>
<LastModified>2013-01-10T10:39:06.000Z</LastModified>
<ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag>
<Size>0</Size>
<StorageClass>STANDARD</StorageClass>
</Contents>
...
```

**Comment by Tycitron6000** [comment]
http://www.mediafire.com/download/1frcsxk8uvwvre8/resources.zip

**Comment by peterix** [comment]
That does look like all of the resources.

Still not getting any sound in game with this in the minecraft folder (instance/minecraft/resources/...)? 

Start the instance, wait for it to load, on the console window, click upload. Post the link here.

**Comment by Tycitron6000** [comment]
What console window?

**Comment by Tycitron6000** [comment]
it loaded i dont see one

**Comment by peterix** [comment]
![console](https://cloud.githubusercontent.com/assets/203326/7671568/adf91f7a-fcd6-11e4-80e4-649fbec9fba9.png)
![settings](https://cloud.githubusercontent.com/assets/203326/7671572/ca19b53e-fcd6-11e4-938d-68499398b0f8.png)

**Comment by Tycitron6000** [comment]
oh ok

**Comment by Tycitron6000** [comment]
i see this error in it: java.net.SocketException: Address family not supported by protocol family: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at bf.run(SourceFile:28)
Loading texture http://www.minecraft.net/skin/<PROFILE NAME>.png
Player count: 1
java.net.SocketException: Address family not supported by protocol family: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at kz.run(SourceFile:23)
96 recipes

**Comment by peterix** [comment]
Please use the upload button.

**Comment by Tycitron6000** [comment]
http://paste.ee/p/FH0Jp

**Comment by peterix** [comment]
Can't see anything sound related here... have you checked the windows sound/volume settings? Minecraft could be muted or rerouted to some an HDMI output or whatever else...

Make sure you actually extract the thing - you are running it from a temp folder - from winrar. That folder and all its contents will likely go away after the next reboot or whenever Windows feels like cleaning it up...

You may want to add `-Djava.net.preferIPv4Stack=true` to the jvm args (MMC settings->Java->JVM arguments)

**Comment by peterix** [comment]
[Moved to workflowy (Ideas -> Inject resources into legacy versions of minecraft)](https://workflowy.com/s/2EyDMcp7CU)

**Comment by peterix** [comment]
I believe we fixed this on Mojang side... For some definition of fixed.
